# uncompyle6 version 3.9.0
# Python bytecode version base 2.5 (62131)
# Decompiled from: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
# Embedded file name: /entities/client/Bitcasters/layers/AccountCreation.py
# Compiled at: 2008-12-16 09:35:38
data = {'account_creation': {'align': (0.636, 0.475), 
                        'orientation': 0, 
                        'sprite': 'account_creation', 
                        'type': 'image'}, 
   'back': {'align': (0.461, 0.154), 
            'orientation': 0, 
            'parent': 'account_creation', 
            'sprite': 'back', 
            'type': 'button', 
            'tooltip': "Go back to login screen and don't create an account."}, 
   'done': {'align': (0.793, 0.878), 
            'labels': {'text': 'DONE'}, 'orientation': 0, 
            'parent': 'account_creation', 
            'sprite': 'thick_short', 
            'type': 'button', 
            'tooltip': 'Create this account.'}, 
   'parent_email': {'align': (0.104, 0.746), 
                    'next': 'password', 
                    'orientation': 0, 
                    'parent': 'account_creation', 
                    'sprite': 'large_text', 
                    'type': 'textfield'}, 
   'password': {'align': (0.67, 0.381), 
                'next': 'retype_password', 
                'parent': 'account_creation', 
                'password': True, 
                'sprite': 'large_text', 
                'type': 'textfield'}, 
   'pp': {'align': (0.809, 0.744), 
          'minsize': (80, 20), 
          'orientation': 0, 
          'parent': 'account_creation', 
          'sprite': '', 
          'type': 'button', 
          'tooltip': 'Read our privacy policy.'}, 
   'privacy_policy': {'align': (0.499, 0.738), 
                      'orientation': 0, 
                      'parent': 'account_creation', 
                      'sprite': 'checkbox', 
                      'type': 'checkbox', 
                      'tooltip': 'Check this box only after you have read the privacy policy.'}, 
   'retype_password': {'align': (0.67, 0.544), 
                       'next': 'username', 
                       'password': True, 
                       'parent': 'account_creation', 
                       'sprite': 'large_text', 
                       'type': 'textfield'}, 
   'terms_and_conditions': {'align': (0.499, 0.681), 
                            'orientation': 0, 
                            'parent': 'account_creation', 
                            'sprite': 'checkbox', 
                            'type': 'checkbox', 
                            'tooltip': 'Check this box only after you have read the terms of service.'}, 
   'tos': {'align': (0.862, 0.688), 
           'minsize': (120, 20), 
           'orientation': 0, 
           'parent': 'account_creation', 
           'sprite': '', 
           'type': 'button', 
           'tooltip': 'Read our terms of service.'}, 
   'username': {'align': (0.13, 0.381), 
                'next': 'your_email', 
                'orientation': 0, 
                'parent': 'account_creation', 
                'sprite': 'large_text', 
                'type': 'textfield'}, 
   'your_email': {'align': (0.13, 0.544), 
                  'next': 'parent_email', 
                  'orientation': 0, 
                  'parent': 'account_creation', 
                  'sprite': 'large_text', 
                  'type': 'textfield'}}
import Factory, BigWorld

class Layer(Factory.Layer):

    def postinit(self):
        self.focus_my('username')