// sho.globals.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

<anonymous> ** g_ptr0000; // 00000000
Eq_179857 g_a0001[];
word16 g_w0002; // 00000002
struct Eq_1218 * g_ptr0004; // 00000004
word16 g_w0005; // 00000005
word16 g_w0007; // 00000007
Eq_3 g_t0008;
word16 g_w0009; // 00000009
word16 g_w000B; // 0000000B
Eq_3 g_t000C;
Eq_85079 g_t0010;
Eq_15803 g_t0014;
Eq_85079 g_t0030;
Eq_85079 g_t0038;
Eq_85079 g_t003C;
Eq_15803 g_t0040;
Eq_168163 g_t0064;
Eq_122883 g_t0066;
Eq_114593 g_t0080;
Eq_85079 g_t0088;
Eq_147235 g_t0100;
Eq_147235 g_t0180;
struct Eq_73053 * g_ptr2000; // 00002000
Eq_3 g_t7FFFFFFF;
Eq_179523 g_aFFFFFFFF[];
