// sho_text_000D.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 004D3B60: void fn004D3B60(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn005A5370
void fn004D3B60(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ecx_13 = dwArg08;
	Eq_3 eax_17 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			eax_17 -= 0x10;
			*eax_17 = *((word32) ecx_13 - 16);
			ecx_13 -= 0x10;
			*((word32) eax_17 + 4) = *((word32) ecx_13 + 4);
			*((word32) eax_17 + 8) = *((word32) ecx_13 + 8);
			*((word32) eax_17 + 0x0C) = *((word32) ecx_13 + 0x0C);
		} while (ecx_13 != dwArg04);
	}
}

// 004DB650: Register Eq_3 fn004DB650(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out Eq_34279 ediOut)
// Called from:
//      fn006204B0
Eq_3 fn004DB650(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, union Eq_34279 & ediOut)
{
	fs->ptr0000 = fp - 0x0C;
	basic_string(fp - 0x50, "vector<T> too long");
	fn004019E0(fp - 0x34, fp - 0x50);
	CxxThrowException();
	int3();
	ptr32 ebp_54;
	ptr32 ebx_55;
	Eq_34279 edi_57;
	ptr32 esi_59;
	Eq_3 ecx_56 = fn004DB6B0(ebx, ebp, esi, edi, out ebx_55, out ebp_54, out esi_59, out edi_57);
	ebxOut = ebx_55;
	ebpOut = ebp_54;
	esiOut = esi_59;
	ediOut = edi_57;
	return ecx_56;
}

// 004DB6B0: Register Eq_3 fn004DB6B0(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register out Eq_3 ebxOut, Register out Eq_3 ebpOut, Register out Eq_3 esiOut, Register out Eq_3 ediOut)
// Called from:
//      fn004DB650
//      fn004DB6B0
//      fn00620670
Eq_3 fn004DB6B0(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, union Eq_3 & ebxOut, union Eq_3 & ebpOut, union Eq_3 & esiOut, union Eq_3 & ediOut)
{
	fs->ptr0000 = fp - 0x0C;
	basic_string(fp - 0x50, "vector<T> too long");
	fn004019E0(fp - 0x34, fp - 0x50);
	struct Eq_34345 * esp_44;
	Eq_3 ecx_46;
	CxxThrowException();
	int3();
	esp_44->tFFFFFFFC = esi;
	esp_44->tFFFFFFF8 = edi;
	Eq_3 edi_56 = esp_44->t0004;
	*((word32) ecx_46 + 4) = 0x00;
	*((word32) ecx_46 + 8) = 0x00;
	*((word32) ecx_46 + 0x0C) = 0x00;
	if (edi_56 != 0x00)
	{
		if (edi_56 > 0x3FFFFFFF)
		{
			word32 ebx_160;
			word32 ebp_161;
			word32 esi_162;
			word32 edi_163;
			fn004DB6B0(ebx, ebp, ecx_46, edi_56, out ebx_160, out ebp_161, out esi_162, out edi_163);
		}
		Eq_3 ecx_84;
		Eq_3 ebp_86;
		Eq_3 ebx_87;
		ui32 edi_88;
		struct Eq_34389 * esi_89;
		word32 edx_159;
		Eq_3 eax_83 = fn007B2480(ebx, ebp, ecx_46, edi_56, edi_56, out ecx_84, out edx_159, out ebx_87, out ebp_86, out esi_89, out edi_88);
		esi_89->t0004 = eax_83;
		esi_89->t0008 = eax_83;
		esi_89->dw000C = (word32) eax_83 + edi_88 * 0x04;
		ebxOut = ebx_87;
		ebpOut = ebp_86;
		esiOut.u0 = 0x00;
		ediOut.u0 = 8664169;
		return ecx_84;
	}
	else
	{
		Eq_3 edi_105 = esp_44->tFFFFFFF8;
		Eq_3 esi_110 = esp_44->tFFFFFFFC;
		ebxOut = ebx;
		ebpOut = ebp;
		esiOut = esi_110;
		ediOut = edi_105;
		return ecx_46;
	}
}

