// sho_text_000E.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 004E2250: Register word32 fn004E2250(Register (ptr32 Eq_1819) ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn004070F0
//      fn0040AB90
//      fn00424A20
//      fn00426100
word32 fn004E2250(struct Eq_1819 * ecx, Eq_3 dwArg04)
{
	Eq_3 eax_6 = *((word32) dwArg04 + 8);
	*((word32) dwArg04 + 8) = *eax_6;
	Eq_3 esi_12 = *eax_6;
	if (*((word32) esi_12 + 45) == 0x00)
		*((word32) esi_12 + 4) = dwArg04;
	*((word32) eax_6 + 4) = *((word32) dwArg04 + 4);
	Eq_3 ecx_23 = ecx->t0004;
	if (dwArg04 != *((word32) ecx_23 + 4))
	{
		Eq_3 ecx_29 = *((word32) dwArg04 + 4);
		if (dwArg04 != *ecx_29)
		{
			*((word32) ecx_29 + 8) = eax_6;
			*eax_6 = dwArg04;
			*((word32) dwArg04 + 4) = eax_6;
			return;
		}
		else
		{
			*ecx_29 = eax_6;
			*eax_6 = dwArg04;
			*((word32) dwArg04 + 4) = eax_6;
			return;
		}
	}
	else
	{
		*((word32) ecx_23 + 4) = eax_6;
		*eax_6 = dwArg04;
		*((word32) dwArg04 + 4) = eax_6;
		return;
	}
}

// 004E6960: Register Eq_3 fn004E6960(Stack Eq_3 dwArg04)
// Called from:
//      fn004070F0
//      fn00426100
Eq_3 fn004E6960(Eq_3 dwArg04)
{
	Eq_3 eax_11 = dwArg04;
	Eq_3 ecx_6 = *((word32) dwArg04 + 8);
	if (*((word32) ecx_6 + 45) == 0x00)
	{
		Eq_3 ecx_10 = ecx_6;
		do
		{
			eax_11 = ecx_10;
			ecx_10 = *((word32) ecx_10 + 8);
		} while (*((word32) ecx_10 + 45) == 0x00);
	}
	return eax_11;
}

// 004EA120: Register Eq_3 fn004EA120(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00411F00
Eq_3 fn004EA120(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	return fn005F8FB0(dwArg04, dwArg08, dwArg0C);
}

// 004EC030: void fn004EC030(Register (ptr32 Eq_26000) ecx)
// Called from:
//      fn00420510
void fn004EC030(struct Eq_26000 * ecx)
{
	ecx->t0000.u0 = 0x00;
}

