// sho_data_0004.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

byte g_bA53ED0 = 0x00; // 00A53ED0
byte g_bA53ED1 = 0x00; // 00A53ED1
byte g_bA53ED2 = 0x00; // 00A53ED2
byte g_bA53EF0 = 0x00; // 00A53EF0
word32 * g_ptrA53F10 = null; // 00A53F10
Eq_6268 g_tA53F14 = // 00A53F14
	{
		0x00
	};
Eq_3 g_tA53F1C = // 00A53F1C
	{
		0x00
	};
word32 g_dwA53F20 = 0x00; // 00A53F20
word32 g_dwA53F24 = 0x00; // 00A53F24
word32 g_dwA53F28 = 0x00; // 00A53F28
struct Eq_1819 * g_ptrA53F2C = null; // 00A53F2C
<anonymous> * g_ptrA53F30 = null; // 00A53F30
Eq_20964 g_tA53F34 = // 00A53F34
	{
		0x00,
		null,
		
		{
			0x00
		},
		0x00,
		0x00,
		0x00,
	};
byte g_bA53F54 = 0x00; // 00A53F54
Eq_23768 g_tA53F58 = // 00A53F58
	{
		0x00
	};
Eq_20964 g_tA53F6C = // 00A53F6C
	{
		0x00,
		null,
		
		{
			0x00
		},
		0x00,
		0x00,
		0x00,
	};
<anonymous> ** g_ptrA53FCC = null; // 00A53FCC
struct Eq_1218 * g_ptrA53FD0 = null; // 00A53FD0
Eq_3 g_tA53FD4 = // 00A53FD4
	{
		0x00
	};
Eq_3 g_tA53FE8 = // 00A53FE8
	{
		0x00
	};
byte g_bA53FED = 0x00; // 00A53FED
Eq_3 g_tA53FF0 = // 00A53FF0
	{
		0x00
	};
Eq_461 g_tA53FF4 = null; // 00A53FF4
Eq_30905 g_tA5423C = // 00A5423C
	{
	};
real32 g_rA544D4 = 0.0F; // 00A544D4
Eq_32064 g_tA54720 = // 00A54720
	{
	};
Eq_31679 g_tA54768 = // 00A54768
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0.0F,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		0x00,
	};
ui32 g_dwA555DC = 0x00; // 00A555DC
word32 g_dwA557F0 = 0x00; // 00A557F0
word32 g_dwA557F4 = 0x00; // 00A557F4
word32 g_dwA557F8 = 0x00; // 00A557F8
word32 g_dwA557FC = 0x00; // 00A557FC
byte g_bA55800 = 0x00; // 00A55800
word32 g_dwA55804 = 0x00; // 00A55804
Eq_33198 g_tA55808 = // 00A55808
	{
		0x00
	};
word32 g_dwA5651C = 0x00; // 00A5651C
word32 g_dwA56520 = 0x00; // 00A56520
Eq_34012 g_tA56524 = // 00A56524
	{
		0x00
	};
word32 g_dwA56628 = 0x00; // 00A56628
word32 g_dwA568D4 = 0x00; // 00A568D4
Eq_34156 g_tA568D8 = // 00A568D8
	{
		0x00
	};
<anonymous> ** g_ptrA577E0 = null; // 00A577E0
word32 g_dwA5C2E0 = 0x00; // 00A5C2E0
word32 g_dwA5C2E4 = 0x00; // 00A5C2E4
Eq_179417 g_aA5C2E8[] = // 00A5C2E8
	{
	};
Eq_179418 g_aA5C2EC[] = // 00A5C2EC
	{
	};
Eq_34675 g_tA5C4EA = // 00A5C4EA
	{
		0x00,
		0x00,
		0x00,
	};
