// sho_text_0004.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 0044C620: Register word32 fn0044C620(Register Eq_3 ebx, Register Eq_3 ebp, Register (ptr32 Eq_33239) esi, Register Eq_3 edi, Register out (ptr32 Eq_33241) ecxOut, Register out Eq_3 ebxOut, Register out Eq_3 ebpOut, Register out (ptr32 Eq_33239) esiOut, Register out Eq_3 ediOut)
// Called from:
//      fn0044D520
//      fn0044F1E0
//      fn005A5370
word32 fn0044C620(Eq_3 ebx, Eq_3 ebp, struct Eq_33239 * esi, Eq_3 edi, struct Eq_33241 & ecxOut, union Eq_3 & ebxOut, union Eq_3 & ebpOut, struct Eq_33239 & esiOut, union Eq_3 & ediOut)
{
	fs->ptr0000 = fp - 0x0C;
	basic_string(fp - 0x50, "vector<T> too long");
	fn004019E0(fp - 0x34, fp - 0x50);
	struct Eq_33266 * esp_44;
	CxxThrowException();
	int3();
	esp_44->dwFFFFFFFC = ~0x00;
	esp_44->dwFFFFFFF8 = 0x00834039;
	esp_44->ptrFFFFFFF4 = fs->ptr0000;
	esp_44->dwFFFFFFAC = g_tA14188 ^ esp_44 - 0x50;
	fs->ptr0000 = esp_44 - 0x0C;
	esp_44->ptrFFFFFFA8 = (basic_string *) g_str8A6998;
	basic_string(esp_44 - 0x50, esp_44->ptrFFFFFFA8);
	esp_44->ptrFFFFFFA8 = esp_44 - 0x50;
	esp_44->dwFFFFFFFC = 0x00;
	fn004019E0(esp_44 - 0x34, esp_44->ptrFFFFFFA8);
	esp_44->ptrFFFFFFA8 = &g_t999C68;
	esp_44->ptrFFFFFFA4 = esp_44 - 0x34;
	esp_44->dwFFFFFFCC = 0x00990030;
	struct Eq_33339 * esp_89;
	CxxThrowException();
	int3();
	esp_89->dwFFFFFFFC = ~0x00;
	esp_89->dwFFFFFFF8 = 0x00834069;
	esp_89->ptrFFFFFFF4 = fs->ptr0000;
	esp_89->dwFFFFFFAC = g_tA14188 ^ esp_89 - 0x50;
	fs->ptr0000 = esp_89 - 0x0C;
	esp_89->ptrFFFFFFA8 = (basic_string *) g_str8A6998;
	basic_string(esp_89 - 0x50, esp_89->ptrFFFFFFA8);
	esp_89->ptrFFFFFFA8 = esp_89 - 0x50;
	esp_89->dwFFFFFFFC = 0x00;
	fn004019E0(esp_89 - 0x34, esp_89->ptrFFFFFFA8);
	esp_89->ptrFFFFFFA8 = &g_t999C68;
	esp_89->ptrFFFFFFA4 = esp_89 - 0x34;
	esp_89->dwFFFFFFCC = 0x00990030;
	struct Eq_33412 * esp_134;
	CxxThrowException();
	int3();
	esp_134->dwFFFFFFFC = ~0x00;
	esp_134->dwFFFFFFF8 = 0x00834099;
	esp_134->ptrFFFFFFF4 = fs->ptr0000;
	esp_134->dwFFFFFFAC = g_tA14188 ^ esp_134 - 0x50;
	fs->ptr0000 = esp_134 - 0x0C;
	esp_134->ptrFFFFFFA8 = &g_t8AC4A4;
	basic_string(esp_134 - 0x50, esp_134->ptrFFFFFFA8);
	esp_134->ptrFFFFFFA8 = esp_134 - 0x50;
	esp_134->dwFFFFFFFC = 0x00;
	fn004019E0(esp_134 - 0x34, esp_134->ptrFFFFFFA8);
	esp_134->ptrFFFFFFA8 = &g_t999C68;
	esp_134->ptrFFFFFFA4 = esp_134 - 0x34;
	esp_134->dwFFFFFFCC = 0x00990030;
	struct Eq_33485 * esp_179;
	CxxThrowException();
	int3();
	struct Eq_33490 * eax_186 = esp_179->ptr0004;
	word32 ecx_187 = eax_186->dw0010;
	word32 edx_188 = eax_186->dw0000;
	esp_179->tFFFFFFE4 = ebx;
	word32 ebx_192 = eax_186->dw000C;
	esp_179->tFFFFFFE0 = ebp;
	esp_179->dwFFFFFFF8 = ecx_187;
	word32 ecx_197 = eax_186->dw0014;
	esp_179->ptrFFFFFFDC = esi;
	word32 esi_201 = eax_186->dw0004;
	esp_179->tFFFFFFD8 = edi;
	word32 edi_205 = eax_186->dw0008;
	esp_179->dwFFFFFFFC = ecx_197;
	struct Eq_33241 * ecx_207 = esp_179->ptr0008;
	eax_186->dw0000 = ecx_207->dw0000;
	eax_186->dw0004 = ecx_207->dw0004;
	eax_186->dw0008 = ecx_207->dw0008;
	eax_186->dw000C = ecx_207->dw000C;
	eax_186->dw0010 = ecx_207->dw0010;
	eax_186->dw0014 = ecx_207->dw0014;
	word32 eax_220 = esp_179->dwFFFFFFFC;
	ecx_207->dw0000 = edx_188;
	word32 edx_222 = esp_179->dwFFFFFFF8;
	ecx_207->dw0004 = esi_201;
	ecx_207->dw0008 = edi_205;
	Eq_3 edi_225 = esp_179->tFFFFFFD8;
	struct Eq_33239 * esi_227 = esp_179->ptrFFFFFFDC;
	ecx_207->dw000C = ebx_192;
	Eq_3 ebp_230 = esp_179->tFFFFFFE0;
	ecx_207->dw0010 = edx_222;
	ecx_207->dw0014 = eax_220;
	Eq_3 ebx_234 = esp_179->tFFFFFFE4;
	ecxOut = ecx_207;
	ebxOut = ebx_234;
	ebpOut = ebp_230;
	esiOut = esi_227;
	ediOut = edi_225;
	return eax_220;
}

// 0044D520: Register byte fn0044D520(Register Eq_3 ecx, Register Eq_3 ebx, Register Eq_3 ebp, Stack (ptr32 Eq_33239) dwArg04, Register out Eq_33623 edxOut)
// Called from:
//      fn005A5680
byte fn0044D520(Eq_3 ecx, Eq_3 ebx, Eq_3 ebp, struct Eq_33239 * dwArg04, union Eq_33623 & edxOut)
{
	((word32) ecx + 4)->u0 = 0x00;
	((word32) ecx + 8)->u0 = 0x00;
	*((word32) ecx + 0x0C) = 0x00;
	struct Eq_33239 * esi_30 = dwArg04;
	int32 eax_24 = 0x00;
	Eq_3 esp_10 = fp - 8;
	Eq_3 edi_14 = ecx;
	if (dwArg04 != null)
	{
		if (dwArg04 > (struct Eq_33239 *) 0x0FFFFFFF)
		{
			word32 ecx_106;
			word32 ebx_107;
			word32 ebp_108;
			eax_24 = fn0044C620(ebx, ebp, dwArg04, ecx, out ecx_106, out ebx_107, out ebp_108, out esi_30, out edi_14);
			esp_10.u0 = <invalid>;
		}
		struct Eq_33650 * esp_37 = esp_10 - 4;
		esp_37->dw0000 = eax_24;
		esp_37->ptrFFFFFFFC = esi_30;
		Eq_33623 edx_45;
		ui32 esi_46;
		Eq_3 eax_43 = fn005DE860(esi_30, esp_37->ptrFFFFFFFC, out edx_45, out esi_46);
		*((word32) edi_14 + 4) = eax_43;
		*((word32) edi_14 + 8) = eax_43;
		*((word32) edi_14 + 0x0C) = (word32) eax_43 + (esi_46 << 0x04);
		edxOut = edx_45;
		return 0x01;
	}
	else
	{
		edxOut = edx;
		return 0x00;
	}
}

// 0044F1E0: Register word32 fn0044F1E0(Register Eq_3 ecx, Stack Eq_3 dwArg04, Register out Eq_33632 ebxOut, Register out ptr32 ebpOut)
// Called from:
//      fn0044F650
word32 fn0044F1E0(Eq_3 ecx, Eq_3 dwArg04, union Eq_33632 & ebxOut, ptr32 & ebpOut)
{
	struct Eq_33239 * esi_43;
	fs->t0000 = fp - 0x10;
	struct Eq_33710 * ebp_129 = fp - 4;
	Eq_3 esp_124 = fp - 0x28;
	Eq_3 edi_102 = ecx;
	Eq_3 ebx_107 = dwArg04;
	Eq_3 eax_37 = *((word32) dwArg04 + 4);
	word32 ecx_38 = 0x00;
	if (eax_37 == 0x00)
		esi_43 = null;
	else
		esi_43 = *((word32) dwArg04 + 8) - eax_37 >> 0x04;
	((word32) ecx + 4)->u0 = 0x00;
	((word32) ecx + 8)->u0 = 0x00;
	*((word32) ecx + 0x0C) = 0x00;
	if (esi_43 != null)
	{
		if (esi_43 > (struct Eq_33239 *) 0x0FFFFFFF)
		{
			fn0044C620(dwArg04, fp - 4, esi_43, ecx, out ecx_38, out ebx_107, out ebp_129, out esi_43, out edi_102);
			esp_124.u0 = <invalid>;
		}
		struct Eq_33761 * esp_75 = esp_124 - 4;
		esp_75->dw0000 = ecx_38;
		esp_75->ptrFFFFFFFC = esi_43;
		ui32 esi_84;
		word32 edx_176;
		Eq_3 eax_81 = fn005DE860(esi_43, esp_75->ptrFFFFFFFC, out edx_176, out esi_84);
		ebp_129->t0008.u0 = 0x00;
		Eq_3 esp_85 = <invalid>;
		*((word32) esp_85 - 4) = ebp_129->t0008;
		*((word32) esp_85 - 8) = ebp_129->t0008;
		*((word32) esp_85 - 0x0C) = edi_102;
		*((word32) edi_102 + 4) = eax_81;
		*((word32) edi_102 + 8) = eax_81;
		*((word32) edi_102 + 0x0C) = (word32) eax_81 + (esi_84 << 0x04);
		Eq_3 ecx_108 = *((word32) ebx_107 + 8);
		Eq_3 ebx_109 = *((word32) ebx_107 + 4);
		*((word32) esp_85 - 16) = eax_81;
		*((word32) esp_85 - 20) = ecx_108;
		*((word32) esp_85 - 24) = ebx_109;
		ebp_129->tFFFFFFFC.u0 = 0x00;
		*((word32) edi_102 + 8) = fn005F9240(*((word32) esp_85 - 24), *((word32) esp_85 - 20), *((word32) esp_85 - 16), out edx);
		esp_124 = (word32) esp_85 + 8;
	}
	fs->t0000 = ebp_129->tFFFFFFF4;
	ptr32 ebp_144 = ebp_129->ptr0000;
	ebxOut = *((word32) esp_124 + 0x0C);
	ebpOut = ebp_144;
	return edx;
}

// 0044F600: Register word32 fn0044F600(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08)
// Called from:
//      fn00414B80
//      fn00418150
//      fn00418AF0
//      fn007B2D10
word32 fn0044F600(Eq_3 dwArg04, Eq_3 dwArg08)
{
	Eq_3 edi_11 = dwArg04;
	if (dwArg04 != dwArg08)
	{
		struct Eq_33866 * esp_14 = fp - 0x0C;
		do
		{
			Eq_3 esi_19 = *edi_11;
			if (esi_19 != 0x00 && (fn00401AE0(esi_19) == 0x01 && esi_19 != 0x00))
			{
				<anonymous> ** eax_34 = *esi_19;
				<anonymous> * edx_35 = *eax_34;
				esp_14->dwFFFFFFFC = 0x01;
				word32 edx_45;
				edx_35();
			}
			*edi_11 = 0x00;
			edi_11 = (word32) edi_11 + 4;
		} while (edi_11 != dwArg08);
		esi = esp_14->dw0000;
	}
	return esi;
}

// 0044F650: Register word32 fn0044F650(Register Eq_3 ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn005A6000
//      fn005A6350
//      fn005A67A0
word32 fn0044F650(Eq_3 ecx, Eq_3 dwArg04)
{
	word32 ecx_19;
	Eq_3 esi_20 = dwArg04;
	Eq_3 edi_21 = ecx;
	for (ecx_19 = 0x0113; ecx_19 != 0x00; --ecx_19)
	{
		*edi_21 = *esi_20;
		esi_20 = (word32) esi_20 + 4;
		edi_21 = (word32) edi_21 + 4;
	}
	word32 * esi_24 = (word32) dwArg04 + 0x044C;
	word32 * edi_26 = (word32) ecx + 0x044C;
	word32 ecx_27;
	for (ecx_27 = 0x4C; ecx_27 != 0x00; --ecx_27)
	{
		*edi_26 = *esi_24;
		++esi_24;
		++edi_26;
	}
	*((word32) ecx + 1404) = *((word32) dwArg04 + 1404);
	*((word32) ecx + 0x0580) = *((word32) dwArg04 + 0x0580);
	*((word32) ecx + 1412) = *((word32) dwArg04 + 1412);
	*((word32) ecx + 0x0588) = *((word32) dwArg04 + 0x0588);
	*((word32) ecx + 0x058C) = *((word32) dwArg04 + 0x058C);
	*((word32) ecx + 1424) = *((word32) dwArg04 + 1424);
	struct Eq_33970 * ebx_51;
	struct Eq_33971 * ebp_56;
	word32 edx_55 = fn0044F1E0((word32) ecx + 0x0594, (word32) dwArg04 + 0x0594, out ebx_51, out ebp_56);
	ebx_51->dw05A4 = ebp_56->dw05A4;
	return edx_55;
}

