// sho_data_0002.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

Eq_179877 g_aA2E9B0[6] = // 00A2E9B0
	{
		
		{
			0x008D1DC8,
		},
		
		{
			9110892,
		},
		
		{
			0x008D46D8,
		},
		
		{
			9279008,
		},
		
		{
			9299912,
		},
		
		{
			0x00,
		},
	};
Eq_74720 g_tA2EA18 = // 00A2EA18
	{
		9300964,
		
		{
			&g_t7AD220
		},
		
		{
			0x008DD028
		},
	};
Eq_75037 g_tA2EC68 = // 00A2EC68
	{
		9301044,
		9301032,
	};
struct Eq_75037 * g_ptrA2EC98 = &g_tA2EC68; // 00A2EC98
Eq_56268 g_tA2EE18 = // 00A2EE18
	{
		0x14,
		0,
	};
Eq_170514 g_aA2EED8[] = // 00A2EED8
	{
	};
int32 g_aA2EF70[] = // 00A2EF70
	{
	};
Eq_56268 g_tA2F030 = // 00A2F030
	{
		0x0C,
		0,
	};
Eq_3 g_tA34F98 = // 00A34F98
	{
		0x20
	};
Eq_3 g_aA35120[5] = // 00A35120
	{
		
		{
			0x8DF950008DF95C
		},
		
		{
			39961990638991688
		},
		
		{
			0x00A6E534
		},
		
		{
			6568611551427785336
		},
		
		{
			2332069060694602867
		},
	};
word32 g_dwA35130 = 0x00A6E534; // 00A35130
