// sho_text_003F.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 007FB450: void fn007FB450(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00622230
void fn007FB450(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	fn00621710(dwArg04, dwArg08, dwArg0C);
}

