// sho_text_001C.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 005C9B40: Register Eq_3 fn005C9B40(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00418AF0
Eq_3 fn005C9B40(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ebx_26 = dwArg04;
	if (dwArg04 == dwArg08)
		return dwArg0C;
	Eq_3 edi_25 = dwArg0C;
	do
	{
		Eq_3 ecx_28 = *ebx_26;
		Eq_3 esi_30 = *edi_25;
		if (esi_30 != ecx_28)
		{
			*edi_25 = ecx_28;
			if (ecx_28 != 0x00)
				fn00401AD0(ecx_28);
			if (esi_30 != 0x00 && fn00401AE0(esi_30) == 0x01)
			{
				<anonymous> ** eax_54 = *esi_30;
				word32 edx_70;
				(*eax_54)();
			}
		}
		ebx_26 = (word32) ebx_26 + 4;
		edi_25 = (word32) edi_25 + 4;
	} while (ebx_26 != dwArg08);
	return edi_25;
}

// 005C9BA0: void fn005C9BA0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00414B80
void fn005C9BA0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 edi_11 = dwArg04;
	if (dwArg04 != dwArg08)
	{
		struct Eq_43525 * esp_18 = fp - 16;
		do
		{
			Eq_3 ecx_23 = *dwArg0C;
			Eq_3 esi_25 = *edi_11;
			if (esi_25 != ecx_23)
			{
				*edi_11 = ecx_23;
				if (ecx_23 != 0x00)
					fn00401AD0(ecx_23);
				if (esi_25 != 0x00 && fn00401AE0(esi_25) == 0x01)
				{
					<anonymous> ** eax_49 = *esi_25;
					<anonymous> * edx_50 = *eax_49;
					esp_18->dwFFFFFFFC = 0x01;
					word32 edx_65;
					edx_50();
				}
			}
			edi_11 = (word32) edi_11 + 4;
		} while (edi_11 != dwArg08);
	}
}

// 005CAB80: void fn005CAB80(Register (ptr32 Eq_43106) ecx)
// Called from:
//      fn005B6640
//      fn005B6780
void fn005CAB80(struct Eq_43106 * ecx)
{
	struct Eq_43567 * ecx_9 = ecx->ptr0004;
	struct Eq_43567 * eax_10 = ecx_9->ptr0000;
	ecx_9->ptr0000 = ecx_9;
	struct Eq_43567 * ecx_12 = ecx->ptr0004;
	ecx_12->ptr0004 = ecx_12;
	ecx->dw0008 = 0x00;
	if (eax_10 != ecx->ptr0004)
	{
		do
		{
			struct Eq_43567 * edi_23 = eax_10->ptr0000;
			operator delete(eax_10);
			eax_10 = edi_23;
		} while (edi_23 != ecx->ptr0004);
	}
	operator delete(ecx->ptr0004);
	ecx->ptr0004 = null;
}

// 005CF0C0: void fn005CF0C0(Register (ptr32 Eq_3) ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn0040E780
//      fn00418D40
void fn005CF0C0(union Eq_3 * ecx, Eq_3 dwArg04)
{
	Eq_3 ecx_14 = *dwArg04;
	Eq_3 esi_15 = *ecx;
	if (esi_15 != ecx_14)
	{
		*ecx = (union Eq_3 *) ecx_14;
		if (ecx_14 != 0x00)
			fn00401AD0(ecx_14);
		if (esi_15 != 0x00)
		{
			Eq_3 eax_31 = fn00401AE0(esi_15);
			if (eax_31 == 0x01)
			{
				<anonymous> ** edx_39 = *esi_15;
				(*edx_39)();
			}
		}
	}
}

