// sho_rdata_0001.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

real32 g_r8B95CC = 400.0F; // 008B95CC
<anonymous> * g_ptr8C27C4 = fn00520C80; // 008C27C4
real32 g_r8C28C0 = 0.95492965F; // 008C28C0
real32 g_r8C2B6C = 240.0F; // 008C2B6C
real32 g_r8C2B70 = 320.0F; // 008C2B70
const char g_str8C2BAC[] = "D3DERR_OUTOFVIDEOMEMORY"; // 008C2BAC
const char g_str8C2BC4[] = "Internal Driver Error"; // 008C2BC4
