// sho_text_0021.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 006129E0: Register word32 fn006129E0(Register (ptr32 Eq_1819) ecx, Stack (ptr32 Eq_3) dwArg04, Stack Eq_3 dwArg08)
// Called from:
//      fn00405CE0
word32 fn006129E0(struct Eq_1819 * ecx, union Eq_3 * dwArg04, Eq_3 dwArg08)
{
	word32 ebx_19;
	Eq_3 eax_17 = fn005B0F90(ecx, dwArg08, out ebx_19);
	if (eax_17 != ecx->t0004)
	{
		word32 eax_36;
		MSVCP80.dll!??$?MDU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@0@Z();
		if ((byte) eax_36 == 0x00)
		{
			*dwArg04 = (union Eq_3 *) eax_17;
			return;
		}
	}
	*dwArg04 = (union Eq_3 *) ecx->t0004;
	return;
}

// 00614080: Register Eq_3 fn00614080(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00417AC0
//      fn00622B40
Eq_3 fn00614080(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ecx_17 = dwArg04;
	Eq_3 eax_13 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			if (eax_13 != 0x00)
			{
				*eax_13 = *ecx_17;
				*((word32) eax_13 + 4) = *((word32) ecx_17 + 4);
			}
			ecx_17 = (word32) ecx_17 + 8;
			eax_13 = (word32) eax_13 + 8;
		} while (ecx_17 != dwArg08);
	}
	return eax_13;
}

// 00614570: Register (ptr32 word32) fn00614570(Stack (ptr32 word32) dwArg04, Stack (ptr32 word32) dwArg08, Stack (ptr32 word32) dwArg0C)
// Called from:
//      fn00618600
word32 * fn00614570(word32 * dwArg04, word32 * dwArg08, word32 * dwArg0C)
{
	word32 * edi_11 = dwArg04;
	if (dwArg04 == dwArg08)
		return dwArg0C;
	word32 * esi_22 = dwArg0C;
	do
	{
		struct Eq_44044 * eax_25 = *edi_11;
		struct Eq_44044 * ecx_27 = *esi_22;
		if (ecx_27 != eax_25)
		{
			*esi_22 = eax_25;
			if (eax_25 != null)
				++eax_25->dw0008;
			if (ecx_27 != null)
			{
				word32 v13_43 = ecx_27->dw0008 + ~0x00;
				ecx_27->dw0008 = v13_43;
				if (v13_43 == 0x00)
				{
					<anonymous> ** eax_47 = ecx_27->ptr0004;
					word32 ecx_61;
					word32 edx_62;
					(*eax_47)();
				}
			}
		}
		++edi_11;
		++esi_22;
	} while (edi_11 != dwArg08);
	return esi_22;
}

// 006150F0: void fn006150F0(Stack (ptr32 word32) dwArg04, Stack (ptr32 word32) dwArg08)
// Called from:
//      fn00618600
void fn006150F0(word32 * dwArg04, word32 * dwArg08)
{
	word32 * esi_15 = dwArg04;
	struct Eq_44091 * esp_28 = fp - 8;
	if (dwArg04 != dwArg08)
	{
		do
		{
			struct Eq_44104 * eax_17 = *esi_15;
			if (eax_17 != null)
			{
				word32 v10_21 = eax_17->dw0008 + ~0x00;
				eax_17->dw0008 = v10_21;
				if (v10_21 == 0x00)
				{
					<anonymous> ** eax_26 = eax_17->ptr0004;
					<anonymous> * edx_27 = *eax_26;
					esp_28->dwFFFFFFFC = 0x01;
					word32 ecx_35;
					word32 edx_36;
					edx_27();
				}
			}
			*esi_15 = 0x00;
			++esi_15;
		} while (esi_15 != dwArg08);
	}
}

// 00618600: void fn00618600()
// Called from:
//      fn005A7560
void fn00618600()
{
	word32 * ecx_7 = g_ptrA67640;
	word32 * eax_8 = g_ptrA67644;
	if (ecx_7 != eax_8)
	{
		word32 * eax_30 = fn00614570(eax_8, eax_8, ecx_7);
		fn006150F0(eax_30, g_ptrA67644);
		g_ptrA67644 = eax_30;
	}
	g_dwA67638 = 0x00;
}

// 006196B0: Register Eq_3 fn006196B0()
// Called from:
//      fn005A7560
Eq_3 fn006196B0()
{
	return SetProcessAffinityMask(GetCurrentProcess(), g_tA11648);
}

<anonymous> g_t61FA90 = <code>; // 0061FA90
// 0061FAC0: Register word32 fn0061FAC0(Stack (ptr32 Eq_1488) dwArg04)
// Called from:
//      fn0061FB20
word32 fn0061FAC0(struct Eq_1488 * dwArg04)
{
	ptr32 esp_13 = fp - 16;
	byte bl_102 = 0x00;
	if (dwArg04->dw0004 >= (word32) (*fn00426500()) + dwArg04->dw0000)
	{
		word32 * esi_39;
		word32 * ebp_46 = *((word32) fn00426500() + 32);
		for (esi_39 = *((word32) fn00426500() + 28); esi_39 != ebp_46; ++esi_39)
		{
			if (bl_102 == 0x00)
			{
				<anonymous> *** ecx_55 = *esi_39;
				<anonymous> * edx_57 = **ecx_55;
				struct Eq_44217 * esp_60 = esp_13 - 4;
				esp_60->ptr0000 = esp_13 + 0x1C;
				esp_60->dwFFFFFFFC = esp_60->dw001C;
				esp_60->dwFFFFFFF8 = dwArg04->dw0004;
				word32 eax_69 = dwArg04->dw0000;
				esp_60->dwFFFFFFF4 = eax_69;
				word32 eax_78;
				edx_57();
				bl_102 = (byte) eax_78;
			}
		}
	}
	return edx;
}

// 0061FB20: Register word32 fn0061FB20(Register (ptr32 Eq_1488) ecx, Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack (ptr32 charconst ) dwArg08, Stack ptr32 dwArg0C, Register out Eq_3 edxOut, Register out Eq_3 ediOut)
// Called from:
//      fn0061FC50
word32 fn0061FB20(struct Eq_1488 * ecx, Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, const char * dwArg08, ptr32 dwArg0C, union Eq_3 & edxOut, union Eq_3 & ediOut)
{
	Eq_3 eax_166;
	ui32 eax_7 = g_tA14188 ^ fp - 0x0408;
	struct Eq_44266 * esp_25;
	MSVCR80.dll!vsprintf();
	esp_25->dwFFFFFFFC = (const char *) &esp_25->t0008 + 0x0C;
	esp_25->dwFFFFFFF8 = 9080676;
	esp_25->ptrFFFFFFF4 = ecx;
	Eq_3 edx_154 = fn0061FAC0(esp_25->ptrFFFFFFF4);
	if (esp_25->b041C != 0x00)
	{
		eax_166 = fn00426500();
		if (*((word32) eax_166 + 4) == 0x00)
			goto l0061FC30;
	}
	esp_25->t0008 = edi;
	Eq_3 eax_63 = fn00426500();
	struct Eq_44299 * esp_101 = &esp_25->t0008;
	word32 * ecx_69 = *((word32) eax_63 + 0x0C);
	if (ecx_69 != null && *((word32) eax_63 + 16) - ecx_69 >> 0x02 != 0x00)
	{
		word32 * esi_114 = *((word32) fn00426500() + 0x0C);
		word32 * edi_92 = *((word32) fn00426500() + 16);
		if (esi_114 != edi_92)
		{
			esp_101 = (struct Eq_44299 *) &esp_25->t0008;
			do
			{
				<anonymous> *** ecx_98 = *esi_114;
				<anonymous> * eax_100 = **ecx_98;
				ptr32 edx_102 = &esp_101->dw0000 + 3;
				esp_101->ptrFFFFFFFC = edx_102;
				eax_100();
				++esi_114;
			} while (esi_114 != edi_92);
		}
	}
	struct Eq_44322 * edi_119 = (const char *) &esp_101->dw0000 + 11 + 1;
	do
	{
		edi_119 = edi_317 + 1;
		edi_317 = edi_119;
	} while (edi_317->w0000 != 0x00);
	word32 ecx_128;
	struct Eq_44379 * esi_129 = g_a8C63C8;
	for (ecx_128 = 0x10; ecx_128 != 0x00; --ecx_128)
	{
		edi_119->w0000 = esi_129->w0000;
		++esi_129;
		edi_119 += 4;
	}
	struct Eq_44429 ** ecx_132 = g_ptrA11680;
	edi_119->w0000 = esi_129->w0000;
	edi = esp_101->dw0000;
	struct Eq_44393 * esp_142 = &esp_101->dw0000 + 1;
	if (ecx_132 == null)
	{
l0061FC18:
		union Eq_3 * esp_229 = esp_142 - 4;
		*esp_229 = (union Eq_3 *) 0x01;
		exit(*esp_229);
	}
	<anonymous> * edx_145 = *((const char *) *ecx_132 + 4);
	esp_142->ptrFFFFFFFC = &esp_142->ptrFFFFFFFC + 3;
	struct Eq_44438 * esp_151;
	word32 eax_152;
	edx_145();
	if (eax_152 != 0x00)
	{
		eax_166 = eax_152 - 0x01;
		if (eax_152 == 0x01)
		{
			struct Eq_44429 ** ecx_217 = g_ptrA11680;
			struct Eq_44429 * eax_218 = *ecx_217;
			<anonymous> * edx_219 = eax_218->ptr0008;
			esp_151->dwFFFFFFFC = 0x01;
			edx_219();
			goto l0061FC18;
		}
	}
	else
	{
		struct Eq_44429 ** ecx_160 = g_ptrA11680;
		struct Eq_44429 * eax_161 = *ecx_160;
		<anonymous> * edx_162 = eax_161->ptr0008;
		esp_151->dwFFFFFFFC = 0x00;
		edx_162();
		int3();
	}
l0061FC30:
	word32 ecx_316;
	word32 eax_207 = fn00694B8E(eax_166, eax_7 ^ fp - 0x0408, edx_154, ebx, ebp, esi, edi, es, ds, esi, out ecx_316);
	edxOut = edx_154;
	ediOut = edi;
	return eax_207;
}

// 0061FC50: Register word32 fn0061FC50(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack (ptr32 Eq_1488) dwArg04, Stack (ptr32 charconst ) dwArg08, Register out Eq_1490 edxOut, Register out (ptr32 byte) ediOut)
// Called from:
//      fn004023A0
//      fn00403F70
//      fn004048C0
//      fn00420190
//      fn005A3D20
//      fn005A6DD0
//      fn005A79D0
word32 fn0061FC50(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, struct Eq_1488 * dwArg04, const char * dwArg08, union Eq_1490 & edxOut, byte & ediOut)
{
	byte * edi_26;
	Eq_1490 edx_27;
	word32 eax_24 = fn0061FB20(dwArg04, ebx, ebp, esi, edi, es, ds, dwArg08, fp + 0x0C, out edx_27, out edi_26);
	edxOut = edx_27;
	ediOut = edi_26;
	return eax_24;
}

// 0061FC90: Register word16 fn0061FC90()
// Called from:
//      fn00402B60
word16 fn0061FC90()
{
	return g_wA11688;
}

// 0061FCA0: Register word16 fn0061FCA0()
// Called from:
//      fn00402B60
word16 fn0061FCA0()
{
	return g_wA1168C;
}

// 0061FCB0: Register word16 fn0061FCB0()
// Called from:
//      fn00402B60
word16 fn0061FCB0()
{
	return g_wA67B60;
}

// 0061FCC0: Register word16 fn0061FCC0()
// Called from:
//      fn00402B60
word16 fn0061FCC0()
{
	return g_wA11690;
}

// 0061FD40: void fn0061FD40(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack word16 wArg04)
// Called from:
//      fn00402B60
void fn0061FD40(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, word16 wArg04)
{
	if (wArg04 == g_wA11688)
		return;
	g_wA11688 = wArg04;
	ui32 eax_11 = g_tA14188 ^ fp - 0x84;
	word32 edx_17 = (word32) g_wA1168C;
	word32 eax_20 = (word32) g_wA11688;
	snprintf();
	word32 ecx_110;
	fn00694B8E(operator =(&g_tA67B64, fp - 0x84), eax_11 ^ fp - 0x84, fp - 0x84, ebx, ebp, esi, edi, es, ds, fp - 0x84, out ecx_110);
}

// 0061FD60: void fn0061FD60(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack word16 wArg04)
// Called from:
//      fn00402B60
void fn0061FD60(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, word16 wArg04)
{
	if (wArg04 == g_wA1168C)
		return;
	g_wA1168C = wArg04;
	ui32 eax_11 = g_tA14188 ^ fp - 0x84;
	word32 edx_17 = (word32) g_wA1168C;
	word32 eax_20 = (word32) g_wA11688;
	snprintf();
	word32 ecx_110;
	fn00694B8E(operator =(&g_tA67B64, fp - 0x84), eax_11 ^ fp - 0x84, fp - 0x84, ebx, ebp, esi, edi, es, ds, fp - 0x84, out ecx_110);
}

// 0061FD80: void fn0061FD80(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack word16 wArg04)
// Called from:
//      fn00402B60
void fn0061FD80(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, word16 wArg04)
{
	g_wA67B60 = wArg04;
	ui32 eax_9 = g_tA14188 ^ fp - 0x84;
	word32 edx_15 = (word32) g_wA1168C;
	word32 eax_18 = (word32) g_wA11688;
	snprintf();
	word32 ecx_88;
	fn00694B8E(operator =(&g_tA67B64, fp - 0x84), eax_9 ^ fp - 0x84, fp - 0x84, ebx, ebp, esi, edi, es, ds, fp - 0x84, out ecx_88);
}

// 0061FD90: Register word32 fn0061FD90(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack word16 wArg04, Register out ptr32 edxOut)
// Called from:
//      fn00402B60
word32 fn0061FD90(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, word16 wArg04, ptr32 & edxOut)
{
	word32 eax_89 = SEQ(eax_16_16, wArg04);
	if (wArg04 == g_wA11690)
	{
		edxOut = edx;
		return eax_89;
	}
	else
	{
		g_wA11690 = wArg04;
		ui32 eax_11 = g_tA14188 ^ fp - 0x84;
		word32 edx_17 = (word32) g_wA1168C;
		word32 eax_20 = (word32) g_wA11688;
		snprintf();
		word32 ecx_111;
		word32 eax_61 = fn00694B8E(operator =(&g_tA67B64, fp - 0x84), eax_11 ^ fp - 0x84, fp - 0x84, ebx, ebp, esi, edi, es, ds, fp - 0x84, out ecx_111);
		edxOut = fp - 0x84;
		return eax_61;
	}
}

// 006204B0: void fn006204B0(Register Eq_3 ecx, Register Eq_3 ebp, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08)
// Called from:
//      fn00620BE0
void fn006204B0(Eq_3 ecx, Eq_3 ebp, Eq_3 dwArg04, Eq_3 dwArg08)
{
	Eq_3 edi_25;
	Eq_3 esi_13 = ecx;
	Eq_3 ecx_16 = *((word32) ecx + 4);
	if (ecx_16 == 0x00)
		edi_25.u0 = 0x00;
	else
		edi_25 = *((word32) ecx + 0x0C) - ecx_16 >> 0x02;
	Eq_3 ebx_32 = dwArg08;
	if (dwArg08 == 0x00)
		return;
	Eq_44673 eax_43;
	if (ecx_16 == 0x00)
		eax_43.u0 = 0x00;
	else
		eax_43 = *((word32) ecx + 8) - ecx_16 >> 0x02;
	if (0x3FFFFFFF - eax_43 < dwArg08)
		ecx_16 = fn004DB650(dwArg08, ebp, ecx, edi_25, out ebx_32, out ebp, out esi_13, out edi_25);
	Eq_44686 eax_86;
	if (ecx_16 == 0x00)
		eax_86.u0 = 0x00;
	else
		eax_86 = *((word32) esi_13 + 8) - ecx_16 >> 0x02;
	if (edi_25 >=u eax_86 + ebx_32)
	{
		Eq_3 ebp_106 = *((word32) esi_13 + 8);
		int32 eax_111 = ebx_32 * 0x04;
		if (ebp_106 - dwArg04 >> 0x02 >= ebx_32)
		{
			Eq_3 ebx_119 = ebp_106 - eax_111;
			*((word32) esi_13 + 8) = fn007B2800(ebx_119, ebp_106, ebp_106);
			fn0050AAA0(dwArg04, ebx_119, ebp_106);
			fn004B3770(dwArg04, (word32) dwArg04 + eax_111, fp + 0x0C);
		}
		else
		{
			fn007B2800(dwArg04, ebp_106, (word32) dwArg04 + eax_111);
			Eq_3 eax_192 = *((word32) esi_13 + 8);
			fn00669E20(eax_192, ebx_32 - (eax_192 - dwArg04 >> 0x02), fp + 0x0C);
			*((word32) esi_13 + 8) = (word32) *((word32) esi_13 + 8) + eax_111;
			fn004B3770(dwArg04, *((word32) esi_13 + 8) - eax_111, fp + 0x0C);
		}
	}
	else
	{
		Eq_3 edi_250;
		Eq_44717 eax_245 = edi_25 >> 0x01;
		if (0x3FFFFFFF - eax_245 < edi_25)
			edi_250.u0 = 0x00;
		else
			edi_250 = edi_25 + eax_245;
		Eq_44725 eax_264;
		if (ecx_16 == 0x00)
			eax_264.u0 = 0x00;
		else
			eax_264 = *((word32) esi_13 + 8) - ecx_16 >> 0x02;
		if (edi_250 <u eax_264 + ebx_32)
		{
			int32 edi_285;
			if (ecx_16 == 0x00)
				edi_285 = 0x00;
			else
				edi_285 = *((word32) esi_13 + 8) - ecx_16 >> 0x02;
			edi_250 = (word32) ebx_32 + edi_285;
		}
		int32 ecx_380;
		Eq_9893 ebx_314;
		ui32 edi_315;
		struct Eq_44785 * esi_316;
		word32 ecx_561;
		word32 edx_562;
		word32 ebp_563;
		Eq_3 eax_310 = fn007B2480(ebx_32, ebp, esi_13, edi_250, edi_250, out ecx_561, out edx_562, out ebx_314, out ebp_563, out esi_316, out edi_315);
		fn007B2800(dwArg04, esi_316->t0008, fn00669E20(fn007B2800(esi_316->t0004, dwArg04, eax_310), ebx_314, fp + 0x0C));
		Eq_3 eax_374 = esi_316->t0004;
		if (eax_374 == 0x00)
			ecx_380 = 0x00;
		else
			ecx_380 = esi_316->t0008 - eax_374 >> 0x02;
		ui32 ebx_387 = (word32) ebx_314 + ecx_380;
		if (eax_374 != 0x00)
			operator delete(eax_374);
		esi_316->t0004 = eax_310;
		esi_316->dw000C = (word32) eax_310 + edi_315 * 0x04;
		esi_316->t0008 = (word32) eax_310 + ebx_387 * 0x04;
	}
}

// 00620670: void fn00620670(Register Eq_3 ecx, Register Eq_3 ebp, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08)
// Called from:
//      fn00620AD0
void fn00620670(Eq_3 ecx, Eq_3 ebp, Eq_3 dwArg04, Eq_3 dwArg08)
{
	Eq_3 edi_25;
	Eq_3 esi_13 = ecx;
	Eq_3 ecx_16 = *((word32) ecx + 4);
	if (ecx_16 == 0x00)
		edi_25.u0 = 0x00;
	else
		edi_25 = *((word32) ecx + 0x0C) - ecx_16 >> 0x02;
	Eq_3 ebx_32 = dwArg08;
	if (dwArg08 == 0x00)
		return;
	Eq_44881 eax_43;
	if (ecx_16 == 0x00)
		eax_43.u0 = 0x00;
	else
		eax_43 = *((word32) ecx + 8) - ecx_16 >> 0x02;
	if (0x3FFFFFFF - eax_43 < dwArg08)
		ecx_16 = fn004DB6B0(dwArg08, ebp, ecx, edi_25, out ebx_32, out ebp, out esi_13, out edi_25);
	Eq_44894 eax_86;
	if (ecx_16 == 0x00)
		eax_86.u0 = 0x00;
	else
		eax_86 = *((word32) esi_13 + 8) - ecx_16 >> 0x02;
	if (edi_25 >=u eax_86 + ebx_32)
	{
		Eq_3 ebp_107 = *((word32) esi_13 + 8);
		int32 eax_112 = ebx_32 * 0x04;
		if (ebp_107 - dwArg04 >> 0x02 >= ebx_32)
		{
			Eq_3 ebx_120 = ebp_107 - eax_112;
			*((word32) esi_13 + 8) = fn007B2800(ebx_120, ebp_107, ebp_107);
			fn0050AAA0(dwArg04, ebx_120, ebp_107);
			fn004B3770(dwArg04, (word32) dwArg04 + eax_112, fp + 0x0C);
		}
		else
		{
			fn007B2800(dwArg04, ebp_107, (word32) dwArg04 + eax_112);
			Eq_3 eax_193 = *((word32) esi_13 + 8);
			fn00669E20(eax_193, ebx_32 - (eax_193 - dwArg04 >> 0x02), fp + 0x0C);
			*((word32) esi_13 + 8) = (word32) *((word32) esi_13 + 8) + eax_112;
			fn004B3770(dwArg04, *((word32) esi_13 + 8) - eax_112, fp + 0x0C);
		}
	}
	else
	{
		Eq_3 edi_251;
		Eq_44924 eax_246 = edi_25 >> 0x01;
		if (0x3FFFFFFF - eax_246 < edi_25)
			edi_251.u0 = 0x00;
		else
			edi_251 = edi_25 + eax_246;
		Eq_44932 eax_265;
		if (ecx_16 == 0x00)
			eax_265.u0 = 0x00;
		else
			eax_265 = *((word32) esi_13 + 8) - ecx_16 >> 0x02;
		if (edi_251 <u eax_265 + ebx_32)
		{
			int32 edi_286;
			if (ecx_16 == 0x00)
				edi_286 = 0x00;
			else
				edi_286 = *((word32) esi_13 + 8) - ecx_16 >> 0x02;
			edi_251 = (word32) ebx_32 + edi_286;
		}
		int32 ecx_381;
		Eq_9893 ebx_315;
		ui32 edi_316;
		struct Eq_44992 * esi_317;
		word32 ecx_562;
		word32 edx_563;
		word32 ebp_564;
		Eq_3 eax_311 = fn007B2480(ebx_32, ebp, esi_13, edi_251, edi_251, out ecx_562, out edx_563, out ebx_315, out ebp_564, out esi_317, out edi_316);
		fn007B2800(dwArg04, esi_317->t0008, fn00669E20(fn007B2800(esi_317->t0004, dwArg04, eax_311), ebx_315, fp + 0x0C));
		Eq_3 eax_375 = esi_317->t0004;
		if (eax_375 == 0x00)
			ecx_381 = 0x00;
		else
			ecx_381 = esi_317->t0008 - eax_375 >> 0x02;
		ui32 ebx_388 = (word32) ebx_315 + ecx_381;
		if (eax_375 != 0x00)
			operator delete(eax_375);
		esi_317->t0004 = eax_311;
		esi_317->dw000C = (word32) eax_311 + edi_316 * 0x04;
		esi_317->t0008 = (word32) eax_311 + ebx_388 * 0x04;
	}
}

// 00620AD0: Register Eq_3 fn00620AD0(Register Eq_3 ecx, Register Eq_3 ebp)
// Called from:
//      fn00620E60
Eq_3 fn00620AD0(Eq_3 ecx, Eq_3 ebp)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	((word32) ecx + 4)->u0 = 0x00;
	((word32) ecx + 8)->u0 = 0x00;
	*((word32) ecx + 0x0C) = null;
	*((word32) ecx + 16) = null;
	*((word32) ecx + 0x0098) = 0x00;
	*((word32) ecx + 0x009C) = 0x00;
	*((word32) ecx + 0x00A0) = 0x00;
	*((word32) ecx + 0x00A4) = CreateMutexA(null, 0x00, 0x00);
	*((word32) ecx + 0x00A8) = 0x00;
	*((word32) ecx + 0x00AC) = 0x00;
	WaitForSingleObject(g_tA67BF8, ~0x00);
	g_bA67BFC = 0x01;
	int32 edx_61 = g_dwA67BEC;
	Eq_3 edi_63 = g_tA67BF0;
	if (edx_61 != 0x00 && edi_63 - edx_61 >> 0x02 < g_dwA67BF4 - edx_61 >> 0x02)
	{
		*edi_63 = ecx;
		g_tA67BF0 = (word32) edi_63 + 4;
	}
	else
		fn00620670(10910696, ebp, edi_63, 0x01);
	*((word32) ecx + 20) = 0x00;
	Eq_3 edx_106 = g_tA67BF8;
	g_bA67BFC = 0x00;
	ReleaseMutex(edx_106);
	fs->ptr0000 = eax_9;
	return ecx;
}

// 00620BE0: Register Eq_3 fn00620BE0(Register Eq_3 ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn0042ACF0
Eq_3 fn00620BE0(Eq_3 ecx, Eq_3 dwArg04)
{
	Eq_3 eax_421;
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	if (g_bA67BA8 == 0x00)
		eax_421.u0 = 0x00A67BB0;
	else
	{
		Eq_3 dwArg04_461;
		Eq_23784 edx_eax_36 = __rdtsc();
		Eq_3 eax_43 = operator new(0x38);
		Eq_3 edx_39 = SLICE(edx_eax_36, word32, 32);
		Eq_3 eax_41 = (word32) edx_eax_36;
		Eq_3 ebp_408 = eax_43;
		if (eax_43 != 0x00)
		{
			basic_string((word32) eax_43 + 16, dwArg04);
			dwArg04_461 = eax_43;
		}
		else
		{
			dwArg04_461.u0 = 0x00;
			ebp_408.u0 = 0x00;
		}
		*ebp_408.u0 = eax_41;
		*((word64) ebp_408.u0 + 4) = edx_39;
		((word64) ebp_408.u0 + 8)->u0 = 0x00;
		*((word64) ebp_408.u0 + 0x0C) = null;
		Eq_29905 eax_72 = *((word32) ecx + 16);
		int32 eax_74 = eax_72 - 0x01;
		if (eax_72 >= 0x01)
		{
			word32 * ecx_100 = (word32) *((word32) ecx + 4) + (eax_72 - 0x01) * 0x04;
			do
			{
				struct Eq_45312 * edx_84 = *ecx_100;
				if ((edx_84->dw0008 | edx_84->dw000C) != 0x00)
					*((word32) ecx + 16) = (word32) *((word32) ecx + 16) - 1;
				--eax_74;
				ecx_100 -= 0x04;
			} while (eax_74 >= 0x00);
		}
		*((word64) ebp_408.u0 + 44) = *((word32) ecx + 16);
		Eq_29905 eax_116 = *((word32) ecx + 16);
		*((word64) ebp_408.u0 + 48) = *((word32) ecx + (eax_116 * 0x04 + 20));
		word32 * eax_118 = (word32) ecx + 20 + eax_116 * 0x04;
		++*eax_118;
		Eq_29905 ecx_124 = 0x00;
		Eq_3 eax_123 = *((word32) ecx + 4);
		if (eax_123 != 0x00)
			ecx_124 = *((word32) ecx + 8) - eax_123 >> 0x02;
		Eq_29905 edx_133 = *((word32) ecx + 16);
		if (ecx_124 <= edx_133)
		{
			Eq_45336 edx_149;
			if (eax_123 == 0x00)
				edx_149.u0 = 0x00;
			else
				edx_149 = *((word32) ecx + 8) - eax_123 >> 0x02;
			if (eax_123 != 0x00 && edx_149 < *((word32) ecx + 0x0C) - eax_123 >> 0x02)
			{
				Eq_3 eax_202 = *((word32) ecx + 8);
				*eax_202 = ebp_408;
				*((word32) ecx + 8) = (word32) eax_202 + 4;
			}
			else
				fn006204B0(ecx, ebp_408, *((word32) ecx + 8), 0x01);
			Eq_3 ecx_209 = *((word32) ecx + 4);
			if (ecx_209 == 0x00)
				*((word32) ecx + 16) = 0x00;
			else
				*((word32) ecx + 16) = *((word32) ecx + 8) - ecx_209 >> 0x02;
		}
		else
		{
			*((word32) eax_123 + edx_133 * 0x04) = ebp_408;
			*((word32) ecx + 16) = (word32) *((word32) ecx + 16) + 1;
		}
		Eq_45386 edx_246;
		*((word32) ecx + (*((word32) ecx + 16) * 0x04 + 20)) = 0x00;
		WaitForSingleObject(*((word32) ecx + 0x00A4), ~0x00);
		*((word32) ecx + 0x00A8) = 0x01;
		Eq_3 ecx_240 = *((word32) ecx + 0x0098);
		if (ecx_240 == 0x00)
			edx_246.u0 = 0x00;
		else
			edx_246 = *((word32) ecx + 0x009C) - ecx_240 >> 0x02;
		if (ecx_240 != 0x00 && edx_246 < *((word32) ecx + 0x00A0) - ecx_240 >> 0x02)
		{
			Eq_3 eax_298 = *((word32) ecx + 0x009C);
			*eax_298 = ebp_408;
			*((word32) ecx + 0x009C) = (word32) eax_298 + 4;
		}
		else
			fn006204B0((word32) ecx + 0x0094, ebp_408, *((word32) ecx + 0x009C), 0x01);
		struct Eq_45455 * esp_324 = fp - 0x24;
		Eq_3 ecx_305 = *((word32) ecx + 0x0098);
		if (ecx_305 != 0x00 && *((word32) ecx + 0x009C) - ecx_305 >> 0x02 > 0x0400)
		{
			struct Eq_45505 ** ecx_317 = *((word32) ecx + 0x00AC);
			if (ecx_317 != null)
			{
				Eq_3 eax_321 = *((word32) ecx + 0x0098);
				<anonymous> * edx_327 = *((const char *) *ecx_317 + 4);
				edx_327();
			}
			int32 ebp_350;
			for (ebp_350 = 0x00; ebp_350 < 0x0400; ebp_350 += 0x04)
			{
				Eq_3 ebx_360 = *((word32) *((word32) ecx + 0x0098) + ebp_350);
				if (ebx_360 != 0x00)
				{
					~basic_string((word32) ebx_360 + 16);
					union Eq_3 * esp_366 = esp_324 - 4;
					*esp_366 = (union Eq_3 *) ebx_360;
					operator delete(*esp_366);
				}
			}
			Eq_3 edx_376 = *((word32) ecx + 0x0098);
			if (edx_376 != (word32) edx_376 + 0x0400)
			{
				int32 eax_384 = *((word32) ecx + 0x009C) - ((word32) edx_376 + 0x0400);
				Eq_25048 ecx_388 = (eax_384 >> 0x02) * 0x04;
				word32 ebp_389 = ecx_388 + edx_376;
				if (eax_384 >> 0x02 > 0x00)
				{
					esp_324->tFFFFFFFC = ecx_388;
					esp_324->tFFFFFFF8 = (word32) edx_376 + 0x0400;
					esp_324->tFFFFFFF4 = ecx_388;
					esp_324->tFFFFFFF0 = edx_376;
					memmove_s(esp_324->tFFFFFFF0, esp_324->tFFFFFFF4, esp_324->tFFFFFFF8, esp_324->tFFFFFFFC);
				}
				*((word32) ecx + 0x009C) = ebp_389;
			}
			ebp_408 = esp_324->t0028;
		}
		union Eq_3 * esp_415 = esp_324 - 4;
		*esp_415 = (union Eq_3 *) *((word32) ecx + 0x00A4);
		*((word32) ecx + 0x00A8) = 0x00;
		ReleaseMutex(*esp_415);
		eax_421 = ebp_408;
	}
	fs->ptr0000 = eax_9;
	return eax_421;
}

// 00620E60: Register word32 fn00620E60(Register Eq_3 ebp)
// Called from:
//      fn0042ACF0
word32 fn00620E60(Eq_3 ebp)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	struct Eq_45606 * esi_26 = fs->ptr002C[g_dwA6B0F4];
	if (esi_26->dw0060 == 0x00)
	{
		word32 eax_38;
		Eq_3 eax_31 = operator new(0xB0);
		if (eax_31 != 0x00)
			eax_38 = fn00620AD0(eax_31, ebp);
		else
			eax_38 = 0x00;
		esi_26->dw0060 = eax_38;
	}
	word32 eax_55 = esi_26->dw0060;
	fs->ptr0000 = eax_9;
	return eax_55;
}

// 00620FC0: void fn00620FC0(Register (ptr32 Eq_29988) ecx)
// Called from:
//      fn00621250
void fn00620FC0(struct Eq_29988 * ecx)
{
	__align(fp - 4);
	Eq_3 eax_19 = ecx->t0020;
	if (eax_19 != 0x00)
	{
		if (ecx->b0024 == 0x00)
		{
			fprintf(eax_19, 0x008C64CC, 0x00);
			int32 edi_34 = 0x00;
			if (ecx->dw002C > 0x00)
			{
				do
				{
					fprintf(ecx->t0020, 9200840, 0x00);
					++edi_34;
				} while (edi_34 < ecx->dw002C);
			}
			int32 edi_58 = 0x01;
			if (ecx->dw002C > 0x01)
			{
				do
				{
					fprintf(ecx->t0020, 9200840, 0x00);
					++edi_58;
				} while (edi_58 < ecx->dw002C);
			}
			fprintf(ecx->t0020, 0x008A6DE8, 0x00);
			ecx->b0024 = 0x01;
		}
		if (ecx->dw0028 > 0x00)
		{
			struct Eq_45783 * eax_124 = fp - 0x0204;
			struct Eq_45786 * edi_125 = &ecx->a0148->dw0000;
			int32 dwLoc0230_422 = ecx->dw0028;
			do
			{
				eax_124->qw0000 = (ui64) 0x00;
				eax_124->dw0004 = 0x00;
				if (ecx->dw002C > 0x00)
				{
					int32 edx_134 = ecx->dw002C;
					struct Eq_45786 * ecx_136 = edi_125;
					do
					{
						ui64 v16_v15_406 = eax_124->qw0000 + SEQ(ebp_144, ecx_136->dw0000);
						eax_124->qw0000 = (ui64) (word32) v16_v15_406;
						ui32 ebp_144 = ecx_136->dw0004;
						eax_124->dw0004 = SLICE(v16_v15_406, word32, 32);
						++ecx_136;
						--edx_134;
					} while (edx_134 != 0x00);
				}
				int32 v17_162 = dwLoc0230_422 - 0x01;
				++eax_124;
				edi_125 = &edi_125->dw0004 + 1;
				dwLoc0230_422 = v17_162;
			} while (v17_162 != 0x00);
		}
		int32 edi_166 = 0x00;
		int32 dwLoc0228_427 = 0x00;
		if (ecx->dw0028 > 0x00)
		{
			do
			{
				fprintf(ecx->t0020, 0x008C64C4, 0x00);
				int32 ebp_192 = 0x00;
				if (ecx->dw002C > 0x00)
				{
					do
					{
						fprintf(ecx->t0020, 0x008C64C4, 0x00);
						++ebp_192;
					} while (ebp_192 < ecx->dw002C);
					edi_166 = dwLoc0228_427;
				}
				int32 ebp_268 = 0x01;
				if (ecx->dw002C > 0x01)
				{
					do
					{
						fprintf(ecx->t0020, 0x008C64C0, 0x00);
						++ebp_268;
					} while (ebp_268 < ecx->dw002C);
					edi_166 = dwLoc0228_427;
				}
				fprintf(ecx->t0020, 0x008A6DE8, 0x00);
				++edi_166;
				dwLoc0228_427 = edi_166;
			} while (edi_166 < ecx->dw0028);
		}
	}
	if (ecx->dw0028 > 0x00)
	{
		struct Eq_45725 * ebp_340 = ecx->a0348;
		struct Eq_45728 * ebx_341 = &ecx->a0148->dw0000;
		int32 edi_342 = 0x00;
		do
		{
			int32 edx_343 = 0x00;
			if (ecx->dw002C > 0x00)
			{
				struct Eq_45728 * eax_349 = ebx_341;
				struct Eq_45725 * ecx_351 = ebp_340;
				do
				{
					ecx_351->dw0000 = 0x00;
					eax_349->dw0000 = 0x00;
					eax_349->dw0004 = 0x00;
					++edx_343;
					++ecx_351;
					++eax_349;
				} while (edx_343 < ecx->dw002C);
			}
			++edi_342;
			ebx_341 = &ebx_341->dw0004 + 1;
			ebp_340 = &ebp_340->dw0000 + 1;
		} while (edi_342 < ecx->dw0028);
	}
}

