// sho_text_000A.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 004AB550: void fn004AB550(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack (ptr32 word32) dwArg0C, Stack Eq_3 dwArg10)
// Called from:
//      fn00621C70
void fn004AB550(Eq_3 dwArg04, Eq_3 dwArg08, word32 * dwArg0C, Eq_3 dwArg10)
{
	Eq_3 edx_28 = dwArg10;
	word32 * ecx_23 = dwArg0C;
	if (dwArg08 >= dwArg10)
	{
		if (dwArg10 > 0x00)
		{
			int32 esi_21 = dwArg04 - dwArg0C;
			do
			{
				ecx_23[esi_21] = *ecx_23;
				--edx_28;
				++ecx_23;
			} while (edx_28 > 0x00);
		}
	}
	else
		_invalid_parameter_noinfo();
}

