// sho_text_001D.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 005D9410: Register (ptr32 Eq_43646) fn005D9410(Register Eq_43647 ebx, Register Eq_3 esi, Register Eq_43649 edi, Stack Eq_43649 dwArg04, Register out Eq_3 esiOut, Register out Eq_43649 ediOut)
// Called from:
//      fn00622B40
struct std::basic_string * fn005D9410(Eq_43647 ebx, Eq_3 esi, Eq_43649 edi, Eq_43649 dwArg04, union Eq_3 & esiOut, union Eq_43649 & ediOut)
{
	Eq_43649 ecx_5 = dwArg04;
	if (dwArg04 <= 0x00)
		ecx_5.u0 = 0x00;
	else if ((uint32) (0xFFFFFFFF /u dwArg04) < 0x08)
	{
		struct Eq_43669 * esp_33;
		CxxThrowException();
		int3();
		int3();
		int3();
		int3();
		int3();
		esp_33->tFFFFFFFC = ebx;
		basic_string * ebx_42 = esp_33->ptr0004;
		esp_33->tFFFFFFF8 = esi;
		basic_string * esi_46 = esp_33->ptr0008;
		if (ebx_42 == esi_46)
		{
			struct std::basic_string * eax_49 = esp_33->ptr000C;
			esiOut = esp_33->tFFFFFFF8;
			ediOut = edi;
			return eax_49;
		}
		else
		{
			esp_33->tFFFFFFF4 = edi;
			struct std::basic_string * edi_57 = esp_33->ptr000C;
			do
			{
				esi_46 -= 0x20;
				esp_33->ptrFFFFFFF0 = esi_46;
				edi_57 -= 0x20;
				operator =(edi_57, esp_33->ptrFFFFFFF0);
				edi_57->b001C = esi_46->b001C;
			} while (esi_46 != ebx_42);
			Eq_43649 edi_74 = esp_33->tFFFFFFF4;
			esiOut = esp_33->tFFFFFFF8;
			ediOut = edi_74;
			return edi_57;
		}
	}
	struct std::basic_string * eax_88 = operator new(ecx_5 * 0x08);
	esiOut = esi;
	ediOut = edi;
	return eax_88;
}

// 005DE860: Register (ptr32 Eq_43740) fn005DE860(Register (ptr32 Eq_33239) esi, Stack (ptr32 Eq_33239) dwArg04, Register out Eq_33666 edxOut, Register out (ptr32 Eq_33239) esiOut)
// Called from:
//      fn0044D520
//      fn0044F1E0
//      fn005A5370
struct std::basic_string * fn005DE860(struct Eq_33239 * esi, struct Eq_33239 * dwArg04, union Eq_33666 & edxOut, struct Eq_33239 & esiOut)
{
	struct Eq_33239 * ecx_5 = dwArg04;
	if (dwArg04 <= null)
		ecx_5 = null;
	else
	{
		edx.u0 = (uint32) (0xFFFFFFFF % dwArg04);
		if ((uint32) (0xFFFFFFFF /u dwArg04) < 0x10)
		{
			struct Eq_43761 * esp_33;
			word32 ecx_34;
			Eq_33666 edx_36;
			CxxThrowException();
			int3();
			int3();
			int3();
			int3();
			int3();
			int3();
			int3();
			int3();
			int3();
			esp_33->dwFFFFFFFC = ecx_34;
			esp_33->ptrFFFFFFF8 = esi;
			struct std::basic_string * esi_44 = esp_33->ptr0004;
			esp_33->ptrFFFFFFF4 = ecx_34 + 0x1C;
			esp_33->dwFFFFFFFC = 0x00;
			basic_string(esi_44, esp_33->ptrFFFFFFF4);
			struct Eq_33239 * esi_54 = esp_33->ptrFFFFFFF8;
			edxOut = edx_36;
			esiOut = esi_54;
			return esi_44;
		}
	}
	struct std::basic_string * eax_66 = operator new(ecx_5 << 0x04);
	edxOut = edx;
	esiOut = esi;
	return eax_66;
}

