// sho_text_0025.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 00651DD0: Register Eq_3 fn00651DD0(Register out ptr32 esiOut)
// Called from:
//      fn0042DF20
Eq_3 fn00651DD0(ptr32 & esiOut)
{
	ptr32 esi_24;
	word32 edx_41;
	Eq_3 eax_23 = fn006EA200(out edx_41, out esi_24);
	esiOut = esi_24;
	return eax_23;
}

// 00656460: Register word32 fn00656460(Stack Eq_3 dwArg04, Register out Eq_540 ecxOut, Register out Eq_540 edxOut)
// Called from:
//      fn006F6BF0
//      fn006F7890
word32 fn00656460(Eq_3 dwArg04, union Eq_540 & ecxOut, union Eq_540 & edxOut)
{
	basic_string(fp - 0x1C, dwArg04);
	struct Eq_51266 ** ecx_16 = g_ptrA69A38;
	<anonymous> * edx_18 = *((const char *) *ecx_16 + 4);
	word32 eax_25;
	edx_18();
	~basic_string(fp - 0x1C);
	if (eax_25 == 0x01)
	{
		ecxOut.u0 = <invalid>;
		edxOut.u0 = <invalid>;
		return 0x01;
	}
	else if (eax_25 == 0x02)
	{
		ecxOut.u0 = <invalid>;
		edxOut.u0 = <invalid>;
		return 0x00;
	}
	else
	{
		ecxOut.u0 = <invalid>;
		edxOut.u0 = <invalid>;
		return ~0x00;
	}
}

// 00656570: Register word32 fn00656570(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Register out ptr32 ecxOut, Register out Eq_3 ediOut)
// Called from:
//      fn0042DF20
word32 fn00656570(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, ptr32 & ecxOut, union Eq_3 & ediOut)
{
	ui32 eax_7 = g_tA14188 ^ fp - 0x0104;
	Eq_3 eax_17 = *((word32) dwArg04 + 4);
	if (eax_17 != 10610664)
	{
		word32 ecx_381;
		word32 edx_382;
		if (fn006D5670(eax_17, 10610664, out ecx_381, out edx_382) == 0x00)
		{
			Eq_3 eax_91 = *((word32) dwArg04 + 4);
			if (eax_91 != 0x00A1B450)
			{
				word32 edx_386;
				word32 ecx_385;
				if (fn006D5670(eax_91, 0x00A1B450, out ecx_385, out edx_386) == 0x00)
					goto l00656622;
			}
			Eq_3 edx_117;
			word32 esi_384;
			word32 ecx_383;
			Eq_3 eax_115 = fn006ECC50(dwArg04, out ecx_383, out edx_117, out esi_384);
			if (_stricmp(eax_115, "true") == 0x00)
			{
				*dwArg08 = 0x01;
				goto l006565F5;
			}
			int32 eax_138 = _stricmp(eax_115, "false");
			int8 al_232 = (byte) eax_138;
			if (eax_138 == 0x00)
			{
				*dwArg08 = al_232;
l006565F5:
				ptr32 ecx_265;
				word32 eax_264 = fn00694B8E(0x00, eax_7 ^ fp - 0x0104, edx_117, ebx, ebp, esi, edi, es, ds, ebx, out ecx_265);
				ecxOut = ecx_265;
				ediOut = edi;
				return eax_264;
			}
l00656622:
			Eq_3 eax_145 = dwArg0C;
			Eq_51385 edx_147 = fp - 0x0104 - dwArg0C;
			do
			{
				byte cl_151 = *eax_145;
				Mem153[edx_147 + eax_145:byte] = cl_151;
				eax_145 = (word32) eax_145 + 1;
			} while (cl_151 != 0x00);
			struct Eq_51423 * edi_160 = fp - 0x0105 + 0x01;
			do
			{
				edi_160 = edi_388 + 1;
				edi_388 = edi_160;
			} while (edi_388->w0000 != 0x00);
			word32 ecx_169;
			struct Eq_51438 * esi_170 = g_a8CA588;
			for (ecx_169 = 0x05; ecx_169 != 0x00; --ecx_169)
			{
				edi_160->w0000 = esi_170->w0000;
				++esi_170;
				edi_160 += 4;
			}
			Eq_3 ecx_173 = g_tA16B7C;
			edi_160->w0000 = esi_170->w0000;
			edi_160[2] = (struct Eq_51423) esi_170->b0002;
			word32 ecx_387;
			Eq_3 edx_192;
			fn006E0F80(ecx_173, fp - 0x0104, out ecx_387, out edx_192);
			ptr32 ecx_218;
			word32 eax_217 = fn00694B8E(~0x00, eax_7 ^ fp - 0x0104, edx_192, ebx, ebp, esi, edi, es, ds, ebx, out ecx_218);
			ecxOut = ecx_218;
			ediOut = edi;
			return eax_217;
		}
	}
	word32 edx_43;
	Eq_3 edi_44;
	word32 esi_380;
	word32 ecx_379;
	int8 dl_54 = (int8) (fn007051A0(edi, dwArg04, out ecx_379, out edx_43, out esi_380, out edi_44) != 0x00);
	*dwArg08 = dl_54;
	ptr32 ecx_82;
	word32 eax_81 = fn00694B8E(0x00, eax_7 ^ fp - 0x0104, SEQ(SLICE(edx_43, word24, 8), dl_54), ebx, ebp, esi, edi_44, es, ds, ebx, out ecx_82);
	ecxOut = ecx_82;
	ediOut = edi_44;
	return eax_81;
}

// 00657140: Register Eq_3 fn00657140(Register Eq_3 ebx, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 bArg10)
// Called from:
//      fn0041F300
//      fn0042DF20
Eq_3 fn00657140(Eq_3 ebx, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 bArg10)
{
	word24 ebx_24_8_47 = SLICE(ebx, word24, 8);
	Eq_3 esi_23 = dwArg04;
	Eq_3 ebx_522 = SEQ(ebx_24_8_47, bArg10);
	if (fn006E0FC0() != 0x00)
	{
		Eq_3 ebx_48 = SEQ(ebx_24_8_47, bArg10);
		if (bArg10 == 0x00)
		{
l0065715E:
			word32 ebp_525;
			word32 edi_526;
			ebx_522 = fn006E8D90(ebx_48, dwArg04, edi, es, ds, out ebp_525, out esi_23, out edi_526);
			goto l00657168;
		}
		ebx_522 = SEQ(ebx_24_8_47, bArg10);
		if (dwArg04 != 0x00)
			goto l0065715E;
	}
l00657168:
	word32 ecx_110;
	byte bl_78 = (byte) ebx_522;
	struct Eq_51505 * esp_171 = fp - 20;
	Eq_3 dwArg04_405 = 0x00;
	if (esi_23 != 0x00)
	{
		if (dwArg08 != 0x00)
		{
			if (fn006DF870(esi_23) != 0x00)
			{
				word32 edx_529;
				dwArg04_405 = fn007036F0(out ecx_110, out edx_529);
			}
			else
			{
				word32 edx_528;
				fn006E15D0(g_tA16B7C, 0x008CA78C, out ecx_110, out edx_528);
			}
l006571D9:
			esp_171 = fp - 0x14;
			if (esi_23 != 0x00)
			{
				word32 v14_165 = (word32) *esi_23 - 1;
				*esi_23 = v14_165;
				if (v14_165 == 0x00)
				{
					struct Eq_51591 * edx_169 = *((word32) esi_23 + 4);
					word32 esp_206;
					edx_169->ptr0018();
					esp_171 = esp_206 + 0x04;
				}
			}
			goto l006571EE;
		}
	}
	else if (dwArg08 != 0x00 && bl_78 != 0x00)
	{
		word32 edx_531;
		word32 ecx_530;
		fn006E1160(out ecx_530, out edx_531);
l006571EE:
		if (dwArg08 != 0x00)
		{
			word32 v16_219 = (word32) *dwArg08 - 1;
			*dwArg08 = v16_219;
			if (v16_219 == 0x00)
			{
				Eq_3 ecx_223 = *((word32) dwArg08 + 4);
				<anonymous> * edx_224 = *((word32) ecx_223 + 24);
				esp_171->tFFFFFFFC = dwArg08;
				word32 esp_238;
				edx_224();
				esp_171 = esp_238 + 0x04;
			}
		}
		if (esp_171->b0028 != 0x00)
		{
			Eq_3 eax_250 = fn006E0FC0();
			if (eax_250 != 0x00)
			{
				struct Eq_51642 * esp_256 = esp_171 - 4;
				esp_256->t0000 = &esp_171->b0028;
				esp_256->tFFFFFFFC = (const char *) &esp_256->t0000 + 32;
				esp_256->tFFFFFFF8 = (const char *) &esp_256->t0000 + 20;
				fn006E1130(esp_256->tFFFFFFF8, esp_256->tFFFFFFFC, esp_256->t0000);
				esp_256->tFFFFFFF4 = eax_250;
				Eq_3 edi_275;
				word32 edx_534;
				esp_256->tFFFFFFF0 = fn006DDF70(esp_256->tFFFFFFF4, out edx_534, out edi_275);
				Eq_3 esi_288;
				word32 ecx_535;
				word32 edx_536;
				esp_256->tFFFFFFEC = fn006ECC50(esp_256->tFFFFFFF0, out ecx_535, out edx_536, out esi_288);
				esp_256->tFFFFFFE8 = dwArg0C;
				esp_256->dwFFFFFFE4 = 0x008CA71C;
				fn00520C80();
				word32 v17_301 = (word32) *esi_288 - 1;
				*esi_288 = v17_301;
				struct Eq_51726 * esp_300 = (const char *) &esp_256->t0000 + 4;
				if (v17_301 == 0x00)
				{
					struct Eq_51591 * eax_305 = *((word32) esi_288 + 4);
					<anonymous> * ecx_306 = eax_305->ptr0018;
					esp_256->t0000 = esi_288;
					word32 esp_317;
					ecx_306();
					esp_300 = esp_317 + 0x04;
				}
				word32 eax_328 = esp_300->dw001C;
				word32 ecx_329 = esp_300->dw0010;
				struct Eq_51739 * esp_330 = esp_300 - 4;
				esp_330->t0000 = esp_300->t0028;
				esp_330->dwFFFFFFFC = eax_328;
				esp_330->dwFFFFFFF8 = ecx_329;
				word32 edx_538;
				word32 ecx_537;
				fn006E0E00(esp_330->t0000, out ecx_537, out edx_538);
				esp_330->dwFFFFFFF4 = 0x00;
				word32 esi_540;
				word32 edi_541;
				word32 ebp_539;
				fn006E8D90(ebx_522, esi_288, edi_275, es, ds, out ebp_539, out esi_540, out edi_541);
			}
			word32 ecx_532;
			word32 edx_533;
			fn006E1160(out ecx_532, out edx_533);
		}
		return dwArg04_405;
	}
	word32 edx_527;
	fn006E15D0(g_tA17E2C, 0x008CA748, out ecx_110, out edx_527);
	goto l006571D9;
}

// 00657290: Register word32 fn00657290(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Register out Eq_3 ebxOut, Register out Eq_540 ebpOut)
// Called from:
//      fn00723540
word32 fn00657290(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04, Eq_3 dwArg08, union Eq_3 & ebxOut, union Eq_540 & ebpOut)
{
	ui32 eax_7 = g_tA14188 ^ fp - 0x3C;
	basic_string(fp - 0x20, dwArg04);
	Eq_3 ebp_34;
	Eq_3 ebx_35;
	word32 edx_192;
	word32 edi_193;
	struct Eq_51835 ** eax_42 = fn00401700(fn004048C0(ebx, ebp, dwArg04, edi, es, ds, out edx_192, out ebx_35, out ebp_34, out edi_193));
	<anonymous> * edx_44 = *((const char *) *eax_42 + 4);
	Eq_3 eax_52;
	Eq_3 edx_54;
	edx_44();
	~basic_string(fp - 0x20);
	if (eax_52 != 0x02)
	{
		word32 ecx_194;
		word32 eax_70 = fn00694B8E(0x00, eax_7 ^ fp - 60, edx_54, ebx_35, ebp_34, esi, edi, es, ds, esi, out ecx_194);
		ebxOut = ebx_35;
		ebpOut.u0 = <invalid>;
		return eax_70;
	}
	else
	{
		basic_string(fp - 0x3C, dwArg04);
		Eq_3 ebx_92 = fn00405370(ebp_34, dwArg04, eax_52, es, ds, fp - 0x20, fp - 0x3C);
		~basic_string(fp - 0x3C);
		c_str(fp - 0x20);
		fn00520C80();
		Eq_3 eax_119 = fn007234D0(dwArg08, ebx_92, ebp_34, dwArg04, eax_52, es, ds, c_str(fp - 0x20));
		~basic_string(fp - 0x20);
		word32 ecx_195;
		word32 eax_139 = fn00694B8E(eax_119, eax_7 ^ fp - 60, dwArg08, ebx_92, ebp_34, esi, edi, es, ds, esi, out ecx_195);
		ebxOut = ebx_92;
		ebpOut.u0 = <invalid>;
		return eax_139;
	}
}

// 00657370: void fn00657370(Register (ptr32 word32) ecx)
// Called from:
//      fn00420C00
void fn00657370(word32 * ecx)
{
	*ecx = 0x008CA578;
}

// 00659040: Register word32 fn00659040(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Register out Eq_3 edxOut, Register out Eq_540 ebxOut, Register out Eq_540 ebpOut)
// Called from:
//      fn006E1AB0
//      fn006F6630
//      fn006F6810
//      fn006F7890
//      fn0072F830
word32 fn00659040(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04, Eq_3 dwArg08, union Eq_3 & edxOut, union Eq_540 & ebxOut, union Eq_540 & ebpOut)
{
	ui32 eax_7 = g_tA14188 ^ fp - 0x6C;
	basic_string(fp - 88, dwArg04);
	struct Eq_51266 ** ecx_24 = g_ptrA69A38;
	<anonymous> * eax_26 = *((const char *) *ecx_24 + 36);
	Eq_3 eax_33;
	Eq_3 edx_35;
	eax_26();
	~basic_string(fp - 88);
	Eq_3 esi_101 = dwArg04;
	if (eax_33 != 0x00)
	{
		const char * eax_52 = strrchr(dwArg04, 0x2F);
		const char * edi_57 = eax_52;
		const char * eax_58 = strrchr(dwArg04, 0x5C);
		if (eax_58 != null && eax_52 < eax_58)
			edi_57 = eax_58;
		Eq_51993 eax_70;
		if (edi_57 != null)
			eax_70 = edi_57 - dwArg04;
		else
			eax_70.u0 = 0x00;
		basic_string(fp - 0x20, dwArg04, eax_70);
		if (edi_57 != null)
			esi_101 = edi_57 + 1;
		basic_string(fp - 0x3C, esi_101);
		struct Eq_51266 ** ecx_106 = g_ptrA69A38;
		<anonymous> * edx_108 = *((const char *) *ecx_106 + 0x0C);
		edx_108();
		uint32 edi_129 = 0x00;
		word32 ebx_130 = 0x00;
		while (dwLoc64 != null)
		{
			int32 ecx_141 = dwLoc60 - dwLoc64;
			int32 edx_145 = SLICE(ecx_141 *s64 0x92492493, word32, 32) + ecx_141;
			if (edi_129 >= ((edx_145 >> 0x04) >> 0x1F) + (edx_145 >> 0x04))
				break;
			word32 eax_249 = dwLoc64 + ebx_130;
			word32 eax_257;
			Eq_3 edx_259;
			MSVCP80.dll!??$?8DU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@0@Z();
			if ((byte) eax_257 != 0x00)
			{
				fn00403900(fp - 0x68);
				~basic_string(fp - 0x3C);
				~basic_string(fp - 0x20);
				word32 ecx_477;
				word32 eax_289 = fn00694B8E(eax_33, eax_7 ^ fp - 0x6C, edx_259, ebx, ebp, esi, edi, es, ds, esi, out ecx_477);
				edxOut = edx_259;
				ebxOut.u0 = <invalid>;
				ebpOut.u0 = <invalid>;
				return eax_289;
			}
			++edi_129;
			ebx_130 += 0x1C;
		}
		fclose(eax_33);
		struct std::basic_string * esi_159 = dwLoc64;
		if (dwLoc64 != null)
		{
			if (dwLoc64 != dwLoc60)
			{
				do
				{
					~basic_string(esi_159);
					esi_159 = (struct std::basic_string *) ((const char *) esi_159 + 28);
				} while (esi_159 != dwLoc60);
			}
			operator delete(dwLoc64);
		}
		~basic_string(fp - 0x3C);
		~basic_string(fp - 0x20);
		word32 ecx_478;
		word32 eax_237 = fn00694B8E(0x00, eax_7 ^ fp - 0x006C, eax_33, ebx, ebp, esi, edi, es, ds, esi, out ecx_478);
		edxOut = eax_33;
		ebxOut.u0 = <invalid>;
		ebpOut.u0 = <invalid>;
		return eax_237;
	}
	else
	{
		word32 ecx_476;
		word32 eax_317 = fn00694B8E(0x00, eax_7 ^ fp - 0x006C, edx_35, ebx, ebp, esi, edi, es, ds, esi, out ecx_476);
		edxOut = edx_35;
		ebxOut.u0 = <invalid>;
		ebpOut.u0 = <invalid>;
		return eax_317;
	}
}

