// sho_text_0026.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 006641A0: void fn006641A0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00622B40
void fn006641A0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ecx_13 = dwArg08;
	Eq_3 eax_17 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			eax_17 -= 0x08;
			*eax_17 = *((word32) ecx_13 - 8);
			ecx_13 -= 0x08;
			*((word32) eax_17 + 4) = *((word32) ecx_13 + 4);
		} while (ecx_13 != dwArg04);
	}
}

// 00669E20: Register word32 fn00669E20(Stack Eq_3 dwArg04, Stack Eq_9893 dwArg08, Stack (ptr32 word32) dwArg0C)
// Called from:
//      fn00409AC0
//      fn004119C0
//      fn00417890
//      fn0041DA20
//      fn006204B0
//      fn00620670
//      fn00622070
word32 fn00669E20(Eq_3 dwArg04, Eq_9893 dwArg08, word32 * dwArg0C)
{
	Eq_9893 eax_14 = dwArg08;
	Eq_3 ecx_15 = dwArg04;
	if (dwArg08 > 0x00)
	{
		do
		{
			*ecx_15 = *dwArg0C;
			--eax_14;
			ecx_15 = (word32) ecx_15 + 4;
		} while (eax_14 > 0x00);
	}
	return (word32) dwArg04 + dwArg08 * 0x04;
}

