// sho_text_000C.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 004C8820: Register (ptr32 Eq_34213) fn004C8820()
// Called from:
//      fn005B62A0
//      fn005B65B0
struct Eq_34213 * fn004C8820()
{
	struct Eq_34213 * eax_6 = operator new(0x0C);
	if (eax_6 != null)
		eax_6->ptr0000 = eax_6;
	if (eax_6 != (struct Eq_34213 *) 0x04)
		eax_6->ptr0004 = eax_6;
	return eax_6;
}

// 004CDDA0: Register word32 fn004CDDA0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00414B80
word32 fn004CDDA0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	fn00417C60(dwArg04, dwArg08, dwArg0C);
	return (word32) dwArg04 + dwArg08 * 0x04;
}

