// sho_text_0002.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 00421080: void fn00421080(Register (ptr32 Eq_25698) ecx, Stack (ptr32 charconst ) dwArg04)
// Called from:
//      fn0042B310
void fn00421080(struct std::exception * ecx, const char * dwArg04)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	basic_string(fp - 0x28, dwArg04);
	fn0041F1A0(ecx, fp - 0x28);
	~basic_string(fp - 0x28);
	ecx->dw0000 = 0x008A89B0;
	fs->ptr0000 = eax_9;
}

// 00421E80: Register byte fn00421E80(Register Eq_3 ecx, Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04, Register out Eq_3 ebpOut, Register out Eq_3 esiOut, Register out Eq_3 ediOut, Register out Eq_26902 xmm0Out)
// Called from:
//      fn0042DF20
byte fn00421E80(Eq_3 ecx, Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04, union Eq_3 & ebpOut, union Eq_3 & esiOut, union Eq_3 & ediOut, union Eq_26902 & xmm0Out)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	Eq_3 eax_23 = *((word32) dwArg04 + 4);
	byte bLoc29_289 = 0x01;
	if (eax_23 <= 0xB7)
	{
		Eq_3 edi_142;
		Eq_3 esi_144;
		Eq_3 ebp_140;
		Eq_3 ebx_141;
		word32 eax_28 = (word32) *((word32) eax_23 + 4333505);
		switch (eax_28)
		{
		case 0x00:
			if (((byte) (*((word32) dwArg04 + 8) >> 0x02) & 0x01) == 0x00)
				goto l00421FA0;
			Eq_3 ebx_177;
			word32 edx_379;
			Eq_3 eax_174 = fn005A74F0(ebx, ebp, esi, edi, es, ds, out edx_379, out ebx_177, out ebp, out esi, out edi, out xmm0);
			if (*((word32) eax_174 + 0x00A8) != 0x00)
			{
				Eq_3 ebx_193;
				word32 edx_380;
				Eq_3 eax_190 = fn005A74F0(ebx_177, ebp, esi, edi, es, ds, out edx_380, out ebx_193, out ebp, out esi, out edi, out xmm0);
				if (*((word32) eax_190 + 0x006C) == 0x00)
				{
					word32 edx_381;
					word128 xmm0_382;
					fn005A74F0(ebx_193, ebp, esi, edi, es, ds, out edx_381, out ebx_141, out ebp_140, out esi_144, out edi_142, out xmm0_382);
					goto l00421F8E;
				}
			}
			break;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case 0x09:
		case 0x0A:
		case 11:
		case 0x0C:
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 22:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case 0x20:
		case 33:
		case 0x22:
		case 0x23:
		case 0x24:
		case 0x25:
		case 0x26:
		case 0x27:
		case 0x28:
		case 0x29:
		case 0x2A:
		case 0x2B:
		case 44:
		case 0x2D:
		case 0x2E:
		case 0x30:
		case 0x31:
		case 0x32:
		case 0x33:
		case 0x34:
		case 0x35:
		case 0x36:
		case 55:
		case 0x38:
		case 0x39:
		case 0x3A:
		case 0x3B:
		case 0x3C:
		case 0x3D:
		case 0x3E:
		case 0x3F:
		case 0x40:
		case 0x41:
		case 66:
		case 0x43:
		case 0x44:
		case 0x45:
		case 0x46:
		case 0x47:
		case 0x48:
		case 0x49:
		case 0x4A:
		case 0x4B:
		case 0x4C:
		case 77:
		case 0x4E:
		case 0x4F:
		case 0x50:
		case 0x51:
		case 0x52:
		case 0x53:
		case 0x54:
		case 0x55:
		case 0x56:
		case 0x57:
		case 88:
		case 0x59:
		case 0x5A:
		case 0x5B:
		case 0x5C:
		case 0x5D:
		case 0x5E:
		case 0x5F:
		case 0x60:
		case 0x61:
		case 0x62:
		case 99:
		case 100:
		case 101:
		case 0x66:
		case 0x67:
		case 0x68:
		case 0x69:
		case 0x6A:
		case 0x6B:
		case 0x6C:
		case 0x6D:
		case 110:
		case 111:
		case 0x70:
		case 113:
		case 114:
		case 115:
		case 116:
		case 117:
		case 118:
		case 0x77:
		case 0x78:
		case 121:
		case 122:
		case 0x7B:
		case 0x7C:
		case 0x7D:
		case 0x7E:
		case 0x7F:
		case 0x80:
		case 0x81:
		case 0x82:
		case 131:
		case 0x84:
		case 133:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 141:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 151:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 155:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 161:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 166:
		case 0xA7:
			goto l00421FA0;
		case 0x0D:
			if (g_bA69758 == 0x00 && g_bA697D8 == 0x00)
				goto l00421FA0;
			Eq_3 ebx_107;
			word32 edx_373;
			Eq_3 eax_104 = fn005A74F0(ebx, ebp, esi, edi, es, ds, out edx_373, out ebx_107, out ebp, out esi, out edi, out xmm0);
			if (*((word32) eax_104 + 0x00A8) != 0x00)
			{
				Eq_3 ebp_123;
				word32 ebx_124;
				Eq_3 edi_125;
				Eq_3 esi_127;
				word128 xmm0_377;
				word32 edx_376;
				word128 xmm0_375;
				word32 edx_374;
				fn005A74F0(SEQ(SLICE(ebx_124, word24, 8), *((word32) fn005A74F0(ebx_107, ebp, esi, edi, es, ds, out edx_374, out ebx_124, out ebp_123, out esi_127, out edi_125, out xmm0_375) + 0x006C)), ebp_123, esi_127, edi_125, es, ds, out edx_376, out ebx_141, out ebp_140, out esi_144, out edi_142, out xmm0_377);
l00421F8E:
				Eq_3 ebx_245;
				Eq_3 edx_247;
				word128 xmm0_378;
				eax_24_8_335 = SLICE((uint32) fn005A7560(fn005A74F0(ebx_141, ebp_140, esi_144, edi_142, es, ds, out edx_247, out ebx_245, out ebp, out esi, out edi, out xmm0_378), edx_247, ebx_245, ebp, esi, edi, es, ds, 0x00, out xmm0), word24, 8);
			}
			break;
		case 0x2F:
			if (((byte) (*((word32) dwArg04 + 8) >> 0x02) & 0x01) != 0x00)
				PostMessageA(*((word32) ecx + 0x04E8), 0x10, 0x00, 0x00);
			break;
		case 0xA8:
			basic_string * eax_30 = basic_string(fp - 0x28);
			Eq_3 ebx_45;
			word128 xmm0_372;
			word32 edx_371;
			fn005A74F0(ebx, ebp, esi, edi, es, ds, out edx_371, out ebx_45, out ebp, out esi, out edi, out xmm0_372);
			xmm0 = fn005A7E10(ebx_45, ebp, esi, edi, es, ds, eax_30);
			~basic_string(fp - 0x28);
			break;
		}
	}
	else
	{
l00421FA0:
		bLoc29_289 = 0x00;
	}
	fs->ptr0000 = eax_9;
	ebpOut = ebp;
	esiOut = esi;
	ediOut = edi;
	xmm0Out = xmm0;
	return bLoc29_289;
}

// 00422220: Register Eq_3 fn00422220(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack (ptr32 word32) dwArg0C, Register out Eq_3 edxOut)
// Called from:
//      fn004295F0
Eq_3 fn00422220(Eq_3 dwArg04, Eq_3 dwArg08, word32 * dwArg0C, union Eq_3 & edxOut)
{
	Eq_3 eax_19 = dwArg04;
	if (dwArg04 != dwArg08)
	{
		do
		{
			Eq_3 edi_20 = eax_19;
			eax_19 = (word32) eax_19 + 332;
			word32 ecx_24;
			word32 * esi_26 = dwArg0C;
			for (ecx_24 = 0x53; ecx_24 != 0x00; --ecx_24)
			{
				*edi_20 = *esi_26;
				++esi_26;
				edi_20 = (word32) edi_20 + 4;
			}
		} while (eax_19 != dwArg08);
	}
	edxOut = dwArg08;
	return eax_19;
}

// 00422320: Register Eq_3 fn00422320(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Register out Eq_3 edxOut)
// Called from:
//      fn00428ED0
//      fn004295F0
Eq_3 fn00422320(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, union Eq_3 & edxOut)
{
	Eq_3 edx_24 = dwArg04;
	Eq_3 eax_19 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			if (eax_19 != 0x00)
			{
				word32 ecx_23;
				Eq_3 esi_25 = edx_24;
				Eq_3 edi_26 = eax_19;
				for (ecx_23 = 0x53; ecx_23 != 0x00; --ecx_23)
				{
					*edi_26 = *esi_25;
					esi_25 = (word32) esi_25 + 4;
					edi_26 = (word32) edi_26 + 4;
				}
			}
			edx_24 = (word32) edx_24 + 332;
			eax_19 = (word32) eax_19 + 332;
		} while (edx_24 != dwArg08);
	}
	edxOut = edx_24;
	return eax_19;
}

// 00422980: Register byte fn00422980(Register Eq_3 ecx, Register Eq_3 esi, Register Eq_3 edi, Stack uint32 dwArg04)
// Called from:
//      fn0042CFC0
byte fn00422980(Eq_3 ecx, Eq_3 esi, Eq_3 edi, uint32 dwArg04)
{
	((word32) ecx + 4)->u0 = 0x00;
	((word32) ecx + 8)->u0 = 0x00;
	*((word32) ecx + 0x0C) = 0x00;
	if (dwArg04 == 0x00)
		return 0x00;
	if (dwArg04 > 0x04924924)
		fn00420860(edi, esi);
	struct Eq_27220 * esi_43;
	word32 eax_40 = fn00420B90(ecx, dwArg04, out esi_43);
	esi_43->dw0004 = eax_40;
	esi_43->dw0008 = eax_40;
	esi_43->dw000C = eax_40 + (dwArg04 * 0x08 - dwArg04) * 0x08;
	return 0x01;
}

// 004229E0: void fn004229E0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack (ptr32 int32) dwArg10, Stack byte bArg14)
// Called from:
//      fn00424A20
void fn004229E0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, int32 * dwArg10, byte bArg14)
{
	ptr32 eax_13 = fs->ptr0000;
	fs->ptr0000 = fp - 0x10;
	struct Eq_27259 * eax_35 = operator new(0x30);
	if (eax_35 != null)
	{
		eax_35->t0000 = dwArg04;
		eax_35->t0004 = dwArg08;
		eax_35->t0008 = dwArg0C;
		eax_35->dw000C = *dwArg10;
		basic_string(&eax_35->dw000C + 1, dwArg10 + 1);
		eax_35->b002C = bArg14;
		eax_35->b002D = 0x00;
	}
	fs->ptr0000 = eax_13;
}

// 00422A90: void fn00422A90(Stack (ptr32 word32) dwArg04)
// Called from:
//      fn00407CD0
//      fn0042F170
//      fn00621380
void fn00422A90(word32 * dwArg04)
{
	*dwArg04 = 0x00;
}

// 00422AE0: void fn00422AE0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn004295F0
void fn00422AE0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 edx_19 = dwArg08;
	Eq_3 eax_21 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			edx_19 -= 332;
			eax_21 -= 332;
			word32 ecx_25;
			Eq_3 esi_26 = edx_19;
			Eq_3 edi_27 = eax_21;
			for (ecx_25 = 0x53; ecx_25 != 0x00; --ecx_25)
			{
				*edi_27 = *esi_26;
				esi_26 = (word32) esi_26 + 4;
				edi_27 = (word32) edi_27 + 4;
			}
		} while (edx_19 != dwArg04);
	}
}

// 00422B20: void fn00422B20(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00426470
//      fn0042B1F0
void fn00422B20(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 edx_32 = dwArg08;
	if (dwArg08 > 0x00)
	{
		Eq_3 eax_10 = dwArg04;
		do
		{
			if (eax_10 != 0x00)
			{
				word32 ecx_25;
				Eq_3 esi_27 = dwArg0C;
				Eq_3 edi_28 = eax_10;
				for (ecx_25 = 0x53; ecx_25 != 0x00; --ecx_25)
				{
					*edi_28 = *esi_27;
					esi_27 = (word32) esi_27 + 4;
					edi_28 = (word32) edi_28 + 4;
				}
			}
			--edx_32;
			eax_10 = (word32) eax_10 + 332;
		} while (edx_32 > 0x00);
	}
}

// 00422DB0: Register Eq_3 fn00422DB0(Register (ptr32 (ptr32 Eq_27369)) ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn0042DF20
Eq_3 fn00422DB0(struct Eq_27369 ** ecx, Eq_3 dwArg04)
{
	struct Eq_27369 * ecx_7 = *ecx;
	*dwArg04 = ecx_7;
	if (ecx_7 != null)
		++ecx_7->dw0004;
	return dwArg04;
}

// 00422E10: void fn00422E10(Register (ptr32 Eq_27386) ecx)
// Called from:
//      fn0042B310
void fn00422E10(struct Eq_27386 * ecx)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	struct Eq_27396 * ecx_29 = ecx->ptr0008;
	if (ecx_29 != null)
	{
		word32 v12_34 = ecx_29->dw0004 + ~0x00;
		ecx_29->dw0004 = v12_34;
		if (v12_34 == 0x00)
		{
			<anonymous> ** eax_38 = ecx_29->ptr0000;
			word32 edx_45;
			(*eax_38)();
		}
	}
	ecx->ptr0008 = null;
	ecx->dw0000 = 9071992;
	fs->ptr0000 = eax_9;
}

// 00424930: Register (ptr32 Eq_27431) fn00424930(Register (ptr32 Eq_27432) ecx, Stack (ptr32 (ptr32 Eq_27431)) dwArg04, Stack (ptr32 int32) dwArg08)
// Called from:
//      fn00429930
struct Eq_27431 * fn00424930(struct Eq_27432 * ecx, struct Eq_27431 ** dwArg04, int32 * dwArg08)
{
	struct Eq_27431 * edx_24 = ecx->ptr0004;
	struct Eq_27431 * eax_19 = edx_24->ptr0004;
	if (eax_19->b002D == 0x00)
	{
		int32 esi_18 = *dwArg08;
		do
		{
			if (eax_19->dw000C < esi_18)
				eax_19 = eax_19->ptr0008;
			else
			{
				edx_24 = eax_19;
				eax_19 = eax_19->ptr0000;
			}
		} while (eax_19->b002D == 0x00);
	}
	struct Eq_27431 * eax_39 = ecx->ptr0004;
	if (edx_24 == eax_39 || *dwArg08 < edx_24->dw000C)
	{
		*dwArg04 = (struct Eq_27431 **) eax_39;
		return eax_39;
	}
	else
	{
		*dwArg04 = (struct Eq_27431 **) edx_24;
		return edx_24;
	}
}

// 00424A20: Register (ptr32 Eq_3) fn00424A20(Register (ptr32 Eq_1819) ecx, Stack (ptr32 Eq_3) dwArg04, Stack byte bArg08, Stack Eq_3 dwArg0C, Stack (ptr32 int32) dwArg10, Register out Eq_3 edxOut)
// Called from:
//      fn004263B0
//      fn00428880
union Eq_3 * fn00424A20(struct Eq_1819 * ecx, union Eq_3 * dwArg04, byte bArg08, Eq_3 dwArg0C, int32 * dwArg10, union Eq_3 & edxOut)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	if (ecx->t0008 >= 0x07FFFFFE)
	{
		basic_string(fp - 0x50, "map/set<T> too long");
		fn004019E0(fp - 0x34, fp - 0x50);
		CxxThrowException();
	}
	Eq_3 eax_68 = ecx->t0004;
	fn004229E0(eax_68, dwArg0C, eax_68, dwArg10, 0x00);
	Eq_3 eax_89 = ecx->t0004;
	ecx->t0008 = (word32) ecx->t0008 + 1;
	if (dwArg0C == eax_89)
	{
		*((word32) eax_89 + 4) = eax_68;
		*ecx->t0004 = eax_68;
		*((word32) ecx->t0004 + 8) = eax_68;
	}
	else if (bArg08 != 0x00)
	{
		*dwArg0C = eax_68;
		Eq_3 eax_103 = ecx->t0004;
		if (dwArg0C == *eax_103)
			*eax_103 = eax_68;
	}
	else
	{
		*((word32) dwArg0C + 8) = eax_68;
		Eq_3 eax_98 = ecx->t0004;
		if (dwArg0C == *((word32) eax_98 + 8))
			*((word32) eax_98 + 8) = eax_68;
	}
	struct Eq_27560 ** eax_116 = (word32) eax_68 + 4;
	Eq_3 esi_117 = eax_68;
	if (*((word32) *((word32) eax_68 + 4) + 44) == 0x00)
	{
		do
		{
			Eq_3 ecx_123 = *eax_116;
			Eq_3 edx_124 = *((word32) ecx_123 + 4);
			if (ecx_123 == *edx_124)
			{
				Eq_3 edx_192 = *((word32) edx_124 + 8);
				if (*((word32) edx_192 + 44) == 0x00)
				{
					*((word32) ecx_123 + 44) = 0x01;
					*((word32) edx_192 + 44) = 0x01;
					*((const char *) *((const char *) *eax_116 + 4) + 44) = (struct Eq_27560 **) 0x00;
					esi_117 = *((const char *) *eax_116 + 4);
				}
				else
				{
					if (esi_117 == *((word32) ecx_123 + 8))
					{
						fn004E2250(ecx, ecx_123);
						esi_117 = ecx_123;
					}
					*((word32) *((word32) esi_117 + 4) + 44) = 0x01;
					*((word32) *((word32) *((word32) esi_117 + 4) + 4) + 44) = 0x00;
					fn00420740(ecx, *((word32) *((word32) esi_117 + 4) + 4));
				}
			}
			else
			{
				Eq_3 edx_127 = *edx_124;
				if (*((word32) edx_127 + 44) == 0x00)
				{
					*((word32) ecx_123 + 44) = 0x01;
					*((word32) edx_127 + 44) = 0x01;
					*((const char *) *((const char *) *eax_116 + 4) + 44) = (struct Eq_27560 **) 0x00;
					esi_117 = *((const char *) *eax_116 + 4);
				}
				else
				{
					if (esi_117 == *ecx_123)
					{
						fn00420740(ecx, ecx_123);
						esi_117 = ecx_123;
					}
					*((word32) *((word32) esi_117 + 4) + 44) = 0x01;
					*((word32) *((word32) *((word32) esi_117 + 4) + 4) + 44) = 0x00;
					Eq_3 eax_157 = *((word32) *((word32) esi_117 + 4) + 4);
					Eq_3 ecx_158 = *((word32) eax_157 + 8);
					*((word32) eax_157 + 8) = *ecx_158;
					Eq_3 edx_161 = *ecx_158;
					if (*((word32) edx_161 + 45) == 0x00)
						*((word32) edx_161 + 4) = eax_157;
					*((word32) ecx_158 + 4) = *((word32) eax_157 + 4);
					Eq_3 edx_172 = ecx->t0004;
					if (eax_157 == *((word32) edx_172 + 4))
						*((word32) edx_172 + 4) = ecx_158;
					else
					{
						Eq_3 edx_175 = *((word32) eax_157 + 4);
						if (eax_157 == *edx_175)
							*edx_175 = ecx_158;
						else
							*((word32) edx_175 + 8) = ecx_158;
					}
					*ecx_158 = eax_157;
					*((word32) eax_157 + 4) = ecx_158;
				}
			}
			eax_116 = (word32) esi_117 + 4;
		} while (*((word32) *((word32) esi_117 + 4) + 44) == 0x00);
	}
	Eq_3 edx_252 = ecx->t0004;
	*((word32) *((word32) edx_252 + 4) + 44) = 0x01;
	*dwArg04 = (union Eq_3 *) eax_68;
	fs->ptr0000 = eax_9;
	edxOut = edx_252;
	return dwArg04;
}

// 00424E30: void fn00424E30(Register Eq_3 ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn00428EA0
//      fn004292A0
void fn00424E30(Eq_3 ecx, Eq_3 dwArg04)
{
	*ecx = *dwArg04;
	*((word32) ecx + 4) = *((word32) dwArg04 + 4);
	*((word32) ecx + 8) = *((word32) dwArg04 + 8);
	*((word32) ecx + 0x0C) = *((word32) dwArg04 + 0x0C);
	*((word32) ecx + 16) = *((word32) dwArg04 + 16);
	*((word32) ecx + 20) = *((word32) dwArg04 + 20);
	*((word32) ecx + 24) = *((word32) dwArg04 + 24);
	*((word32) ecx + 28) = *((word32) dwArg04 + 28);
	*((word32) ecx + 32) = *((word32) dwArg04 + 32);
	*((word32) ecx + 36) = *((word32) dwArg04 + 36);
	*((word32) ecx + 40) = *((word32) dwArg04 + 40);
	*((word32) ecx + 44) = *((word32) dwArg04 + 44);
	*((word32) ecx + 48) = *((word32) dwArg04 + 48);
	Eq_3 eax_37 = *((word32) dwArg04 + 52);
	Eq_3 edi_41 = *((word32) ecx + 52);
	if (edi_41 != eax_37)
	{
		*((word32) ecx + 52) = eax_37;
		if (eax_37 != 0x00)
			fn00401AD0(eax_37);
		if (edi_41 != 0x00)
		{
			Eq_3 eax_58 = fn00401AE0(edi_41);
			if (eax_58 == 0x01)
			{
				<anonymous> ** edx_66 = *edi_41;
				(*edx_66)();
			}
		}
	}
}

// 00424EC0: void fn00424EC0(Register Eq_3 ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn004298F0
void fn00424EC0(Eq_3 ecx, Eq_3 dwArg04)
{
	*ecx = *dwArg04;
	*((word32) ecx + 4) = *((word32) dwArg04 + 4);
	*((word32) ecx + 8) = *((word32) dwArg04 + 8);
	*((word32) ecx + 0x0C) = *((word32) dwArg04 + 0x0C);
	*((word32) ecx + 16) = *((word32) dwArg04 + 16);
	*((word32) ecx + 20) = *((word32) dwArg04 + 20);
	*((word32) ecx + 24) = *((word32) dwArg04 + 24);
	*((word32) ecx + 28) = *((word32) dwArg04 + 28);
	*((word32) ecx + 32) = *((word32) dwArg04 + 32);
	*((word32) ecx + 36) = *((word32) dwArg04 + 36);
	*((word32) ecx + 40) = *((word32) dwArg04 + 40);
	*((word32) ecx + 44) = *((word32) dwArg04 + 44);
	*((word32) ecx + 48) = *((word32) dwArg04 + 48);
	Eq_3 eax_37 = *((word32) dwArg04 + 52);
	*((word32) ecx + 52) = eax_37;
	if (eax_37 != 0x00)
		fn00401AD0(eax_37);
}

// 00424FD0: void fn00424FD0(Register (ptr32 Eq_3) ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn0042B310
void fn00424FD0(union Eq_3 * ecx, Eq_3 dwArg04)
{
	Eq_3 ecx_7 = *ecx;
	*dwArg04 = ecx_7;
	if (ecx_7 != 0x00)
		fn00401AD0(ecx_7);
}

// 00426100: Register Eq_3 fn00426100(Register (ptr32 Eq_1819) ecx, Stack (ptr32 Eq_3) dwArg04, Stack Eq_3 dwArg08)
// Called from:
//      fn00428A30
//      fn00429930
Eq_3 fn00426100(struct Eq_1819 * ecx, union Eq_3 * dwArg04, Eq_3 dwArg08)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	Eq_3 eax_33 = dwArg08;
	if (*((word32) dwArg08 + 45) != 0x00)
	{
		basic_string(fp - 0x50, "invalid map/set<T> iterator");
		fn004019E0(fp - 0x34, fp - 0x50);
		CxxThrowException();
	}
	Eq_3 esi_104;
	Eq_3 edi_129;
	Eq_3 edx_305 = fn005B0EC0(fp + 0x08);
	Eq_3 eax_76 = *eax_33;
	if (*((word32) eax_76 + 45) != 0x00)
		edi_129 = *((word32) eax_33 + 8);
	else
	{
		edx_305 = *((word32) eax_33 + 8);
		if (*((word32) edx_305 + 45) != 0x00)
			edi_129 = eax_76;
		else
		{
			edi_129 = *((word32) dwArg08 + 8);
			if (dwArg08 != eax_33)
			{
				*((word32) eax_76 + 4) = dwArg08;
				Eq_3 edx_87 = *eax_33;
				*dwArg08 = edx_87;
				word24 edx_24_8_497 = SLICE(edx_87, word24, 8);
				if (dwArg08 == *((word32) eax_33 + 8))
					esi_104 = dwArg08;
				else
				{
					esi_104 = *((word32) dwArg08 + 4);
					if (*((word32) edi_129 + 45) == 0x00)
						*((word32) edi_129 + 4) = esi_104;
					*esi_104 = edi_129;
					*((word32) dwArg08 + 8) = *((word32) eax_33 + 8);
					Eq_3 edx_102 = *((word32) eax_33 + 8);
					*((word32) edx_102 + 4) = dwArg08;
					edx_24_8_497 = SLICE(edx_102, word24, 8);
				}
				Eq_3 eax_109 = ecx->t0004;
				if (*((word32) eax_109 + 4) == eax_33)
					*((word32) eax_109 + 4) = dwArg08;
				else
				{
					Eq_3 eax_113 = *((word32) eax_33 + 4);
					if (*eax_113 == eax_33)
						*eax_113 = dwArg08;
					else
						*((word32) eax_113 + 8) = dwArg08;
				}
				*((word32) dwArg08 + 4) = *((word32) eax_33 + 4);
				Eq_27569 dl_125 = *((word32) eax_33 + 44);
				Eq_27569 al_126 = *((word32) dwArg08 + 44);
				*((word32) dwArg08 + 44) = dl_125;
				*((word32) eax_33 + 44) = al_126;
				edx_305 = SEQ(edx_24_8_497, dl_125);
l00426265:
				if (*((word32) eax_33 + 44) == 0x01)
				{
					if (edi_129 != *((word32) ecx->t0004 + 4))
					{
						while (*((word32) edi_129 + 44) == 0x01)
						{
							Eq_3 eax_230 = *esi_740;
							if (edi_129 == eax_230)
							{
								eax_230 = *((word32) esi_740 + 8);
								if (*((word32) eax_230 + 44) == 0x00)
								{
									*((word32) eax_230 + 44) = 0x01;
									*((word32) esi_740 + 44) = 0x00;
									fn004E2250(ecx, esi_740);
									eax_230 = *((word32) esi_740 + 8);
								}
								if (*((word32) eax_230 + 45) != 0x00)
									goto l00426322;
								struct Eq_28332 * edx_332 = *eax_230;
								if (edx_332->b002C != 0x01 || *((word32) (*((word32) eax_230 + 8)) + 44) != 0x01)
								{
									if (*((word32) *((word32) eax_230 + 8) + 44) == 0x01)
									{
										edx_332->b002C = 0x01;
										*((word32) eax_230 + 44) = 0x00;
										fn00420740(ecx, eax_230);
										eax_230 = *((word32) esi_740 + 8);
									}
									*((word32) eax_230 + 44) = *((word32) esi_740 + 44);
									*((word32) esi_740 + 44) = 0x01;
									*((word32) *((word32) eax_230 + 8) + 44) = 0x01;
									edx_305 = fn004E2250(ecx, esi_740);
									break;
								}
								goto l0042631E;
							}
							if (*((word32) eax_230 + 44) == 0x00)
							{
								*((word32) eax_230 + 44) = 0x01;
								*((word32) esi_740 + 44) = 0x00;
								fn00420740(ecx, esi_740);
								eax_230 = *esi_740;
							}
							if (*((word32) eax_230 + 45) == 0x00)
							{
								Eq_3 edx_255 = *((word32) eax_230 + 8);
								if (*((word32) edx_255 + 44) != 0x01 || *((word32) (*eax_230) + 44) != 0x01)
								{
									if (*((word32) *eax_230 + 44) == 0x01)
									{
										*((word32) edx_255 + 44) = 0x01;
										*((word32) eax_230 + 44) = 0x00;
										fn004E2250(ecx, eax_230);
										eax_230 = *esi_740;
									}
									*((word32) eax_230 + 44) = *((word32) esi_740 + 44);
									*((word32) esi_740 + 44) = 0x01;
									*((word32) *eax_230 + 44) = 0x01;
									edx_305 = fn00420740(ecx, esi_740);
									break;
								}
l0042631E:
								*((word32) eax_230 + 44) = 0x00;
							}
l00426322:
							edx_305 = ecx->t0004;
							edi_129 = esi_740;
							esi_104 = *((word32) esi_740 + 4);
							esi_740 = esi_104;
							if (esi_740 == *((word32) edx_305 + 4))
								break;
						}
					}
					*((word32) edi_129 + 44) = 0x01;
				}
				~basic_string((word32) eax_33 + 16);
				operator delete(eax_33);
				Eq_3 eax_423 = ecx->t0008;
				if (eax_423 > 0x00)
					ecx->t0008 = (word32) eax_423 - 1;
				*dwArg04 = (union Eq_3 *) dwArg08;
				fs->ptr0000 = eax_9;
				return edx_305;
			}
		}
	}
	esi_104 = *((word32) eax_33 + 4);
	if (*((word32) edi_129 + 45) == 0x00)
		*((word32) edi_129 + 4) = esi_104;
	Eq_3 eax_141 = ecx->t0004;
	if (*((word32) eax_141 + 4) == eax_33)
		*((word32) eax_141 + 4) = edi_129;
	else if (*esi_104 == eax_33)
		*esi_104 = edi_129;
	else
		*((word32) esi_104 + 8) = edi_129;
	Eq_3 ebx_154 = ecx->t0004;
	if (*ebx_154 == eax_33)
	{
		Eq_3 eax_166;
		if (*((word32) edi_129 + 45) != 0x00)
			eax_166 = esi_104;
		else
			eax_166 = fn00406ED0(edi_129);
		*ebx_154 = eax_166;
	}
	Eq_3 ebx_182 = ecx->t0004;
	if (*((word32) ebx_182 + 8) == eax_33)
	{
		if (*((word32) edi_129 + 45) != 0x00)
			*((word32) ebx_182 + 8) = esi_104;
		else
			*((word32) ebx_182 + 8) = fn004E6960(edi_129);
	}
	goto l00426265;
}

// 004263B0: Register Eq_3 fn004263B0(Register (ptr32 Eq_1819) ecx, Stack (ptr32 Eq_28498) dwArg04, Stack (ptr32 int32) dwArg08, Register out Eq_3 edxOut)
// Called from:
//      fn00428880
Eq_3 fn004263B0(struct Eq_1819 * ecx, struct Eq_28498 * dwArg04, int32 * dwArg08, union Eq_3 & edxOut)
{
	Eq_3 esi_18 = ecx->t0004;
	word24 nLoc03_184 = SLICE(ecx, word24, 8);
	Eq_3 eax_19 = *((word32) esi_18 + 4);
	int8 cl_21 = 0x01;
	word32 dwLoc04_183 = SEQ(nLoc03_184, 0x01);
	if (*((word32) eax_19 + 45) == 0x00)
	{
		int32 edx_24 = *dwArg08;
		do
		{
			cl_21 = (int8) (edx_24 < *((word32) eax_19 + 0x0C));
			esi_18 = eax_19;
			dwLoc04_183 = SEQ(nLoc03_184, cl_21);
			if (cl_21 != 0x00)
				eax_19 = *eax_19;
			else
				eax_19 = *((word32) eax_19 + 8);
		} while (*((word32) eax_19 + 45) == 0x00);
	}
	if (cl_21 != 0x00)
	{
		if (esi_18 == *ecx->t0004)
		{
			word32 edx_221;
			Eq_3 edx_144 = *fn00424A20(ecx, fp + 0x08, 0x01, esi_18, dwArg08, out edx_221);
			dwArg04->b0004 = 0x01;
			dwArg04->t0000 = edx_144;
			edxOut = edx_144;
			return <invalid>;
		}
		fn005F58C0(fp + 0x08);
	}
	if (*((word32) esi_18 + 0x0C) >= *dwArg08)
	{
		dwArg04->b0004 = 0x00;
		dwArg04->t0000 = esi_18;
		edxOut = esi_18;
		return <invalid>;
	}
	else
	{
		Eq_3 edx_109;
		dwArg04->t0000 = *fn00424A20(ecx, fp + 0x08, (byte) dwLoc04_183, esi_18, dwArg08, out edx_109);
		dwArg04->b0004 = 0x01;
		edxOut = edx_109;
		return <invalid>;
	}
}

// 00426470: Register int32 fn00426470(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn004295F0
int32 fn00426470(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	fn00422B20(dwArg04, dwArg08, dwArg0C);
	return (word32) dwArg04 + dwArg08 *s 332;
}

// 004264B0: Register (ptr32 Eq_28617) fn004264B0(Register (ptr32 Eq_28617) ecx)
// Called from:
//      fn00426500
struct Eq_28617 * fn004264B0(struct Eq_28617 * ecx)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	ecx->dw0000 = 0x00;
	ecx->b0004 = 0x01;
	ecx->dw000C = 0x00;
	ecx->dw0010 = 0x00;
	ecx->dw0014 = 0x00;
	ecx->dw001C = 0x00;
	ecx->dw0020 = 0x00;
	ecx->dw0024 = 0x00;
	fs->ptr0000 = eax_9;
	return ecx;
}

// 00426500: Register word32 fn00426500()
// Called from:
//      fn0061FAC0
//      fn0061FB20
word32 fn00426500()
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	word32 eax_21 = g_dwA67C98;
	if (eax_21 == 0x00)
	{
		struct Eq_28617 * eax_27 = operator new(0x28);
		if (eax_27 != null)
		{
			word32 eax_48 = fn004264B0(eax_27);
			g_dwA67C98 = eax_48;
			fs->ptr0000 = eax_9;
			return eax_48;
		}
		g_dwA67C98 = 0x00;
		eax_21 = 0x00;
	}
	fs->ptr0000 = eax_9;
	return eax_21;
}

// 00428850: void fn00428850(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08)
// Called from:
//      fn0042CFC0
void fn00428850(Eq_3 dwArg04, Eq_3 dwArg08)
{
	Eq_3 esi_15 = dwArg04;
	if (dwArg04 != dwArg08)
	{
		do
		{
			fn005B87B0(esi_15);
			esi_15 = (word32) esi_15 + 56;
		} while (esi_15 != dwArg08);
	}
}

// 00428880: Register Eq_3 fn00428880(Register (ptr32 Eq_1819) ecx, Stack (ptr32 Eq_3) dwArg04, Stack Eq_3 dwArg08, Stack (ptr32 int32) dwArg0C, Register out ptr32 edxOut)
// Called from:
//      fn00428F30
Eq_3 fn00428880(struct Eq_1819 * ecx, union Eq_3 * dwArg04, Eq_3 dwArg08, int32 * dwArg0C, ptr32 & edxOut)
{
	if (ecx->t0008 != 0x00)
	{
		Eq_3 eax_15 = ecx->t0004;
		if (dwArg08 == *eax_15)
		{
			if (*dwArg0C < *((word32) dwArg08 + 0x0C))
			{
				ptr32 edx_265;
				fn00424A20(ecx, dwArg04, 0x01, dwArg08, dwArg0C, out edx_265);
				edxOut = edx_265;
				return <invalid>;
			}
		}
		else if (dwArg08 == eax_15)
		{
			Eq_3 eax_187 = *((word32) eax_15 + 8);
			if (*((word32) eax_187 + 0x0C) < *dwArg0C)
			{
				ptr32 edx_203;
				fn00424A20(ecx, dwArg04, 0x00, eax_187, dwArg0C, out edx_203);
				edxOut = edx_203;
				return <invalid>;
			}
		}
		else
		{
			int32 ebp_28 = *dwArg0C;
			bool v19_309 = *((word32) dwArg08 + 0x0C) >= ebp_28;
			if (*((word32) dwArg08 + 0x0C) > ebp_28)
			{
				fn005F58C0(fp + 0x0C);
				if (*((word32) dwArg08 + 0x0C) < ebp_28)
				{
					if (*((word32) *((word32) dwArg08 + 8) + 45) == 0x00)
					{
						ptr32 edx_145;
						fn00424A20(ecx, dwArg04, 0x01, dwArg08, dwArg0C, out edx_145);
						edxOut = edx_145;
						return <invalid>;
					}
					else
					{
						ptr32 edx_170;
						fn00424A20(ecx, dwArg04, 0x00, dwArg08, dwArg0C, out edx_170);
						edxOut = edx_170;
						return <invalid>;
					}
				}
				v19_309 = *((word32) dwArg08 + 0x0C) >= ebp_28;
			}
			if (!v19_309)
			{
				fn005B0EC0(fp + 0x0C);
				if (dwArg08 == ecx->t0004 || ebp_28 < *((word32) dwArg08 + 0x0C))
				{
					if (*((word32) *((word32) dwArg08 + 8) + 45) == 0x00)
					{
						ptr32 edx_88;
						fn00424A20(ecx, dwArg04, 0x01, dwArg08, dwArg0C, out edx_88);
						edxOut = edx_88;
						return <invalid>;
					}
					else
					{
						ptr32 edx_113;
						fn00424A20(ecx, dwArg04, 0x00, dwArg08, dwArg0C, out edx_113);
						edxOut = edx_113;
						return <invalid>;
					}
				}
			}
		}
		ptr32 edx_235;
		*dwArg04 = *fn004263B0(ecx, fp - 0x08, dwArg0C, out edx_235);
		edxOut = edx_235;
		return <invalid>;
	}
	else
	{
		ptr32 edx_296;
		fn00424A20(ecx, dwArg04, 0x01, ecx->t0004, dwArg0C, out edx_296);
		edxOut = edx_296;
		return <invalid>;
	}
}

// 00428A30: void fn00428A30(Register (ptr32 Eq_1819) ecx, Stack (ptr32 Eq_3) dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn0042A250
void fn00428A30(struct Eq_1819 * ecx, union Eq_3 * dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 esi_108 = dwArg08;
	Eq_3 eax_17 = ecx->t0004;
	if (dwArg08 != *eax_17 || dwArg0C != eax_17)
	{
		if (dwArg08 != dwArg0C)
		{
			do
			{
				if (*((word32) esi_108 + 45) == 0x00)
				{
					Eq_3 eax_33 = *((word32) esi_108 + 8);
					if (*((word32) eax_33 + 45) == 0x00)
					{
						esi_108 = eax_33;
						Eq_3 eax_51 = *eax_33;
						while (*((word32) eax_51 + 45) == 0x00)
						{
							esi_108 = eax_51;
							eax_51 = *eax_51;
						}
					}
					else
					{
						Eq_3 eax_36 = *((word32) esi_108 + 4);
						esi_39 = esi_108;
						while (*((word32) eax_36 + 45) == 0x00)
						{
							Eq_3 esi_39;
							if (esi_39 != *((word32) eax_36 + 8))
								break;
							esi_39 = eax_36;
							eax_36 = *((word32) eax_36 + 4);
						}
						esi_108 = eax_36;
					}
				}
				fn00426100(ecx, fp + 0x08, esi_108);
			} while (esi_108 != dwArg0C);
		}
		*dwArg04 = (union Eq_3 *) esi_108;
	}
	else
	{
		fn004064E0(*((word32) eax_17 + 4));
		Eq_3 eax_124 = ecx->t0004;
		*((word32) eax_124 + 4) = eax_124;
		Eq_3 eax_126 = ecx->t0004;
		ecx->t0008.u0 = 0x00;
		*eax_126 = eax_126;
		Eq_3 eax_129 = ecx->t0004;
		*((word32) eax_129 + 8) = eax_129;
		*dwArg04 = (union Eq_3 *) *ecx->t0004;
	}
}

// 00428EA0: Register Eq_3 fn00428EA0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn0042CFC0
Eq_3 fn00428EA0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 esi_11 = dwArg04;
	Eq_3 edi_16 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			fn00424E30(edi_16, esi_11);
			esi_11 = (word32) esi_11 + 56;
			edi_16 = (word32) edi_16 + 56;
		} while (esi_11 != dwArg08);
	}
	return edi_16;
}

// 00428ED0: Register Eq_3 fn00428ED0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn004295F0
Eq_3 fn00428ED0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	word32 edx_50;
	return fn00422320(dwArg04, dwArg08, dwArg0C, out edx_50);
}

// 00428F30: Register ptr32 fn00428F30(Register (ptr32 Eq_1819) ecx, Stack (ptr32 int32) dwArg04, Register out ptr32 edxOut)
// Called from:
//      fn00429930
ptr32 fn00428F30(struct Eq_1819 * ecx, int32 * dwArg04, ptr32 & edxOut)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	Eq_3 ecx_30 = ecx->t0004;
	Eq_3 eax_31 = *((word32) ecx_30 + 4);
	Eq_3 esi_105 = ecx_30;
	if (*((word32) eax_31 + 45) == 0x00)
	{
		int32 ecx_36 = *dwArg04;
		do
		{
			if (*((word32) eax_31 + 0x0C) < ecx_36)
				eax_31 = *((word32) eax_31 + 8);
			else
			{
				esi_105 = eax_31;
				eax_31 = *eax_31;
			}
		} while (*((word32) eax_31 + 45) == 0x00);
	}
	if (esi_105 == ecx->t0004 || *dwArg04 < *((word32) esi_105 + 0x0C))
	{
		basic_string(fp - 0x28, basic_string(fp - 0x48));
		esi_105 = *fn00428880(ecx, fp + 0x04, esi_105, fp - 44, out edx);
		~basic_string(fp - 0x28);
		~basic_string(fp - 0x48);
	}
	fs->ptr0000 = eax_9;
	edxOut = edx;
	return (word32) esi_105 + 16;
}

// 004292A0: void fn004292A0(Register Eq_3 ecx, Stack (ptr32 Eq_3) dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn0042CFC0
void fn004292A0(Eq_3 ecx, union Eq_3 * dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 edi_10 = dwArg0C;
	if (dwArg08 != dwArg0C)
	{
		Eq_3 ebx_19 = *((word32) ecx + 8);
		Eq_3 esi_24 = dwArg08;
		if (dwArg0C != ebx_19)
		{
			do
			{
				fn00424E30(esi_24, edi_10);
				edi_10 = (word32) edi_10 + 56;
				esi_24 = (word32) esi_24 + 56;
			} while (edi_10 != ebx_19);
		}
		Eq_3 ebx_49 = *((word32) ecx + 8);
		Eq_3 edi_52 = esi_24;
		if (esi_24 != ebx_49)
		{
			do
			{
				fn005B87B0(edi_52);
				edi_52 = (word32) edi_52 + 56;
			} while (edi_52 != ebx_49);
		}
		*((word32) ecx + 8) = esi_24;
	}
	*dwArg04 = (union Eq_3 *) dwArg08;
}

// 004295F0: Register Eq_3 fn004295F0(Register Eq_3 ecx, Register Eq_3 edx, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Register out Eq_3 ediOut)
// Called from:
//      fn0042A0A0
Eq_3 fn004295F0(Eq_3 ecx, Eq_3 edx, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, union Eq_3 & ediOut)
{
	ptr32 eax_14 = fs->ptr0000;
	Eq_3 eax_19 = g_tA14188 ^ fp - 0x0154;
	fs->ptr0000 = fp - 0x0160;
	ptr32 esp_215 = fp - 0x017C;
	Eq_3 eax_208 = fp - 0x0160;
	Eq_3 esi_37 = dwArg0C;
	word32 ecx_40;
	word32 * edi_41 = fp - 0x0154;
	for (ecx_40 = 0x53; ecx_40 != 0x00; --ecx_40)
	{
		*edi_41 = (word32) *esi_37;
		esi_37 = (word32) esi_37 + 4;
		++edi_41;
	}
	uint32 esi_139;
	Eq_3 ecx_101 = *((word32) ecx + 4);
	if (ecx_101 == 0x00)
		esi_139 = 0x00;
	else
	{
		int32 edx_50 = *((word32) ecx + 0x0C) - ecx_101;
		int32 edx_53 = SLICE(edx_50 *s64 0x3159721F, word32, 32);
		eax_208 = (word32) (edx_50 *s64 0x3159721F);
		edx = edx_53 >> 0x06;
		esi_139 = (edx_53 >> 0x06 >> 0x1F) + (edx_53 >> 0x06);
	}
	if (dwArg08 != 0x00)
	{
		uint32 eax_82;
		if (ecx_101 == 0x00)
			eax_82 = 0x00;
		else
		{
			int32 edx_78 = SLICE((*((word32) ecx + 8) - ecx_101) *s64 0x3159721F, word32, 32);
			eax_82 = (edx_78 >> 0x06 >> 0x1F) + (edx_78 >> 0x06);
		}
		if (0x00C565C8 - eax_82 < dwArg08)
			ecx_101 = fn00420AA0(eax_19, edi);
		uint32 eax_127;
		if (ecx_101 == 0x00)
			eax_127 = 0x00;
		else
		{
			int32 edx_123 = SLICE((*((word32) ecx + 8) - ecx_101) *s64 0x3159721F, word32, 32);
			eax_127 = (edx_123 >> 0x06 >> 0x1F) + (edx_123 >> 0x06);
		}
		if (esi_139 < (word32) dwArg08 + eax_127)
		{
			Eq_3 esi_294;
			uint32 eax_289 = esi_139 >> 0x01;
			if (0x00C565C8 - eax_289 < esi_139)
				esi_294.u0 = 0x00;
			else
				esi_294 = esi_139 + eax_289;
			uint32 eax_314;
			if (ecx_101 == 0x00)
				eax_314 = 0x00;
			else
			{
				int32 edx_310 = SLICE((*((word32) ecx + 8) - ecx_101) *s64 0x3159721F, word32, 32);
				eax_314 = (edx_310 >> 0x06 >> 0x1F) + (edx_310 >> 0x06);
			}
			if (esi_294 < (word32) dwArg08 + eax_314)
				esi_294 = (word32) dwArg08 + fn00420840(ecx);
			Eq_29384 eax_445;
			int32 esi_355;
			Eq_3 eax_352 = fn00420C00(esi_294, esi_294, out esi_355);
			Eq_3 esp_356 = <invalid>;
			Eq_3 ecx_362 = *((word32) ecx + 4);
			Eq_3 dwLoc0168_648 = SEQ(nLoc0167, 0x00);
			*((word32) esp_356 - 4) = dwLoc0168_648;
			*((word32) esp_356 - 8) = dwLoc0168_648;
			*((word32) esp_356 - 0x0C) = ecx;
			*((word32) esp_356 - 16) = eax_352;
			*((word32) esp_356 - 20) = dwArg04;
			*((word32) esp_356 - 24) = ecx_362;
			word32 edx_719;
			Eq_3 eax_384 = fn00422320(*((word32) esp_356 - 24), *((word32) esp_356 - 20), *((word32) esp_356 - 16), out edx_719);
			*((word32) esp_356 + 4) = fp - 0x0154;
			*esp_356 = dwArg08;
			*((word32) esp_356 - 4) = eax_384;
			Eq_3 eax_401 = fn00426470(*((word32) esp_356 - 4), *esp_356, *((word32) esp_356 + 4));
			Eq_3 ecx_409 = *((word32) ecx + 8);
			*((word32) esp_356 + 4) = dwLoc0168_648;
			*esp_356 = dwLoc0168_648;
			*((word32) esp_356 - 4) = ecx;
			*((word32) esp_356 - 8) = eax_401;
			*((word32) esp_356 - 0x0C) = ecx_409;
			*((word32) esp_356 - 16) = dwArg04;
			fn00422320(*((word32) esp_356 - 16), *((word32) esp_356 - 0x0C), *((word32) esp_356 - 8), out edx);
			Eq_3 ecx_432 = *((word32) ecx + 4);
			if (ecx_432 == 0x00)
				eax_445.u0 = 0x00;
			else
			{
				int32 edx_441 = SLICE((*((word32) ecx + 8) - ecx_432) *s64 0x3159721F, word32, 32);
				edx = edx_441 >> 0x06;
				eax_445 = (edx_441 >> 0x06 >> 0x1F) + (edx_441 >> 0x06);
			}
			word32 edi_452 = dwArg08 + eax_445;
			if (ecx_432 != 0x00)
			{
				*((word32) esp_356 + 4) = ecx_432;
				operator delete(*((word32) esp_356 + 4));
			}
			*((word32) ecx + 0x0C) = (word32) eax_352 + esi_355 *s 332;
			*((word32) ecx + 8) = (word32) eax_352 + edi_452 *s 332;
			*((word32) ecx + 4) = eax_352;
			esp_215 = (word32) esp_356 + 8;
			eax_208 = eax_352;
		}
		else
		{
			Eq_3 ecx_144 = *((word32) ecx + 8);
			int32 edx_153 = SLICE((ecx_144 - dwArg04) *s64 0x3159721F, word32, 32);
			if ((edx_153 >> 0x06 >> 0x1F) + (edx_153 >> 0x06) < dwArg08)
			{
				fn00428ED0(dwArg04, ecx_144, (word32) dwArg04 + dwArg08 *s 332);
				Eq_3 ecx_237 = *((word32) ecx + 8);
				int32 edx_245 = SLICE((ecx_237 - dwArg04) *s64 0x3159721F, word32, 32);
				fn00426470(ecx_237, dwArg08 - (((edx_245 >> 0x06) >>u 0x1F) + (edx_245 >> 0x06)), fp - 0x0154);
				*((word32) ecx + 8) = (word32) *((word32) ecx + 8) + dwArg08 *s 332;
				eax_208 = fn00422220(dwArg04, *((word32) ecx + 8) - dwArg08 *s 332, fp - 0x0154, out edx);
				esp_215 = fp - 0x017C;
			}
			else
			{
				Eq_3 eax_167 = ecx_144 - dwArg08 *s 332;
				*((word32) ecx + 8) = fn00428ED0(eax_167, ecx_144, ecx_144);
				fn00422AE0(dwArg04, eax_167, ecx_144);
				eax_208 = fn00422220(dwArg04, (word32) dwArg04 + dwArg08 *s 332, fp - 0x0154, out edx);
				esp_215 = fp - 0x017C;
			}
		}
	}
	fs->ptr0000 = eax_14;
	struct Eq_29206 * esp_490 = esp_215 + 4;
	Eq_3 edi_491 = esp_490->t0000;
	Eq_3 esi_493 = esp_490->t0004;
	word32 ecx_718;
	fn00694B8E(eax_208, eax_19 ^ fp - 0x0154, edx, esp_490->t0008, fp - 0x0154, esi_493, edi_491, es, ds, esp_490->t0008, out ecx_718);
	ediOut = edi_491;
	return esi_493;
}

// 004298F0: Register Eq_3 fn004298F0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn005AF380
Eq_3 fn004298F0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 esi_11 = dwArg04;
	if (dwArg04 == dwArg08)
		return dwArg0C;
	Eq_3 edi_22 = dwArg0C;
	do
	{
		if (edi_22 != 0x00)
			fn00424EC0(edi_22, esi_11);
		esi_11 = (word32) esi_11 + 56;
		edi_22 = (word32) edi_22 + 56;
	} while (esi_11 != dwArg08);
	return edi_22;
}

// 00429930: void fn00429930(Register Eq_3 ecx, Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack (ptr32 Eq_29567) dwArg08)
// Called from:
//      fn0042ACF0
void fn00429930(Eq_3 ecx, Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, basic_string * dwArg08)
{
	Eq_3 edx_121;
	ptr32 eax_9 = fs->ptr0000;
	ui32 eax_14 = g_tA14188 ^ fp - 0x30;
	fs->ptr0000 = fp - 0x0C;
	if (dwArg08->dw0014 == 0x00)
	{
		edx_121 = fn00424930((word32) ecx + 0x051C, fp - 0x30, fp + 0x04);
		if (dwLoc30 != *((word32) ecx + 1312))
			edx_121 = fn00426100((word32) ecx + 0x051C, fp - 0x30, dwLoc30);
	}
	else
		operator =(fn00428F30((word32) ecx + 0x051C, fp + 0x04, out edx_121), dwArg08);
	basic_string(fp - 44, g_tA0D00C);
	if (*((word32) ecx + 1316) != 0x00)
	{
		Eq_3 eax_99 = *((word32) ecx + 1312);
		Eq_3 esi_100 = *eax_99;
		word32 ebx_101 = 0x00;
		if (esi_100 != eax_99)
		{
			do
			{
				const char * eax_108 = ", ";
				if (ebx_101 == 0x00)
					eax_108 = (const char *) " [";
				operator +=(fp - 44, eax_108);
				edx_121 = (word32) esi_100 + 16;
				operator +=(fp - 44, edx_121);
				if (*((word32) esi_100 + 45) == 0x00)
				{
					Eq_3 eax_129 = *((word32) esi_100 + 8);
					if (*((word32) eax_129 + 45) == 0x00)
					{
						esi_100 = eax_129;
						Eq_3 eax_147 = *eax_129;
						while (*((word32) eax_147 + 45) == 0x00)
						{
							esi_100 = eax_147;
							eax_147 = *eax_147;
						}
					}
					else
					{
						Eq_3 eax_132 = *((word32) esi_100 + 4);
						if (*((word32) eax_132 + 45) == 0x00)
						{
							while (esi_100 == *((word32) eax_132 + 8))
							{
								esi_100 = eax_132;
								eax_132 = *((word32) eax_132 + 4);
								if (*((word32) eax_132 + 45) != 0x00)
									break;
							}
						}
						esi_100 = eax_132;
					}
				}
				++ebx_101;
			} while (esi_100 != *((word32) ecx + 1312));
		}
		operator +=(fp - 44, "]");
	}
	Eq_3 eax_193 = SetWindowTextA(*((word32) ecx + 0x04E8), c_str(fp - 44));
	~basic_string(fp - 44);
	fs->ptr0000 = eax_9;
	word32 ecx_388;
	fn00694B8E(eax_193, eax_14 ^ fp - 0x30, edx_121, ebx, ebp, esi, edi, es, ds, ebx, out ecx_388);
}

// 0042A0A0: void fn0042A0A0(Register Eq_3 ecx, Register Eq_3 edx, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack (ptr32 int32) dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn0042B1F0
void fn0042A0A0(Eq_3 ecx, Eq_3 edx, struct Eq_7 * es, struct Eq_8 * ds, int32 * dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 esi_16 = *((word32) ecx + 4);
	if (esi_16 != 0x00)
	{
		int32 edx_24 = SLICE((*((word32) ecx + 8) - esi_16) *s64 0x3159721F, word32, 32);
		edx = edx_24 >> 0x06;
		if ((edx_24 >> 0x06 >> 0x1F) + (edx_24 >> 0x06) != 0x00)
		{
			edx = SLICE((dwArg08 - esi_16) *s64 0x3159721F, word32, 32) >> 0x06;
l0042A0E1:
			struct Eq_29799 * edi_84;
			*dwArg04 = fn004295F0(ecx, edx, ecx, es, ds, dwArg08, 0x01, dwArg0C, out edi_84) *s 332 + edi_84->dw0004;
			return;
		}
	}
	goto l0042A0E1;
}

// 0042A250: Register Eq_3 fn0042A250(Register Eq_3 ecx, Register Eq_3 ebp, Register Eq_3 edi)
// Called from:
//      fn004014B0
Eq_3 fn0042A250(Eq_3 ecx, Eq_3 ebp, Eq_3 edi)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	*ecx = 9085668;
	fn00401730(0x00);
	Eq_3 edi_47;
	Eq_3 ebx_46;
	Eq_3 esi_49;
	Eq_3 ebp_131;
	if (*((word32) fn006233B0(0x00, ebp, ecx, edi, out ebx_46, out ebp_131, out esi_49, out edi_47) + 72) != (byte) ebx_46)
	{
		word32 edi_147;
		Eq_3 eax_57 = fn006233B0(ebx_46, ebp_131, esi_49, edi_47, out ebx_46, out ebp_131, out esi_49, out edi_147);
		struct Eq_29896 * edx_68 = *eax_57;
		edx_68->ptr0004();
	}
	g_tA53FE8 = ebx_46;
	Eq_3 eax_80 = *((word32) esi_49 + 1312);
	struct Eq_1819 * esi_82 = (word32) esi_49 + 0x051C;
	fn00428A30(esi_82, fp - 0x10, *eax_80, eax_80);
	operator delete(esi_82->t0004);
	esi_82->t0004 = ebx_46;
	esi_82->t0008 = ebx_46;
	fs->ptr0000 = eax_9;
	return ebp_131;
}

// 0042A300: Register Eq_3 fn0042A300(Register Eq_3 ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn005A6DD0
Eq_3 fn0042A300(Eq_3 ecx, Eq_3 dwArg04)
{
	Eq_29905 ecx_15;
	Eq_3 edx_9 = *((word32) ecx + 4);
	if (edx_9 == 0x00)
		ecx_15.u0 = 0x00;
	else
		ecx_15 = *((word32) ecx + 8) - edx_9 >> 0x06;
	Eq_29905 eax_22 = *((word32) ecx + 16);
	if (ecx_15 > eax_22)
	{
		Eq_3 esi_31 = dwArg04;
		Eq_3 ecx_40;
		word32 * edi_41 = (word32) edx_9 + (eax_22 << 0x06);
		for (ecx_40 = 0x10; ecx_40 != 0x00; --ecx_40)
		{
			*edi_41 = (word32) *esi_31;
			esi_31 = (word32) esi_31 + 4;
			++edi_41;
		}
		*((word32) ecx + 16) = (word32) *((word32) ecx + 16) + 1;
		return ecx_40;
	}
	else
	{
		fn00412EF0(ecx, dwArg04);
		Eq_3 ecx_77 = *((word32) ecx + 4);
		if (ecx_77 != 0x00)
		{
			*((word32) ecx + 16) = *((word32) ecx + 8) - ecx_77 >> 0x06;
			return ecx_77;
		}
		else
		{
			*((word32) ecx + 16) = 0x00;
			return ecx_77;
		}
	}
}

// 0042ACF0: Register byte fn0042ACF0(Register Eq_3 ecx, Register Eq_3 ebx, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Register Eq_409 xmm0, Stack Eq_599 bArg04, Register out Eq_723 xmm0Out)
// Called from:
//      fn004014B0
byte fn0042ACF0(Eq_3 ecx, Eq_3 ebx, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_409 xmm0, Eq_599 bArg04, union Eq_723 & xmm0Out)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	Eq_3 ebp_37;
	fn00621250(fn0041F120(out ebp_37));
	basic_string(fp - 0x28, "A");
	fn00620BE0(fn00620E60(ebp_37), fp - 0x28);
	~basic_string(fp - 0x28);
	word32 ebx_86;
	Eq_3 edi_87;
	Eq_3 esi_88;
	Eq_409 xmm0_89;
	Eq_3 ebp_101;
	Eq_3 ebx_102;
	Eq_3 edi_103;
	Eq_3 esi_104;
	Eq_409 xmm0_105;
	word32 ebp_724;
	ui32 ecx_119 = (uint32) (int8) (fn0081DDF0(SEQ(SLICE(ebx_86, word24, 8), (int8) (fn0081DDF0(ebx, ecx, edi, xmm0, out ebx_86, out ebp_724, out esi_88, out edi_87, out xmm0_89)->t0000 == 0x01)), esi_88, edi_87, xmm0_89, out ebx_102, out ebp_101, out esi_104, out edi_103, out xmm0_105)->t0000 == 0x02) * 0x02 | (word32) ((byte) ebx_102);
	if (ecx_119 != g_dwA555DC)
	{
		g_dwA555DC = ecx_119;
		basic_string(fp - 0x28, (fp - 0x28)[ecx_119]);
		fn00429930(esi_104, ebx_102, ebp_101, esi_104, edi_103, es, ds, fp - 0x28);
		~basic_string(fp - 0x28);
	}
	uint32 eax_606;
	Eq_723 xmm0_167;
	Eq_3 ebp_164 = fn00420510(esi_104, xmm0_105, out xmm0_167);
	word24 eax_24_8_607 = SLICE(eax_163, word24, 8);
	if (*((word32) esi_104 + 0x04F0) > 0.0)
	{
		struct Eq_30109 * esp_239;
		Eq_3 esi_220;
		basic_string(fp - 0x28, "T");
		if (bArg04 != 0x00)
		{
			Eq_3 eax_257 = fn00620BE0(fn00620E60(ebp_164), fp - 0x28);
			~basic_string(fp - 0x28);
			Eq_3 ebp_270;
			Eq_3 ebx_271;
			Eq_3 edi_272;
			Eq_3 esi_274;
			Eq_3 eax_268 = fn006233B0(ebx_102, ebp_164, esi_104, eax_257, out ebx_271, out ebp_270, out esi_274, out edi_272);
			struct Eq_29896 * edx_281 = *eax_268;
			struct Eq_30109 * esp_288;
			edx_281->ptr0008();
			fn00419D20(edi_272);
			Eq_3 ebp_299;
			Eq_3 ebx_300;
			word128 xmm0_730;
			word32 edi_729;
			word32 edx_728;
			Eq_3 eax_297 = fn005A74F0(ebx_271, ebp_270, esi_274, edi_272, es, ds, out edx_728, out ebx_300, out ebp_299, out esi_220, out edi_729, out xmm0_730);
			esp_288->tFFFFFFFC.u0 = 0x00;
			esp_239 = esp_288;
			if ((byte) (uint32) fn005A79D0(eax_297, ebx_300, es, ds, esp_288->tFFFFFFFC, out xmm0_167) != 0x00)
			{
				esp_288->tFFFFFFFC.u0 = 9086004;
				basic_string((const char *) &esp_288->t0014 + 4, esp_288->tFFFFFFFC);
				esp_288->tFFFFFFFC = (const char *) &esp_288->t0014 + 4;
				esp_288->t003C.u0 = 0x03;
				Eq_3 eax_348 = fn00620BE0(fn00620E60(ebp_299), esp_288->tFFFFFFFC);
				esp_288->t003C = ebp_299;
				~basic_string((const char *) &esp_288->t0014 + 4);
				Eq_3 edi_363;
				word32 ebx_731;
				word32 ebp_732;
				Eq_3 eax_359 = fn006233B0(ebx_300, ebp_299, esi_220, eax_348, out ebx_731, out ebp_732, out esi_220, out edi_363);
				struct Eq_29896 * edx_370 = *eax_359;
				edx_370->ptr000C();
				fn00419D20(edi_363);
			}
		}
		else
		{
			fn00620BE0(fn00620E60(ebp_164), fp - 0x28);
			~basic_string(fp - 0x28);
			word32 ebx_725;
			word32 ebp_726;
			word32 edi_727;
			Eq_3 eax_214 = fn006233B0(ebx_102, ebp_164, esi_104, edi_103, out ebx_725, out ebp_726, out esi_220, out edi_727);
			struct Eq_29896 * edx_227 = *eax_214;
			edx_227->ptr0010();
		}
		Eq_23784 edx_eax_382 = __rdtsc();
		up32 edx_383 = SLICE(edx_eax_382, word32, 32);
		up32 eax_390 = (word32) edx_eax_382;
		up32 edx_387 = *((word32) esi_220 + 1292);
		up32 eax_392 = *((word32) esi_220 + 1288);
		if (edx_387 > 0x00 || eax_392 > 0x00)
		{
			ui64 eax_ecx_550 = SEQ(eax_405, *((word32) esi_220 + 0x0500)) + SEQ(edx_387, eax_392);
			up32 ecx_403 = (word32) eax_ecx_550;
			up32 eax_408 = SLICE(eax_ecx_550, word32, 32);
			ui32 eax_405 = *((word32) esi_220 + 0x0504);
			if (edx_383 <= eax_408 && (edx_383 < eax_408 || eax_390 < ecx_403))
			{
				Eq_3 edx_417;
				Eq_3 eax_416 = fn00626B20(out edx_417);
				Eq_30346 edx_ecx_555 = (word32) *((word32) esi_220 + 1288) + (*((word32) esi_220 + 0x0500) - edx_eax_382);
				struct Eq_30355 * esp_440 = esp_239 - 4;
				esp_440->t0000.u0 = 0x00;
				esp_440->tFFFFFFFC.u0 = 1000;
				esp_440->tFFFFFFF8 = SLICE(edx_ecx_555, word32, 32);
				esp_440->tFFFFFFF4 = (word32) edx_ecx_555;
				esp_440->t0048 = edx_417;
				Eq_3 edx_454;
				Eq_3 eax_452 = fn00694FE0(esp_440->tFFFFFFF4, esp_440->tFFFFFFF8, esp_440->tFFFFFFFC, esp_440->t0000, out edx_454);
				esp_440->t0000 = esp_440->t0048;
				esp_440->tFFFFFFFC = eax_416;
				esp_440->tFFFFFFF8 = edx_454;
				esp_440->tFFFFFFF4 = eax_452;
				word32 edx_733;
				esp_440->t0000 = fn006951B0(esp_440->tFFFFFFF4, esp_440->tFFFFFFF8, esp_440->tFFFFFFFC, esp_440->t0000, out edx_733);
				Sleep(esp_440->t0000);
			}
		}
		Eq_23784 edx_eax_480 = __rdtsc();
		Eq_3 ecx_483 = esp_239->t0014;
		*((word32) esi_220 + 0x0500) = (word32) edx_eax_480;
		*((word32) esi_220 + 0x0504) = SLICE(edx_eax_480, word32, 32);
		fn00419D20(ecx_483);
		eax_24_8_607 = SLICE(eax_489, word24, 8);
		Eq_3 ecx_491 = g_tA0D154;
		if (ecx_491 > 0x00)
		{
			g_tA0D154 = ecx_491 - 0x01;
			int32 edx_498 = SLICE((ecx_491 - 0x01) *s64 1374389535, word32, 32);
			Eq_3 ecx_495 = ecx_491 - 0x01;
			if (ecx_491 - 0x01 - (((edx_498 >> 0x05) >>u 0x1F) + (edx_498 >> 0x05)) *s 100 == 0x00)
			{
				struct Eq_30475 * esp_509 = esp_239 - 4;
				esp_509->dw0000 = ecx_491 - 0x01;
				esp_509->dwFFFFFFFC = 9085980;
				fn00520C80();
				ecx_495 = g_tA0D154;
			}
			eax_606 = (uint32) (int8) (ecx_495 > 0x00);
l0042AFE2:
			fs->ptr0000 = eax_9;
			xmm0Out = xmm0_167;
			return (byte) eax_606;
		}
	}
	eax_606 = SEQ(eax_24_8_607, 0x01);
	goto l0042AFE2;
}

// 0042B1F0: void fn0042B1F0(Register Eq_3 ecx, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04)
// Called from:
//      fn0042D270
void fn0042B1F0(Eq_3 ecx, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04)
{
	uint32 ecx_26;
	Eq_3 edi_14 = *((word32) ecx + 4);
	if (edi_14 == 0x00)
		ecx_26 = 0x00;
	else
	{
		int32 edx_22 = SLICE((*((word32) ecx + 8) - edi_14) *s64 0x3159721F, word32, 32);
		ecx_26 = (edx_22 >> 0x06 >> 0x1F) + (edx_22 >> 0x06);
	}
	if (edi_14 != 0x00)
	{
		int32 edx_41 = SLICE((*((word32) ecx + 0x0C) - edi_14) *s64 0x3159721F, word32, 32);
		if (ecx_26 < ((edx_41 >> 0x06) >> 0x1F) + (edx_41 >> 0x06))
		{
			Eq_3 edi_101 = *((word32) ecx + 8);
			fn00422B20(edi_101, 0x01, dwArg04);
			*((word32) ecx + 8) = (word32) edi_101 + 332;
			return;
		}
	}
	fn0042A0A0(ecx, fp + 0x04, es, ds, fp + 0x04, *((word32) ecx + 8), dwArg04);
}

// 0042B310: Register Eq_3 fn0042B310(Register Eq_3 ecx, Register Eq_3 ebp, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Register Eq_409 xmm0, Register out Eq_3 ebpOut, Register out Eq_3 esiOut, Register out ptr32 ediOut, Register out Eq_540 xmm0Out)
// Called from:
//      fn004014B0
Eq_3 fn0042B310(Eq_3 ecx, Eq_3 ebp, struct Eq_7 * es, struct Eq_8 * ds, Eq_409 xmm0, union Eq_3 & ebpOut, union Eq_3 & esiOut, ptr32 & ediOut, union Eq_540 & xmm0Out)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	*((word32) ecx + 0x04F0) = 0.0F;
	((word32) ecx + 0x0510)->u1 = 0.0;
	*ecx = 9085668;
	real64 rLoc1_756 = (real64) g_r8AA5B8;
	*((word32) ecx + 0x04E8) = null;
	*((word32) ecx + 0x0518) = (real32) rLoc1_756;
	((word32) ecx + 1272)->u0 = 0x00;
	((word32) ecx + 0x04FC)->u0 = 0x00;
	*((word32) ecx + 0x0500) = 0x00;
	*((word32) ecx + 0x0504) = 0x00;
	*((word32) ecx + 1288) = 0x00;
	*((word32) ecx + 1292) = 0x00;
	Eq_3 eax_59 = fn00811B80();
	*((word32) ecx + 1312) = eax_59;
	*((word32) eax_59 + 45) = 0x01;
	Eq_3 eax_67 = *((word32) ecx + 1312);
	*((word32) eax_67 + 4) = eax_67;
	Eq_3 eax_69 = *((word32) ecx + 1312);
	*eax_69 = eax_69;
	Eq_3 eax_71 = *((word32) ecx + 1312);
	*((word32) eax_71 + 8) = eax_71;
	*((word32) ecx + 1316) = 0x00;
	*((word32) ecx + 0x0528) = 0x00;
	*((word32) ecx + 0x052C) = 0x00;
	timeBeginPeriod(0x01);
	*((word32) ecx + 1272) = timeGetTime();
	((word32) ecx + 0x04FC)->u0 = 0x00;
	g_tA53FE8 = ecx;
	memset((word32) ecx + 4, 0x00, 0x04E4);
	Eq_3 esi_128 = ecx;
	Eq_3 edi_126 = (word32) ecx + 0x051C;
	ptr32 esp_117 = fp - 100;
	Eq_3 ebp_103;
	word128 xmm0_108;
	if ((byte) (uint32) fn007B2D10(ebp, (word32) ecx + 0x051C, es, ds, xmm0, 0x00A540FC, out ebp_103, out xmm0_108) == 0x00)
	{
		esi_128 = fn00420190(0x00, es, ds, 0x008AA560, out edi_126);
		fn00421080(fp - 0x34, "Could not load resources XML");
		CxxThrowException();
	}
	Eq_3 ebx_172;
	word32 edx_918;
	word32 ebp_919;
	word32 edi_920;
	fn004048C0(0x00, ebp_103, esi_128, edi_126, es, ds, out edx_918, out ebx_172, out ebp_919, out edi_920);
	struct Eq_30718 * esp_179 = esp_117 - 4;
	esp_179->t0000 = ebx_172;
	esp_179->tFFFFFFFC.u0 = 10830112;
	esp_179->tFFFFFFF8 = &esp_179->t0018;
	word32 edx_921;
	Eq_3 edi_193 = *fn00402A20(esp_179->tFFFFFFF8, esp_179->tFFFFFFFC, esp_179->t0000, out edx_921);
	esp_179->t0020 = edi_193;
	ptr32 esp_194 = (const char *) &esp_179->t0000 + 4;
	if (edi_193 != ebx_172)
		fn00401AD0(edi_193);
	Eq_3 ecx_205 = esp_179->t0018;
	esp_179->b0064 = 0x01;
	if (ecx_205 != ebx_172 && (fn00401AE0(ecx_205) == 0x01 && ecx_205 != ebx_172))
	{
		<anonymous> ** eax_220 = *ecx_205;
		<anonymous> * edx_221 = *eax_220;
		esp_179->t0000.u0 = 0x01;
		edx_221();
	}
	Eq_3 esp_247 = esp_194 - 4;
	*esp_247 = ecx_205;
	*((word32) esp_247 + 24) = ebx_172;
	*((word32) esp_247 + 28) = esp_247;
	*esp_247 = edi_193;
	if (edi_193 != ebx_172)
		fn00401AD0(edi_193);
	*((word32) esp_247 + 100) = 0x02;
	Eq_3 ebp_269;
	Eq_3 ebx_270;
	Eq_3 esi_273;
	Eq_3 edi_272;
	union Eq_3 * eax_268 = fn0046E360(ebx_172, esi_128, edi_193, out ebx_270, out ebp_269, out esi_273, out edi_272);
	*((word32) esp_247 + 100) = 0x01;
	byte bl_289 = (byte) ebx_270;
	if ((byte) (uint32) fn0046E280(eax_268, *esp_247) == bl_289)
	{
		fn007B1F20((word32) esp_247 + 40);
		edi_272 = *((word32) esp_247 + 0x006C);
		*esp_247 = ebx_270;
		*((word32) esp_247 - 4) = edi_272;
		*((word32) esp_247 + 100) = 0x03;
		Eq_3 ecx_317;
		if (fn007B22E0((word32) esp_247 + 40, es, ds, *((word32) esp_247 - 4), *esp_247, out ecx_317) == 0x00)
		{
			*esp_247 = ecx_317;
			*((word32) esp_247 + 0x006C) = esp_247;
			*((word32) esp_247 - 4) = esp_247;
			Eq_3 esi_339 = fn007B1F60((word32) esp_247 + 40, esi_273, *((word32) esp_247 - 4));
			*((word32) esp_247 + 100) = 0x04;
			union Eq_3 * eax_346 = fn0046E360(ebx_270, esi_339, edi_272, out ebx_270, out ebp_269, out esi_273, out edi_272);
			*((word32) esp_247 + 100) = 0x03;
			if ((byte) (uint32) fn0046E280(eax_346, *esp_247) != (byte) ebx_270)
			{
				*esp_247 = edi_272;
				g_bA53FED = 0x01;
				operator =(&g_tA5423C, *esp_247);
				esp_247->u0 = 0x008AA4D8;
				fn00520C80();
				*((word32) esp_247 + 100) = 0x01;
				fn00422E10((word32) esp_247 + 40);
l0042B54D:
				word32 edx_555;
				Eq_3 eax_554;
				struct Eq_30914 * esp_498 = esp_194 - 4;
				esp_498->t0000 = esp_194 + 0x18;
				word32 edi_923;
				word32 ebp_922;
				Eq_3 ebx_506;
				struct Eq_30925 * esi_509;
				fn00424FD0(fn0046E360(ebx_270, esi_273, edi_272, out ebx_506, out ebp_922, out esi_509, out edi_923), esp_498->t0000);
				esp_498->b0064 = 0x05;
				Eq_23784 edx_eax_523 = __rdtsc();
				esp_498->t0000.u0 = 0x008AA4C0;
				esi_509->dw0500 = (word32) edx_eax_523;
				esi_509->dw0504 = SLICE(edx_eax_523, word32, 32);
				basic_string((const char *) &esp_498->t001C + 24, esp_498->t0000);
				Eq_3 edi_533 = esp_498->t001C;
				esp_498->t0000 = ebx_506;
				esp_498->tFFFFFFFC = (const char *) &esp_498->t001C + 24;
				esp_498->b0064 = 0x06;
				Eq_3 eax_541 = fn0040EF50(edi_533, esp_498->tFFFFFFFC, esp_498->t0000);
				esp_498->b0064 = 0x05;
				~basic_string((const char *) &esp_498->t001C + 24);
				byte bl_694 = (byte) ebx_506;
				if (eax_541 != ebx_506)
				{
					Eq_3 edx_559;
					Eq_3 eax_558 = fn00626B20(out edx_559);
					esp_498->t006C = edx_559;
					int64 edx_eax_569 = (int64) eax_541;
					esp_498->t0000 = SLICE(edx_eax_569, word32, 32);
					esp_498->tFFFFFFFC = (word32) edx_eax_569;
					esp_498->tFFFFFFF8 = esp_498->t006C;
					esp_498->tFFFFFFF4 = eax_558;
					eax_554 = fn006951B0(esp_498->tFFFFFFF4, esp_498->tFFFFFFF8, esp_498->tFFFFFFFC, esp_498->t0000, out edx_555);
				}
				else
				{
					eax_554.u0 = 0x00;
					edx_555 = 0x00;
				}
				struct Eq_31049 * esp_590 = esp_194 - 4;
				esp_590->t0000.u0 = 0x008AA4AC;
				esi_509->t0508 = eax_554;
				esi_509->dw050C = edx_555;
				basic_string((const char *) &esp_590->t0000 + 52, esp_590->t0000);
				esp_590->t0000 = ebx_506;
				esp_590->tFFFFFFFC = (const char *) &esp_590->t0000 + 52;
				esp_590->b0064 = 0x07;
				g_tA0D154 = fn0040EF50(edi_533, esp_590->tFFFFFFFC, esp_590->t0000);
				esp_590->b0064 = 0x05;
				~basic_string((const char *) &esp_590->t0000 + 52);
				esp_590->t0000.u0 = 9086108;
				basic_string((const char *) &esp_590->t0000 + 52, esp_590->t0000);
				esp_590->t0000 = ebx_506;
				esp_590->tFFFFFFFC = (const char *) &esp_590->t0000 + 52;
				esp_590->b0064 = 0x08;
				esp_590->b006C = (byte) (uint32) fn0040EEA0(edi_533, esp_590->tFFFFFFFC, esp_590->t0000);
				*fn00419A50() = esp_590->b006C;
				esp_590->b0064 = 0x05;
				~basic_string((const char *) &esp_590->t0000 + 52);
				esp_590->b0064 = 0x01;
				struct Eq_31167 * esp_640 = (const char *) &esp_590->t0000 + 4;
				if (edi_533 != ebx_506)
				{
					Eq_3 eax_656 = fn00401AE0(edi_533);
					if (eax_656 == 0x01)
					{
						<anonymous> ** edx_663 = *edi_533;
						esp_590->t0000 = eax_656;
						(*edx_663)();
					}
				}
				Eq_3 edi_691 = esp_640->t001C;
				esp_640->b0060 = bl_694;
				if (edi_691 != ebx_506)
				{
					Eq_3 eax_698 = fn00401AE0(edi_691);
					if (eax_698 == 0x01)
					{
						<anonymous> ** edx_705 = *edi_691;
						esp_640->tFFFFFFFC = eax_698;
						(*edx_705)();
					}
				}
				fs->ptr0000 = eax_9;
				ebpOut = ebp;
				esiOut = esi;
				ediOut = edi;
				xmm0Out.u0 = <invalid>;
				return ebx;
			}
		}
		struct Eq_31171 * esp_374 = esp_194 - 4;
		esp_374->ptr0000 = c_str(edi_272);
		esp_374->ptrFFFFFFFC = 9086076;
		ptr32 edi_387;
		Eq_3 esi_389 = fn00420190(ebx_270, es, ds, esp_374->ptrFFFFFFFC, out edi_387);
		esp_374->ptr0000 = (const char *) "Could not load config file";
		fn00421080((const char *) &esp_374->ptr0000 + 52, esp_374->ptr0000);
		esp_374->ptr0000 = (const char *) "";
		esp_374->ptrFFFFFFFC = (const char *) &esp_374->ptr0000 + 52;
		struct Eq_31213 * esp_420;
		struct std::exception * ecx_422;
		CxxThrowException();
		int3();
		int3();
		int3();
		int3();
		int3();
		int3();
		int3();
		int3();
		esp_420->dwFFFFFFFC = ~0x00;
		esp_420->dwFFFFFFF8 = 8589433;
		esp_420->ptrFFFFFFF4 = fs->ptr0000;
		esp_420->ptrFFFFFFF0 = ecx_422;
		esp_420->tFFFFFFEC = esi_389;
		esp_420->ptrFFFFFFE8 = edi_387;
		esp_420->dwFFFFFFE4 = g_tA14188 ^ esp_420 - 24;
		fs->ptr0000 = esp_420 - 0x0C;
		esp_420->ptrFFFFFFF0 = ecx_422;
		union Eq_31270 * edi_447 = esp_420->ptr0004;
		esp_420->ptrFFFFFFE0 = edi_447;
		exception(ecx_422, esp_420->ptrFFFFFFE0);
		esp_420->ptrFFFFFFE0 = (union Eq_31270 *) ((const char *) edi_447 + 0x0C);
		esp_420->dwFFFFFFFC = 0x00;
		ecx_422->dw0000 = 0x008A8634;
		basic_string(&ecx_422->dw0000 + 3, esp_420->ptrFFFFFFE0);
		fs->ptr0000 = esp_420->ptrFFFFFFF4;
		ptr32 edi_465 = esp_420->ptrFFFFFFE8;
		Eq_3 esi_467 = esp_420->tFFFFFFEC;
		ebpOut = ebp_269;
		esiOut = esi_467;
		ediOut = edi_465;
		xmm0Out.u0 = <invalid>;
		return ebx_270;
	}
	else
	{
		esp_247->u0 = 10830112;
		g_bA53FED = bl_289;
		operator =(&g_tA5423C, *esp_247);
		goto l0042B54D;
	}
}

// 0042CFC0: void fn0042CFC0(Register Eq_3 ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn0042DC50
void fn0042CFC0(Eq_3 ecx, Eq_3 dwArg04)
{
	if (ecx == dwArg04)
		return;
	Eq_3 eax_15 = *((word32) dwArg04 + 4);
	if (eax_15 != 0x00)
	{
		int32 ecx_20 = *((word32) dwArg04 + 8) - eax_15;
		int32 edx_24 = SLICE(ecx_20 *s64 0x92492493, word32, 32) + ecx_20;
		uint32 ecx_28 = (edx_24 >> 0x05 >> 0x1F) + (edx_24 >> 0x05);
		if (ecx_28 != 0x00)
		{
			uint32 eax_50;
			Eq_3 edi_37 = *((word32) ecx + 4);
			if (edi_37 == 0x00)
				eax_50 = 0x00;
			else
			{
				int32 ebx_42 = *((word32) ecx + 8) - edi_37;
				int32 edx_46 = SLICE(ebx_42 *s64 0x92492493, word32, 32) + ebx_42;
				eax_50 = (edx_46 >> 0x05 >> 0x1F) + (edx_46 >> 0x05);
			}
			if (ecx_28 > eax_50)
			{
				uint32 eax_74;
				if (edi_37 == 0x00)
					eax_74 = 0x00;
				else
				{
					int32 ebx_66 = *((word32) ecx + 0x0C) - edi_37;
					int32 edx_70 = SLICE(ebx_66 *s64 0x92492493, word32, 32) + ebx_66;
					eax_74 = (edx_70 >> 0x05 >> 0x1F) + (edx_70 >> 0x05);
				}
				if (ecx_28 > eax_74)
				{
					if (edi_37 != 0x00)
					{
						fn00428850(edi_37, *((word32) ecx + 8));
						operator delete(*((word32) ecx + 4));
					}
					if ((byte) (uint32) fn00422980(ecx, ecx, edi_37, fn005F8790(dwArg04)) != 0x00)
						*((word32) ecx + 8) = fn005AF380(*((word32) dwArg04 + 4), *((word32) dwArg04 + 8), *((word32) ecx + 4));
					return;
				}
				else
				{
					uint32 eax_180 = fn005F8790(ecx);
					Eq_3 eax_190 = *((word32) dwArg04 + 4);
					word32 ebx_191 = eax_190 + (eax_180 * 0x08 - eax_180) * 0x08;
					fn00428EA0(eax_190, ebx_191, edi_37);
					*((word32) ecx + 8) = fn005AF380(ebx_191, *((word32) dwArg04 + 8), *((word32) ecx + 8));
					return;
				}
			}
			else
			{
				fn00428850(fn00428EA0(*((word32) dwArg04 + 4), *((word32) dwArg04 + 8), edi_37), *((word32) ecx + 8));
				Eq_3 eax_265 = *((word32) dwArg04 + 4);
				if (eax_265 != 0x00)
				{
					Eq_31539 ecx_270 = *((word32) dwArg04 + 8) - eax_265;
					int32 edx_274 = (word32) ecx_270 + SLICE(ecx_270 *s64 0x92492493, word32, 32);
					eax_265 = (edx_274 >> 0x05 >> 0x1F) + (edx_274 >> 0x05);
				}
				Mem293[ecx + 0x08:word32] = Mem255[ecx + 0x04:word32] + (eax_265 * 0x08 - eax_265) * 0x08;
				return;
			}
		}
	}
	fn004292A0(ecx, fp + 0x04, *((word32) ecx + 4), *((word32) ecx + 8));
}

// 0042D270: void fn0042D270(Register word32 ecx, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack (ptr32 word32) dwArg04)
// Called from:
//      fn0042DF20
void fn0042D270(word32 ecx, struct Eq_7 * es, struct Eq_8 * ds, word32 * dwArg04)
{
	__align(fp - 4);
	word32 * esi_16 = dwArg04;
	word32 ecx_21;
	word32 * edi_22 = fp - 332;
	for (ecx_21 = 0x52; ecx_21 != 0x00; --ecx_21)
	{
		*edi_22 = *esi_16;
		++esi_16;
		++edi_22;
	}
	fn0042B1F0(ecx + 0x08, es, ds, fp - 336);
}

// 0042DC50: void fn0042DC50(Register (ptr32 Eq_31679) ecx, Stack (ptr32 Eq_31680) dwArg04)
// Called from:
//      fn0042DE90
void fn0042DC50(struct std::basic_string * ecx, basic_string * dwArg04)
{
	operator =(ecx, dwArg04);
	ecx->dw001C = dwArg04->dw001C;
	ecx->dw0020 = dwArg04->dw0020;
	ecx->dw0024 = dwArg04->dw0024;
	ecx->dw0028 = dwArg04->dw0028;
	ecx->dw002C = dwArg04->dw002C;
	ecx->dw0030 = dwArg04->dw0030;
	ecx->dw0034 = dwArg04->dw0034;
	ecx->dw0038 = dwArg04->dw0038;
	ecx->dw003C = dwArg04->dw003C;
	ecx->dw0040 = dwArg04->dw0040;
	ecx->dw0044 = dwArg04->dw0044;
	ecx->dw0048 = dwArg04->dw0048;
	ecx->r004C = dwArg04->r004C;
	ecx->b0050 = dwArg04->b0050;
	ecx->dw0054 = dwArg04->dw0054;
	ecx->dw0058 = dwArg04->dw0058;
	ecx->dw005C = dwArg04->dw005C;
	ecx->b0060 = dwArg04->b0060;
	ecx->dw0064 = dwArg04->dw0064;
	ecx->b0068 = dwArg04->b0068;
	ecx->b0069 = dwArg04->b0069;
	ecx->b006A = dwArg04->b006A;
	ecx->b006B = dwArg04->b006B;
	ecx->b006C = dwArg04->b006C;
	ecx->dw0070 = dwArg04->dw0070;
	ecx->dw0074 = dwArg04->dw0074;
	ecx->dw0078 = dwArg04->dw0078;
	fn0042CFC0(&ecx->dw0078 + 1, &dwArg04->dw0078 + 1);
	ecx->dw008C = dwArg04->dw008C;
	ecx->dw0090 = dwArg04->dw0090;
	ecx->dw0094 = dwArg04->dw0094;
	ecx->dw0098 = dwArg04->dw0098;
	ecx->dw009C = dwArg04->dw009C;
	ecx->dw00A0 = dwArg04->dw00A0;
	ecx->dw00A4 = dwArg04->dw00A4;
	ecx->dw00A8 = dwArg04->dw00A8;
	ecx->dw00B0 = dwArg04->dw00B0;
	ecx->dw00B4 = dwArg04->dw00B4;
	ecx->b00B8 = dwArg04->b00B8;
	ecx->dw00BC = dwArg04->dw00BC;
	ecx->dw00C0 = dwArg04->dw00C0;
	ecx->dw00C4 = dwArg04->dw00C4;
	ecx->dw00C8 = dwArg04->dw00C8;
	struct Eq_31945 * esp_163 = fp - 0x0C;
	Eq_3 ecx_128 = dwArg04->t00CC;
	Eq_3 ebx_129 = ecx->t00CC;
	if (ebx_129 != ecx_128)
	{
		ecx->t00CC = ecx_128;
		if (ecx_128 != 0x00)
			fn00401AD0(ecx_128);
		if (ebx_129 != 0x00 && fn00401AE0(ebx_129) == 0x01)
		{
			<anonymous> ** eax_153 = *ebx_129;
			(*eax_153)();
		}
	}
	Eq_3 ecx_171 = dwArg04->t00D0;
	Eq_3 ebx_173 = ecx->t00D0;
	if (ebx_173 != ecx_171)
	{
		ecx->t00D0 = ecx_171;
		if (ecx_171 != 0x00)
			fn00401AD0(ecx_171);
		if (ebx_173 != 0x00 && fn00401AE0(ebx_173) == 0x01)
		{
			<anonymous> ** eax_197 = *ebx_173;
			<anonymous> * edx_198 = *eax_197;
			esp_163->dwFFFFFFFC = 0x01;
			edx_198();
		}
	}
	Eq_3 ecx_218 = dwArg04->t00D4;
	Eq_3 ebx_220 = ecx->t00D4;
	if (ebx_220 != ecx_218)
	{
		ecx->t00D4 = ecx_218;
		if (ecx_218 != 0x00)
			fn00401AD0(ecx_218);
		if (ebx_220 != 0x00 && fn00401AE0(ebx_220) == 0x01)
		{
			<anonymous> ** eax_244 = *ebx_220;
			<anonymous> * edx_245 = *eax_244;
			esp_163->dwFFFFFFFC = 0x01;
			edx_245();
		}
	}
	ecx->b00D8 = dwArg04->b00D8;
}

// 0042DE90: Register Eq_409 fn0042DE90(Register Eq_409 xmm0)
// Called from:
//      fn0042F170
Eq_409 fn0042DE90(Eq_409 xmm0)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	operator =(&g_tA54720, "/");
	Eq_409 xmm0_30;
	fn0042DC50(&g_tA54768, fn005AEDE0(fp - 0xEC, xmm0, out xmm0_30));
	fn005AEED0(fp - 0xEC);
	fs->ptr0000 = eax_9;
	return xmm0_30;
}

// 0042DF20: Register word32 fn0042DF20(Register Eq_3 ecx, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Register Eq_409 xmm0, Stack Eq_3 dwArg04, Register out ptr32 ebpOut, Register out (ptr32 word32) esiOut, Register out Eq_409 xmm0Out)
// Called from:
//      fn0042DF20
//      fn007B2D10
word32 fn0042DF20(Eq_3 ecx, struct Eq_7 * es, struct Eq_8 * ds, Eq_409 xmm0, Eq_3 dwArg04, ptr32 & ebpOut, word32 & esiOut, union Eq_409 & xmm0Out)
{
	__align(fp - 4);
	fs->ptr0000 = fp - 0x10;
	Eq_3 ebp_168 = fp - 4;
	Eq_3 esp_141 = fp - 0x0188;
	Eq_3 edi_206 = ecx;
	Eq_3 ebx_169 = dwArg04;
	Eq_3 eax_35 = *((word32) dwArg04 + 4);
	if (eax_35 == 0x0115 || eax_35 == 0x3A)
	{
		word32 esi_42 = *dwArg04;
		fn0041F0B0();
		if (*((word32) ecx + 0x0528) != 0x00 || g_bA69858 == 0x01 && esi_42 == 0x02)
		{
			g_bA69858 = (int8) (esi_42 == 0x01);
			word32 esi_1098;
			word128 xmm0_1099;
			word32 ebp_1097;
			fn0042DF20(ecx, es, ds, xmm0, fp - 0x0168, out ebp_1097, out esi_1098, out xmm0_1099);
			esp_141.u0 = <invalid>;
		}
	}
	*((word32) esp_141 + 23) = 0x00;
	((word32) esp_141 + 24)->u0 = 0x00;
	Eq_3 esi_109 = 0x00;
	if (*dwArg04 == 0x02)
	{
		Eq_3 eax_102 = *((word32) dwArg04 + 4);
		if (*((word32) ecx + (eax_102 * 0x04 + 4)) == 0x00)
			goto l0042DFD1;
		Eq_3 ecx_106 = *((word32) ecx + (eax_102 * 0x04 + 4));
		((word32) ecx + (eax_102 * 0x04 + 4))->u0 = 0x00;
		*((word64) esp_141.u0 + 24) = ecx_106;
		esi_109 = ecx_106;
	}
	if (*dwArg04 == 0x01 && g_bA69858 != 0x00)
		*((word64) esp_141.u0 + 23) = 0x00;
	if (esi_109 != 0x05)
	{
		<anonymous> ** edx_123 = g_ptrA577E0;
		<anonymous> * eax_124 = *edx_123;
		*((word64) esp_141.u0 - 4) = dwArg04;
		uint32 eax_1090;
		eax_124();
		byte al_147 = (byte) eax_1090;
		*((word64) esp_141.u0 + 23) = al_147;
		if (al_147 != 0x00 && *dwArg04 == 0x01)
			((word32) ecx + (*((word32) dwArg04 + 4) * 0x04 + 4))->u0 = 0x01;
		if (esi_109 != 0x01)
		{
			if (al_147 == 0x00)
			{
				ebx_169 = fn0045E0B0(dwArg04, esi_109, ecx, out ebp_168);
				((word64) esp_141.u0 - 4)->u0 = 0x01;
				((word64) esp_141.u0 - 8)->u0 = 0x00;
				((word64) esp_141.u0 - 0x0C)->u0 = 0x008AA9BC;
				*((word64) esp_141.u0 - 16) = ebx_169;
				Eq_3 esi_191;
				*((word64) esp_141.u0 - 16) = fn00651DD0(out esi_191);
				((word64) esp_141.u0 - 20)->u0 = 9079908;
				*((word64) esp_141.u0 - 24) = esi_191;
				word32 edx_1100;
				*((word64) esp_141.u0 - 20) = fn006DF760(*((word64) esp_141.u0 - 24), *((word64) esp_141.u0 - 20), out edx_1100, out edi_206);
				Eq_3 eax_251 = fn00657140(ebx_169, edi_206, es, ds, *((word64) esp_141.u0 - 20), *((word64) esp_141.u0 - 16), *((word64) esp_141.u0 - 0x0C), *((word64) esp_141.u0 - 8));
				word24 eax_24_8_878 = SLICE(eax_251, word24, 8);
				if (eax_251 != 0x00)
				{
					((word64) esp_141.u0 - 4)->u0 = 0x008AA998;
					*((word64) esp_141.u0 - 8) = (word64) esp_141.u0 + 23;
					*((word64) esp_141.u0 - 0x0C) = eax_251;
					word32 ecx_272;
					Eq_3 eax_271 = fn00656570(ebx_169, ebp_168, eax_251, edi_206, es, ds, *((word64) esp_141.u0 - 0x0C), *((word64) esp_141.u0 - 8), *((word64) esp_141.u0 - 4), out ecx_272, out edi_206);
					word32 v18_282 = (word32) *eax_251 - 1;
					*eax_251 = v18_282;
					*((word64) esp_141.u0 + 28) = eax_271;
					eax_24_8_878 = SLICE(eax_271, word24, 8);
					if (v18_282 == 0x00)
					{
						Eq_3 edx_287 = *((word32) eax_251 + 4);
						Eq_3 eax_288 = *((word32) edx_287 + 24);
						*((word64) esp_141.u0 - 4) = eax_251;
						word32 esp_292;
						word32 eax_293;
						eax_288();
						eax_24_8_878 = SLICE(eax_293, word24, 8);
						esp_141 = esp_292 + 0x04;
					}
					if (*((word64) esp_141.u0 + 28) != 0x00)
					{
						word32 * esp_304 = esp_141 - 4;
						*esp_304 = 0x00;
						word32 esi_1101;
						ebx_169 = fn006E8D90(ebx_169, eax_251, edi_206, es, ds, out ebp_168, out esi_1101, out edi_206);
						esp_141 = esp_304 + 1;
						word32 ecx_1102;
						word32 edx_1103;
						eax_24_8_878 = SLICE(fn006E1160(out ecx_1102, out edx_1103), word24, 8);
					}
				}
				byte al_339 = *((word64) esp_141.u0 + 23);
				if (al_339 != 0x00 && *ebx_169 == 0x01)
					((word32) edi_206 + (*((word32) ebx_169 + 4) * 0x04 + 4))->u0 = 0x06;
				esi_109 = *((word32) esp_141 + 24);
				eax_1090 = SEQ(eax_24_8_878, al_339);
			}
			byte al_355 = (byte) eax_1090;
			if (esi_109 != 0x06)
			{
				uint32 eax_1085 = eax_1090;
				if (al_355 == 0x00)
				{
					struct Eq_32491 * esp_362 = esp_141 - 4;
					esp_362->t0000 = (word32) esp_141 + 28;
					<anonymous> *** ecx_373 = *fn00422DB0(fn00462790(), esp_362->t0000);
					<anonymous> ** edx_374 = *ecx_373;
					<anonymous> * eax_375 = *edx_374;
					esp_362->t0000 = ebx_169;
					esp_362->dw0184 = 0x00;
					uint32 eax_1092;
					eax_375();
					Eq_3 ecx_416 = *((word32) esp_141 + 28);
					*((word32) esp_141 + 23) = (byte) eax_1092;
					*((word32) esp_141 + 384) = ~0x00;
					if (ecx_416 != 0x00)
					{
						Eq_3 v19_423 = (word32) *((word32) ecx_416 + 4) - 1;
						*((word32) ecx_416 + 4) = v19_423;
						word24 eax_24_8_887 = SLICE((word32) ecx_416 + 4, word24, 8);
						if (v19_423 == 0x00)
						{
							Eq_3 ecx_428 = *((word32) ecx_416 + 8);
							Eq_3 edx_429 = *((word32) ecx_428 + 24);
							*((word32) esp_141 - 4) = (word32) ecx_416 + 4;
							word32 esp_432;
							word32 eax_433;
							word32 edx_435;
							edx_429();
							eax_24_8_887 = SLICE(eax_433, word24, 8);
							esp_141 = esp_432 + 0x04;
						}
						eax_1092 = SEQ(eax_24_8_887, *((word32) esp_141 + 23));
					}
					eax_1085 = eax_1092;
					if ((byte) eax_1092 != 0x00)
					{
						eax_1085 = eax_1092;
						if (*ebx_169 == 0x01)
						{
							((word32) edi_206 + (*((word32) ebx_169 + 4) * 0x04 + 4))->u0 = 0x03;
							eax_1085 = eax_1092;
						}
					}
				}
				byte al_461 = (byte) eax_1085;
				if (esi_109 != 0x03)
				{
					uint32 eax_1082 = eax_1085;
					if (al_461 == 0x00)
					{
						eax_1082 = eax_1085;
						if (*ebx_169 == 0x01)
						{
							struct Eq_32608 * esp_472 = esp_141 - 4;
							esp_472->t0000 = ebx_169;
							eax_1082 = (uint32) fn00421E80(edi_206, ebx_169, ebp_168, esi_109, edi_206, es, ds, esp_472->t0000, out ebp_168, out esi_109, out edi_206, out xmm0);
							byte al_511 = (byte) eax_1082;
							esp_472->b001B = al_511;
							if (al_511 != 0x00 && *ebx_169 == 0x01)
								((word32) edi_206 + (*((word32) ebx_169 + 4) * 0x04 + 4))->u0 = 0x04;
						}
					}
					byte al_523 = (byte) eax_1082;
					if (esi_109 != 0x04)
					{
						uint32 eax_1079 = eax_1082;
						if (al_523 != 0x00)
						{
l0042E249:
							byte al_723 = (byte) eax_1079;
							if (esi_109 != 0x00 && al_723 == 0x00)
							{
								Eq_3 eax_731 = *((word32) ebx_169 + 4);
								struct Eq_32800 * esp_733 = esp_141 - 4;
								esp_733->t0000 = esi_109;
								esp_733->tFFFFFFFC = eax_731;
								esp_733->dwFFFFFFF8 = 0x008AA950;
								fn00520C80();
							}
							fs->ptr0000 = (ptr32) *((word32) esp_141 + 376);
							struct Eq_32780 * esp_750 = (word32) esp_141 + 4;
							word32 * esi_753 = esp_750->ptr0004;
							word32 ebx_755 = esp_750->dw0008;
							ebpOut = (ptr32) *ebp_168;
							esiOut = esi_753;
							xmm0Out = xmm0;
							return ebx_755;
						}
						Eq_409 xmm0_551;
						word32 ebp_1104;
						Eq_3 ebx_548;
						Eq_3 edi_549;
						Eq_3 esi_550;
						if (fn0081DDF0(ebx_169, esi_109, edi_206, xmm0, out ebx_548, out ebp_1104, out esi_550, out edi_549, out xmm0_551)->t0000 != 0x02 && (fn0043D330)(ebx_548, esi_550, edi_549, out ebx_548, out esi_550, out edi_549)->dw0010 != 0x00)
						{
							word32 esi_1105;
							word32 edi_1106;
							fn0043D330(ebx_548, esi_550, edi_549, out ebx_548, out esi_1105, out edi_1106);
							struct Eq_32700 * esp_583 = esp_141 - 4;
							esp_583->dw0000 = 0x00;
							esp_583->tFFFFFFFC.u0 = 0x008AA980;
							esp_583->tFFFFFFF8 = ebx_548;
							Eq_3 esi_592;
							esp_583->tFFFFFFF8 = fn00651DD0(out esi_592);
							esp_583->tFFFFFFF4.u0 = 9079908;
							esp_583->tFFFFFFF0 = esi_592;
							word32 edx_1107;
							esp_583->tFFFFFFF4 = fn006DF760(esp_583->tFFFFFFF0, esp_583->tFFFFFFF4, out edx_1107, out edi_549);
							fn0041F300(ebx_548, edi_549, es, ds, esp_583->tFFFFFFF4, esp_583->tFFFFFFF8, esp_583->tFFFFFFFC, esp_583->dw0000);
							esi_550 = esp_583->t001C;
						}
						word32 eax_636 = *ebx_548;
						if (eax_636 == 0x01)
							((word32) edi_549 + (*((word32) ebx_548 + 4) * 0x04 + 4))->u0 = 0x02;
						else
						{
							if (eax_636 != 0x02)
								goto l0042E203;
							((word32) edi_549 + (*((word32) ebx_548 + 4) * 0x04 + 4))->u0 = 0x00;
						}
						*((word32) esp_141 + 23) = 0x01;
l0042E203:
						word32 edi_1108;
						struct Eq_26000 * eax_662 = fn0081DDF0(ebx_548, esi_550, edi_549, xmm0_551, out ebx_169, out ebp_168, out esi_109, out edi_1108, out xmm0);
						word24 eax_24_8_895 = SLICE(eax_662, word24, 8);
						if (eax_662->t0000 == 0x01)
						{
							Eq_27569 edx_677 = *ebx_169;
							Eq_3 eax_678 = *((word32) ebx_169 + 4);
							*((word32) esp_141 + 52) = *((word32) ebx_169 + 8);
							*((word32) esp_141 + 44) = edx_677;
							*((word32) esp_141 + 48) = eax_678;
							word32 ecx_683;
							struct Eq_32866 * esi_684 = g_aA69720;
							struct Eq_32868 * edi_685 = (word32) esp_141 + 56;
							for (ecx_683 = 0x4E; ecx_683 != 0x00; --ecx_683)
							{
								edi_685->b0000 = esi_684->b0000;
								++esi_684;
								++edi_685;
							}
							struct Eq_32871 * esp_689 = esp_141 - 4;
							esp_689->ptr0000 = (word32) esp_141 + 44;
							edi_685->b0000 = esi_684->b0000;
							fn0042D270(0x00A0D1B8, es, ds, esp_689->ptr0000);
							eax_24_8_895 = SLICE(eax_704, word24, 8);
							esi_109 = esp_689->t001C;
						}
						eax_1079 = SEQ(eax_24_8_895, *((word32) esp_141 + 23));
						goto l0042E249;
					}
				}
			}
		}
	}
l0042DFD1:
	fs->ptr0000 = (ptr32) *((word64) esp_141.u0 + 376);
	struct Eq_32210 * esp_777 = (word64) esp_141.u0 + 4;
	word32 * esi_780 = esp_777->ptr0004;
	word32 ebx_782 = esp_777->dw0008;
	ebpOut = (ptr32) *ebp_168;
	esiOut = esi_780;
	xmm0Out = xmm0;
	return ebx_782;
}

// 0042F170: Register byte fn0042F170(Register Eq_3 ecx, Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Register Eq_409 xmm0, Stack Eq_3 dwArg04, Stack Eq_461 dwArg08, Register out ptr32 ebpOut, Register out ptr32 ediOut, Register out Eq_409 xmm0Out)
// Called from:
//      fn004014B0
byte fn0042F170(Eq_3 ecx, Eq_3 ebx, Eq_3 ebp, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_409 xmm0, Eq_3 dwArg04, Eq_461 dwArg08, ptr32 & ebpOut, ptr32 & ediOut, union Eq_409 & xmm0Out)
{
	*((word32) ecx + 0x04E8) = dwArg08;
	g_tA53FF0 = dwArg04;
	g_tA53FF4 = dwArg08;
	g_bA115B4 = 0x00;
	Eq_3 ebp_30;
	Eq_3 ebx_31;
	Eq_3 edi_32;
	Eq_3 esi_34;
	fn00623E00(ebx_31, ebp_30, esi_34, edi_32, es, ds, fn006233B0(ebx, ebp, ecx, edi, out ebx_31, out ebp_30, out esi_34, out edi_32), 0x00, 9089040);
	Eq_3 ebp_67;
	Eq_3 ebx_68;
	Eq_3 edi_69;
	Eq_3 esi_71;
	fn00623E00(ebx_68, ebp_67, esi_71, edi_69, es, ds, fn006233B0(ebx_31, ebp_30, esi_34, edi_32, out ebx_68, out ebp_67, out esi_71, out edi_69), 0x00, 9080004);
	Eq_3 ebp_99;
	Eq_3 ebx_100;
	Eq_3 edi_101;
	Eq_3 esi_103;
	fn00623E00(ebx_100, ebp_99, esi_103, edi_101, es, ds, fn006233B0(ebx_68, ebp_67, esi_71, edi_69, out ebx_100, out ebp_99, out esi_103, out edi_101), 0x00, 0x008AAFF8);
	Eq_3 ebp_131;
	Eq_3 ebx_132;
	Eq_3 edi_133;
	Eq_3 esi_135;
	fn00623E00(ebx_132, ebp_131, esi_135, edi_133, es, ds, fn006233B0(ebx_100, ebp_99, esi_103, edi_101, out ebx_132, out ebp_131, out esi_135, out edi_133), 0x00, 0x008A85F0);
	Eq_3 ebp_163;
	Eq_3 ebx_164;
	Eq_3 edi_165;
	Eq_3 esi_167;
	fn00623E00(ebx_164, ebp_163, esi_167, edi_165, es, ds, fn006233B0(ebx_132, ebp_131, esi_135, edi_133, out ebx_164, out ebp_163, out esi_167, out edi_165), 0x00, 0x008A85E8);
	Eq_3 ebp_195;
	Eq_3 ebx_196;
	Eq_3 edi_197;
	Eq_3 esi_199;
	fn00623E00(ebx_196, ebp_195, esi_199, edi_197, es, ds, fn006233B0(ebx_164, ebp_163, esi_167, edi_165, out ebx_196, out ebp_195, out esi_199, out edi_197), 0x00, 0x008A85E0);
	Eq_3 ebp_227;
	Eq_3 ebx_228;
	Eq_3 edi_229;
	Eq_3 esi_231;
	fn00623E00(ebx_228, ebp_227, esi_231, edi_229, es, ds, fn006233B0(ebx_196, ebp_195, esi_199, edi_197, out ebx_228, out ebp_227, out esi_231, out edi_229), 0x00, 0x008A85D8);
	Eq_3 ebp_259;
	Eq_3 ebx_260;
	Eq_3 edi_261;
	Eq_3 esi_263;
	fn00623E00(ebx_260, ebp_259, esi_263, edi_261, es, ds, fn006233B0(ebx_228, ebp_227, esi_231, edi_229, out ebx_260, out ebp_259, out esi_263, out edi_261), 0x00, 0x008A85D0);
	Eq_3 ebp_291;
	Eq_3 ebx_292;
	Eq_3 edi_293;
	Eq_3 esi_295;
	fn00623E00(ebx_292, ebp_291, esi_295, edi_293, es, ds, fn006233B0(ebx_260, ebp_259, esi_263, edi_261, out ebx_292, out ebp_291, out esi_295, out edi_293), 0x00, 0x008A8AD8);
	Eq_3 ebp_323;
	Eq_3 ebx_324;
	Eq_3 edi_325;
	Eq_3 esi_327;
	fn00623E00(ebx_324, ebp_323, esi_327, edi_325, es, ds, fn006233B0(ebx_292, ebp_291, esi_295, edi_293, out ebx_324, out ebp_323, out esi_327, out edi_325), 0x00, 0x008AAFB8);
	Eq_3 ebp_355;
	Eq_3 ebx_356;
	Eq_3 edi_357;
	Eq_3 esi_359;
	fn00623E00(ebx_356, ebp_355, esi_359, edi_357, es, ds, fn006233B0(ebx_324, ebp_323, esi_327, edi_325, out ebx_356, out ebp_355, out esi_359, out edi_357), 0x00, 0x008AAFA8);
	ptr32 ebp_379;
	ptr32 edi_381;
	word32 ebx_592;
	struct Eq_25904 * esi_383;
	Eq_3 eax_377 = fn006233B0(ebx_356, ebp_355, esi_359, edi_357, out ebx_592, out ebp_379, out esi_383, out edi_381);
	<anonymous> ** edx_388 = *eax_377;
	struct Eq_33101 * esp_391;
	word32 eax_392;
	(*edx_388)();
	esp_391->dwFFFFFFFC = 9088900;
	esp_391->dwFFFFFFF8 = 0x02;
	esp_391->dwFFFFFFF4 = &esi_383->dw04FC + 11;
	esp_391->dwFFFFFFF0 = 9088876;
	esp_391->ptrFFFFFFEC = &esp_391->ptr0010;
	fn00422A90(esp_391->ptrFFFFFFEC);
	byte al_409 = (byte) eax_392;
	struct Eq_33135 * ecx_413 = esp_391->ptr0010;
	if (ecx_413 != null)
	{
		word32 v14_418 = ecx_413->dw0004 + ~0x00;
		ecx_413->dw0004 = v14_418;
		if (v14_418 == 0x00)
		{
			<anonymous> ** eax_422 = ecx_413->ptr0000;
			<anonymous> * edx_423 = *eax_422;
			esp_391->dwFFFFFFFC = 0x01;
			edx_423();
		}
	}
	if (esi_383->ptr052C == null)
		esi_383 = fn00420470(esi_383);
	if (al_409 != 0x00)
		xmm0 = fn0042DE90(xmm0);
	Eq_3 eax_471 = timeGetTime();
	esi_383->t04F8 = eax_471;
	esi_383->dw04FC = 0x00;
	ebpOut = ebp_379;
	ediOut = edi_381;
	xmm0Out = xmm0;
	return al_409;
}

