// sho_text_0023.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 00634DD0: void fn00634DD0(Register (ptr32 (ptr32 Eq_51208)) ecx)
// Called from:
//      fn004100F0
void fn00634DD0(struct Eq_51208 ** ecx)
{
	struct Eq_51208 * ecx_9 = *ecx;
	if (ecx_9 != null)
	{
		word32 v8_13 = ecx_9->dw0004 + ~0x00;
		ecx_9->dw0004 = v8_13;
		if (v8_13 == 0x00)
		{
			<anonymous> ** eax_17 = ecx_9->ptr0000;
			word32 edx_24;
			(*eax_17)();
		}
	}
	*ecx = (struct Eq_51208 **) null;
}

