// sho_text_0005.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 0045E0B0: Register Eq_3 fn0045E0B0(Register Eq_3 ebx, Register Eq_3 esi, Register Eq_3 edi, Register out (ptr32 ptr32) ebpOut)
// Called from:
//      fn0042DF20
Eq_3 fn0045E0B0(Eq_3 ebx, Eq_3 esi, Eq_3 edi, ptr32 & ebpOut)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	if ((g_tA56524 & 0x01) == 0x00)
	{
		g_tA56524 |= 0x01;
		fn005B62A0(&g_dwA5651C);
		g_dwA5651C = 0x008AEAE0;
		g_dwA56520 = 0x00;
		word32 esi_86;
		word32 edi_87;
		ebx = fn00694C8C(ebx, esi, edi, out ebp, out esi_86, out edi_87);
	}
	fs->ptr0000 = eax_9;
	ebpOut = ebp;
	return ebx;
}

