// sho_text_000B.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 004B3770: void fn004B3770(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack (ptr32 word32) dwArg0C)
// Called from:
//      fn00409AC0
//      fn004119C0
//      fn00417890
//      fn0041DA20
//      fn006204B0
//      fn00620670
//      fn00622070
void fn004B3770(Eq_3 dwArg04, Eq_3 dwArg08, word32 * dwArg0C)
{
	Eq_3 eax_16 = dwArg04;
	if (dwArg04 != dwArg08)
	{
		do
		{
			*eax_16 = *dwArg0C;
			eax_16 = (word32) eax_16 + 4;
		} while (eax_16 != dwArg08);
	}
}

