// sho_text_0003.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 0043D330: Register word32 fn0043D330(Register Eq_3 ebx, Register Eq_3 esi, Register Eq_3 edi, Register out Eq_3 ebxOut, Register out Eq_3 esiOut, Register out Eq_3 ediOut)
// Called from:
//      fn0042DF20
word32 fn0043D330(Eq_3 ebx, Eq_3 esi, Eq_3 edi, union Eq_3 & ebxOut, union Eq_3 & esiOut, union Eq_3 & ediOut)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	if ((g_tA55808 & 0x01) == 0x00)
	{
		g_tA55808 |= 0x01;
		g_dwA557F0 = 0x00;
		g_dwA557F4 = 0x00;
		g_dwA557F8 = 0x00;
		g_dwA557FC = 0x00;
		g_bA55800 = 0x01;
		g_dwA55804 = 0x00;
		word32 ebp_82;
		ebx = fn00694C8C(ebx, esi, edi, out ebp_82, out esi, out edi);
	}
	fs->ptr0000 = eax_9;
	ebxOut = ebx;
	esiOut = esi;
	ediOut = edi;
	return 0x00A557EC;
}

