// sho_data_0001.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

Eq_56268 g_tA1D1B8 = // 00A1D1B8
	{
		0x7C,
		0,
	};
Eq_179571 g_aA1D510[4] = // 00A1D510
	{
		
		{
			&g_tA1D510,
			&g_tA1D510,
			0,
		},
		
		{
			&g_tA1D528,
			&g_tA1D528,
			0,
		},
		
		{
			&g_tA1D540,
			&g_tA1D540,
			0,
		},
		
		{
			&g_tA1D510,
			&g_t0001,
			0x656E6F4E,
		},
	};
Eq_83565 g_aA1D520[3] = // 00A1D520
	{
		
		{
			700
		},
		
		{
			0
		},
		
		{
			10605864
		},
	};
Eq_82593 g_tA1D528 = // 00A1D528
	{
		10605864,
		10605864,
	};
Eq_179572 g_aA1D53C[] = // 00A1D53C
	{
	};
Eq_82593 g_tA1D540 = // 00A1D540
	{
		10605888,
		10605888,
	};
Eq_83483 g_tA1D554 = // 00A1D554
	{
		0x0A,
		0,
	};
Eq_3 g_tA1D558 = // 00A1D558
	{
		0x100A1D510
	};
word32 g_dwA1D55C = 0x01; // 00A1D55C
Eq_3 g_tA1E8A8 = // 00A1E8A8
	{
		0x3E8000003E8
	};
Eq_3 g_tA1E8AC = // 00A1E8AC
	{
		0x64000003E8
	};
int32 g_dwA1E8B0 = 100; // 00A1E8B0
int32 g_dwA1E8B4 = 100; // 00A1E8B4
Eq_55464 g_tA1EB98 = // 00A1EB98
	{
		&g_t70EFF0,
		&g_t70D9A0,
	};
Eq_3 g_aA1EDE0[] = // 00A1EDE0
	{
	};
word32 g_dwA1F410 = 0x0E; // 00A1F410
int32 g_dwA1F414 = 2; // 00A1F414
Eq_56268 g_tA215C0 = // 00A215C0
	{
		0x0C,
		0,
	};
Eq_53944 g_tA23B20 = // 00A23B20
	{
		&g_t71FE40,
	};
Eq_179686 g_aA23BE0[] = // 00A23BE0
	{
	};
Eq_56268 g_tA249B8 = // 00A249B8
	{
		44,
		0,
	};
Eq_56268 g_tA250F8 = // 00A250F8
	{
		0x10,
		0,
	};
Eq_3 g_tA253C0 = // 00A253C0
	{
		0x14
	};
word32 g_dwA25B38 = 0x01; // 00A25B38
Eq_53715 g_tA25D30 = // 00A25D30
	{
		
		{
			0x14
		},
	};
Eq_51591 g_tA25E40 = // 00A25E40
	{
		&g_t724880,
		0x00,
	};
byte * g_ptrA27250 = &g_b8DB7E0; // 00A27250
Eq_74292 g_tA27458 = // 00A27458
	{
		&g_t735170,
	};
Eq_3 g_tA27468 = // 00A27468
	{
		0x44
	};
struct Eq_1218 g_tA2B6F8 = // 00A2B6F8
	{
		&g_t738370,
	};
Eq_56268 g_tA2B8D8 = // 00A2B8D8
	{
		0x013C,
		4,
	};
Eq_53715 g_tA2BCA8 = // 00A2BCA8
	{
		
		{
			0x38
		},
	};
Eq_3 g_tA2BD68 = // 00A2BD68
	{
		0x8B655C008D9878
	};
