// sho_text_0011.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 00520C80: void fn00520C80()
// Called from:
//      fn004023A0
//      fn00403F70
//      fn00404190
//      fn004046D0
//      fn0040CBA0
//      fn00416A10
//      fn00416D90
//      fn00418D40
//      fn00419800
//      fn0041C4C0
//      fn0041E260
//      fn0041EE00
//      fn0042ACF0
//      fn0042B310
//      fn0042DF20
//      fn005A7E10
//      fn00623A00
//      fn00623E00
//      fn00657140
//      fn00657290
//      fn007B22E0
void fn00520C80()
{
}

