// sho_text_0006.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 00462790: Register word32 fn00462790()
// Called from:
//      fn0042DF20
word32 fn00462790()
{
	return g_dwA56628;
}

// 0046E280: Register byte fn0046E280(Register (ptr32 Eq_3) ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn0042B310
byte fn0046E280(union Eq_3 * ecx, Eq_3 dwArg04)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	struct Eq_34057 * esp_116 = fp - 28;
	if (dwArg04 != 0x00)
	{
		struct Eq_34068 * eax_34 = *dwArg04;
		word32 eax_38;
		word32 edx_40;
		eax_34->ptr0004();
		if (eax_38 != 0x00)
		{
			Eq_3 edi_91 = *ecx;
			if (edi_91 != dwArg04)
			{
				*ecx = (union Eq_3 *) dwArg04;
				fn00401AD0(dwArg04);
				if (edi_91 != 0x00 && fn00401AE0(edi_91) == 0x01)
				{
					<anonymous> ** eax_111 = *edi_91;
					<anonymous> * edx_112 = *eax_111;
					esp_116->dwFFFFFFFC = 0x01;
					word32 edx_119;
					edx_112();
				}
			}
			esp_116->dw0018 = ~0x00;
			Eq_3 eax_126 = fn00401AE0(dwArg04);
			if (eax_126 == 0x01)
			{
				struct Eq_34068 * eax_133 = *dwArg04;
				<anonymous> * edx_134 = eax_133->ptr0000;
				esp_116->dwFFFFFFFC = 0x01;
				word32 edx_145;
				edx_134();
			}
			fs->ptr0000 = eax_9;
			return 0x01;
		}
	}
	esp_116->dw0018 = ~0x00;
	if (dwArg04 != 0x00)
	{
		Eq_3 eax_53 = fn00401AE0(dwArg04);
		if (eax_53 == 0x01)
		{
			struct Eq_34068 * eax_60 = *dwArg04;
			<anonymous> * edx_61 = eax_60->ptr0000;
			esp_116->dwFFFFFFFC = 0x01;
			word32 edx_72;
			edx_61();
		}
	}
	fs->ptr0000 = eax_9;
	return 0x00;
}

// 0046E360: Register word32 fn0046E360(Register Eq_3 ebx, Register Eq_3 esi, Register Eq_3 edi, Register out Eq_3 ebxOut, Register out ptr32 ebpOut, Register out Eq_3 esiOut, Register out Eq_3 ediOut)
// Called from:
//      fn0042B310
word32 fn0046E360(Eq_3 ebx, Eq_3 esi, Eq_3 edi, union Eq_3 & ebxOut, ptr32 & ebpOut, union Eq_3 & esiOut, union Eq_3 & ediOut)
{
	if ((g_tA568D8 & 0x01) == 0x00)
	{
		g_tA568D8 |= 0x01;
		g_dwA568D4 = 0x00;
		ebx = fn00694C8C(ebx, esi, edi, out ebp, out esi, out edi);
	}
	ebxOut = ebx;
	ebpOut = ebp;
	esiOut = esi;
	ediOut = edi;
	return 0x00A568D4;
}

