// sho_text_001F.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 005F58C0: void fn005F58C0(Register (ptr32 (ptr32 Eq_43815)) ecx)
// Called from:
//      fn0040B930
//      fn0040BA10
//      fn004263B0
//      fn00428880
void fn005F58C0(struct Eq_43815 ** ecx)
{
	struct Eq_43815 * eax_6 = *ecx;
	if (eax_6->b002D == 0x00)
	{
		struct Eq_43815 * edx_36 = eax_6->ptr0000;
		if (edx_36->b002D != 0x00)
		{
			struct Eq_43815 * eax_12 = eax_6->ptr0004;
			if (eax_12->b002D == 0x00)
			{
				while (*ecx == eax_12->ptr0000)
				{
					*ecx = (struct Eq_43815 **) eax_12;
					eax_12 = eax_12->ptr0004;
					if (eax_12->b002D != 0x00)
						break;
				}
			}
			if (*((const char *) *ecx + 45) == 0x00)
				*ecx = (struct Eq_43815 **) eax_12;
		}
		else
		{
			struct Eq_43815 * eax_32 = edx_36->ptr0008;
			while (eax_32->b002D == 0x00)
			{
				edx_36 = eax_32;
				eax_32 = eax_32->ptr0008;
			}
			*ecx = (struct Eq_43815 **) edx_36;
		}
	}
	else
		*ecx = (struct Eq_43815 **) eax_6->ptr0008;
}

// 005F8790: Register Eq_3 fn005F8790(Register Eq_3 ecx)
// Called from:
//      fn0042CFC0
Eq_3 fn005F8790(Eq_3 ecx)
{
	Eq_3 eax_6 = *((word32) ecx + 4);
	if (eax_6 == 0x00)
		return eax_6;
	int32 ecx_11 = *((word32) ecx + 8) - eax_6;
	int32 edx_15 = SLICE(ecx_11 *s64 0x92492493, word32, 32) + ecx_11;
	return (edx_15 >> 0x05 >> 0x1F) + (edx_15 >> 0x05);
}

// 005F8FB0: Register Eq_3 fn005F8FB0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00411F00
//      fn004EA120
Eq_3 fn005F8FB0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 edx_24 = dwArg04;
	Eq_3 eax_19 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			if (eax_19 != 0x00)
			{
				word32 ecx_23;
				Eq_3 esi_25 = edx_24;
				Eq_3 edi_26 = eax_19;
				for (ecx_23 = 0x10; ecx_23 != 0x00; --ecx_23)
				{
					*edi_26 = *esi_25;
					esi_25 = (word32) esi_25 + 4;
					edi_26 = (word32) edi_26 + 4;
				}
			}
			edx_24 = (word32) edx_24 + 64;
			eax_19 = (word32) eax_19 + 64;
		} while (edx_24 != dwArg08);
	}
	return eax_19;
}

// 005F9240: Register Eq_3 fn005F9240(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Register out Eq_3 edxOut)
// Called from:
//      fn0044F1E0
//      fn0059EB70
//      fn005A5370
Eq_3 fn005F9240(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, union Eq_3 & edxOut)
{
	Eq_3 ecx_17 = dwArg04;
	Eq_3 eax_13 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			if (eax_13 != 0x00)
			{
				*eax_13 = *ecx_17;
				*((word32) eax_13 + 4) = *((word32) ecx_17 + 4);
				*((word32) eax_13 + 8) = *((word32) ecx_17 + 8);
				*((word32) eax_13 + 0x0C) = *((word32) ecx_17 + 0x0C);
			}
			ecx_17 = (word32) ecx_17 + 16;
			eax_13 = (word32) eax_13 + 16;
		} while (ecx_17 != dwArg08);
	}
	edxOut = dwArg08;
	return eax_13;
}

