// sho_text_001B.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 005B60D0: void fn005B60D0(Register (ptr32 Eq_42670) ecx)
// Called from:
//      fn005B6640
//      fn005B6780
void fn005B60D0(struct Eq_42670 * ecx)
{
	struct Eq_42671 * ecx_9 = ecx->ptr0004;
	struct Eq_42671 * eax_10 = ecx_9->ptr0000;
	ecx_9->ptr0000 = ecx_9;
	struct Eq_42671 * ecx_12 = ecx->ptr0004;
	ecx_12->ptr0004 = ecx_12;
	ecx->dw0008 = 0x00;
	if (eax_10 != ecx->ptr0004)
	{
		do
		{
			struct Eq_42671 * edi_23 = eax_10->ptr0000;
			operator delete(eax_10);
			eax_10 = edi_23;
		} while (edi_23 != ecx->ptr0004);
	}
}

// 005B6110: void fn005B6110(Register (ptr32 Eq_42709) ecx, Stack up32 dwArg04)
// Called from:
//      fn005B61E0
//      fn005B62A0
void fn005B6110(struct Eq_42709 * ecx, up32 dwArg04)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	up32 eax_23 = ecx->dw0008;
	up32 edx_24 = dwArg04;
	if (0x3FFFFFFF - eax_23 < dwArg04)
	{
		basic_string(fp - 0x50, "list<T> too long");
		fn004019E0(fp - 0x34, fp - 0x50);
		CxxThrowException();
	}
	ecx->dw0008 = eax_23 + edx_24;
	fs->ptr0000 = eax_9;
}

// 005B61E0: void fn005B61E0(Register (ptr32 Eq_42709) ecx, Stack (ptr32 Eq_42671) dwArg04, Stack (ptr32 Eq_42671) dwArg08, Stack (ptr32 Eq_42671) dwArg0C)
// Called from:
//      fn005B65B0
void fn005B61E0(struct Eq_42709 * ecx, struct Eq_42671 * dwArg04, struct Eq_42671 * dwArg08, struct Eq_42671 * dwArg0C)
{
	ptr32 eax_13 = fs->ptr0000;
	fs->ptr0000 = fp - 0x10;
	struct Eq_42671 * edi_41;
	for (edi_41 = dwArg08; edi_41 != dwArg0C; edi_41 = edi_41->ptr0000)
	{
		struct Eq_42671 * eax_71 = fn008119C0(dwArg04, dwArg04->ptr0004, &edi_41->t0008);
		fn005B6110(ecx, 0x01);
		dwArg04->ptr0004 = eax_71;
		eax_71->ptr0004->ptr0000 = eax_71;
	}
	fs->ptr0000 = eax_13;
}

// 005B62A0: void fn005B62A0(Register (ptr32 word32) ecx)
// Called from:
//      fn0045E0B0
void fn005B62A0(word32 * ecx)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	*ecx = 9189596;
	if (g_ptrA62CC8 == null)
	{
		struct Eq_42709 * eax_40 = operator new(0x0C);
		struct Eq_42709 * esi_41 = eax_40;
		if (eax_40 != null)
		{
			eax_40->ptr0004 = fn004C8820();
			eax_40->dw0008 = 0x00;
		}
		else
			esi_41 = null;
		g_ptrA62CC8 = esi_41;
		struct Eq_42812 * eax_65 = operator new(0x08);
		struct Eq_42812 * esi_67 = eax_65;
		if (eax_65 != null)
		{
			eax_65->t0000 = CreateMutexA(null, 0x00, 0x00);
			eax_65->b0004 = 0x00;
		}
		else
			esi_67 = null;
		g_ptrA62CD4 = esi_67;
		struct Eq_42670 * eax_90 = operator new(0x0C);
		struct Eq_42670 * esi_114 = eax_90;
		if (eax_90 != null)
		{
			eax_90->ptr0004 = fn004C8820();
			eax_90->dw0008 = 0x00;
		}
		else
			esi_114 = null;
		g_ptrA62CCC = esi_114;
		struct Eq_42931 * eax_116 = operator new(0x08);
		struct Eq_42931 * esi_117 = eax_116;
		if (eax_116 != null)
		{
			eax_116->t0000 = CreateMutexA(null, 0x00, 0x00);
			eax_116->b0004 = 0x00;
		}
		else
			esi_117 = null;
		g_ptrA62CD0 = esi_117;
	}
	struct Eq_42812 * eax_139 = g_ptrA62CD4;
	WaitForSingleObject(eax_139->t0000, ~0x00);
	eax_139->b0004 = 0x01;
	struct Eq_42709 * ecx_153 = g_ptrA62CC8;
	struct Eq_42671 * esi_154 = ecx_153->ptr0004;
	struct Eq_42671 * eax_171 = fn008119C0(esi_154, esi_154->ptr0004, fp - 0x18);
	fn005B6110(ecx_153, 0x01);
	esi_154->ptr0004 = eax_171;
	eax_171->ptr0004->ptr0000 = eax_171;
	Eq_3 edx_199 = eax_139->t0000;
	eax_139->b0004 = 0x00;
	ReleaseMutex(edx_199);
	fs->ptr0000 = eax_9;
}

// 005B65B0: void fn005B65B0(Register (ptr32 Eq_42709) ecx, Stack (ptr32 Eq_42709) dwArg04)
// Called from:
//      fn005B6640
//      fn005B6780
void fn005B65B0(struct Eq_42709 * ecx, struct Eq_42709 * dwArg04)
{
	ptr32 eax_13 = fs->ptr0000;
	fs->ptr0000 = fp - 0x10;
	struct Eq_42671 * eax_38 = fn004C8820();
	ecx->ptr0004 = eax_38;
	ecx->dw0008 = 0x00;
	struct Eq_42671 * ecx_48 = dwArg04->ptr0004;
	fn005B61E0(ecx, eax_38->ptr0000, ecx_48->ptr0000, ecx_48);
	fs->ptr0000 = eax_13;
}

// 005B6640: void fn005B6640()
// Called from:
//      fn005A7560
void fn005B6640()
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	if (g_ptrA62CC8 != null)
	{
		struct Eq_42812 * eax_33 = g_ptrA62CD4;
		WaitForSingleObject(eax_33->t0000, ~0x00);
		eax_33->b0004 = 0x01;
		fn005B65B0(fp - 0x18, g_ptrA62CC8);
		fn005B60D0(g_ptrA62CCC);
		struct Eq_42812 * eax_63 = g_ptrA62CD4;
		Eq_3 edx_64 = eax_63->t0000;
		eax_63->b0004 = 0x00;
		ReleaseMutex(edx_64);
		struct Eq_43044 * esp_148 = fp - 44;
		struct Eq_43047 * esi_154 = dwLoc14->ptr0000;
		if (esi_154 != dwLoc14)
		{
			do
			{
				struct Eq_42931 * eax_77 = g_ptrA62CD0;
				Eq_3 eax_79 = eax_77->t0000;
				struct Eq_43116 * esp_81 = esp_148 - 4;
				esp_81->t0000.u0 = ~0x00;
				esp_81->tFFFFFFFC = eax_79;
				WaitForSingleObject(esp_81->tFFFFFFFC, esp_81->t0000);
				eax_77->b0004 = 0x01;
				struct Eq_42671 * eax_89 = g_ptrA62CCC->ptr0004;
				struct Eq_42671 * ecx_100 = eax_89->ptr0000;
				if (ecx_100 != eax_89)
				{
					Eq_43128 edi_94 = esi_154->t0008;
					while (ecx_100->t0008 != edi_94)
					{
						ecx_100 = ecx_100->ptr0000;
						if (ecx_100 == eax_89)
							break;
					}
					if (ecx_100 == eax_89)
						goto l005B6715;
					struct Eq_42931 * eax_155 = g_ptrA62CD0;
					esi_154 = esi_154->ptr0000;
					esp_81->t0000 = eax_155->t0000;
					eax_155->b0004 = 0x00;
					ReleaseMutex(esp_81->t0000);
					esp_148 = (struct Eq_43044 *) ((const char *) &esp_81->t0000 + 4);
				}
				else
				{
l005B6715:
					struct Eq_42931 * eax_110 = g_ptrA62CD0;
					esp_81->t0000 = eax_110->t0000;
					eax_110->b0004 = 0x00;
					ReleaseMutex(esp_81->t0000);
					Eq_43128 ecx_145 = esi_154->t0008;
					<anonymous> ** eax_146 = *ecx_145;
					word32 edx_151;
					(*eax_146)();
					esi_154 = esi_154->ptr0000;
				}
			} while (esi_154 != esp_148[6]);
		}
		struct Eq_42931 * eax_173 = g_ptrA62CD0;
		Eq_3 eax_175 = eax_173->t0000;
		struct Eq_43060 * esp_177 = esp_148 - 4;
		esp_177->t0000.u0 = ~0x00;
		esp_177->tFFFFFFFC = eax_175;
		WaitForSingleObject(esp_177->tFFFFFFFC, esp_177->t0000);
		eax_173->b0004 = 0x01;
		fn005B60D0(g_ptrA62CCC);
		struct Eq_42931 * eax_204 = g_ptrA62CD0;
		esp_177->t0000 = eax_204->t0000;
		eax_204->b0004 = 0x00;
		ReleaseMutex(esp_177->t0000);
		fn005CAB80((const char *) &esp_177->t0000 + 24);
	}
	fs->ptr0000 = eax_9;
}

// 005B6780: void fn005B6780()
// Called from:
//      fn005A7560
void fn005B6780()
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	if (g_ptrA62CC8 != null)
	{
		struct Eq_42812 * eax_33 = g_ptrA62CD4;
		WaitForSingleObject(eax_33->t0000, ~0x00);
		eax_33->b0004 = 0x01;
		fn005B65B0(fp - 0x18, g_ptrA62CC8);
		fn005B60D0(g_ptrA62CCC);
		struct Eq_42812 * eax_63 = g_ptrA62CD4;
		Eq_3 edx_64 = eax_63->t0000;
		eax_63->b0004 = 0x00;
		ReleaseMutex(edx_64);
		struct Eq_43272 * esp_148 = fp - 44;
		struct Eq_43275 * esi_154 = dwLoc14->ptr0000;
		if (esi_154 != dwLoc14)
		{
			do
			{
				struct Eq_42931 * eax_77 = g_ptrA62CD0;
				Eq_3 eax_79 = eax_77->t0000;
				struct Eq_43342 * esp_81 = esp_148 - 4;
				esp_81->t0000.u0 = ~0x00;
				esp_81->tFFFFFFFC = eax_79;
				WaitForSingleObject(esp_81->tFFFFFFFC, esp_81->t0000);
				eax_77->b0004 = 0x01;
				struct Eq_42671 * eax_89 = g_ptrA62CCC->ptr0004;
				struct Eq_42671 * ecx_100 = eax_89->ptr0000;
				if (ecx_100 != eax_89)
				{
					Eq_43128 edi_94 = esi_154->t0008;
					while (ecx_100->t0008 != edi_94)
					{
						ecx_100 = ecx_100->ptr0000;
						if (ecx_100 == eax_89)
							break;
					}
					if (ecx_100 == eax_89)
						goto l005B6855;
					struct Eq_42931 * eax_155 = g_ptrA62CD0;
					esi_154 = esi_154->ptr0000;
					esp_81->t0000 = eax_155->t0000;
					eax_155->b0004 = 0x00;
					ReleaseMutex(esp_81->t0000);
					esp_148 = (struct Eq_43272 *) ((const char *) &esp_81->t0000 + 4);
				}
				else
				{
l005B6855:
					struct Eq_42931 * eax_110 = g_ptrA62CD0;
					esp_81->t0000 = eax_110->t0000;
					eax_110->b0004 = 0x00;
					ReleaseMutex(esp_81->t0000);
					Eq_43128 ecx_145 = esi_154->t0008;
					struct Eq_43358 * eax_146 = *ecx_145;
					word32 edx_151;
					eax_146->ptr0004();
					esi_154 = esi_154->ptr0000;
				}
			} while (esi_154 != esp_148[6]);
		}
		struct Eq_42931 * eax_173 = g_ptrA62CD0;
		Eq_3 eax_175 = eax_173->t0000;
		struct Eq_43288 * esp_177 = esp_148 - 4;
		esp_177->t0000.u0 = ~0x00;
		esp_177->tFFFFFFFC = eax_175;
		WaitForSingleObject(esp_177->tFFFFFFFC, esp_177->t0000);
		eax_173->b0004 = 0x01;
		fn005B60D0(g_ptrA62CCC);
		struct Eq_42931 * eax_204 = g_ptrA62CD0;
		esp_177->t0000 = eax_204->t0000;
		eax_204->b0004 = 0x00;
		ReleaseMutex(esp_177->t0000);
		fn005CAB80((const char *) &esp_177->t0000 + 24);
	}
	fs->ptr0000 = eax_9;
}

// 005B87B0: void fn005B87B0(Register Eq_3 ecx)
// Called from:
//      fn00428850
//      fn004292A0
//      fn005AEBE0
void fn005B87B0(Eq_3 ecx)
{
	Eq_3 esi_15 = *((word32) ecx + 52);
	if (esi_15 != 0x00 && (fn00401AE0(esi_15) == 0x01 && esi_15 != 0x00))
	{
		Eq_3 eax_29 = *esi_15;
		word32 edx_37;
		(*eax_29)();
	}
	((word32) ecx + 52)->u0 = 0x00;
}

// 005BB700: Register word32 fn005BB700(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00622B40
word32 fn005BB700(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	fn007C2D70(dwArg04, dwArg08, dwArg0C);
	return (word32) dwArg04 + dwArg08 * 0x08;
}

