// sho_text_003B.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 007B1C20: void fn007B1C20(Register (ptr32 Eq_177300) ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn007B2160
void fn007B1C20(struct Eq_177300 * ecx, Eq_3 dwArg04)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	ecx->dw0004 = 0x00;
	ecx->dw0000 = 9999152;
	basic_string(&ecx->dw0008 + 1);
	basic_string(&ecx->dw0008 + 8);
	ecx->dw0008 = 0x00;
	operator =(&ecx->dw0008 + 1, "*** No Error.\n");
	operator =(&ecx->dw0008 + 8, dwArg04);
	fs->ptr0000 = eax_9;
}

// 007B1F20: void fn007B1F20(Register (ptr32 Eq_30859) ecx)
// Called from:
//      fn0042B310
void fn007B1F20(struct Eq_30859 * ecx)
{
	ecx->dw0004 = 0x00;
	ecx->dw0000 = 9999200;
	ecx->dw0008 = 0x00;
}

// 007B1F60: Register Eq_3 fn007B1F60(Register (ptr32 Eq_31333) ecx, Register Eq_3 esi, Stack Eq_3 dwArg04)
// Called from:
//      fn0042B310
Eq_3 fn007B1F60(struct Eq_31333 * ecx, Eq_3 esi, Eq_3 dwArg04)
{
	struct Eq_177375 ** ecx_8 = ecx->ptr0008;
	if (ecx_8 == null)
	{
		*dwArg04 = 0x00;
		return esi;
	}
	else
	{
		<anonymous> * eax_17 = *((const char *) *ecx_8 + 4);
		struct Eq_177379 * esp_24;
		union Eq_3 * eax_26;
		eax_17();
		Eq_3 ecx_30 = *eax_26;
		*esp_24->ptr000C = (union Eq_3 *) ecx_30;
		if (ecx_30 != 0x00)
			fn00401AD0(ecx_30);
		Eq_3 ecx_42 = esp_24->t0004;
		if (ecx_42 != 0x00)
		{
			esp_24->tFFFFFFFC = esi;
			union Eq_3 * esp_46 = esp_24 - 4;
			Eq_3 eax_51 = fn00401AE0(ecx_42);
			if (eax_51 == 0x01 && ecx_42 != 0x00)
			{
				Eq_177163 edx_61 = *ecx_42;
				esp_24->tFFFFFFF8 = eax_51;
				(*edx_61)();
			}
			esi = *esp_46;
		}
		return esi;
	}
}

// 007B20A0: Register word32 fn007B20A0(Register (ptr32 Eq_177300) ecx, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Register out ptr32 ebpOut)
// Called from:
//      fn007B2160
word32 fn007B20A0(struct Eq_177300 * ecx, struct Eq_7 * es, struct Eq_8 * ds, ptr32 & ebpOut)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	ptr32 ebp_45;
	word32 ebx_46;
	Eq_3 ecx_56 = *fn00419800(es, ds, dwLoc2C, c_str(&ecx->dw0008 + 8), out ebx_46, out ebp_45);
	struct Eq_177459 * esp_102 = fp - 0x1C;
	Eq_3 esi_57 = ecx->t0044;
	if (esi_57 != ecx_56)
	{
		ecx->t0044 = ecx_56;
		if (ecx_56 != 0x00)
			fn00401AD0(ecx_56);
		if (esi_57 != 0x00)
		{
			Eq_3 eax_74 = fn00401AE0(esi_57);
			if (eax_74 == 0x01)
			{
				Eq_177163 edx_82 = *esi_57;
				(*edx_82)();
			}
		}
	}
	Eq_3 ecx_104 = esp_102->t000C;
	esp_102->dw0018 = ~0x00;
	if (ecx_104 != 0x00)
	{
		Eq_3 eax_110 = fn00401AE0(ecx_104);
		if (eax_110 == 0x01 && ecx_104 != 0x00)
		{
			Eq_177163 edx_120 = *ecx_104;
			esp_102->tFFFFFFFC = eax_110;
			(*edx_120)();
		}
	}
	fs->ptr0000 = eax_9;
	ebpOut = ebp_45;
	return ebx_46;
}

// 007B2160: Register (ptr32 Eq_177300) fn007B2160(Register (ptr32 Eq_177300) ecx, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04, Register out (ptr32 Eq_177522) ebxOut, Register out ptr32 ebpOut)
// Called from:
//      fn007B22E0
struct Eq_177300 * fn007B2160(struct Eq_177300 * ecx, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04, struct std::basic_string & ebxOut, ptr32 & ebpOut)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	fn007B1C20(ecx, dwArg04);
	ecx->dw0000 = 9999204;
	ecx->t0044.u0 = 0x00;
	ptr32 ebp_52;
	struct std::basic_string * ebx_53 = fn007B20A0(ecx, es, ds, out ebp_52);
	fs->ptr0000 = eax_9;
	ebxOut = ebx_53;
	ebpOut = ebp_52;
	return ecx;
}

// 007B22E0: Register word32 fn007B22E0(Register (ptr32 Eq_30879) ecx, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Register out Eq_30884 ecxOut)
// Called from:
//      fn0042B310
word32 fn007B22E0(struct Eq_30879 * ecx, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04, Eq_3 dwArg08, union Eq_30884 & ecxOut)
{
	word32 eax_162;
	ptr32 eax_9 = fs->ptr0000;
	Eq_30884 eax_25 = g_tA14188 ^ fp - 28;
	fs->ptr0000 = fp - 0x0C;
	c_str(dwArg04);
	fn00520C80();
	Eq_3 ebx_34 = dwArg04;
	struct Eq_177576 * esi_42 = null;
	word32 ebp_185 = 0x01;
	if (ecx->ptr0008 == null)
	{
		if (dwArg08 != 0x00)
		{
			struct Eq_177582 * ecx_166 = ecx->ptr0008;
			if (ecx_166 != null)
			{
				ecx->ptr0008 = null;
				word32 v14_171 = ecx_166->dw0004 + ~0x00;
				ecx_166->dw0004 = v14_171;
				if (v14_171 == 0x00)
				{
					<anonymous> ** eax_175 = ecx_166->ptr0000;
					word32 edx_182;
					(*eax_175)();
				}
			}
		}
		else
		{
			struct Eq_177300 * eax_51 = operator new(0x48);
			if (eax_51 != null)
				esi_42 = fn007B2160(eax_51, es, ds, dwArg04, out ebx_34, out ebp_185);
			if (esi_42->dw0044 != 0x00)
			{
				++esi_42->dw0004;
				fn00529B70(&ecx->ptr0008, fp + 0x04);
				word32 v17_146 = esi_42->dw0004 + ~0x00;
				esi_42->dw0004 = v17_146;
				if (v17_146 == 0x00)
				{
					<anonymous> ** edx_151 = esi_42->ptr0000;
					(*edx_151)();
				}
				eax_162 = 0x00;
l007B2407:
				fs->ptr0000 = eax_9;
				ecxOut = eax_25;
				return eax_162;
			}
			c_str(ebx_34);
			fn00520C80();
			<anonymous> ** edx_91 = esi_42->ptr0000;
			struct Eq_177642 * esp_107;
			(*edx_91)();
			esp_107->dw0024 = 0x00;
			esp_107->tFFFFFFFC = &esp_107->dw0024;
			esp_107->dw001C = 0x02;
			fn00529B70(&ecx->ptr0008, esp_107->tFFFFFFFC);
		}
	}
	eax_162 = ebp_185;
	goto l007B2407;
}

// 007B2480: Register (ptr32 void) fn007B2480(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Stack Eq_3 dwArg04, Register out Eq_3 ecxOut, Register out Eq_9944 edxOut, Register out Eq_3 ebxOut, Register out Eq_3 ebpOut, Register out Eq_3 esiOut, Register out Eq_3 ediOut)
// Called from:
//      fn00409AC0
//      fn004119C0
//      fn00411D40
//      fn00414B80
//      fn00417890
//      fn00418150
//      fn0041DA20
//      fn004DB6B0
//      fn006204B0
//      fn00620670
//      fn006218A0
//      fn00622070
//      fn00622230
void * fn007B2480(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, Eq_3 dwArg04, union Eq_3 & ecxOut, union Eq_9944 & edxOut, union Eq_3 & ebxOut, union Eq_3 & ebpOut, union Eq_3 & esiOut, union Eq_3 & ediOut)
{
	Eq_3 ecx_5 = dwArg04;
	if (dwArg04 <= 0x00)
		ecx_5.u0 = 0x00;
	else if ((uint32) (0xFFFFFFFF /u dwArg04) < 0x04)
	{
		struct Eq_177717 * esp_33;
		CxxThrowException();
		int3();
		int3();
		int3();
		int3();
		int3();
		esp_33->tFFFFFFF4 = ebx;
		esp_33->tFFFFFFF0 = ebp;
		struct Eq_107701 * ebp_46 = g_ptrA6EBE0;
		esp_33->tFFFFFFEC = esi;
		esp_33->tFFFFFFE8 = edi;
		if (ebp_46 == null)
		{
			Eq_3 ebp_57;
			Eq_3 ebx_58;
			Eq_3 edi_59;
			Eq_3 esi_60;
			Eq_3 ecx_62;
			Eq_9944 edx_63;
			void * eax_56 = fn007B24F7(ebp_46, null, esp_33->tFFFFFFE8, esp_33->tFFFFFFEC, esp_33->tFFFFFFF0, esp_33->tFFFFFFF4, esp_33->t0004, out ecx_62, out edx_63, out ebx_58, out ebp_57, out esi_60, out edi_59);
			ecxOut = ecx_62;
			edxOut = edx_63;
			ebxOut = ebx_58;
			ebpOut = ebp_57;
			esiOut = esi_60;
			ediOut = edi_59;
			return eax_56;
		}
		else
		{
			Eq_3 ebp_69;
			Eq_3 ebx_70;
			Eq_3 edi_71;
			Eq_3 esi_72;
			Eq_3 ecx_74;
			Eq_9944 edx_75;
			void * eax_68 = fn007B24F7(ebp_46, null, esp_33->tFFFFFFE8, esp_33->tFFFFFFEC, esp_33->tFFFFFFF0, esp_33->tFFFFFFF4, esp_33->t0004, out ecx_74, out edx_75, out ebx_70, out ebp_69, out esi_72, out edi_71);
			ecxOut = ecx_74;
			edxOut = edx_75;
			ebxOut = ebx_70;
			ebpOut = ebp_69;
			esiOut = esi_72;
			ediOut = edi_71;
			return eax_68;
		}
	}
	Eq_9944 edx_84 = ecx_5 * 0x04;
	void * eax_88 = operator new(edx_84);
	ecxOut = ecx_5;
	edxOut = edx_84;
	ebxOut = ebx;
	ebpOut = ebp;
	esiOut = esi;
	ediOut = edi;
	return eax_88;
}

// 007B24E0: Register byte fn007B24E0(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Stack Eq_3 dwArg04, Register out Eq_3 ebxOut, Register out Eq_3 ebpOut, Register out Eq_3 ediOut)
// Called from:
//      fn007B2D10
byte fn007B24E0(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, Eq_3 dwArg04, union Eq_3 & ebxOut, union Eq_3 & ebpOut, union Eq_3 & ediOut)
{
	struct Eq_107701 * ebp_11 = g_ptrA6EBE0;
	if (ebp_11 == null)
	{
		ebxOut = ebx;
		ebpOut = ebp;
		ediOut = edi;
		return 0x01;
	}
	else
	{
		Eq_3 ebp_33;
		Eq_3 ebx_34;
		Eq_3 edi_35;
		word32 ecx_73;
		word32 edx_74;
		word32 esi_75;
		void * eax_32 = fn007B24F7(ebp_11, null, edi, esi, ebp, ebx, dwArg04, out ecx_73, out edx_74, out ebx_34, out ebp_33, out esi_75, out edi_35);
		ebxOut = ebx_34;
		ebpOut = ebp_33;
		ediOut = edi_35;
		return (byte) eax_32;
	}
}

// 007B24F7: Register word32 fn007B24F7(Register (ptr32 Eq_107701) ebp, Register (ptr32 Eq_107701) edi, Stack Eq_3 dwArg00, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg1C, Register out Eq_3 ecxOut, Register out ptr32 edxOut, Register out Eq_3 ebxOut, Register out Eq_3 ebpOut, Register out Eq_3 esiOut, Register out Eq_3 ediOut)
// Called from:
//      fn007B2480
//      fn007B24E0
word32 fn007B24F7(struct Eq_107701 * ebp, struct Eq_107701 * edi, Eq_3 dwArg00, Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg1C, union Eq_3 & ecxOut, ptr32 & edxOut, union Eq_3 & ebxOut, union Eq_3 & ebpOut, union Eq_3 & esiOut, union Eq_3 & ediOut)
{
	struct Eq_177856 * esp_100 = fp;
	struct Eq_107701 * eax_6 = *((word32) dwArg1C + 4);
	word24 eax_24_8_177 = SLICE(eax_6, word24, 8);
	if (eax_6 != edi)
	{
		int32 ecx_11 = *((word32) dwArg1C + 8) - eax_6;
		ecx = ecx_11 >> 0x02;
		if (ecx_11 >> 0x02 != 0x00)
		{
			struct Eq_107701 * ebx_16 = ebp[1];
			if (ebx_16 != ebp[2])
			{
				do
				{
					ptr32 edx_82;
					uint32 edi_23 = 0x01;
					if (fn0040D910(dwArg1C, out edx) >= 0x01)
					{
						do
						{
							struct Eq_177928 ** ebx_34 = ebx_16->t0000;
							struct Eq_177900 * esp_36 = esp_100 - 4;
							esp_36->t0000 = dwArg1C;
							esp_36->ptr0018 = esp_36;
							word32 edx_265;
							Eq_3 ecx_52 = *((word32) *((word32) dwArg1C + 4) + (fn0040D910(dwArg1C, out edx_265) - edi_23) * 0x04);
							esp_36->t0000 = ecx_52;
							if (ecx_52 != 0x00)
								fn00401AD0(ecx_52);
							struct Eq_177928 * eax_63 = *ebx_34;
							eax_63->ptr0004();
							uint32 eax_81 = fn0040D910(dwArg1C, out edx_82);
							++edi_23;
							ebx_16 = (struct Eq_107701 *) esp_100[4];
						} while (edi_23 <= eax_81);
						ebp = g_ptrA6EBE0;
						edx = edx_82;
					}
					++ebx_16;
					esp_100[4] = (struct Eq_177856) ebx_16;
					ecx = dwArg1C;
				} while (ebx_16 != ebp[2]);
				edi = null;
			}
			struct Eq_107701 * eax_108 = ebp[1];
			word24 eax_24_8_180 = SLICE(eax_108, word24, 8);
			word32 * ebp_110 = ebp + 1;
			if (eax_108 != edi)
				operator delete(eax_108);
			*ebp_110 = edi;
			ebp[2] = (struct Eq_107701) edi;
			ebp[3] = (struct Eq_107701) edi;
			operator delete(ebp);
			g_ptrA6EBE0 = edi;
			ecxOut = ecx;
			edxOut = edx;
			ebxOut = dwLoc0C;
			ebpOut = dwLoc10;
			esiOut = dwLoc14;
			ediOut = dwLoc18;
			return SEQ(eax_24_8_180, 0x01);
		}
	}
	ecxOut = ecx;
	edxOut = edx;
	ebxOut = dwArg0C;
	ebpOut = dwArg08;
	esiOut = dwArg04;
	ediOut = dwArg00;
	return SEQ(eax_24_8_177, 0x00);
}

// 007B2800: Register ui32 fn007B2800(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00409AC0
//      fn004119C0
//      fn00411D40
//      fn00417890
//      fn0041DA20
//      fn006204B0
//      fn00620670
//      fn00622070
//      fn00622230
ui32 fn007B2800(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	int32 eax_8 = dwArg08 - dwArg04;
	Eq_25048 eax_11 = (eax_8 >> 0x02) * 0x04;
	word32 esi_15 = eax_11 + dwArg0C;
	if (eax_8 >> 0x02 != 0x00)
		memmove_s(dwArg0C, eax_11, dwArg04, eax_11);
	return esi_15;
}

// 007B2D10: Register byte fn007B2D10(Register Eq_3 ebp, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Register Eq_409 xmm0, Stack Eq_3 dwArg04, Register out Eq_3 ebpOut, Register out Eq_409 xmm0Out)
// Called from:
//      fn0042B310
byte fn007B2D10(Eq_3 ebp, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_409 xmm0, Eq_3 dwArg04, union Eq_3 & ebpOut, union Eq_409 & xmm0Out)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	word32 edx_551;
	fn00402A20(fp - 0x50, dwArg04, 0x00, out edx_551);
	if (dwLoc50 != 0x00)
	{
		word32 edx_552;
		word32 edi_553;
		Eq_3 ebx_102;
		Eq_3 ebp_153;
		struct Eq_51835 ** eax_67 = fn00401700(fn004048C0(0x00, ebp, dwArg04, edi, es, ds, out edx_552, out ebx_102, out ebp_153, out edi_553));
		<anonymous> * edx_72 = *((const char *) *eax_67 + 44);
		struct Eq_178048 * esp_162;
		edx_72();
		esp_162[0x0D] = (struct Eq_178048) 0x00;
		esp_162[0x0E] = (struct Eq_178048) ebx_102;
		esp_162[0x0F] = (struct Eq_178048) ebx_102;
		Eq_3 esi_100 = esp_162[9];
		esp_162[25] = (struct Eq_178048) 0x02;
		Eq_3 edi_213 = 0x00;
		if (esi_100 != esp_162[0x0A])
		{
			do
			{
				struct Eq_178108 * esp_95 = esp_162 - 4;
				esp_95->t0000.u0 = 0x008A6C20;
				basic_string(&esp_95->ptr0020 + 9, esp_95->t0000);
				Eq_3 eax_101 = *esi_100;
				esp_95->t0000.u0 = 0x01;
				esp_95->tFFFFFFFC = &esp_95->ptr0020 + 9;
				esp_95->b0068 = 0x03;
				esp_95->ptr0020 = esp_95 - 4;
				esp_95->tFFFFFFFC = eax_101;
				if (eax_101 != ebx_102)
					*((word32) eax_101 + 4) = (word32) *((word32) eax_101 + 4) + 1;
				esp_95->ptrFFFFFFF8 = (basic_string *) (&esp_95->ptr0020 + 9);
				esp_95->ptrFFFFFFF4 = &esp_95->t0018;
				fn004100F0(es, ds, esp_95->ptrFFFFFFF4, esp_95->ptrFFFFFFF8, esp_95->tFFFFFFFC, esp_95->t0000);
				esp_95->b0068 = 0x05;
				~basic_string(&esp_95->ptr0020 + 9);
				esp_95->t0000 = &esp_95->t0018;
				ebx_102 = fn00414E50(&esp_95->ptr0020 + 5, esp_95->t0000, out ebp_153);
				Eq_3 ecx_163 = esp_95->t0018;
				esp_95->b0068 = 0x02;
				esp_162 = (struct Eq_178048 *) ((const char *) &esp_95->t0000 + 4);
				if (ecx_163 != ebx_102 && (fn00401AE0(ecx_163) == 0x01 && ecx_163 != ebx_102))
				{
					esp_95->t0000.u0 = 0x01;
					Eq_3 esp_192 = <invalid>;
					ebx_102 = fn0042DF20(ecx_163, es, ds, xmm0, esp_95->t0000, out ebp_153, out esi_100, out xmm0);
					esp_162 = (word32) esp_192 + 4;
				}
				esp_162[5] = (struct Eq_178048) ebx_102;
				esi_100 = (word32) esi_100 + 4;
			} while (esi_100 != esp_162[0x0A]);
			edi_213 = esp_162[0x0D];
		}
		struct Eq_178076 * esp_216 = esp_162 - 4;
		esp_216->t0000 = esp_162 + 0x0C;
		Eq_3 ebx_225;
		Eq_3 edi_227;
		Eq_3 ebp_224;
		esp_216->b0017 = (byte) (uint32) fn007B24E0(ebx_102, ebp_153, esi_100, edi_213, esp_216->t0000, out ebx_225, out ebp_224, out edi_227);
		esp_216->b0068 = 0x01;
		byte bl_268 = (byte) ebx_225;
		if (edi_227 != ebx_225)
		{
			Eq_3 eax_241 = esp_216->t003C;
			esp_216->t0000 = esp_216->t0020;
			esp_216->ptrFFFFFFFC = (const char *) &esp_216->t0020 + 20;
			esp_216->tFFFFFFF8 = eax_241;
			esp_216->tFFFFFFF4 = edi_227;
			fn0044F600(esp_216->tFFFFFFF4, esp_216->tFFFFFFF8);
			esp_216->tFFFFFFF0 = edi_227;
			operator delete(esp_216->tFFFFFFF0);
		}
		Eq_3 eax_265 = esp_162[9];
		esp_162[25] = (struct Eq_178048) bl_268;
		if (eax_265 != ebx_225)
		{
			struct Eq_178312 * esp_272 = esp_162 - 4;
			esp_272->dw0000 = (word32) esp_162[7];
			Eq_3 ecx_274 = esp_272->t002C;
			esp_272->ptrFFFFFFFC = &esp_272->dw0000 + 9;
			esp_272->tFFFFFFF8 = ecx_274;
			esp_272->tFFFFFFF4 = eax_265;
			fn00409C80(esp_272->tFFFFFFF4, esp_272->tFFFFFFF8);
			esp_272->ptrFFFFFFF0 = esp_272->ptr0028;
			operator delete(esp_272->ptrFFFFFFF0);
		}
		Eq_3 ecx_296 = esp_162[6];
		esp_162[9] = (struct Eq_178048) ebx_225;
		esp_162[0x0A] = (struct Eq_178048) ebx_225;
		esp_162[11] = (struct Eq_178048) ebx_225;
		esp_162[25] = (struct Eq_178048) ~0x00;
		if (ecx_296 != ebx_225)
		{
			Eq_3 eax_305 = fn00401AE0(ecx_296);
			if (eax_305 == 0x01 && ecx_296 != ebx_225)
			{
				union Eq_3 * esp_316 = esp_162 - 4;
				*esp_316 = (union Eq_3 *) 0x01;
				word32 esi_554;
				fn0042DF20(ecx_296, es, ds, xmm0, *esp_316, out ebp_224, out esi_554, out xmm0);
			}
		}
		fs->ptr0000 = eax_9;
		ebpOut = ebp_224;
		xmm0Out = xmm0;
		return bLoc55;
	}
	else
	{
		fs->ptr0000 = eax_9;
		ebpOut = ebp;
		xmm0Out = xmm0;
		return 0x00;
	}
}

