// sho_rdata_0003.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

Eq_3 g_t8D41A4 = // 008D41A4
	{
		7598817671477616479
	};
byte g_b8D46D8 = 114; // 008D46D8
byte g_b8D54C0 = 0x2E; // 008D54C0
byte g_b8D57DC = 111; // 008D57DC
Eq_74961 g_t8D57E0 = // 008D57E0
	{
		0x5F
	};
word32 g_dw8D57E4 = 1600091241; // 008D57E4
word32 g_dw8D57E8 = 0x0079702E; // 008D57E8
byte g_b8D6850 = 0x25; // 008D6850
real64 g_r8D6C28 = 16777216.0; // 008D6C28
real64 g_r8D6C30 = 268435456.0; // 008D6C30
real64 g_r8D6C80 = 3.725290298461914e-09; // 008D6C80
real64 g_r8D6C88 = 5.960464477539063e-08; // 008D6C88
Eq_92476 g_t8D7718 = // 008D7718
	{
		0x6C632023,
		&g_t756E6165,
	};
Eq_115859 g_t8D9474 = // 008D9474
	{
		1696616028,
		&g_t70616373,
	};
byte g_b8D9620 = 0x78; // 008D9620
Eq_3 g_t8D9650 = // 008D9650
	{
		0x6969637361
	};
Eq_3 g_t8D9674 = // 008D9674
	{
		13842226097709420
	};
Eq_3 g_t8D9878 = // 008D9878
	{
		0x7363626D
	};
Eq_3 g_t8D9880 = // 008D9880
	{
		241279857781
	};
Eq_119826 g_t8D9B3C = // 008D9B3C
	{
		0x50,
	};
byte g_b8D9B44 = 77; // 008D9B44
byte g_b8D9B80 = 0x70; // 008D9B80
byte g_b8D9BA4 = 0x44; // 008D9BA4
byte g_b8D9BC8 = 0x69; // 008D9BC8
byte g_b8DA664 = 0x5F; // 008DA664
byte g_b8DA698 = 117; // 008DA698
byte g_b8DA718 = 0x5F; // 008DA718
Eq_53824 g_t8DA8A0 = // 008DA8A0
	{
		6563118,
		&g_t6D616C3C,
	};
Eq_132398 g_t8DA8B0 = // 008DA8B0
	{
		0x6D6F7266,
		&g_t665F5F20,
	};
byte g_b8DA8F0 = 0x5F; // 008DA8F0
byte g_b8DAD60 = 0x20; // 008DAD60
byte g_b8DB7E0 = 0x30; // 008DB7E0
byte g_b8DBB70 = 0x69; // 008DBB70
byte g_b8DBB78 = 0x61; // 008DBB78
const char g_str8DBB90[] = "with"; // 008DBB90
byte g_b8DBBCC = 0x69; // 008DBBCC
const char g_str8DBBE0[] = "as"; // 008DBBE0
byte g_b8DBBE4 = 0x66; // 008DBBE4
byte g_b8DBBEC = 0x69; // 008DBBEC
byte g_b8DC148 = 0x69; // 008DC148
byte g_b8DC828 = 99; // 008DC828
Eq_153506 g_t8DCA8C = // 008DCA8C
	{
		0x2D667475,
		&g_t622D3631,
	};
Eq_153482 g_t8DCA98 = // 008DCA98
	{
		117
	};
word16 g_w8DCA9C = 99; // 008DCA9C
byte g_b8DCAA0 = 0x69; // 008DCAA0
byte g_b8DCF50 = 0x67; // 008DCF50
byte g_b8DDB00 = 0x66; // 008DDB00
byte g_b8DDB50 = 117; // 008DDB50
byte g_b8DDB8C = 0x69; // 008DDB8C
byte g_b8DDCC8 = 110; // 008DDCC8
byte g_b8DDCFC = 110; // 008DDCFC
const char g_str8DEA38[] = "'l%"; // 008DEA38
byte g_b8DF8F4 = 0x62; // 008DF8F4
byte g_b8DF8FC = 0x77; // 008DF8FC
byte g_b8DF90C = 0x61; // 008DF90C
byte g_b8DF91C = 100; // 008DF91C
byte g_b8DF928 = 110; // 008DF928
Eq_171661 g_t8DFB8C = // 008DFB8C
	{
		
		{
			0x69
		},
	};
