// sho_text_0012.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 00529B70: void fn00529B70(Register (ptr32 ui32) ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn004100F0
//      fn00418D40
//      fn007B22E0
void fn00529B70(ui32 * ecx, Eq_3 dwArg04)
{
	struct Eq_34537 * eax_6 = *dwArg04;
	struct Eq_34537 * ecx_12 = *ecx;
	if (ecx_12 != eax_6)
	{
		*ecx = eax_6;
		if (eax_6 != null)
			++eax_6->dw0004;
		if (ecx_12 != null)
		{
			word32 v11_27 = ecx_12->dw0004 + ~0x00;
			ecx_12->dw0004 = v11_27;
			if (v11_27 == 0x00)
			{
				<anonymous> ** edx_31 = ecx_12->ptr0000;
				(*edx_31)();
			}
		}
	}
}

