// sho_text_0019.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 0059EB70: Register Eq_3 fn0059EB70(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Register out Eq_34668 edxOut)
// Called from:
//      fn005A5370
//      fn005A5680
Eq_3 fn0059EB70(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, union Eq_34668 & edxOut)
{
	Eq_34668 edx_27;
	Eq_3 eax_25 = fn005F9240(dwArg04, dwArg08, dwArg0C, out edx_27);
	edxOut = edx_27;
	return eax_25;
}

