// sho_text_0013.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 00540F70: void fn00540F70(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00411F00
void fn00540F70(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 eax_19 = dwArg04;
	if (dwArg04 != dwArg08)
	{
		do
		{
			Eq_3 edi_20 = eax_19;
			eax_19 = (word32) eax_19 + 64;
			word32 ecx_24;
			Eq_3 esi_26 = dwArg0C;
			for (ecx_24 = 0x10; ecx_24 != 0x00; --ecx_24)
			{
				*edi_20 = *esi_26;
				esi_26 = (word32) esi_26 + 4;
				edi_20 = (word32) edi_20 + 4;
			}
		} while (eax_19 != dwArg08);
	}
}

