// sho_text_0022.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 00621250: void fn00621250(Register (ptr32 Eq_29988) ecx)
// Called from:
//      fn0042ACF0
void fn00621250(struct Eq_29988 * ecx)
{
	__align(fp - 4);
	int32 ebp_19 = 0x00;
	if (ecx->dw002C > 0x00)
	{
		real64 rLoc1_116 = (real64) g_r8C64BC;
		word32 edi_27 = 0x00;
		real64 rLoc2_117 = (real64) g_r8B2050;
		word32 edx_30 = 0x00;
		struct Eq_45940 * ecx_33 = &ecx->dw002C + 0x0044;
		do
		{
			ui32 eax_38 = ecx->dw0028 + edx_30;
			ui32 eax_40 = ecx->a0148[eax_38].dw0004;
			++ecx_33;
			ecx_33->rFFFFFCF0 = (real32) (((real64) SEQ(eax_40 & 0x7FFFFFFF, ecx->a0148[eax_38].dw0000) + -((real64) SEQ(eax_40 & 0x80000000, 0x00))) / ecx->r0008 * rLoc2_117 + (real64) ecx_33->rFFFFFCF0 * rLoc1_116);
			ecx_33->dwFFFFFCF4 = ecx->a0348[ecx->dw0028 + edi_27];
			++ebp_19;
			edx_30 += 0x62;
			edi_27 += 0xC4;
		} while (ebp_19 < ecx->dw002C);
	}
	++ecx->dw0028;
	if (ecx->dw0028 == 0x40)
	{
		fn00620FC0(ecx);
		ecx->dw0028 = 0x00;
	}
}

// 00621380: Register word32 fn00621380(Register Eq_3 ecx)
// Called from:
//      fn0041F120
word32 fn00621380(Eq_3 ecx)
{
	*ecx = GetCurrentThreadId();
	*((word32) ecx + 8) = fn00626B50() * g_r8A8950;
	Eq_23784 edx_eax_32 = __rdtsc();
	*((word32) ecx + 24) = (word32) edx_eax_32;
	*((word32) ecx + 28) = SLICE(edx_eax_32, word32, 32);
	*((word32) ecx + 32) = 0x00;
	*((word32) ecx + 36) = 0x00;
	*((word32) ecx + 40) = 0x00;
	*((word32) ecx + 44) = 0x01;
	((word32) ecx + 48)->u0 = 0x00;
	*((word32) ecx + 308) = 0x00;
	memset((word32) ecx + 312, 0x00, 0x00031000);
	*((word32) ecx + 312) = 9200852;
	fn00422A90(fp - 0x04);
	if (ecx != 0x00)
	{
		Eq_3 v16_74 = (word32) *((word32) ecx + 4) - 1;
		*((word32) ecx + 4) = v16_74;
		if (v16_74 == 0x00)
		{
			Eq_3 edx_78 = *ecx;
			(*edx_78)();
		}
	}
	g_tA67C00 = ecx;
	word32 ebp_98;
	word32 edi_147;
	word32 esi_146;
	fn00694C8C(0x00, ecx, (word32) ecx + 312, out ebp_98, out esi_146, out edi_147);
	return ebp_98;
}

// 00621430: Register word32 fn00621430(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10, Register out ptr32 edxOut)
// Called from:
//      fn00622B40
word32 fn00621430(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10, ptr32 & edxOut)
{
	fs->ptr0000 = fp - 0x0C;
	basic_string(fp - 0x50, "vector<T> too long");
	fn004019E0(fp - 0x34, fp - 0x50);
	CxxThrowException();
	int3();
	ptr32 edx_51;
	word32 ecx_74;
	word32 eax_49 = fn00621490(dwArg04, dwArg08, dwArg0C, dwArg10, out ecx_74, out edx_51);
	edxOut = edx_51;
	return eax_49;
}

// 00621490: Register word32 fn00621490(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10, Register out Eq_3 ecxOut, Register out ptr32 edxOut)
// Called from:
//      fn00621430
//      fn00622070
word32 fn00621490(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10, union Eq_3 & ecxOut, ptr32 & edxOut)
{
	fs->ptr0000 = fp - 0x0C;
	basic_string(fp - 0x50, "vector<T> too long");
	fn004019E0(fp - 0x34, fp - 0x50);
	struct Eq_46178 * esp_44;
	CxxThrowException();
	int3();
	esp_44->dwFFFFFFFC = ~0x00;
	esp_44->dwFFFFFFF8 = 8819449;
	esp_44->ptrFFFFFFF4 = fs->ptr0000;
	esp_44->dwFFFFFFAC = g_tA14188 ^ esp_44 - 0x50;
	fs->ptr0000 = esp_44 - 0x0C;
	esp_44->ptrFFFFFFA8 = (basic_string *) g_str8A6998;
	basic_string(esp_44 - 0x50, esp_44->ptrFFFFFFA8);
	esp_44->ptrFFFFFFA8 = esp_44 - 0x50;
	esp_44->dwFFFFFFFC = 0x00;
	fn004019E0(esp_44 - 0x34, esp_44->ptrFFFFFFA8);
	esp_44->ptrFFFFFFA8 = &g_t999C68;
	esp_44->ptrFFFFFFA4 = esp_44 - 0x34;
	esp_44->dwFFFFFFCC = 0x00990030;
	ptr32 edx_92;
	CxxThrowException();
	int3();
	if (dwArg08 >= dwArg10)
	{
		ptr32 edx_99;
		Eq_3 ecx_100;
		word32 eax_98 = fn00621563(dwArg10, dwArg04, dwArg0C, out ecx_100, out edx_99);
		ecxOut = ecx_100;
		edxOut = edx_99;
		return eax_98;
	}
	else
	{
		_invalid_parameter_noinfo();
		ecxOut = dwArg10;
		edxOut = edx_92;
		return 0x00;
	}
}

// 006214F0: void fn006214F0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10)
// Called from:
//      fn00621680
void fn006214F0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10)
{
	fs->ptr0000 = fp - 0x0C;
	basic_string(fp - 0x50, "vector<T> too long");
	fn004019E0(fp - 0x34, fp - 0x50);
	CxxThrowException();
	int3();
	if (dwArg08 >= dwArg10)
	{
		word32 ecx_91;
		word32 edx_92;
		fn00621563(dwArg10, dwArg04, dwArg0C, out ecx_91, out edx_92);
	}
	else
		_invalid_parameter_noinfo();
}

// 00621550: void fn00621550(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10)
// Called from:
//      fn00621800
void fn00621550(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10)
{
	if (dwArg08 >= dwArg10)
	{
		word32 edx_36;
		word32 ecx_35;
		fn00621563(dwArg10, dwArg04, dwArg0C, out ecx_35, out edx_36);
	}
	else
		_invalid_parameter_noinfo();
}

// 00621563: Register Eq_3 fn00621563(Register Eq_3 ecx, Stack Eq_3 dwArg04, Stack Eq_3 dwArg0C, Register out Eq_3 ecxOut, Register out Eq_3 edxOut)
// Called from:
//      fn00621490
//      fn006214F0
//      fn00621550
Eq_3 fn00621563(Eq_3 ecx, Eq_3 dwArg04, Eq_3 dwArg0C, union Eq_3 & ecxOut, union Eq_3 & edxOut)
{
	Eq_3 edx_102 = dwArg0C;
	Eq_3 esi_14 = dwArg04;
	if (dwArg0C < dwArg04)
	{
		Eq_3 edi_17 = (word32) dwArg0C + ecx * 0x04;
		if (dwArg04 < edi_17)
		{
			word32 * esi_43 = (word32) dwArg04 + ecx * 0x04;
			edx_102 = edi_17;
			if (ecx > 0x00)
			{
				do
				{
					esi_43 -= 0x04;
					*esi_43 = (word32) *((word32) edx_102 - 4);
					edx_102 -= 0x04;
					--ecx;
				} while (ecx != 0x00);
				ecxOut = ecx;
				edxOut = edx_102;
				return <invalid>;
			}
			goto l006215B1;
		}
	}
	for (; ecx > 0x00; --ecx)
	{
		*esi_14 = *edx_102;
		esi_14 = (word32) esi_14 + 4;
		edx_102 = (word32) edx_102 + 4;
	}
l006215B1:
	ecxOut = ecx;
	edxOut = edx_102;
	return <invalid>;
}

// 00621620: Register word32 fn00621620(Register Eq_3 ecx, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00622470
word32 fn00621620(Eq_3 ecx, Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ecx_30 = dwArg08;
	if (dwArg08 != 0x01)
	{
		Eq_3 eax_12;
		if (*((word32) ecx + 24) >= 0x04)
			eax_12 = *((word32) ecx + 4);
		else
			eax_12 = (word32) ecx + 4;
		word32 edi_26 = eax_12 + dwArg04 * 0x04;
		if (dwArg08 > 0x00)
		{
			for (; ecx_30 != 0x00; --ecx_30)
			{
				*edi_26 = dwArg0C;
				edi_26 += 4;
			}
		}
		return;
	}
	else if (*((word32) ecx + 24) < 0x04)
	{
		*((word32) ecx + (dwArg04 * 0x04 + 4)) = dwArg0C;
		return;
	}
	else
	{
		*((word32) *((word32) ecx + 4) + dwArg04 * 0x04) = dwArg0C;
		return;
	}
}

// 00621680: Register byte fn00621680(Register Eq_3 ecx, Register Eq_3 esi, Register Eq_3 edi, Stack Eq_3 dwArg00, Stack Eq_3 dwArg04)
// Called from:
//      fn00623840
byte fn00621680(Eq_3 ecx, Eq_3 esi, Eq_3 edi, Eq_3 dwArg00, Eq_3 dwArg04)
{
	((word32) ecx + 4)->u0 = 0x00;
	((word32) ecx + 8)->u0 = 0x00;
	*((word32) ecx + 0x0C) = null;
	if (dwArg04 == 0x00)
		return 0x00;
	if (dwArg04 > 0x09249249)
		fn006214F0(edi, esi, dwArg00, dwArg04);
	word32 ecx_96;
	word32 edx_97;
	Eq_3 eax_36 = fn0040DDE0(dwArg04, out ecx_96, out edx_97);
	*((word32) ecx + 4) = eax_36;
	*((word32) ecx + 8) = eax_36;
	*((word32) ecx + 0x0C) = (word32) eax_36 + (dwArg04 * 0x08 - dwArg04) * 0x04;
	return 0x01;
}

// 006216E0: void fn006216E0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00622230
void fn006216E0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ecx_13 = dwArg04;
	Eq_3 eax_16 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			*eax_16 = *ecx_13;
			ecx_13 = (word32) ecx_13 + 4;
			eax_16 = (word32) eax_16 + 4;
		} while (ecx_13 != dwArg08);
	}
}

// 00621710: Register Eq_3 fn00621710(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00622230
//      fn007FB450
Eq_3 fn00621710(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ecx_17 = dwArg04;
	Eq_3 eax_13 = dwArg0C;
	if (dwArg04 != dwArg08)
	{
		do
		{
			if (eax_13 != 0x00)
				*eax_13 = *ecx_17;
			ecx_17 = (word32) ecx_17 + 4;
			eax_13 = (word32) eax_13 + 4;
		} while (ecx_17 != dwArg08);
	}
	return eax_13;
}

// 00621740: Register (ptr32 word32) fn00621740(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Register out (ptr32 word32) edxOut)
// Called from:
//      fn006228B0
word32 * fn00621740(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, word32 & edxOut)
{
	int32 ecx_19 = dwArg0C - dwArg04;
	int32 ebx_18 = dwArg08 - dwArg04;
	word32 * eax_119 = ecx_19 >> 0x02;
	word32 * esi_25 = ebx_18 >> 0x02;
	if (ebx_18 >> 0x02 != 0x00)
	{
		do
		{
			edx = (int32) ((int64) eax_119 % esi_25);
			eax_119 = esi_25;
			esi_25 = edx;
		} while (edx != null);
	}
	if (eax_119 < ecx_19 >> 0x02 && eax_119 > null)
	{
		int32 ebp_56 = (ebx_18 >> 0x02) * 0x04;
		word32 * esi_124 = (word32) dwArg04 + eax_119 * 0x04;
		do
		{
			word32 ** ecx_71;
			word32 ecx_62 = *esi_124;
			word32 * edi_127 = esi_124;
			if (esi_124 + ebp_56 == dwArg0C)
				ecx_71 = fp + 0x04;
			else
				ecx_71 = fp + 0x08;
			edx = *ecx_71;
			while (edx != esi_124)
			{
				word32 ** ecx_104;
				*edi_127 = *edx;
				edi_127 = edx;
				if (ebx_18 >> 0x02 < dwArg0C - edx >> 0x02)
					ecx_104 = fp - 0x0C;
				else
					ecx_104 = fp - 0x08;
				edx = *ecx_104;
			}
			*edi_127 = ecx_62;
			--eax_119;
			esi_124 -= 0x04;
		} while (eax_119 > null);
	}
	edxOut = edx;
	return eax_119;
}

// 00621800: void fn00621800(Register Eq_3 ecx, Register Eq_3 edi, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08)
// Called from:
//      fn00621C70
//      fn00623A00
void fn00621800(Eq_3 ecx, Eq_3 edi, Eq_3 dwArg04, Eq_3 dwArg08)
{
	if (*((word32) ecx + 20) < dwArg04)
		_Xran(edi);
	Eq_3 edi_22 = dwArg08;
	Eq_3 eax_24 = *((word32) ecx + 20) - dwArg04;
	if (eax_24 < dwArg08)
		edi_22 = eax_24;
	if (edi_22 > 0x00)
	{
		Eq_3 dwArg04_125;
		Eq_3 ecx_35 = *((word32) ecx + 24);
		Eq_3 ebp_100 = (word32) ecx + 4;
		if (ecx_35 >= 0x04)
			dwArg04_125 = *((word32) ecx + 4);
		else
			dwArg04_125 = (word32) ecx + 4;
		Eq_3 dwArg08_127;
		if (ecx_35 >= 0x04)
			dwArg08_127 = *((word32) ecx + 4);
		else
			dwArg08_127 = (word32) ecx + 4;
		fn00621550((word32) dwArg08_127 + dwArg04 * 0x04, ecx_35 - dwArg04, dwArg04_125 + (dwArg04 + edi_22) * 0x04, eax_24 - edi_22);
		Eq_3 eax_94 = *((word32) ecx + 20) - edi_22;
		*((word32) ecx + 20) = eax_94;
		if (*((word32) ecx + 24) >= 0x04)
			ebp_100 = *((word32) ecx + 4);
		*((word32) ebp_100 + eax_94 * 0x04) = 0x00;
	}
}

// 006218A0: Register Eq_3 fn006218A0(Register Eq_3 ecx, Register Eq_3 ebx, Stack Eq_3 dwArg04, Register out ptr32 ebpOut)
// Called from:
//      fn00621C70
//      fn00622470
Eq_3 fn006218A0(Eq_3 ecx, Eq_3 ebx, Eq_3 dwArg04, ptr32 & ebpOut)
{
	fs->ptr0000 = fp - 0x10;
	Eq_3 esi_38 = dwArg04 | 0x03;
	if ((dwArg04 | 0x03) > 0x3FFFFFFE)
		esi_38 = dwArg04;
	else
	{
		ebx = *((word32) ecx + 24);
		if (SLICE((dwArg04 | 0x03) *64 ~0x55555554, word32, 32) >> 0x01 < ebx >> 0x01 && ebx <= 0x3FFFFFFE - (ebx >> 0x01))
			esi_38 = (word32) ebx + (ebx >> 0x01);
	}
	word32 ecx_227;
	struct Eq_46687 * ebp_70;
	struct Eq_46688 * edi_72;
	up32 esi_73;
	word32 ebx_228;
	Eq_3 edx_102;
	ebp_70->t0008 = fn007B2480(ebx, fp - 4, esi_38, ecx, (word32) esi_38 + 1, out ecx_227, out edx_102, out ebx_228, out ebp_70, out esi_73, out edi_72);
	uint32 ebx_113 = ebp_70->dw000C;
	if (ebx_113 > 0x00)
	{
		Eq_3 ecx_107;
		if (edi_72->dw0018 >= 0x04)
			ecx_107 = edi_72->t0004;
		else
			ecx_107 = &edi_72->t0004;
		edx_102 = esi_73 + 0x01;
		uint32 eax_104 = ebx_113;
		if (esi_73 + 0x01 < ebx_113)
			_invalid_parameter_noinfo();
		else
		{
			edx_102 = ebp_70->t0008;
			do
			{
				*edx_102 = *ecx_107;
				--eax_104;
				edx_102 = (word32) edx_102 + 4;
				ecx_107 = (word32) ecx_107 + 4;
			} while (eax_104 > 0x00);
			ebx_113 = ebp_70->dw000C;
		}
	}
	if (edi_72->dw0018 >= 0x04)
		operator delete(edi_72->t0004);
	Eq_3 ecx_135 = ebp_70->t0008;
	edi_72->t0004.u0 = 0x00;
	edi_72->t0004 = ecx_135;
	edi_72->dw0018 = esi_73;
	edi_72->dw0014 = ebx_113;
	Eq_3 eax_137 = &edi_72->t0004;
	if (esi_73 >= 0x04)
		eax_137 = ecx_135;
	*((word32) eax_137 + ebx_113 * 0x04) = 0x00;
	fs->ptr0000 = ebp_70->ptrFFFFFFF4;
	ebpOut = ebp_70->ptr0000;
	return edx_102;
}

// 00621A00: void fn00621A00(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10)
// Called from:
//      fn00621D60
void fn00621A00(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10)
{
	Eq_3 eax_8 = *((word32) dwArg10 + 20);
	struct Eq_46809 * ecx_23 = *((word32) eax_8 + *dwArg04 * 0x08);
	struct Eq_46809 * eax_24 = *((word32) eax_8 + *dwArg08 * 0x08);
	do
	{
		int32 eax_43;
		cu8 dl_27 = eax_24->b0000;
		if (dl_27 != ecx_23->b0000)
		{
l00621A40:
			up32 eax_40 = 0x00 - (dl_27 < ecx_23->b0000);
			eax_43 = eax_40 - ~0x00 - (eax_40 < 0x00);
			goto l00621A45;
		}
		if (dl_27 == 0x00)
			break;
		byte dl_34 = eax_24->b0001;
		if (dl_34 != ecx_23->b0001)
			goto l00621A40;
		++eax_24;
		++ecx_23;
	} while (dl_34 != 0x00);
	eax_43 = 0x00;
l00621A45:
	if (eax_43 < 0x00)
	{
		ui32 eax_69 = *dwArg08;
		*dwArg08 = *dwArg04;
		*dwArg04 = eax_69;
	}
	Eq_3 eax_78 = *((word32) dwArg10 + 20);
	struct Eq_46867 * ecx_112 = *((word32) eax_78 + *dwArg08 * 0x08);
	struct Eq_46867 * eax_111 = *((word32) eax_78 + *dwArg0C * 0x08);
	do
	{
		int32 eax_109;
		cu8 dl_93 = eax_111->b0000;
		if (dl_93 != ecx_112->b0000)
		{
l00621A86:
			up32 eax_106 = 0x00 - (dl_93 < ecx_112->b0000);
			eax_109 = eax_106 - ~0x00 - (eax_106 < 0x00);
			goto l00621A8B;
		}
		if (dl_93 == 0x00)
			break;
		byte dl_100 = eax_111->b0001;
		if (dl_100 != ecx_112->b0001)
			goto l00621A86;
		++eax_111;
		++ecx_112;
	} while (dl_100 != 0x00);
	eax_109 = 0x00;
l00621A8B:
	if (eax_109 < 0x00)
	{
		ui32 eax_135 = *dwArg0C;
		*dwArg0C = *dwArg08;
		*dwArg08 = eax_135;
	}
	Eq_3 eax_144 = *((word32) dwArg10 + 20);
	struct Eq_46809 * ecx_155 = *((word32) eax_144 + *dwArg04 * 0x08);
	struct Eq_46809 * eax_156 = *((word32) eax_144 + *dwArg08 * 0x08);
	do
	{
		int32 eax_175;
		cu8 dl_159 = eax_156->b0000;
		if (dl_159 != ecx_155->b0000)
		{
l00621AC7:
			up32 eax_172 = 0x00 - (dl_159 < ecx_155->b0000);
			eax_175 = eax_172 - ~0x00 - (eax_172 < 0x00);
			goto l00621ACC;
		}
		if (dl_159 == 0x00)
			break;
		byte dl_166 = eax_156->b0001;
		if (dl_166 != ecx_155->b0001)
			goto l00621AC7;
		++eax_156;
		++ecx_155;
	} while (dl_166 != 0x00);
	eax_175 = 0x00;
l00621ACC:
	if (eax_175 < 0x00)
	{
		ui32 eax_201 = *dwArg08;
		*dwArg08 = *dwArg04;
		*dwArg04 = eax_201;
	}
}

// 00621AE0: Register Eq_47018 fn00621AE0(Stack Eq_3 dwArg04, Stack int32 dwArg08, Stack int32 dwArg0C, Stack Eq_47018 dwArg10, Stack Eq_3 dwArg14)
// Called from:
//      fn00621E10
Eq_47018 fn00621AE0(Eq_3 dwArg04, int32 dwArg08, int32 dwArg0C, Eq_47018 dwArg10, Eq_3 dwArg14)
{
	int64 edx_eax_9 = (int64) (dwArg08 - 0x01);
	int32 ebp_112 = dwArg08;
	int32 eax_13 = (word32) edx_eax_9 - SLICE(edx_eax_9, word32, 32) >> 0x01;
	if (dwArg0C < dwArg08)
	{
		do
		{
			Eq_3 ecx_30 = *((word32) dwArg14 + 20);
			struct Eq_47042 * edx_36 = *((word32) ecx_30 + dwArg10 * 0x08);
			struct Eq_47042 * ecx_37 = *((word32) ecx_30 + *((word32) dwArg04 + eax_204 * 0x04) * 0x08);
			do
			{
				int32 ecx_56;
				cu8 bl_40 = ecx_37->b0000;
				if (bl_40 != edx_36->b0000)
				{
l00621B36:
					up32 ecx_53 = 0x00 - (bl_40 < edx_36->b0000);
					ecx_56 = ecx_53 - ~0x00 - (ecx_53 < 0x00);
					goto l00621B3B;
				}
				if (bl_40 == 0x00)
					break;
				byte bl_47 = ecx_37->b0001;
				if (bl_47 != edx_36->b0001)
					goto l00621B36;
				++ecx_37;
				++edx_36;
			} while (bl_47 != 0x00);
			ecx_56 = 0x00;
l00621B3B:
			if (ecx_56 >= 0x00)
				break;
			*((word32) dwArg04 + ebp_112 * 0x04) = *((word32) dwArg04 + eax_204 * 0x04);
			int64 edx_eax_90 = (int64) (eax_204 + ~0x00);
			ebp_112 = eax_204;
			eax_13 = (word32) edx_eax_90 - SLICE(edx_eax_90, word32, 32) >> 0x01;
			eax_204 = eax_13;
		} while (dwArg0C < eax_204);
	}
	*((word32) dwArg04 + ebp_112 * 0x04) = dwArg10;
	return dwArg10;
}

// 00621C70: void fn00621C70(Register Eq_3 ecx, Register Eq_3 edi, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00623280
void fn00621C70(Eq_3 ecx, Eq_3 edi, Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ebp_11 = dwArg08;
	if (*((word32) dwArg04 + 20) < dwArg08)
		_Xran(edi);
	Eq_3 edi_28 = *((word32) dwArg04 + 20) - dwArg08;
	if (dwArg0C < edi_28)
		edi_28 = dwArg0C;
	if (ecx != dwArg04)
	{
		if (edi_28 > 0x3FFFFFFE)
			_Xlen(edi);
		bool v19_212;
		Eq_3 eax_44 = *((word32) ecx + 24);
		if (eax_44 < edi_28)
		{
			fn006218A0(ecx, dwArg04, edi_28, out ebp_11);
			v19_212 = edi_28 <= 0x00;
		}
		else
		{
			v19_212 = edi_28 <= 0x00;
			if (edi_28 == 0x00)
			{
				*((word32) ecx + 20) = edi_28;
				if (eax_44 < 0x04)
				{
					((word32) ecx + 4)->u0 = 0x00;
					return;
				}
				else
				{
					**((word32) ecx + 4) = edi_28;
					return;
				}
			}
		}
		if (!v19_212)
		{
			Eq_3 edx_109;
			if (*((word32) dwArg04 + 24) >= 0x04)
				edx_109 = *((word32) dwArg04 + 4);
			else
				edx_109 = (word32) dwArg04 + 4;
			Eq_3 eax_118;
			Eq_3 ecx_114 = *((word32) ecx + 24);
			Eq_3 ebx_116 = (word32) ecx + 4;
			if (ecx_114 >= 0x04)
				eax_118 = *((word32) ecx + 4);
			else
				eax_118 = (word32) ecx + 4;
			fn004AB550(eax_118, ecx_114, (word32) edx_109 + ebp_11 * 0x04, edi_28);
			*((word32) ecx + 20) = edi_28;
			if (*((word32) ecx + 24) >= 0x04)
				ebx_116 = *((word32) ecx + 4);
			*((word32) ebx_116 + edi_28 * 0x04) = 0x00;
		}
	}
	else
	{
		word32 edi_177 = edi_28 + dwArg08;
		fn00621800(ecx, edi_177, edi_177, ~0x00);
		fn00621800(ecx, edi_177, 0x00, dwArg08);
	}
}

// 00621D60: void fn00621D60(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10)
// Called from:
//      fn00622530
void fn00621D60(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10)
{
	int32 eax_13 = dwArg0C - dwArg04;
	if (eax_13 >> 0x02 <= 0x28)
		fn00621A00(dwArg04, dwArg08, dwArg0C, dwArg10);
	else
	{
		int64 edx_eax_41 = (int64) ((eax_13 >> 0x02) + 0x01);
		int32 eax_48 = (word32) edx_eax_41 + (SLICE(edx_eax_41, word32, 32) & 0x07);
		ui32 esi_63 = (eax_48 >> 0x03) * 0x04;
		ui32 edx_57 = (eax_48 >> 0x03) * 0x08;
		Eq_3 eax_64 = (word32) dwArg04 + esi_63;
		fn00621A00(dwArg04, eax_64, (word32) dwArg04 + edx_57, dwArg10);
		fn00621A00(dwArg08 - esi_63, dwArg08, (word32) dwArg08 + esi_63, dwArg10);
		Eq_3 ebp_106 = dwArg0C - esi_63;
		fn00621A00(dwArg0C - edx_57, ebp_106, dwArg0C, dwArg10);
		fn00621A00(eax_64, dwArg08, ebp_106, dwArg10);
	}
}

// 00621E10: Register word32 fn00621E10(Stack Eq_3 dwArg04, Stack int32 dwArg08, Stack int32 dwArg0C, Stack Eq_47018 dwArg10, Stack Eq_3 dwArg14)
// Called from:
//      fn00622A00
//      fn00622EF0
word32 fn00621E10(Eq_3 dwArg04, int32 dwArg08, int32 dwArg0C, Eq_47018 dwArg10, Eq_3 dwArg14)
{
	int32 esi_15 = dwArg08 + 0x02 + dwArg08;
	int32 ebx_108 = dwArg08;
	bool v19_151 = esi_15 != dwArg0C;
	while (esi_15 < dwArg0C)
	{
		Eq_3 eax_27 = *((word32) dwArg14 + 20);
		struct Eq_47288 * ecx_33 = *((word32) eax_27 + (dwArg04 - 0x04)[esi_15] * 0x08);
		struct Eq_47288 * eax_34 = *((word32) eax_27 + *((word32) dwArg04 + esi_15 * 0x04) * 0x08);
		do
		{
			int32 eax_53;
			cu8 dl_37 = eax_34->b0000;
			if (dl_37 != ecx_33->b0000)
			{
l00621E66:
				up32 eax_50 = 0x00 - (dl_37 < ecx_33->b0000);
				eax_53 = eax_50 - ~0x00 - (eax_50 < 0x00);
				goto l00621E6B;
			}
			if (dl_37 == 0x00)
				break;
			byte dl_44 = eax_34->b0001;
			if (dl_44 != ecx_33->b0001)
				goto l00621E66;
			++eax_34;
			++ecx_33;
		} while (dl_44 != 0x00);
		eax_53 = 0x00;
l00621E6B:
		if (eax_53 < 0x00)
			--esi_15;
		*((word32) dwArg04 + ebx_108 * 0x04) = *((word32) dwArg04 + esi_15 * 0x04);
		esi_15 = esi_15 + 0x02 + esi_15;
		ebx_108 = esi_15;
		v19_151 = esi_15 != dwArg0C;
	}
	if (!v19_151)
	{
		*((word32) dwArg04 + ebx_108 * 0x04) = (dwArg04 - 0x04)[dwArg0C];
		ebx_108 = dwArg0C - 0x01;
	}
	return fn00621AE0(dwArg04, ebx_108, dwArg08, dwArg10, dwArg14);
}

// 00622070: void fn00622070(Register Eq_3 ecx, Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Stack Eq_3 dwArg00, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08)
// Called from:
//      fn00623130
//      fn006234C0
void fn00622070(Eq_3 ecx, Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, Eq_3 dwArg00, Eq_3 dwArg04, Eq_3 dwArg08)
{
	Eq_47379 edi_25;
	Eq_3 ecx_16 = *((word32) ecx + 4);
	if (ecx_16 == 0x00)
		edi_25.u0 = 0x00;
	else
		edi_25 = *((word32) ecx + 0x0C) - ecx_16 >> 0x02;
	if (dwArg08 == 0x00)
		return;
	Eq_47395 eax_43;
	if (ecx_16 == 0x00)
		eax_43.u0 = 0x00;
	else
		eax_43 = *((word32) ecx + 8) - ecx_16 >> 0x02;
	if (0x3FFFFFFF - eax_43 < dwArg08)
	{
		word32 edx_559;
		fn00621490(edi, esi, ebx, dwArg00, out ecx_16, out edx_559);
	}
	Eq_47408 eax_76;
	if (ecx_16 == 0x00)
		eax_76.u0 = 0x00;
	else
		eax_76 = *((word32) ecx + 8) - ecx_16 >> 0x02;
	if (edi_25 >=u eax_76 + dwArg08)
	{
		Eq_3 ebp_101 = *((word32) ecx + 8);
		if (ebp_101 - dwArg04 >> 0x02 >= dwArg08)
		{
			Eq_3 ebx_114 = ebp_101 - dwArg08 * 0x04;
			*((word32) ecx + 8) = fn007B2800(ebx_114, ebp_101, ebp_101);
			fn0050AAA0(dwArg04, ebx_114, ebp_101);
			fn004B3770(dwArg04, (word32) dwArg04 + dwArg08 * 0x04, fp + 0x0C);
		}
		else
		{
			fn007B2800(dwArg04, ebp_101, (word32) dwArg04 + dwArg08 * 0x04);
			Eq_3 eax_187 = *((word32) ecx + 8);
			fn00669E20(eax_187, dwArg08 - (eax_187 - dwArg04 >> 0x02), fp + 0x0C);
			*((word32) ecx + 8) = (word32) *((word32) ecx + 8) + dwArg08 * 0x04;
			fn004B3770(dwArg04, *((word32) ecx + 8) - dwArg08 * 0x04, fp + 0x0C);
		}
	}
	else
	{
		Eq_3 edi_245;
		Eq_47434 eax_240 = edi_25 >> 0x01;
		if (0x3FFFFFFF - eax_240 < edi_25)
			edi_245.u0 = 0x00;
		else
			edi_245 = edi_25 + eax_240;
		Eq_47442 eax_259;
		if (ecx_16 == 0x00)
			eax_259.u0 = 0x00;
		else
			eax_259 = *((word32) ecx + 8) - ecx_16 >> 0x02;
		if (edi_245 <u eax_259 + dwArg08)
		{
			int32 edi_280;
			if (ecx_16 == 0x00)
				edi_280 = 0x00;
			else
				edi_280 = *((word32) ecx + 8) - ecx_16 >> 0x02;
			edi_245 = (word32) dwArg08 + edi_280;
		}
		int32 ecx_375;
		word32 ecx_560;
		word32 edx_561;
		word32 ebp_562;
		Eq_9893 ebx_309;
		ui32 edi_310;
		struct Eq_47511 * esi_311;
		Eq_3 eax_305 = fn007B2480(dwArg08, ebp, ecx, edi_245, edi_245, out ecx_560, out edx_561, out ebx_309, out ebp_562, out esi_311, out edi_310);
		fn007B2800(dwArg04, esi_311->t0008, fn00669E20(fn007B2800(esi_311->t0004, dwArg04, eax_305), ebx_309, fp + 0x0C));
		Eq_3 eax_369 = esi_311->t0004;
		if (eax_369 == 0x00)
			ecx_375 = 0x00;
		else
			ecx_375 = esi_311->t0008 - eax_369 >> 0x02;
		ui32 ebx_382 = (word32) ebx_309 + ecx_375;
		if (eax_369 != 0x00)
			operator delete(eax_369);
		esi_311->t0004 = eax_305;
		esi_311->dw000C = (word32) eax_305 + edi_310 * 0x04;
		esi_311->t0008 = (word32) eax_305 + ebx_382 * 0x04;
	}
}

// 00622230: void fn00622230(Register Eq_3 ecx, Register Eq_3 edi, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00623E00
void fn00622230(Eq_3 ecx, Eq_3 edi, Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ebx_107;
	ptr32 eax_13 = fs->ptr0000;
	Eq_3 eax_27 = g_tA14188 ^ fp - 4;
	fs->ptr0000 = fp - 0x10;
	int32 eax_36 = dwArg0C - dwArg08;
	Eq_3 ecx_37 = *((word32) ecx + 4);
	Eq_24591 eax_102 = eax_36 >> 0x02;
	if (ecx_37 == 0x00)
		ebx_107.u0 = 0x00;
	else
		ebx_107 = *((word32) ecx + 0x0C) - ecx_37 >> 0x02;
	if (eax_36 >> 0x02 != 0x00)
	{
		Eq_47626 edx_62;
		if (ecx_37 == 0x00)
			edx_62.u0 = 0x00;
		else
			edx_62 = *((word32) ecx + 8) - ecx_37 >> 0x02;
		if (0x3FFFFFFF - edx_62 < eax_36 >> 0x02)
			eax_102 = fn0041BB30(eax_27, edi, out ecx_37);
		Eq_47640 edx_100;
		if (ecx_37 == 0x00)
			edx_100.u0 = 0x00;
		else
			edx_100 = *((word32) ecx + 8) - ecx_37 >> 0x02;
		if (ebx_107 <u edx_100 + eax_102)
		{
			Eq_3 ebx_276;
			Eq_47664 edx_271 = ebx_107 >> 0x01;
			Eq_3 edi_273 = 0x3FFFFFFF - edx_271;
			if (edi_273 < ebx_107)
				ebx_276.u0 = 0x00;
			else
				ebx_276 = ebx_107 + edx_271;
			Eq_47673 edx_290;
			if (ecx_37 == 0x00)
				edx_290.u0 = 0x00;
			else
				edx_290 = *((word32) ecx + 8) - ecx_37 >> 0x02;
			if (ebx_276 <u edx_290 + eax_102)
			{
				int32 edx_311;
				if (ecx_37 == 0x00)
					edx_311 = 0x00;
				else
					edx_311 = *((word32) ecx + 8) - ecx_37 >> 0x02;
				ebx_276 = (word32) eax_102 + edx_311;
			}
			int32 eax_420;
			word32 edx_640;
			word32 edi_641;
			word32 ecx_639;
			struct Eq_47740 * ebp_341;
			ui32 ebx_342;
			struct Eq_47742 * esi_344;
			Eq_3 eax_338 = fn007B2480(ebx_276, fp - 4, ecx, edi_273, ebx_276, out ecx_639, out edx_640, out ebx_342, out ebp_341, out esi_344, out edi_641);
			Eq_3 ecx_349 = esi_344->t0004;
			Eq_3 eax_353 = ebp_341->t0008;
			ebp_341->tFFFFFFE4 = eax_338;
			ebp_341->dwFFFFFFFC = 0x00;
			Eq_3 eax_363 = fn007B2800(ecx_349, eax_353, eax_338);
			ebp_341->bFFFFFFE8 = 0x00;
			fn007B2800(ebp_341->t0008, esi_344->t0008, fn00621710(ebp_341->t000C, ebp_341->t0010, eax_363));
			Eq_3 ecx_414 = esi_344->t0004;
			if (ecx_414 == 0x00)
				eax_420 = 0x00;
			else
				eax_420 = esi_344->t0008 - ecx_414 >> 0x02;
			ebp_341->dwFFFFFFEC += eax_420;
			if (ecx_414 != 0x00)
				operator delete(ecx_414);
			Eq_3 edx_447 = (word32) eax_338 + ebp_341->dwFFFFFFEC * 0x04;
			esi_344->dw000C = (word32) eax_338 + ebx_342 * 0x04;
			esi_344->t0008 = edx_447;
			esi_344->t0004 = eax_338;
			fs->ptr0000 = ebp_341->ptrFFFFFFF4;
			return;
		}
		Eq_3 ebx_112 = *((word32) ecx + 8);
		if (ebx_112 - dwArg04 >> 0x02 < eax_102)
		{
			ui32 eax_195 = eax_102 * 0x02;
			fn007B2800(dwArg04, ebx_112, (word32) dwArg04 + eax_195 * 0x02);
			Eq_3 eax_214 = *((word32) ecx + 8);
			Eq_3 ebx_220 = (word32) dwArg08 + (eax_214 - dwArg04 >> 0x02) * 0x04;
			fn007FB450(ebx_220, dwArg0C, eax_214);
			*((word32) ecx + 8) = (word32) *((word32) ecx + 8) + eax_195 * 0x02;
			fn006216E0(dwArg08, ebx_220, dwArg04);
			fs->ptr0000 = eax_13;
			return;
		}
		Eq_3 eax_130 = ebx_112 - eax_102 * 0x04;
		*((word32) ecx + 8) = fn007B2800(eax_130, ebx_112, ebx_112);
		fn0050AAA0(dwArg04, eax_130, ebx_112);
		fn006216E0(dwArg08, dwArg0C, dwArg04);
	}
	fs->ptr0000 = eax_13;
}

// 00622470: Register Eq_3 fn00622470(Register Eq_3 ecx, Register Eq_3 esi, Register Eq_3 edi, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Register out (ptr32 void) edxOut)
// Called from:
//      fn00623A00
Eq_3 fn00622470(Eq_3 ecx, Eq_3 esi, Eq_3 edi, Eq_3 dwArg04, Eq_3 dwArg08, void & edxOut)
{
	if (~0x00 - *((word32) ecx + 20) <= dwArg04)
		_Xlen(esi);
	if (dwArg04 > 0x00)
	{
		Eq_3 edi_33 = *((word32) ecx + 20);
		word32 edi_34 = edi_33 + dwArg04;
		if (edi_34 > 0x3FFFFFFE)
			_Xlen(edi);
		Eq_3 eax_40 = *((word32) ecx + 24);
		if (eax_40 < edi_34)
		{
			word32 ebp_245;
			edx = fn006218A0(ecx, dwArg04, edi_34, out ebp_245);
		}
		else if (edi_34 == 0x00)
		{
			*((word32) ecx + 20) = edi_34;
			if (eax_40 < 0x04)
			{
				((word32) ecx + 4)->u0 = 0x00;
				edxOut = edx;
				return <invalid>;
			}
			else
			{
				**((word32) ecx + 4) = edi_34;
				edxOut = edx;
				return <invalid>;
			}
		}
		if (edi_33 + dwArg04 >u 0x00)
		{
			edx = fn00621620(ecx, *((word32) ecx + 20), dwArg04, dwArg08);
			*((word32) ecx + 20) = edi_34;
			if (*((word32) ecx + 24) >= 0x04)
			{
				*((word32) *((word32) ecx + 4) + edi_34 * 0x04) = 0x00;
				edxOut = edx;
				return <invalid>;
			}
			((word32) ecx + (edi_34 * 0x04 + 4))->u0 = 0x00;
		}
	}
	edxOut = edx;
	return <invalid>;
}

// 00622530: void fn00622530(Stack (ptr32 Eq_47939) dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10)
// Called from:
//      fn006235F0
void fn00622530(struct Eq_47939 * dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10)
{
	int64 edx_eax_17 = (int64) (dwArg0C - dwArg08 >> 0x02);
	Eq_3 esi_30 = (word32) dwArg08 + ((word32) edx_eax_17 - SLICE(edx_eax_17, word32, 32) >> 0x01) * 0x04;
	fn00621D60(dwArg08, esi_30, dwArg0C - 0x04, dwArg10);
	Eq_3 ebp_149 = esi_30;
	Eq_3 dwLoc04_686 = esi_30;
	Eq_3 dwLoc0C_1004 = (word32) esi_30 + 4;
	if (dwArg08 < esi_30)
	{
		Eq_3 ebx_54 = *((word32) dwArg10 + 20);
		do
		{
			ui32 ecx_57 = *((word32) ebp_149 - 4);
			ui32 edx_58 = *ebp_149;
			struct Eq_47977 * eax_60 = *((word32) ebx_54 + ecx_57 * 0x08);
			struct Eq_48045 ** esi_61 = (word32) ebx_54 + ecx_57 * 0x08;
			struct Eq_47977 * ecx_62 = *((word32) ebx_54 + edx_58 * 0x08);
			struct Eq_48050 ** edi_63 = (word32) ebx_54 + edx_58 * 0x08;
			do
			{
				int32 eax_82;
				cu8 dl_66 = eax_60->b0000;
				if (dl_66 != ecx_62->b0000)
				{
l006225A7:
					up32 eax_79 = 0x00 - (dl_66 < ecx_62->b0000);
					eax_82 = eax_79 - ~0x00 - (eax_79 < 0x00);
					goto l006225AC;
				}
				if (dl_66 == 0x00)
					break;
				byte dl_73 = eax_60->b0001;
				if (dl_73 != ecx_62->b0001)
					goto l006225A7;
				++eax_60;
				++ecx_62;
			} while (dl_73 != 0x00);
			eax_82 = 0x00;
l006225AC:
			if (eax_82 < 0x00)
				break;
			struct Eq_48045 * ecx_103 = *esi_61;
			struct Eq_48050 * eax_108 = *edi_63;
			do
			{
				int32 eax_127;
				cu8 dl_111 = eax_108->b0000;
				if (dl_111 != ecx_103->b0000)
				{
l006225D4:
					up32 eax_124 = 0x00 - (dl_111 < ecx_103->b0000);
					eax_127 = eax_124 - ~0x00 - (eax_124 < 0x00);
					goto l006225D9;
				}
				if (dl_111 == 0x00)
					break;
				byte dl_118 = eax_108->b0001;
				if (dl_118 != ecx_103->b0001)
					goto l006225D4;
				++eax_108;
				++ecx_103;
			} while (dl_118 != 0x00);
			eax_127 = 0x00;
l006225D9:
			if (eax_127 < 0x00)
				break;
			ebp_149 = (word32) ebp_149 - 4;
		} while (dwArg08 < ebp_149);
		dwLoc04_686 = ebp_149;
	}
	if ((word32) esi_30 + 4 < dwArg0C)
	{
		Eq_3 edi_174 = *((word32) dwArg10 + 20);
		struct Eq_48024 * ebx_176 = *((word32) edi_174 + *dwLoc04_686 * 0x08);
		do
		{
			ui32 edx_181 = *dwLoc0C_1226;
			struct Eq_48024 * eax_183 = *((word32) edi_174 + edx_181 * 0x08);
			struct Eq_48203 ** esi_184 = (word32) edi_174 + edx_181 * 0x08;
			struct Eq_48024 * ecx_186 = ebx_176;
			do
			{
				int32 eax_206;
				cu8 dl_190 = eax_183->b0000;
				if (dl_190 != ecx_186->b0000)
				{
l00622640:
					up32 eax_203 = 0x00 - (dl_190 < ecx_186->b0000);
					eax_206 = eax_203 - ~0x00 - (eax_203 < 0x00);
					goto l00622645;
				}
				if (dl_190 == 0x00)
					break;
				byte dl_197 = eax_183->b0001;
				if (dl_197 != ecx_186->b0001)
					goto l00622640;
				++eax_183;
				++ecx_186;
			} while (dl_197 != 0x00);
			eax_206 = 0x00;
l00622645:
			if (eax_206 < 0x00)
				break;
			struct Eq_48024 * eax_232 = ebx_176;
			struct Eq_48203 * ecx_233 = *esi_184;
			do
			{
				int32 eax_252;
				cu8 dl_236 = eax_232->b0000;
				if (dl_236 != ecx_233->b0000)
				{
l00622670:
					up32 eax_249 = 0x00 - (dl_236 < ecx_233->b0000);
					eax_252 = eax_249 - ~0x00 - (eax_249 < 0x00);
					goto l00622675;
				}
				if (dl_236 == 0x00)
					break;
				byte dl_243 = eax_232->b0001;
				if (dl_243 != ecx_233->b0001)
					goto l00622670;
				++eax_232;
				++ecx_233;
			} while (dl_243 != 0x00);
			eax_252 = 0x00;
l00622675:
			if (eax_252 < 0x00)
				break;
			dwLoc0C_1004 = dwLoc0C_1226 + 0x04;
			dwLoc0C_1226 = dwLoc0C_1004;
		} while (dwLoc0C_1226 + 0x04 <u dwArg0C);
	}
	Eq_3 ebp_285 = dwLoc04_686;
	Eq_3 dwLoc08_1003 = dwLoc0C_1004;
	Eq_3 dwLoc04_763 = dwLoc04_686;
	Eq_3 ebx_288 = dwLoc0C_1004;
	while (true)
	{
		while (true)
		{
			if (ebx_288 < dwArg0C)
			{
				Eq_3 ebx_294 = ebx_288;
				do
				{
					Eq_3 eax_298 = *((word32) dwArg10 + 20);
					ui32 edx_302 = *ebx_294;
					struct Eq_48156 ** esi_303 = (word32) eax_298 + *ebp_285 * 0x08;
					struct Eq_47977 * ecx_304 = *((word32) eax_298 + edx_302 * 0x08);
					struct Eq_48255 ** edi_305 = (word32) eax_298 + edx_302 * 0x08;
					struct Eq_48156 * eax_306 = *esi_303;
					do
					{
						int32 eax_325;
						cu8 dl_309 = eax_306->b0000;
						if (dl_309 != ecx_304->b0000)
						{
l006226E7:
							up32 eax_322 = 0x00 - (dl_309 < ecx_304->b0000);
							eax_325 = eax_322 - ~0x00 - (eax_322 < 0x00);
							goto l006226EC;
						}
						if (dl_309 == 0x00)
							break;
						byte dl_316 = eax_306->b0001;
						if (dl_316 != ecx_304->b0001)
							goto l006226E7;
						++eax_306;
						++ecx_304;
					} while (dl_316 != 0x00);
					eax_325 = 0x00;
l006226EC:
					if (eax_325 >= 0x00)
					{
						struct Eq_48156 * ecx_346 = *esi_303;
						struct Eq_48255 * eax_351 = *edi_305;
						do
						{
							int32 eax_370;
							cu8 dl_354 = eax_351->b0000;
							if (dl_354 != ecx_346->b0000)
							{
l00622714:
								up32 eax_367 = 0x00 - (dl_354 < ecx_346->b0000);
								eax_370 = eax_367 - ~0x00 - (eax_367 < 0x00);
								goto l00622719;
							}
							if (dl_354 == 0x00)
								break;
							byte dl_361 = eax_351->b0001;
							if (dl_361 != ecx_346->b0001)
								goto l00622714;
							++eax_351;
							++ecx_346;
						} while (dl_361 != 0x00);
						eax_370 = 0x00;
l00622719:
						if (eax_370 < 0x00)
							break;
						word32 ecx_409 = *dwLoc0C_1004;
						*dwLoc0C_1004 = *ebx_294;
						*ebx_294 = ecx_409;
						dwLoc0C_1004 += 0x04;
					}
					ebx_294 = (word32) ebx_294 + 4;
				} while (ebx_294 < dwArg0C);
				dwLoc08_1003 = ebx_294;
			}
			if (dwArg08 < dwLoc04_763)
			{
				word32 ebx_427 = dwLoc04_763 + ~0x03;
				do
				{
					Eq_3 eax_432 = *((word32) dwArg10 + 20);
					struct Eq_48349 ** edi_437 = (word32) eax_432 + *ebp_285 * 0x08;
					struct Eq_48365 ** esi_439 = (word32) eax_432 + ebx_427->dw0000 * 0x08;
					struct Eq_48349 * ecx_438 = *edi_437;
					struct Eq_48365 * eax_440 = *esi_439;
					do
					{
						int32 eax_460;
						cu8 dl_444 = eax_440->b0000;
						if (dl_444 != ecx_438->b0000)
						{
l00622790:
							up32 eax_457 = 0x00 - (dl_444 < ecx_438->b0000);
							eax_460 = eax_457 - ~0x00 - (eax_457 < 0x00);
							goto l00622795;
						}
						if (dl_444 == 0x00)
							break;
						byte dl_451 = eax_440->b0001;
						if (dl_451 != ecx_438->b0001)
							goto l00622790;
						++eax_440;
						++ecx_438;
					} while (dl_451 != 0x00);
					eax_460 = 0x00;
l00622795:
					if (eax_460 >= 0x00)
					{
						struct Eq_48349 * eax_486 = *edi_437;
						struct Eq_48365 * ecx_487 = *esi_439;
						do
						{
							int32 eax_506;
							cu8 dl_490 = eax_486->b0000;
							if (dl_490 != ecx_487->b0000)
							{
l006227C0:
								up32 eax_503 = 0x00 - (dl_490 < ecx_487->b0000);
								eax_506 = eax_503 - ~0x00 - (eax_503 < 0x00);
								goto l006227C5;
							}
							if (dl_490 == 0x00)
								break;
							byte dl_497 = eax_486->b0001;
							if (dl_497 != ecx_487->b0001)
								goto l006227C0;
							++eax_486;
							++ecx_487;
						} while (dl_497 != 0x00);
						eax_506 = 0x00;
l006227C5:
						if (eax_506 < 0x00)
							break;
						word32 eax_540 = *((word32) ebp_285 - 4);
						ebp_285 -= 0x04;
						*ebp_285 = ebx_427->dw0000;
						ebx_427->dw0000 = eax_540;
					}
					ebx_427 -= (struct Eq_48431 *) 0x04;
					dwLoc04_763 = dwLoc04_1225 - (struct Eq_48434 *) 0x04;
					dwLoc04_1225 = dwLoc04_763;
				} while (dwArg08 < dwLoc04_1225 - (struct Eq_48434 *) 0x04);
			}
			if (dwLoc04_763 == dwArg08)
				break;
			dwLoc04_763 -= (struct Eq_48388 *) 0x04;
			if (dwLoc08_1003 == dwArg0C)
			{
				ebp_285 -= 0x04;
				if (dwLoc04_763 - (struct Eq_48388 *) 0x04 != ebp_285)
				{
					ui32 eax_599 = *((word32) dwLoc04_763 - 4);
					*((word32) dwLoc04_763 - 4) = *ebp_285;
					*ebp_285 = eax_599;
				}
				ui32 eax_607 = *ebp_285;
				*ebp_285 = *((word32) dwLoc0C_1004 - 4);
				*((word32) dwLoc0C_1004 - 4) = eax_607;
				ebx_288 = dwLoc08_1003;
				dwLoc0C_1004 -= (struct Eq_48558 *) 0x04;
			}
			else
			{
				word32 ecx_577 = *dwLoc08_1003;
				*dwLoc08_1003 = *((word32) dwLoc04_763 - 4);
				*((word32) dwLoc04_763 - 4) = ecx_577;
				dwLoc08_1003 += 0x04;
				ebx_288 = dwLoc08_1003;
			}
		}
		if (dwLoc08_1003 == dwArg0C)
			break;
		if (dwLoc0C_1004 != dwLoc08_1003)
		{
			ui32 eax_634 = *ebp_285;
			*ebp_285 = *dwLoc0C_1004;
			*dwLoc0C_1004 = eax_634;
		}
		ui32 edx_650 = *ebp_285;
		*ebp_285 = *dwLoc08_1003;
		*dwLoc08_1003 = edx_650;
		dwLoc08_1003 += 0x04;
		ebx_288 = dwLoc08_1003;
		dwLoc0C_1004 += 0x04;
		ebp_285 = (word32) ebp_285 + 4;
	}
	dwArg04->t0000 = ebp_285;
	dwArg04->t0004 = dwLoc0C_1004;
}

// 006228B0: Register Eq_3 fn006228B0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Register out ptr32 edxOut)
// Called from:
//      fn006235F0
Eq_3 fn006228B0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, ptr32 & edxOut)
{
	Eq_3 eax_112 = dwArg08;
	Eq_3 esi_11 = dwArg04;
	if (dwArg04 != dwArg08)
	{
		Eq_3 ebx_17 = (word32) dwArg04 + 4;
		Eq_3 dwLoc04_305 = (word32) dwArg04 + 4;
		if ((word32) dwArg04 + 4 != dwArg08)
		{
			do
			{
				ui32 edx_34 = *esi_11;
				Eq_3 ebp_30 = *((word32) dwArg0C + 20);
				ui32 ecx_32 = *ebx_17;
				word24 edx_24_8_481 = SLICE(edx_34, word24, 8);
				struct Eq_48591 * eax_35 = *((word32) ebp_30 + ecx_32 * 0x08);
				struct Eq_48646 ** edi_36 = (word32) ebp_30 + ecx_32 * 0x08;
				struct Eq_48591 * ecx_37 = *((word32) ebp_30 + edx_34 * 0x08);
				do
				{
					int32 eax_56;
					cu8 dl_40 = eax_35->b0000;
					edx = SEQ(edx_24_8_481, dl_40);
					if (dl_40 != ecx_37->b0000)
					{
l00622910:
						up32 eax_53 = 0x00 - (dl_40 < ecx_37->b0000);
						eax_56 = eax_53 - ~0x00 - (eax_53 < 0x00);
						goto l00622915;
					}
					edx = SEQ(edx_24_8_481, dl_40);
					if (dl_40 == 0x00)
						break;
					byte dl_47 = eax_35->b0001;
					edx = SEQ(edx_24_8_481, dl_47);
					if (dl_47 != ecx_37->b0001)
						goto l00622910;
					++eax_35;
					++ecx_37;
					edx = SEQ(edx_24_8_481, dl_47);
				} while (dl_47 != 0x00);
				eax_56 = 0x00;
l00622915:
				word24 edx_24_8_491 = SLICE(edx, word24, 8);
				if (eax_56 < 0x00)
				{
					eax_112 = (word32) ebx_17 + 4;
					if (esi_11 != ebx_17 && ebx_17 != eax_112)
						eax_112 = fn00621740(esi_11, ebx_17, eax_112, out edx);
				}
				else
				{
					struct Eq_48591 * ecx_115 = *((word32) ebp_30 + *((word32) ebx_17 - 4) * 0x08);
					struct Eq_48646 * eax_114 = *edi_36;
					Eq_3 esi_134 = ebx_17 - 0x04;
					do
					{
						cu8 dl_96 = eax_114->b0000;
						edx = SEQ(edx_24_8_491, dl_96);
						if (dl_96 != ecx_115->b0000)
						{
l00622970:
							up32 eax_109 = 0x00 - (dl_96 < ecx_115->b0000);
							eax_112 = eax_109 - ~0x00 - (eax_109 < 0x00);
							goto l00622975;
						}
						edx = SEQ(edx_24_8_491, dl_96);
						if (dl_96 == 0x00)
							break;
						byte dl_103 = eax_114->b0001;
						edx = SEQ(edx_24_8_491, dl_103);
						if (dl_103 != ecx_115->b0001)
							goto l00622970;
						++eax_114;
						++ecx_115;
						edx = SEQ(edx_24_8_491, dl_103);
					} while (dl_103 != 0x00);
					eax_112.u0 = 0x00;
l00622975:
					word24 edx_24_8_501 = SLICE(edx, word24, 8);
					if (eax_112 < 0x00)
					{
						struct Eq_48646 * edi_133 = *edi_36;
						do
						{
							struct Eq_48591 * ecx_138 = *((word32) ebp_30 + *((word32) esi_541 - 4) * 0x08);
							esi_134 = esi_541 - 0x04;
							struct Eq_48646 * eax_143 = edi_133;
							do
							{
								cu8 dl_147 = eax_143->b0000;
								edx = SEQ(edx_24_8_501, dl_147);
								if (dl_147 != ecx_138->b0000)
								{
l006229B0:
									up32 eax_160 = 0x00 - (dl_147 < ecx_138->b0000);
									eax_112 = eax_160 - ~0x00 - (eax_160 < 0x00);
									goto l006229B5;
								}
								edx = SEQ(edx_24_8_501, dl_147);
								if (dl_147 == 0x00)
									break;
								byte dl_154 = eax_143->b0001;
								edx = SEQ(edx_24_8_501, dl_154);
								if (dl_154 != ecx_138->b0001)
									goto l006229B0;
								++eax_143;
								++ecx_138;
								edx = SEQ(edx_24_8_501, dl_154);
							} while (dl_154 != 0x00);
							eax_112.u0 = 0x00;
l006229B5:
							edx_24_8_501 = SLICE(edx, word24, 8);
							esi_541 = esi_134;
						} while (eax_112 < 0x00);
						if (esi_541 != dwLoc04_305)
						{
							eax_112 = (word32) dwLoc04_305 + 4;
							if (dwLoc04_305 != (word32) dwLoc04_305 + 4)
								eax_112 = fn00621740(esi_541, dwLoc04_305, (word32) dwLoc04_305 + 4, out edx);
						}
						ebx_17 = dwLoc04_305;
					}
					esi_11 = dwArg04;
				}
				ebx_17 = (word32) ebx_17 + 4;
				dwLoc04_305 = ebx_17;
			} while (ebx_17 != dwArg08);
		}
	}
	edxOut = edx;
	return eax_112;
}

// 00622A00: void fn00622A00(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn006235F0
void fn00622A00(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	int32 edi_15 = dwArg08 - dwArg04;
	int64 edx_eax_18 = (int64) (edi_15 >> 0x02);
	int32 eax_21 = (word32) edx_eax_18 - SLICE(edx_eax_18, word32, 32);
	int32 esi_23 = eax_21 >> 0x01;
	if (eax_21 >> 0x01 > 0x00)
	{
		do
		{
			--esi_23;
			fn00621E10(dwArg04, esi_23, edi_15 >> 0x02, (&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(dwArg04 - 0x04)[esi_23].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0], dwArg0C);
		} while (esi_23 > 0x00);
	}
}

// 00622B40: Register Eq_3 fn00622B40(Register Eq_3 ecx, Register Eq_3 ebx, Register Eq_3 esi, Register Eq_3 edi, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 nArg0C, Register out (ptr32 word32) ediOut)
// Called from:
//      fn00623210
Eq_3 fn00622B40(Eq_3 ecx, Eq_3 ebx, Eq_3 esi, Eq_3 edi, Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 nArg0C, word32 & ediOut)
{
	word24 nArg0D_541 = SLICE(dwArg0C, word24, 8);
	Eq_43647 edi_110;
	ptr32 eax_13 = fs->ptr0000;
	Eq_3 eax_27 = g_tA14188 ^ fp - 4;
	fs->ptr0000 = fp - 0x10;
	ptr32 esp_127 = fp - 0x30;
	Eq_3 eax_38 = *((word32) ecx + 4);
	if (eax_38 == 0x00)
		edi_110.u0 = 0x00;
	else
		edi_110 = *((word32) ecx + 0x0C) - eax_38 >> 0x03;
	Eq_3 edx_105 = dwArg08;
	if (dwArg08 != 0x00)
	{
		Eq_48889 ecx_64;
		if (eax_38 == 0x00)
			ecx_64.u0 = 0x00;
		else
			ecx_64 = *((word32) ecx + 8) - eax_38 >> 0x03;
		if (0x1FFFFFFF - ecx_64 < dwArg08)
		{
			eax_38 = fn00621430(eax_27, edi, esi, ebx, out edx_105);
			esp_127 = fp - 0x34;
		}
		Eq_48902 ecx_100;
		if (eax_38 == 0x00)
			ecx_100.u0 = 0x00;
		else
			ecx_100 = *((word32) ecx + 8) - eax_38 >> 0x03;
		if (edi_110 <u ecx_100 + edx_105)
		{
			Eq_43649 edi_283;
			Eq_48929 ecx_278 = edi_110 >> 0x01;
			Eq_43647 ebx_280 = 0x1FFFFFFF - ecx_278;
			if (ebx_280 < edi_110)
				edi_283.u0 = 0x00;
			else
				edi_283 = edi_110 + ecx_278;
			Eq_48938 ecx_297;
			if (eax_38 == 0x00)
				ecx_297.u0 = 0x00;
			else
				ecx_297 = *((word32) ecx + 8) - eax_38 >> 0x03;
			if (edi_283 <u ecx_297 + edx_105)
			{
				int32 ecx_318;
				if (eax_38 == 0x00)
					ecx_318 = 0x00;
				else
					ecx_318 = *((word32) ecx + 8) - eax_38 >> 0x03;
				edi_283 = (word32) edx_105 + ecx_318;
			}
			Eq_49134 eax_433;
			struct Eq_49135 * esp_330 = esp_127 - 4;
			esp_330->dw0000 = 0x00;
			esp_330->tFFFFFFFC = edi_283;
			Eq_3 esi_345;
			ui32 edi_347;
			Eq_3 eax_341 = fn005D9410(ebx_280, ecx, edi_283, esp_330->tFFFFFFFC, out esi_345, out edi_347);
			Eq_3 esp_346 = <invalid>;
			Eq_3 dwArg0C_543 = SEQ(nArg0D_541, 0x00);
			*((word32) esp_346 - 4) = dwArg0C_543;
			*((word32) esp_346 - 8) = dwArg08;
			Eq_3 eax_365 = *((word32) esi_345 + 4);
			*((word32) esp_346 - 0x0C) = esi_345;
			*((word32) esp_346 - 16) = eax_341;
			*((word32) esp_346 - 20) = dwArg04;
			*((word32) esp_346 - 24) = eax_365;
			Eq_3 eax_376 = fn00614080(*((word32) esp_346 - 24), *((word32) esp_346 - 20), *((word32) esp_346 - 16));
			*((word32) esp_346 + 4) = fp - 0x20;
			*esp_346 = dwArg08;
			*((word32) esp_346 - 4) = eax_376;
			Eq_3 eax_394 = fn005BB700(*((word32) esp_346 - 4), *esp_346, *((word32) esp_346 + 4));
			Eq_3 ecx_402 = *((word32) esi_345 + 8);
			*((word32) esp_346 + 4) = dwArg0C_543;
			*esp_346 = dwArg08;
			*((word32) esp_346 - 4) = esi_345;
			*((word32) esp_346 - 8) = eax_394;
			*((word32) esp_346 - 0x0C) = ecx_402;
			*((word32) esp_346 - 16) = dwArg04;
			fn00614080(*((word32) esp_346 - 16), *((word32) esp_346 - 0x0C), *((word32) esp_346 - 8));
			Eq_3 ecx_426 = *((word32) esi_345 + 4);
			if (ecx_426 == 0x00)
				eax_433.u0 = 0x00;
			else
				eax_433 = *((word32) esi_345 + 8) - ecx_426 >> 0x03;
			word32 v16_441 = dwArg08 + eax_433;
			if (ecx_426 != 0x00)
			{
				*((word32) esp_346 + 4) = ecx_426;
				operator delete(*((word32) esp_346 + 4));
			}
			*((word32) esi_345 + 0x0C) = (word32) eax_341 + edi_347 * 0x08;
			*((word32) esi_345 + 8) = (word32) eax_341 + v16_441 * 0x08;
			*((word32) esi_345 + 4) = eax_341;
			fs->ptr0000 = eax_13;
			Eq_3 ebx_481 = *((word32) esp_346 + 20);
			ediOut = (word32 *) *((word32) esp_346 + 0x0C);
			return ebx_481;
		}
		Eq_3 ebx_115 = *((word32) ecx + 8);
		if (ebx_115 - dwArg04 >> 0x03 < edx_105)
		{
			ui32 eax_200 = edx_105 * 0x08;
			struct Eq_49027 * esp_204 = esp_127 - 4;
			esp_204->t0000 = (word32) dwArg04 + eax_200;
			esp_204->tFFFFFFFC = ebx_115;
			esp_204->tFFFFFFF8 = dwArg04;
			fn00417AC0(esp_204->tFFFFFFF8, esp_204->tFFFFFFFC, esp_204->t0000);
			Eq_3 eax_219 = *((word32) ecx + 8);
			esp_204->t0000 = fp - 0x20;
			esp_204->tFFFFFFFC = dwArg08 - (eax_219 - dwArg04 >> 0x03);
			esp_204->tFFFFFFF8 = eax_219;
			fn005BB700(esp_204->tFFFFFFF8, esp_204->tFFFFFFFC, esp_204->t0000);
			*((word32) ecx + 8) = (word32) *((word32) ecx + 8) + eax_200;
			Eq_3 esi_246 = *((word32) ecx + 8);
			esp_204->t0000 = fp - 0x20;
			esp_204->tFFFFFFFC = esi_246 - eax_200;
			esp_204->tFFFFFFF8 = dwArg04;
			fn004166A0(esp_204->tFFFFFFF8, esp_204->tFFFFFFFC, esp_204->t0000);
			fs->ptr0000 = eax_13;
			Eq_3 ebx_273 = esp_204->t0010;
			ediOut = esp_204->ptr0008;
			return ebx_273;
		}
		struct Eq_48941 * esp_128 = esp_127 - 4;
		esp_128->t0000 = ebx_115;
		esp_128->tFFFFFFFC = ebx_115;
		int32 ecx_125 = edx_105 * 0x08;
		Eq_3 eax_131 = ebx_115 - ecx_125;
		esp_128->tFFFFFFF8 = eax_131;
		Eq_3 eax_140 = fn00417AC0(esp_128->tFFFFFFF8, esp_128->tFFFFFFFC, esp_128->t0000);
		esp_128->t0000 = ebx_115;
		esp_128->tFFFFFFFC = eax_131;
		esp_128->tFFFFFFF8 = dwArg04;
		*((word32) ecx + 8) = eax_140;
		fn006641A0(esp_128->tFFFFFFF8, esp_128->tFFFFFFFC, esp_128->t0000);
		esp_128->tFFFFFFF4 = fp - 0x20;
		esp_128->tFFFFFFF0 = (word32) dwArg04 + ecx_125;
		esp_128->tFFFFFFEC = dwArg04;
		fn004166A0(esp_128->tFFFFFFEC, esp_128->tFFFFFFF0, esp_128->tFFFFFFF4);
		esp_127 = (const char *) &esp_128->t0000 + 4;
	}
	fs->ptr0000 = eax_13;
	struct Eq_48879 * esp_191 = esp_127 + 4;
	Eq_3 ebx_196 = esp_191->t0008;
	ediOut = esp_191->ptr0000;
	return ebx_196;
}

// 00622EF0: Register int32 fn00622EF0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Register out ptr32 edxOut)
// Called from:
//      fn006235F0
int32 fn00622EF0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, ptr32 & edxOut)
{
	int32 esi_12 = dwArg08 - dwArg04;
	int32 eax_14 = esi_12 >> 0x02;
	while (esi_12 >> 0x02 > 0x01)
	{
		Eq_47018 eax_24 = (&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(dwArg04 - 0x04)[esi_12 / 4].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0];
		(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(dwArg04 - 0x04)[esi_12 / 4].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0] = (Eq_49332) *dwArg04;
		esi_12 -= 0x04;
		edx = fn00621E10(dwArg04, 0x00, esi_12 - 0x04 >> 0x02, eax_24, dwArg0C);
		eax_14 = esi_12 >> 0x02;
	}
	edxOut = edx;
	return eax_14;
}

// 00623130: void fn00623130(Register Eq_3 ecx, Register Eq_3 ebp)
// Called from:
//      fn00623340
void fn00623130(Eq_3 ecx, Eq_3 ebp)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	((word32) ecx + 4)->u0 = 0x00;
	((word32) ecx + 8)->u0 = 0x00;
	*((word32) ecx + 0x0C) = null;
	((word32) ecx + 20)->u0 = 0x00;
	((word32) ecx + 24)->u0 = 0x00;
	*((word32) ecx + 28) = null;
	Eq_3 eax_42 = operator new(0x0200);
	Eq_3 edi_43 = eax_42;
	if (eax_42 != 0x00)
		memset(eax_42, 0x00, 0x0200);
	else
		edi_43.u0 = 0x00;
	Eq_49400 ecx_70;
	Eq_3 edx_61 = *((word32) ecx + 4);
	if (edx_61 == 0x00)
		ecx_70.u0 = 0x00;
	else
		ecx_70 = *((word32) ecx + 8) - edx_61 >> 0x02;
	if (edx_61 == 0x00 || ecx_70 >= *((word32) ecx + 0x0C) - edx_61 >> 0x02)
	{
		fn00622070(ecx, 0x00, ebp, ecx, edi_43, dwLoc34, *((word32) ecx + 8), 0x01);
		fs->ptr0000 = eax_9;
	}
	else
	{
		Eq_3 eax_131 = *((word32) ecx + 8);
		*eax_131 = edi_43;
		*((word32) ecx + 8) = (word32) eax_131 + 4;
		fs->ptr0000 = eax_9;
	}
}

// 00623210: Register Eq_3 fn00623210(Register Eq_3 ecx, Register Eq_3 ebx, Register Eq_3 edi, Stack Eq_3 dwArg04, Register out Eq_3 ediOut)
// Called from:
//      fn00623420
Eq_3 fn00623210(Eq_3 ecx, Eq_3 ebx, Eq_3 edi, Eq_3 dwArg04, union Eq_3 & ediOut)
{
	Eq_49453 ecx_17;
	Eq_3 edx_11 = *((word32) ecx + 4);
	if (edx_11 == 0x00)
		ecx_17.u0 = 0x00;
	else
		ecx_17 = *((word32) ecx + 8) - edx_11 >> 0x03;
	if (edx_11 == 0x00 || ecx_17 >= *((word32) ecx + 0x0C) - edx_11 >> 0x03)
	{
		Eq_3 edi_59;
		Eq_3 ebx_57 = fn00622B40(ecx, ebx, ecx, edi, *((word32) ecx + 8), 0x01, dwArg04, out edi_59);
		ediOut = edi_59;
		return ebx_57;
	}
	else
	{
		Eq_3 edi_75 = *((word32) ecx + 8);
		fn007C2D70(edi_75, 0x01, dwArg04);
		*((word32) ecx + 8) = (word32) edi_75 + 8;
		ediOut = edi;
		return ebx;
	}
}

// 00623280: void fn00623280(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn00623840
void fn00623280(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	ptr32 eax_13 = fs->ptr0000;
	fs->ptr0000 = fp - 0x10;
	Eq_3 esi_33 = dwArg04;
	Eq_3 edi_34;
	for (edi_34 = dwArg08; edi_34 > 0x00; --edi_34)
	{
		if (esi_33 != 0x00)
		{
			*((word32) esi_33 + 24) = 0x03;
			*((word32) esi_33 + 20) = 0x00;
			*((word32) esi_33 + 4) = 0x00;
			fn00621C70(esi_33, edi_34, dwArg0C, 0x00, ~0x00);
		}
		esi_33 = (word32) esi_33 + 28;
	}
	fs->ptr0000 = eax_13;
}

// 00623340: Register (ptr32 Eq_49539) fn00623340(Register (ptr32 Eq_49539) ecx, Register Eq_3 ebp)
// Called from:
//      fn006233B0
//      fn00623E00
struct Eq_49539 * fn00623340(struct Eq_49539 * ecx, Eq_3 ebp)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	ecx->b0004 = 0x01;
	ecx->dw0000 = 9200888;
	fn00623130(&ecx->b0004 + 4, ebp);
	ecx->dw002C = 0x00;
	ecx->dw0030 = 0x00;
	ecx->dw0034 = 0x00;
	ecx->dw003C = 0x00;
	ecx->dw0040 = 0x00;
	ecx->dw0044 = 0x00;
	ecx->b0048 = 0x00;
	ecx->b0049 = 0x00;
	fs->ptr0000 = eax_9;
	return ecx;
}

// 006233B0: Register word32 fn006233B0(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register out Eq_3 ebxOut, Register out Eq_3 ebpOut, Register out Eq_3 esiOut, Register out Eq_3 ediOut)
// Called from:
//      fn0042A250
//      fn0042ACF0
//      fn0042F170
word32 fn006233B0(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, union Eq_3 & ebxOut, union Eq_3 & ebpOut, union Eq_3 & esiOut, union Eq_3 & ediOut)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	if ((g_tA67C54 & 0x01) == 0x00)
	{
		g_tA67C54 |= 0x01;
		fn00623340(&g_tA67C08, ebp);
		ebx = fn00694C8C(ebx, esi, edi, out ebp, out esi, out edi);
	}
	fs->ptr0000 = eax_9;
	ebxOut = ebx;
	ebpOut = ebp;
	esiOut = esi;
	ediOut = edi;
	return 0x00A67C08;
}

// 00623420: Register int32 fn00623420(Register Eq_3 ecx, Stack (ptr32 (ptr32 Eq_49695)) dwArg04, Stack word16 wArg0C, Stack Eq_3 dwArg10, Stack byte bArg14)
// Called from:
//      fn006234C0
//      fn006236E0
int32 fn00623420(Eq_3 ecx, struct Eq_49695 ** dwArg04, word16 wArg0C, Eq_3 dwArg10, byte bArg14)
{
	Eq_3 eax_16 = dwArg10;
	do
	{
		eax_16 = (word32) eax_151 + 1;
		eax_151 = eax_16;
	} while (*eax_151 != 0x00);
	int32 esi_68;
	word32 eax_31 = eax_16 - ((word32) dwArg10 + 1);
	fn00694B89(eax_31 + 0x01);
	struct Eq_49656 * edi_54;
	Eq_3 ebx_53 = fn00623210((word32) ecx + 16, eax_31 + 0x01, ecx, fp - 0x08, out edi_54);
	Eq_3 eax_62 = *((word32) ecx + 20);
	if (eax_62 == 0x00)
		esi_68 = 0x00;
	else
		esi_68 = *((word32) ecx + 24) - eax_62 >> 0x03;
	Eq_49681 eax_75 = edi_54->t0014;
	Eq_3 ecx_77 = (eax_75 - 0x08)[esi_68].t0000;
	*dwArg04 = (struct Eq_49695 **) (eax_75 - 0x08 + esi_68 * 0x08);
	memcpy(ecx_77, dwArg10, ebx_53);
	int32 edx_100 = ~(*dwArg04 - edi_54->t0014 >> 0x03);
	*((word16) (&edi_54->ptr0004[(int32) wArg0C])[0] + (word32) bArg14 * 0x02) = (word16) edx_100;
	return edx_100;
}

// 006234C0: Register (ptr32 Eq_49695) fn006234C0(Register Eq_3 ecx, Stack (ptr32 (ptr32 Eq_49695)) dwArg04, Stack Eq_49727 wArg0C, Stack Eq_3 dwArg10, Stack (ptr32 Eq_49695) dwArg14, Stack ptr32 dwArg18)
// Called from:
//      fn006236E0
struct Eq_49695 * fn006234C0(Eq_3 ecx, struct Eq_49695 ** dwArg04, Eq_49727 wArg0C, Eq_3 dwArg10, struct Eq_49695 * dwArg14, ptr32 dwArg18)
{
	byte * ebx_21 = (word32) dwArg10 + dwArg18;
	Eq_3 edi_27 = dwArg14->dw0000 + dwArg18;
	byte bl_32 = *ebx_21;
	word32 ecx_142 = dwArg0C;
	byte * dwArg18_221 = ebx_21;
	Eq_3 dwArg0C_222 = *((word32) *((word32) ecx + 4) + (int32) ((word16) dwArg0C) * 0x04);
	byte al_150 = *edi_27;
	Eq_3 ebx_109 = SEQ(SLICE(ebx_21, word24, 8), bl_32);
	word32 dwLoc08_255 = SEQ(nLoc07, bl_32);
	if (bl_32 == al_150)
	{
		do
		{
			byte * v15_40 = dwArg18_221 + 1;
			Eq_3 eax_46 = operator new(0x0200);
			byte bl_137 = (byte) ebx_109;
			word24 ebx_24_8_211 = SLICE(ebx_109, word24, 8);
			dwArg18_221 = v15_40;
			edi_27 = (word32) edi_27 + 1;
			Eq_3 ebp_47 = eax_46;
			if (eax_46 != 0x00)
				memset(eax_46, 0x00, 0x0200);
			else
				ebp_47.u0 = 0x00;
			Eq_49805 ecx_76;
			Eq_3 edx_67 = *((word32) ecx + 4);
			if (edx_67 == 0x00)
				ecx_76.u0 = 0x00;
			else
				ecx_76 = *((word32) ecx + 8) - edx_67 >> 0x02;
			if (edx_67 != 0x00 && ecx_76 < *((word32) ecx + 0x0C) - edx_67 >> 0x02)
			{
				Eq_3 eax_127 = *((word32) ecx + 8);
				*eax_127 = ebp_47;
				*((word32) ecx + 8) = (word32) eax_127 + 4;
			}
			else
				fn00622070(ecx, ebx_109, ebp_47, ecx, edi_27, dwLoc28, *((word32) ecx + 8), 0x01);
			ecx_142 = (word32) (word16) (*((word32) ecx + 8) - *((word32) ecx + 4) - 0x04 >> 0x02);
			*((word32) dwArg0C_222 + (word32) bl_137 * 0x02) = (word16) ecx_142;
			byte bl_148 = *v15_40;
			al_150 = (byte) *edi_27;
			dwArg0C_222 = ebp_47;
			ebx_109 = SEQ(ebx_24_8_211, bl_148);
		} while (bl_148 == al_150);
		dwLoc08_255 = SEQ(nLoc07, bl_148);
	}
	*((word32) dwArg0C_222 + (word32) al_150 * 0x02) = (word16) ~(dwArg14 - *((word32) ecx + 20) >> 0x03);
	return fn00623420(ecx, dwArg04, (word16) ecx_142, dwArg10, (byte) dwLoc08_255);
}

// 006235F0: Register int32 fn006235F0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10, Register out (ptr32 void) edxOut, Register out Eq_540 ebpOut, Register out Eq_540 esiOut, Register out Eq_540 ediOut)
// Called from:
//      fn006235F0
//      fn00623A00
int32 fn006235F0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10, void & edxOut, union Eq_540 & ebpOut, union Eq_540 & esiOut, union Eq_540 & ediOut)
{
	int32 eax_20 = dwArg08 - dwArg04;
	Eq_3 ebx_162 = dwArg04;
	Eq_3 edi_146 = dwArg08;
	int32 eax_167 = eax_20 >> 0x02;
	if (eax_20 >> 0x02 > 0x20)
	{
		Eq_3 esi_119 = dwArg0C;
		do
		{
			if (esi_119 <= 0x00)
			{
				if (eax_167 <= 0x20)
					break;
				if ((edi_146 - ebx_162 & ~0x03) > 0x04)
					fn00622A00(ebx_162, edi_146, dwArg10);
				void * edx_73;
				int32 eax_71 = fn00622EF0(ebx_162, edi_146, dwArg10, out edx_73);
				edxOut = edx_73;
				ebpOut.u0 = <invalid>;
				esiOut.u0 = <invalid>;
				ediOut.u0 = <invalid>;
				return eax_71;
			}
			fn00622530(fp - 0x08, ebx_162, edi_146, dwArg10);
			int64 edx_eax_108 = (int64) esi_119;
			int32 eax_111 = (word32) edx_eax_108 - SLICE(edx_eax_108, word32, 32);
			int64 edx_eax_114 = (int64) (eax_111 >> 0x01);
			esi_119 = (eax_111 >> 0x01) + ((word32) edx_eax_114 - SLICE(edx_eax_114, word32, 32) >> 0x01);
			if ((dwLoc08 - ebx_162 & ~0x03) < (edi_146 - dwLoc04 & ~0x03))
			{
				word32 esi_324;
				word32 edi_325;
				word32 ebp_323;
				fn006235F0(ebx_162, dwArg04, dwArg08, dwArg0C, out edx, out ebp_323, out esi_324, out edi_325);
				ebx_162 = dwLoc04;
			}
			else
			{
				word32 edi_322;
				word32 ebp_320;
				word32 esi_321;
				fn006235F0(dwLoc04, dwArg04, dwArg08, dwArg0C, out edx, out ebp_320, out esi_321, out edi_322);
				edi_146 = dwLoc08;
			}
			int32 eax_166 = edi_146 - ebx_162;
			eax_167 = eax_166 >> 0x02;
		} while (eax_166 >> 0x02 > 0x20);
	}
	if (eax_167 > 0x01)
		eax_167 = fn006228B0(ebx_162, edi_146, dwArg10, out edx);
	edxOut = edx;
	ebpOut.u0 = <invalid>;
	esiOut.u0 = <invalid>;
	ediOut.u0 = <invalid>;
	return eax_167;
}

// 006236E0: Register (ptr32 Eq_49695) fn006236E0(Register Eq_3 ecx, Stack (ptr32 (ptr32 Eq_49695)) dwArg04, Stack Eq_3 dwArg08, Stack (ptr32 word32) dwArg0C)
// Called from:
//      fn00623910
//      fn00623A00
//      fn00623E00
struct Eq_49695 * fn006236E0(Eq_3 ecx, struct Eq_49695 ** dwArg04, Eq_3 dwArg08, word32 * dwArg0C)
{
	Eq_3 esi_14 = dwArg08;
	Eq_3 edi_19 = *((word32) ecx + 4);
	ci16 ax_232 = 0x00;
	do
	{
		byte dl_25 = *esi_14;
		Eq_49727 ebp_27 = (word32) ax_232;
		ax_232 = (ci16) *((word32) *((word32) edi_19 + (int32) ax_232 * 0x04) + (word32) dl_25 * 0x02);
		esi_14 = (word32) esi_14 + 1;
	} while (ax_232 > 0x00 && dl_25 != 0x00);
	struct Eq_49695 * edx_322 = SEQ(edx_24_8, dl_25);
	if (ax_232 < 0x00)
	{
		struct Eq_49695 * ebp_55 = (word32) *((word32) ecx + 20) + ~((int32) ax_232) * 0x08;
		int32 eax_56 = ebp_55->dw0000;
		ptr32 edi_60 = esi_14 - dwArg08;
		byte bl_62 = eax_56 + (edi_60 - 0x01);
		byte * eax_64 = eax_56 + (edi_60 - 0x01) + 0x01;
		struct Eq_49695 * edx_324 = SEQ(edx_24_8, dl_25);
		while (dl_25 != 0x00)
		{
			if (bl_62 != dl_25)
			{
				edx_324 = SEQ(edx_24_8, dl_25);
				if (dl_25 == 0x00)
					break;
				goto l006237B9;
			}
			dl_25 = (byte) *esi_14;
			bl_62 = *eax_64;
			esi_14 = (word32) esi_14 + 1;
			++eax_64;
			edx_324 = SEQ(edx_24_8, dl_25);
		}
		if (bl_62 != 0x00)
		{
l006237B9:
			if (dwArg0C != null)
				return fn006234C0(ecx, dwArg04, ebp_27, dwArg08, ebp_55, edi_60 - 0x01);
			struct Eq_49695 * edx_148 = *((word32) ecx + 24);
			*dwArg04 = (struct Eq_49695 **) edx_148;
			return edx_148;
		}
		else
		{
			if (dwArg0C != null)
				ebp_55->dw0004 = *dwArg0C;
			*dwArg04 = (struct Eq_49695 **) ebp_55;
			return edx_324;
		}
	}
	else
	{
		if (dwArg0C != null)
			return fn00623420(ecx, dwArg04, (word16) ebp_27, dwArg08, dl_25);
		*dwArg04 = (struct Eq_49695 **) *((word32) ecx + 24);
		return edx_322;
	}
}

// 00623840: void fn00623840(Register Eq_3 ecx, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08)
// Called from:
//      fn00623980
void fn00623840(Eq_3 ecx, Eq_3 dwArg04, Eq_3 dwArg08)
{
	ptr32 eax_13 = fs->ptr0000;
	fs->ptr0000 = fp - 0x10;
	if ((byte) (uint32) fn00621680(ecx, ecx, dwArg04, dwLoc30, dwArg04) != 0x00)
	{
		Eq_3 ebx_54 = *((word32) ecx + 4);
		fn00623280(ebx_54, dwArg04, dwArg08);
		*((word32) ecx + 8) = (word32) ebx_54 + (dwArg04 * 0x08 - dwArg04) * 0x04;
	}
	fs->ptr0000 = eax_13;
}

// 00623910: void fn00623910(Register Eq_3 ecx, Stack (ptr32 (ptr32 Eq_49695)) dwArg04)
// Called from:
//      fn00623E00
void fn00623910(Eq_3 ecx, struct Eq_49695 ** dwArg04)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	fn006236E0(ecx, dwArg04, c_str(fp + 0x08), null);
	~basic_string(fp + 0x08);
	fs->ptr0000 = eax_9;
}

// 00623980: void fn00623980(Register Eq_3 ecx, Stack Eq_3 dwArg04)
// Called from:
//      fn00623A00
void fn00623980(Eq_3 ecx, Eq_3 dwArg04)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	fn00623840(ecx, dwArg04, fp - 0x28);
	if (false)
		operator delete(null);
	fs->ptr0000 = eax_9;
}

// 00623A00: Register Eq_25053 fn00623A00(Register Eq_3 ecx, Register out Eq_3 edxOut)
// Called from:
//      fn00623E00
Eq_25053 fn00623A00(Eq_3 ecx, union Eq_3 & edxOut)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	Eq_25053 eax_1135 = fp - 0x0C;
	Eq_3 ecx_33 = *((word32) ecx + 48);
	Eq_3 edx_1147 = *((word32) ecx + 44);
	if (edx_1147 != ecx_33)
	{
		eax_1135.u0 = 0x00;
		if (false)
			eax_1135 = memmove_s(edx_1147, 0x00, ecx_33, 0x00);
		*((word32) ecx + 48) = edx_1147;
	}
	if (*((word32) ecx + 73) == 0x00)
	{
		Eq_3 eax_68;
		Eq_3 ecx_62 = *((word32) ecx + 28);
		Eq_3 ebx_213 = 0x00;
		if (ecx_62 == 0x00)
			eax_68.u0 = 0x00;
		else
			eax_68 = *((word32) ecx + 32) - ecx_62 >> 0x03;
		fn00623980(fp - 0x1C, eax_68);
		Eq_3 esi_152 = *((word32) ecx + 60);
		if (esi_152 != *((word32) ecx + 64))
		{
			Eq_3 ebp_217 = dwLoc18;
			do
			{
				byte * eax_101 = *esi_152;
				while (eax_101 != null)
				{
					byte cl_107 = *eax_101;
					if (cl_107 == 0x3C)
					{
						fn006236E0((word32) ecx + 8, fp - 0x30, eax_101 + 1, null);
						if (dwLoc30 != *((word32) ecx + 32))
						{
							int32 eax_183 = dwLoc30 - *((word32) ecx + 28);
							word32 edx_1200;
							fn00622470((word32) dwLoc18 + ((eax_183 >> 0x03) * 0x08 - (eax_183 >> 0x03)) * 0x04, esi_152, ecx, 0x01, ebx_213, out edx_1200);
						}
					}
					else if (cl_107 == 0x3E)
					{
						fn006236E0((word32) ecx + 8, fp - 0x34, eax_101 + 1, null);
						if (dwLoc34 != *((word32) ecx + 32))
						{
							word32 edx_1201;
							fn00622470(ebp_217, esi_152, ecx, 0x01, dwLoc34 - *((word32) ecx + 28) >> 0x03, out edx_1201);
						}
					}
					else
						fn00520C80();
					eax_101 = (byte *) *((word32) esi_152 + 4);
					esi_152 = (word32) esi_152 + 4;
				}
				esi_152 = (word32) esi_152 + 4;
				ebx_213 = (word32) ebx_213 + 1;
				ebp_217 = (word32) ebp_217 + 28;
			} while (esi_152 != *((word32) ecx + 64));
		}
		Eq_3 edx_228 = 0x00;
		Eq_3 dwLoc24_754 = 0x00;
		Eq_50261 ebx_237 = 0x00;
		while (true)
		{
			Eq_3 ecx_242 = *((word32) ecx + 28);
			if (ecx_242 == 0x00 || ebx_237 >= *((word32) ecx + 32) - ecx_242 >> 0x03)
				break;
			if (false && edx_228 >> 0x02 < 0x00)
			{
				*edx_228 = ebx_237;
				edx_228 = (word32) edx_228 + 4;
				dwLoc24_754 = edx_228;
				ebx_237 = (word32) ebx_237 + 1;
			}
			else
			{
				fn004119C0(fp - 44, 0x00, ecx, edx_228, 0x01);
				edx_228 = dwLoc24_754;
				ebx_237 = (word32) ebx_237.u1 + 1;
			}
		}
		Eq_50336 ebp_273;
		Eq_3 edi_276;
		ui32 esi_278[];
		eax_1135 = fn006235F0(0x00, edx_228, edx_228 >> 0x02, (word32) ecx + 8, out edx_1147, out ebp_273, out esi_278, out edi_276);
		Eq_50336 dwLoc30_761 = ebp_273;
		while (true)
		{
			Eq_3 ecx_288 = *((word32) edi_276 + 28);
			if (ecx_288 == 0x00)
				break;
			int32 eax_293 = *((word32) edi_276 + 32) - ecx_288;
			eax_1135 = eax_293 >> 0x03;
			if (dwLoc30_761 >= eax_293 >> 0x03)
				break;
			edx_1147 = *((word32) edi_276 + 28);
			Eq_25053 ecx_350 = 0x00;
			while (true)
			{
				ui32 ebx_369;
				if (edx_1147 == 0x00 || ecx_350 >= *((word32) edi_276 + 32) - edx_1147 >> 0x03)
					break;
				ebx_369 = esi_278[ecx_350];
				dwLoc38 = ebx_369;
				if (*((word32) dwLoc18 + ((ebx_369 * 0x08 - ebx_369) * 0x04 + 20)) == 0x00)
					goto l00623C48;
				ecx_350 = (word32) ecx_350.u0 + 1;
			}
			ebx_369 = dwLoc38;
l00623C48:
			if (edx_1147 == 0x00)
				eax_1135.u0 = 0x00;
			else
				eax_1135 = *((word32) edi_276 + 32) - edx_1147 >> 0x03;
			if (ecx_350 == eax_1135)
			{
				fn00520C80();
				if (esi_278 != null)
					operator delete(esi_278);
				if (dwLoc18 == 0x00)
					goto l00623DE0;
				if (dwLoc18 != dwLoc14)
				{
					struct Eq_50626 * esi_426 = (word32) dwLoc18 + 24;
					do
					{
						if (esi_426->dw0000 >= 0x04)
						{
							edx_1147 = esi_426->dwFFFFFFEC;
							operator delete(edx_1147);
						}
						esi_426->dw0000 = 0x03;
						esi_426->dwFFFFFFFC = 0x00;
						esi_426->dwFFFFFFEC = 0x00;
						++esi_426;
						eax_1135 = esi_426 - 0x18;
					} while (esi_426 - 0x18 != dwLoc14);
				}
				goto l00623DD8;
			}
			Eq_50498 ecx_501;
			Eq_3 edx_494 = *((word32) edi_276 + 44);
			Eq_3 esi_497 = (word32) edi_276 + 40;
			if (edx_494 == 0x00)
				ecx_501.u0 = 0x00;
			else
				ecx_501 = *((word32) edi_276 + 48) - edx_494 >> 0x02;
			if (edx_494 != 0x00 && ecx_501 < *((word32) edi_276 + 52) - edx_494 >> 0x02)
			{
				Eq_3 eax_545 = *((word32) edi_276 + 48);
				*eax_545 = ebx_369;
				*((word32) edi_276 + 48) = (word32) eax_545 + 4;
			}
			else
				fn004119C0((word32) edi_276 + 40, dwLoc18, edi_276, *((word32) edi_276 + 48), 0x01);
			Eq_50543 dwLoc34_898 = 0x00;
			struct Eq_50545 * ebp_556 = (word32) dwLoc18 + 20;
			while (true)
			{
				Eq_3 ecx_560 = *((word32) edi_276 + 28);
				if (ecx_560 == 0x00 || dwLoc34_898 >= *((word32) edi_276 + 32) - ecx_560 >> 0x03)
					break;
				esi_497.u0 = 0x00;
				if (ebp_556->t0000 > 0x00)
				{
					Eq_50586 ebx_604 = ebp_556 - 0x10;
					do
					{
						Eq_50586 eax_609;
						if (ebx_604.ptr0000->dw0014 >= 0x04)
							eax_609 = (Eq_50586) (&(&(&(&(&ebx_604.ptr0000->a0000[0].ptr0000.a0000)[0].ptr0000.a0000)[0].ptr0000.a0000)[0].ptr0000.a0000)[0].ptr0000.a0000)[0].ptr0000;
						else
							eax_609 = ebx_604;
						if (eax_609.ptr0000[esi_497 * 0x04 / 24] == dwLoc38)
						{
							fn00621800(ebp_556 - 0x14, edi_276, esi_497, 0x01);
							--esi_497;
						}
						esi_497 = (word64) esi_497.u0 + 1;
					} while (esi_497 < ebp_556->t0000);
					ebx_369 = dwLoc38;
				}
				dwLoc34_898 = (word32) dwLoc34_898.u1 + 1;
				++ebp_556;
			}
			eax_1135 = fn00622470((word32) dwLoc18 + (ebx_369 * 0x08 - ebx_369) * 0x04, esi_497, edi_276, 0x01, ~0x00, out edx_1147);
			dwLoc30_761 = (word32) dwLoc30_761.u1 + 1;
			esi_278 = null;
		}
		if (esi_278 != null)
			operator delete(esi_278);
		if (dwLoc18 != 0x00)
		{
			if (dwLoc18 != dwLoc14)
			{
				struct Eq_50466 * esi_318 = (word32) dwLoc18 + 24;
				do
				{
					if (esi_318->dw0000 >= 0x04)
						operator delete(esi_318->dwFFFFFFEC);
					esi_318->dw0000 = 0x03;
					esi_318->dwFFFFFFFC = 0x00;
					esi_318->dwFFFFFFEC = 0x00;
					++esi_318;
					edx_1147 = esi_318 - 0x18;
				} while (esi_318 - 0x18 != dwLoc14);
			}
l00623DD8:
			operator delete(dwLoc18);
		}
	}
l00623DE0:
	fs->ptr0000 = eax_9;
	edxOut = edx_1147;
	return eax_1135;
}

// 00623E00: void fn00623E00(Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn0042F170
//      fn00623E00
void fn00623E00(Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	ptr32 eax_9 = fs->ptr0000;
	ui32 eax_14 = g_tA14188 ^ fp - 0x50;
	fs->ptr0000 = fp - 0x0C;
	Eq_3 eax_44 = strchr(dwArg0C, 0x2F);
	Eq_3 ebp_143 = dwArg0C;
	Eq_3 edi_139 = dwArg04;
	Eq_3 esi_159 = eax_44;
	if (eax_44 != 0x00)
	{
		edi_139 = dwArg04;
		do
		{
			basic_string(fp - 44, ebp_143, esi_159 - ebp_143);
			basic_string(fp - 0x80, fp - 44);
			fn00623910((word32) edi_139 + 8, fp - 0x48);
			Eq_3 ebp_110 = 0x00;
			if (dwLoc48 == *((word32) edi_139 + 32))
			{
				struct Eq_49539 * eax_96 = operator new(0x4C);
				if (eax_96 != null)
					ebp_110 = fn00623340(eax_96, 0x00);
				c_str(fp - 44);
				fn00623E00(strchr, ebp_110, esi_159, edi_139, es, ds, edi_139, dwArg04, dwArg08);
				edi_139 = ebp_110;
			}
			else
				edi_139 = dwLoc48[1];
			~basic_string(fp - 44);
			ebp_143 = (word32) esi_159 + 1;
			Eq_3 eax_154 = strchr(ebp_143, 0x2F);
			esi_159 = eax_154;
		} while (eax_154 != 0x00);
	}
	Eq_3 esi_164 = 0x00;
	Eq_3 ebx_165 = 0x00;
	Eq_3 dwLoc34_752 = 0x00;
	struct Eq_50239 * edx_173 = fp + 0x0C + 0x04;
	do
	{
		word32 ecx_176 = edx_173->dw0000;
		struct Eq_50239 * edx_177 = edx_173 + 1;
		if (ebx_165 != 0x00 && esi_164 - ebx_165 >> 0x02 < 0x00 - ebx_165 >> 0x02)
		{
			*esi_164 = ecx_176;
			esi_164 = (word32) esi_164 + 4;
			dwLoc34_752 = esi_164;
		}
		else
		{
			fn0041DA20(fp - 0x3C, ebp_143, esi_164, edi_139, esi_164, 0x01);
			esi_164 = dwLoc34_752;
			ebx_165.u0 = 0x00;
		}
		edx_173 = edx_177;
	} while (ecx_176 != 0x00);
	Eq_3 eax_504;
	Eq_3 edx_243 = fn006236E0((word32) edi_139 + 8, fp - 0x50, ebp_143, null);
	if (edx_177 != *((word32) edi_139 + 32))
	{
		if (dwArg08 != 0x00 && dwArg08 != edx_177[1])
		{
			fn00520C80();
			eax_504 = dwArg0C;
			goto l006240F9;
		}
		Eq_50775 eax_395 = edx_177 - *((word32) edi_139 + 28);
		Eq_3 ebp_396 = *((word32) edi_139 + 60);
		int32 eax_397 = eax_395 >> 0x03;
		Eq_3 ecx_400 = ebp_396;
		if (eax_395 >> 0x03 > 0x00)
		{
			do
			{
				do
				{
					ecx_400 = (word32) ecx_977 + 4;
					ecx_977 = ecx_400;
				} while (*ecx_977 != 0x00);
				--eax_397;
			} while (eax_397 > 0x00);
		}
		Eq_3 edx_412 = ecx_400;
		do
		{
			edx_412 = (word32) edx_978 + 4;
			edx_978 = edx_412;
		} while (*edx_978 != 0x00);
		int32 esi_428 = ecx_400 - ebp_396;
		Eq_3 eax_434 = (word32) edi_139 + 56;
		if (ecx_400 != edx_412)
		{
			int32 eax_437 = *((word32) eax_434 + 8) - edx_412;
			Eq_25048 ebp_441 = (eax_437 >> 0x02) * 0x04;
			word32 ebx_442 = ecx_400 + ebp_441;
			if (eax_437 >> 0x02 > 0x00)
				memmove_s(ecx_400, ebp_441, edx_412, ebp_441);
			eax_434 = (word32) edi_139 + 56;
			*((word32) eax_434 + 8) = ebx_442;
			ebx_165.u0 = 0x00;
		}
		fn00622230(eax_434, edi_139, (word32) *((word32) edi_139 + 60) + (esi_428 >> 0x02) * 0x04, ebx_165, dwLoc34_752);
	}
	else
	{
		if (dwArg08 == 0x00)
		{
			struct Eq_49539 * eax_257 = operator new(0x4C);
			if (eax_257 != null)
				fn00623340(eax_257, ebp_143);
		}
		fn006236E0((word32) edi_139 + 8, fp - 0x50, ebp_143, fp - 0x44);
		*((word32) edi_139 + 28) != 0x00;
		fn00412E50((word32) edi_139 + 40, ebp_143, edi_139, fp - 0x50);
		fn00622230((word32) edi_139 + 56, edi_139, *((word32) edi_139 + 64), ebx_165, esi_164);
		Eq_3 esp_361 = <invalid>;
		if (*((word32) *((word32) esp_361 + 52) + 72) != 0x00)
		{
			<anonymous> *** ecx_370 = *((word32) esp_361 + 40);
			<anonymous> ** eax_371 = *ecx_370;
			(*eax_371)();
		}
	}
	eax_504 = fn00623A00(edi_139, out edx_243);
l006240F9:
	if (ebx_165 != 0x00)
		operator delete(ebx_165);
	fs->ptr0000 = eax_9;
	word32 ecx_976;
	fn00694B8E(eax_504, eax_14 ^ fp - 80, edx_243, ebx, ebp, esi, edi, es, ds, ebx, out ecx_976);
}

DWORD g_t6269E0(LPVOID lpThreadParameter) = ??/* Unexpected function type (fn DWORD (LPVOID)) */ ; // 006269E0
// 00626A30: Register Eq_3 fn00626A30(Register out ptr32 edxOut)
// Called from:
//      fn00626B20
//      fn00626B50
Eq_3 fn00626A30(ptr32 & edxOut)
{
	SetThreadAffinityMask(GetCurrentThread(), 0x01);
	g_bA67CA0 = 0x01;
	Eq_3 eax_39 = CreateThread(null, 0x00, &g_t6269E0, null, 0x00, fp - 0x28);
	Sleep(100);
	QueryPerformanceCounter(fp - 0x18);
	QueryPerformanceCounter(fp - 0x18);
	QueryPerformanceCounter(fp - 0x18);
	Eq_23784 edx_eax_62 = __rdtsc();
	Sleep(500);
	QueryPerformanceCounter(fp - 0x20);
	QueryPerformanceCounter(fp - 0x20);
	QueryPerformanceCounter(fp - 0x20);
	Eq_23784 edx_eax_85 = __rdtsc();
	QueryPerformanceFrequency(fp - 0x10);
	g_bA67CA0 = 0x00;
	CloseHandle(eax_39);
	ui64 ebx_ebp_157 = qwLoc20 - qwLoc18;
	ui64 edi_esi_159 = edx_eax_85 - edx_eax_62;
	Eq_3 edx_124;
	ptr32 edx_140;
	Eq_3 eax_138 = fn006951B0(fn00694FE0((word32) edi_esi_159, SLICE(edi_esi_159, word32, 32), dwLoc10, dwLoc0C, out edx_124), edx_124, (word32) ebx_ebp_157, SLICE(ebx_ebp_157, word32, 32), out edx_140);
	edxOut = edx_140;
	return eax_138;
}

// 00626B20: Register uint32 fn00626B20(Register out Eq_30343 edxOut)
// Called from:
//      fn0042ACF0
//      fn0042B310
uint32 fn00626B20(union Eq_30343 & edxOut)
{
	if ((g_tA67CB8 & 0x01) != 0x00)
	{
		uint32 eax_10 = g_dwA67CB0;
		edxOut = g_tA67CB4;
		return eax_10;
	}
	else
	{
		g_tA67CB8 |= 0x01;
		Eq_30343 edx_18;
		uint32 eax_16 = fn00626A30(out edx_18);
		g_dwA67CB0 = eax_16;
		g_tA67CB4 = edx_18;
		edxOut = edx_18;
		return eax_16;
	}
}

// 00626B50: FpuStack real64 fn00626B50()
// Called from:
//      fn00621380
real64 fn00626B50()
{
	if ((g_tA67CC8 & 0x01) != 0x00)
		return g_rA67CC0;
	g_tA67CC8 |= 0x01;
	if ((g_tA67CB8 & 0x01) == 0x00)
	{
		g_tA67CB8 |= 0x01;
		Eq_30343 edx_27;
		g_dwA67CB0 = fn00626A30(out edx_27);
		g_tA67CB4 = edx_27;
	}
	Eq_30343 eax_38 = g_tA67CB4;
	real64 rLoc1_66 = (real64) SEQ(eax_38 & 0x7FFFFFFF, g_dwA67CB0) + -((real64) SEQ(eax_38 & 0x80000000, 0x00));
	g_rA67CC0 = rLoc1_66;
	return rLoc1_66;
}

// 00629600: void fn00629600(Stack Eq_3 dwArg04)
// Called from:
//      fn00407670
//      fn0040CA60
//      fn00629600
void fn00629600(Eq_3 dwArg04)
{
	struct Eq_51161 * esp_10 = fp - 0x0C;
	Eq_3 edi_13 = dwArg04;
	Eq_3 esi_17 = dwArg04;
	if (*((word32) dwArg04 + 45) == 0x00)
	{
		do
		{
			struct Eq_51161 * esp_23 = esp_10 - 4;
			esp_23->t0000 = *((word32) esi_17 + 8);
			// Failed to bind call argument.
			// Please report this issue at https://github.com/uxmal/reko
			Eq_3 stackArg4 = <invalid>;
			fn00629600(stackArg4);
			esi_17 = *esi_17;
			~basic_string((word32) edi_13 + 0x0C);
			esp_23->tFFFFFFFC = edi_13;
			operator delete(esp_23->tFFFFFFFC);
			esp_10 = esp_23;
			edi_13 = esi_17;
		} while (*((word32) esi_17 + 45) == 0x00);
	}
}

