// sho_text_0029.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 00694B89: Register (ptr32 void) fn00694B89(Stack Eq_3 dwArg04)
// Called from:
//      fn00401080
//      fn0040A480
//      fn00417BC0
//      fn0041A830
//      fn0041A910
//      fn0041DF20
//      fn00623420
void * fn00694B89(Eq_3 dwArg04)
{
	return operator new(dwArg04);
}

// 00694B8E: Register Eq_3 fn00694B8E(Register Eq_3 eax, Register Eq_14 ecx, Register Eq_3 edx, Register Eq_3 ebx, Register Eq_3 ebp, Register Eq_3 esi, Register Eq_3 edi, Register (ptr16 Eq_7) es, Register (ptr16 Eq_8) ds, Stack Eq_3 dwArg00, Register out Eq_14 ecxOut)
// Called from:
//      fn00401080
//      fn00402150
//      fn004023A0
//      fn00402D20
//      fn00403200
//      fn00403420
//      fn00403570
//      fn00403950
//      fn00403F70
//      fn00404190
//      fn004046D0
//      fn00404FF0
//      fn00405370
//      fn0040CBA0
//      fn00413A20
//      fn0041EE00
//      fn00420190
//      fn004295F0
//      fn00429930
//      fn005A67A0
//      fn005A6DD0
//      fn005A7560
//      fn005A7E10
//      fn0061FB20
//      fn0061FD40
//      fn0061FD60
//      fn0061FD80
//      fn0061FD90
//      fn00623E00
//      fn00656570
//      fn00657290
//      fn00659040
//      fn006E1260
//      fn006E1400
//      fn006E1AB0
//      fn006E5590
//      fn006E7660
//      fn006E8060
//      fn006E8800
//      fn006F68F0
//      fn006F7890
//      fn006F8440
//      fn006F8960
//      fn006F8EC0
//      fn006FF4A0
//      fn00700EC0
//      fn00701650
//      fn00716A00
//      fn007189B0
//      fn007234D0
//      fn00723540
//      fn007272E0
//      fn00727910
//      fn0072F830
//      fn00735890
//      fn00736780
//      fn007367D0
//      fn00737880
//      fn0073B9B0
//      fn0073BBE0
//      fn00747960
//      fn00748310
//      fn00748E50
//      fn00752FC0
//      fn00753600
//      fn007544F0
Eq_3 fn00694B8E(Eq_3 eax, Eq_14 ecx, Eq_3 edx, Eq_3 ebx, Eq_3 ebp, Eq_3 esi, Eq_3 edi, struct Eq_7 * es, struct Eq_8 * ds, Eq_3 dwArg00, union Eq_14 & ecxOut)
{
	if (ecx != g_tA14188)
	{
		g_tA6B208 = eax;
		g_tA6B204 = ecx;
		g_tA6B200 = edx;
		g_tA6B1FC = ebx;
		g_tA6B1F8 = esi;
		g_tA6B1F4 = edi;
		g_ptrA6B220 = ss;
		g_ptrA6B214 = cs;
		g_ptrA6B1F0 = ds;
		g_ptrA6B1EC = es;
		g_ptrA6B1E8 = fs;
		g_ptrA6B1E4 = gs;
		g_tA6B218 = cond(fp - 0x032C) | SCZDOP;
		g_tA6B20C = ebp;
		g_tA6B210 = dwArg00;
		g_ptrA6B21C = fp + 0x04;
		g_dwA6B158 = 0x00010001;
		g_tA6B10C = g_tA6B210;
		g_dwA6B100 = 0xC0000409;
		g_dwA6B104 = 0x01;
		Eq_14 eax_55 = g_tA14188;
		ui32 eax_57 = g_dwA1418C;
		Eq_3 eax_59 = IsDebuggerPresent();
		g_tA6B150 = eax_59;
		union Eq_14 * esp_63;
		word32 edx_66;
		crt_debugger_hook();
		Eq_14 ecx_123 = *esp_63;
		*esp_63 = (union Eq_14 *) 0x00;
		SetUnhandledExceptionFilter(*esp_63);
		*esp_63 = (union Eq_14 *) 0x008CD010;
		Eq_3 eax_77 = UnhandledExceptionFilter(*esp_63);
		ptr32 esp_78 = (const char *) esp_63 + 4;
		if (g_tA6B150 == 0x00)
		{
			*esp_63 = (union Eq_14 *) 0x01;
			union Eq_14 * esp_83;
			crt_debugger_hook();
			ecx_123 = *esp_83;
			esp_78 = (const char *) esp_83 + 4;
		}
		struct Eq_52280 * esp_92 = esp_78 - 4;
		esp_92->t0000.u0 = 0xC0000409;
		esp_92->tFFFFFFFC = GetCurrentProcess();
		Eq_3 eax_97 = TerminateProcess(esp_92->tFFFFFFFC, esp_92->t0000);
		ecxOut = ecx_123;
		return eax_97;
	}
	else
	{
		ecxOut = ecx;
		return eax;
	}
}

// 00694BED: Register Eq_52316 fn00694BED(Register Eq_3 ebx, Register Eq_3 esi, Register Eq_3 edi, Register out Eq_52320 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
// Called from:
//      fn00694C8C
Eq_52316 fn00694BED(Eq_3 ebx, Eq_3 esi, Eq_3 edi, union Eq_52320 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	Eq_52316 eax_111;
	struct Eq_52325 * esp_80;
	struct Eq_52326 * ebp_13 = fn0069557C(ebx, esi, edi, dwLoc0C, 0x14);
	Eq_3 eax_22 = _decode_pointer(g_ptrA74B20);
	ebp_13->tFFFFFFE4 = eax_22;
	if (eax_22 == ~0x00)
	{
		eax_111 = _onexit(ebp_13->t0008);
		esp_80 = fp - 8;
	}
	else
	{
		struct Eq_52349 * esp_30;
		lock();
		void * ecx_35 = esp_30->ptr0000;
		ebp_13->dwFFFFFFFC = 0x00;
		esp_30->ptr0000 = g_ptrA74B20;
		ebp_13->tFFFFFFE4 = _decode_pointer(esp_30->ptr0000);
		esp_30->ptrFFFFFFFC = g_ptrA74B1C;
		ebp_13->tFFFFFFE0 = _decode_pointer(esp_30->ptrFFFFFFFC);
		esp_30->ptrFFFFFFF8 = ebp_13 - 0x20;
		esp_30->ptrFFFFFFF4 = ebp_13 - 0x1C;
		esp_30->tFFFFFFF0 = ebp_13->t0008;
		Eq_52316 eax_60 = __dllonexit(esp_30->tFFFFFFF0, esp_30->ptrFFFFFFF4, esp_30->ptrFFFFFFF8);
		ebp_13->tFFFFFFDC = eax_60;
		esp_30->tFFFFFFEC = ebp_13->tFFFFFFE4;
		struct Eq_52427 * esp_66;
		void * eax_67;
		encode_pointer();
		g_ptrA74B20 = eax_67;
		esp_66->tFFFFFFFC = ebp_13->tFFFFFFE0;
		word32 esp_75;
		void * eax_76;
		encode_pointer();
		g_ptrA74B1C = eax_76;
		ebp_13->dwFFFFFFFC = ~0x01;
		fn00694C83();
		esp_80 = esp_75 + 0x1C;
		eax_111 = ebp_13->tFFFFFFDC;
	}
	ptr32 ebp_96;
	ptr32 edi_99;
	ptr32 esi_100;
	ebxOut = fn006955C1(ebp_13, esp_80->ptrFFFFFFFC, out ebp_96, out esi_100, out edi_99);
	ebpOut = ebp_96;
	esiOut = esi_100;
	ediOut = edi_99;
	return eax_111;
}

// 00694C83: void fn00694C83()
// Called from:
//      fn00694BED
void fn00694C83()
{
	unlock();
}

// 00694C8C: Register Eq_3 fn00694C8C(Register Eq_3 ebx, Register Eq_3 esi, Register Eq_3 edi, Register out ptr32 ebpOut, Register out (ptr32 Eq_6294) esiOut, Register out ptr32 ediOut)
// Called from:
//      fn004048C0
//      fn0043D330
//      fn0045E0B0
//      fn0046E360
//      fn005A74F0
//      fn00621380
//      fn006233B0
//      fn0081DDF0
Eq_3 fn00694C8C(Eq_3 ebx, Eq_3 esi, Eq_3 edi, ptr32 & ebpOut, struct Eq_6294 & esiOut, ptr32 & ediOut)
{
	ptr32 ebp_13;
	Eq_3 ebx_14;
	ptr32 edi_16;
	struct Eq_6294 * esi_17;
	fn00694BED(ebx, esi, edi, out ebx_14, out ebp_13, out esi_17, out edi_16);
	ebpOut = ebp_13;
	esiOut = esi_17;
	ediOut = edi_16;
	return ebx_14;
}

// 00694FAA: Register Eq_3 Win32CrtStartup()
Eq_3 Win32CrtStartup()
{
	fn00695766();
	struct Eq_52326 * ebp_138 = fn0069557C(ebx, esi, edi, dwLoc0C, 88);
	ebp_138->tFFFFFFE4.u0 = 0x00;
	ebp_138->dwFFFFFFFC = 0x00;
	GetStartupInfoA(ebp_138 - 0x68);
	ebp_138->dwFFFFFFFC = ~0x01;
	ebp_138->dwFFFFFFFC = 0x01;
	Eq_3 ebx_106 = 0x00;
	Eq_3 esi_35 = fs->ptr0018->t0004;
	Eq_3 edi_141 = 0x00A74B14;
	while (true)
	{
		Eq_3 dwLoc0C_439 = 0x00;
		Eq_3 eax_46 = InterlockedCompareExchange(&g_tA74B14, esi_35, 0x00);
		if (eax_46 == 0x00)
			break;
		if (eax_46 == esi_35)
		{
			ebx_106.u0 = 0x01;
			break;
		}
		Sleep(1000);
	}
	if (g_dwA74B10 == 0x01)
		_amsg_exit(0x1F);
	Eq_3 eax_330;
	struct Eq_52552 * esp_313;
	if (g_dwA74B10 == 0x00)
	{
		g_dwA74B10 = 0x01;
		dwLoc0C_439.u0 = 0x008A68E0;
		esp_313 = fp - 0x08;
		if (_initterm_e(&g_t8A68D4, &g_t8A68E0) != 0x00)
		{
			ebp_138->dwFFFFFFFC = ~0x01;
			eax_330.u0 = 0xFF;
			goto l00694EC2;
		}
	}
	else
		g_dwA6B0F0 = 0x01;
	if (g_dwA74B10 == 0x01)
	{
		_initterm(&g_t8A4A48, &g_t8A68D0);
		g_dwA74B10 = 0x02;
		dwLoc0C_439.u0 = 9070800;
	}
	if (ebx_106 == 0x00)
	{
		InterlockedExchange(&g_tA74B14, ebx_106);
		dwLoc0C_439 = ebx_106;
	}
	struct Eq_52615 * esp_125 = fp - 0x08;
	if (g_ptrA74B18 != null)
	{
		dwLoc0C_439.u0 = 10963736;
		esp_125 = fp - 0x08;
		if (fn006956C2(ebx_106, 0x01, 0x00A74B14, out ebx_106, out ebp_138, out edi_141) != 0x00)
		{
			word32 edx_168;
			g_ptrA74B18();
			dwLoc0C_439.u0 = 0x00;
		}
	}
	Eq_3 esi_172 = *acmdln;
	while (true)
	{
		ebp_138->tFFFFFFE0 = esi_172;
		cu8 al_176 = *esi_172;
		if (al_176 <= 0x20 && (al_176 == 0x00 || ebp_138->tFFFFFFE4 == 0x00))
			break;
		if (al_176 == 0x22)
			ebp_138->tFFFFFFE4 = (uint32) (int8) (ebp_138->tFFFFFFE4 == 0x00);
		word32 eax_197 = (word32) al_176;
		esp_125->dwFFFFFFFC = eax_197;
		word32 esp_217;
		word32 eax_218;
		word32 edx_221;
		ismbblead();
		esp_125 = esp_217 + 4;
		if (eax_218 != 0x00)
		{
			esi_172 = (word32) esi_172 + 1;
			ebp_138->tFFFFFFE0 = esi_172;
		}
		esi_172 = (word32) esi_172 + 1;
	}
	while (true)
	{
		cu8 al_237 = *esi_172;
		if (al_237 == 0x00 || al_237 > 0x20)
			break;
		esi_172 = (word32) esi_172 + 1;
		ebp_138->tFFFFFFE0 = esi_172;
	}
	int32 eax_253;
	if ((ebp_138->bFFFFFFC4 & 0x01) != 0x00)
		eax_253 = (word32) ebp_138->wFFFFFFC8;
	else
	{
		int32 * esp_251 = esp_125 - 4;
		*esp_251 = 0x0A;
		eax_253 = *esp_251;
	}
	struct Eq_52702 * esp_257 = esp_125 - 4;
	esp_257->dw0000 = eax_253;
	esp_257->tFFFFFFFC = esi_172;
	esp_257->dwFFFFFFF8 = 0x00;
	esp_257->tFFFFFFF4 = (Eq_410) &g_t400000;
	Eq_3 esp_302 = <invalid>;
	Eq_3 eax_295 = fn004014B0(ebx_106, esi_172, edi_141, es, ds, xmm0, esp_257->tFFFFFFF4, esp_257->tFFFFFFFC, esp_257->dw0000, out ebp_138);
	g_tA6B0EC = eax_295;
	esp_313 = (word32) esp_302 + 16;
	if (g_dwA6B0E0 == 0x00)
	{
		*((word32) esp_302 + 0x0C) = eax_295;
		exit(*((word32) esp_302 + 0x0C));
	}
	if (g_dwA6B0F0 == 0x00)
	{
		word32 edx_326;
		cexit();
	}
	ebp_138->dwFFFFFFFC = ~0x01;
	eax_330 = g_tA6B0EC;
l00694EC2:
	word32 ebp_346;
	word32 edi_349;
	word32 esi_350;
	fn006955C1(ebp_138, esp_313->ptrFFFFFFFC, out ebp_346, out esi_350, out edi_349);
	return eax_330;
}

// 00694FE0: Register word32 fn00694FE0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10, Register out ptr32 edxOut)
// Called from:
//      fn0042ACF0
//      fn00626A30
//      fn00711700
word32 fn00694FE0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10, ptr32 & edxOut)
{
	if ((dwArg10 | dwArg08) != 0x00)
	{
		uint64 edx_eax_23 = dwArg0C *64 dwArg04;
		edxOut = SLICE(edx_eax_23, word32, 32) + (word32) (dwArg0C *64 dwArg08 + dwArg10 *64 dwArg04);
		return (word32) edx_eax_23;
	}
	else
	{
		uint64 edx_eax_30 = dwArg0C *64 dwArg04;
		edxOut = SLICE(edx_eax_30, word32, 32);
		return (word32) edx_eax_30;
	}
}

// 00695040: Register int32 fn00695040(FpuStack real64 rArg0)
// Called from:
//      fn007120F0
int32 fn00695040(real64 rArg0)
{
	if (g_dwA74B08 == 0x00)
	{
		__align(fp - 0x24);
		int64 qwLoc14_90 = (int64) rArg0;
		int32 dwLoc14_92 = (word32) qwLoc14_90;
		Eq_52847 dwLoc10_93 = SLICE(qwLoc14_90, word32, 32);
		real64 rLoc1_91 = (real64) qwLoc14_90;
		Eq_52847 edx_21 = (real32) rArg0;
		int32 eax_112 = dwLoc14_92;
		if (dwLoc14_92 == 0x00)
		{
			edx_21 = dwLoc10_93;
			if ((dwLoc10_93 & 0x7FFFFFFF) == 0x00)
				return eax_112;
		}
		real64 rArg0_98 = rArg0 - rLoc1_91;
		if (edx_21 < 0x00)
			eax_112 = (int32) ((bool) (((real32) rArg0_98 ^ 0x80000000) < 0x7FFFFFFF) + dwLoc14_92);
		else
			eax_112 = dwLoc14_92 - ((real32) rArg0_98 < 0x7FFFFFFF);
		return eax_112;
	}
	else
	{
		__align(fp - 0x0C);
		return (int32) rArg0;
	}
}

// 006951B0: Register uint32 fn006951B0(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C, Stack Eq_3 dwArg10, Register out Eq_30422 edxOut)
// Called from:
//      fn0042ACF0
//      fn0042B310
//      fn00626A30
uint32 fn006951B0(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C, Eq_3 dwArg10, union Eq_30422 & edxOut)
{
	uint32 eax_110;
	Eq_30422 edx_114;
	if (dwArg10 == 0x00)
	{
		uint64 edx_eax_69 = (uint64) dwArg08;
		eax_110 = (uint32) (SEQ((uint32) (edx_eax_69 % dwArg0C), dwArg04) /u dwArg0C);
		edx_114.u0 = (uint32) (edx_eax_69 /u dwArg0C);
	}
	else
	{
		Eq_3 ecx_15 = dwArg10;
		Eq_3 ebx_16 = dwArg0C;
		Eq_3 edx_17 = dwArg08;
		Eq_3 eax_18 = dwArg04;
		do
		{
			Eq_3 ecx_20 = ecx_15 >> 0x01;
			edx_17 >>= 0x01;
			ebx_16 = __rcr(ebx_16, 0x01, SLICE(cond(ecx_20), bool, 1));
			eax_18 = __rcr(eax_18, 0x01, SLICE(cond(edx_17), bool, 1));
			ecx_15 = ecx_20;
		} while (ecx_20 != 0x00);
		uint32 eax_39 = (uint32) (SEQ(edx_17, eax_18) /u ebx_16);
		uint64 edx_eax_47 = eax_39 *64 dwArg0C;
		uint32 esi_40 = eax_39;
		Eq_3 eax_55 = (word32) edx_eax_47;
		Eq_3 edx_49 = SLICE(edx_eax_47, word32, 32) + (word32) (dwArg10 *64 eax_39);
		if (edx_49 < 0x00 || (edx_49 > dwArg08 || edx_49 >= dwArg08 && eax_55 > dwArg04))
			esi_40 = eax_39 - 0x01;
		edx_114.u0 = 0x00;
		eax_110 = esi_40;
	}
	edxOut = edx_114;
	return eax_110;
}

// 006952A0: void fn006952A0(Register ui32 eax, Stack word32 dwArg00)
// Called from:
//      fn00737880
//      fn0082ABF0
void fn006952A0(ui32 eax, word32 dwArg00)
{
	Eq_52942 ecx_9 = fp - eax;
	word32 * ecx_14 = ecx_9 & ~(0x00 - (ecx_9 < 0x00));
	word32 * eax_16;
	for (eax_16 = fp - 4 & ~0x0FFF; ecx_14 < eax_16; eax_16 -= 0x1000)
		;
	*ecx_14 = dwArg00;
}

// 0069557C: Register ptr32 fn0069557C(Register Eq_3 ebx, Register Eq_3 esi, Register Eq_3 edi, Stack word32 dwArg00, Stack ui32 dwArg08)
// Called from:
//      fn00694BED
//      Win32CrtStartup
//      fn006956C2
ptr32 fn0069557C(Eq_3 ebx, Eq_3 esi, Eq_3 edi, word32 dwArg00, ui32 dwArg08)
{
	struct Eq_52964 * esp_14 = fp - 8 - dwArg08;
	esp_14->tFFFFFFFC = ebx;
	esp_14->tFFFFFFF8 = esi;
	esp_14->tFFFFFFF4 = edi;
	esp_14->dwFFFFFFF0 = g_tA14188 ^ fp + 0x08;
	esp_14->dwFFFFFFEC = dwArg00;
	fs->ptr0000 = fp - 0x08;
	return fp + 0x08;
}

// 006955C1: Register word32 fn006955C1(Register (ptr32 Eq_52326) ebp, Stack ptr32 dwArg00, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
// Called from:
//      fn00694BED
//      Win32CrtStartup
//      fn006956C2
word32 fn006955C1(struct Eq_52326 * ebp, ptr32 dwArg00, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	fs->dw0000 = ebp->dwFFFFFFF0;
	ptr32 ebp_19 = ebp->ptr0000;
	ebp->ptr0000 = dwArg00;
	ebpOut = ebp_19;
	esiOut = dwArg0C;
	ediOut = dwArg08;
	return dwArg10;
}

// 00695650: Register uint32 fn00695650(Stack (ptr32 Eq_53013) dwArg04)
// Called from:
//      fn006956C2
uint32 fn00695650(struct Eq_53013 * dwArg04)
{
	if (dwArg04->w0000 != 23117)
		return 0x00;
	struct Eq_53019 * eax_9 = dwArg04 + dwArg04->dw003C / 64;
	if (eax_9->dw0000 != 0x4550)
		return 0x00;
	return (uint32) (int8) (eax_9->w0018 == 0x010B);
}

// 00695680: Register (ptr32 Eq_53037) fn00695680(Stack (ptr32 Eq_53038) dwArg04, Stack up32 dwArg08)
// Called from:
//      fn006956C2
struct Eq_53037 * fn00695680(struct Eq_53038 * dwArg04, up32 dwArg08)
{
	struct Eq_53040 * ecx_7 = dwArg04 + dwArg04->dw003C / 64;
	up32 esi_15 = (word32) ecx_7->w0006;
	up32 edx_16 = 0x00;
	struct Eq_53037 * eax_22 = ecx_7 + ((word32) ecx_7->w0014 + 0x18) / 22;
	if (esi_15 > 0x00)
	{
		do
		{
			up32 ecx_28 = eax_22->dw000C;
			if (dwArg08 >= ecx_28 && dwArg08 < eax_22->dw0008 + ecx_28)
				return eax_22;
			++edx_16;
			++eax_22;
		} while (edx_16 < esi_15);
	}
	eax_22 = null;
	return eax_22;
}

// 006956C2: Register ui32 fn006956C2(Register Eq_3 ebx, Register Eq_3 esi, Register Eq_3 edi, Register out Eq_52320 ebxOut, Register out (ptr32 Eq_52643) ebpOut, Register out ptr32 ediOut)
// Called from:
//      Win32CrtStartup
ui32 fn006956C2(Eq_3 ebx, Eq_3 esi, Eq_3 edi, union Eq_52320 & ebxOut, struct Eq_52643 & ebpOut, ptr32 & ediOut)
{
	ui32 eax_59;
	struct Eq_52326 * ebp_13 = fn0069557C(ebx, esi, edi, dwLoc0C, 0x08);
	ebp_13->dwFFFFFFFC = 0x00;
	ptr32 dwLoc0C_84 = 0x00400000;
	if (fn00695650(&g_t400000) != 0x00)
	{
		Eq_52316 eax_36 = ebp_13->t0008;
		dwLoc0C_84 = eax_36 - 0x00400000;
		struct Eq_53108 * eax_43 = fn00695680(&g_t400000, eax_36 - 0x00400000);
		if (eax_43 != null)
		{
			eax_59 = ~(eax_43->dw0024 >> 0x1F) & 0x01;
			ebp_13->dwFFFFFFFC = ~0x01;
l00695728:
			struct Eq_52643 * ebp_75;
			ptr32 edi_78;
			word32 esi_107;
			ebxOut = fn006955C1(ebp_13, dwLoc0C_84, out ebp_75, out esi_107, out edi_78);
			ebpOut = ebp_75;
			ediOut = edi_78;
			return eax_59;
		}
	}
	ebp_13->dwFFFFFFFC = ~0x01;
	eax_59 = 0x00;
	goto l00695728;
}

// 00695766: void fn00695766()
// Called from:
//      Win32CrtStartup
void fn00695766()
{
	Eq_14 eax_9 = g_tA14188;
	if (eax_9 != 0xBB40E64E && (eax_9 & 0xFFFF0000) != 0x00)
		g_dwA1418C = ~eax_9;
	else
	{
		GetSystemTimeAsFileTime(fp - 0x0C);
		ui32 esi_46 = GetCurrentProcessId() ^ GetCurrentThreadId() ^ GetTickCount();
		QueryPerformanceCounter(fp - 0x14);
		Eq_14 esi_54 = esi_46 ^ (dwLoc10 ^ dwLoc14);
		if (esi_54 == 0xBB40E64E)
			&esi_54.u0->ExceptionRecord = ~0x44BF19B0;
		else if ((esi_54 & 0xFFFF0000) == 0x00)
			esi_54 |= esi_54 << 0x10;
		g_tA14188 = esi_54;
		g_dwA1418C = ~esi_54;
	}
}

// 00697A30: void fn00697A30(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn005A5950
//      fn00697E60
void fn00697A30(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ecx_30 = dwArg08;
	if (dwArg08 > 0x00)
	{
		Eq_3 eax_11 = dwArg04;
		do
		{
			if (eax_11 != 0x00)
			{
				*eax_11 = *dwArg0C;
				*((word32) eax_11 + 4) = *((word32) dwArg0C + 4);
				*((word32) eax_11 + 8) = *((word32) dwArg0C + 8);
				*((word32) eax_11 + 0x0C) = *((word32) dwArg0C + 0x0C);
			}
			--ecx_30;
			eax_11 = (word32) eax_11 + 16;
		} while (ecx_30 > 0x00);
	}
}

// 00697E60: Register ui32 fn00697E60(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn005A5370
ui32 fn00697E60(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	fn00697A30(dwArg04, dwArg08, dwArg0C);
	return (word32) dwArg04 + (dwArg08 << 0x04);
}

