// sho_text_0041.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 008119C0: Register (ptr32 Eq_178412) fn008119C0(Stack (ptr32 Eq_42671) dwArg04, Stack (ptr32 Eq_42671) dwArg08, Stack (ptr32 word32) dwArg0C)
// Called from:
//      fn005B61E0
//      fn005B62A0
struct Eq_178412 * fn008119C0(struct Eq_42671 * dwArg04, struct Eq_42671 * dwArg08, word32 * dwArg0C)
{
	struct Eq_178412 * eax_6 = operator new(0x0C);
	if (eax_6 != null)
		eax_6->ptr0000 = dwArg04;
	if (eax_6 != (struct Eq_178412 *) 0x04)
		eax_6->ptr0004 = dwArg08;
	if (eax_6 != (struct Eq_178412 *) 0x08)
		eax_6->dw0008 = *dwArg0C;
	return eax_6;
}

// 00811B80: Register (ptr32 Eq_178437) fn00811B80()
// Called from:
//      fn00406B00
//      fn00407CD0
//      fn0040D620
//      fn0042B310
struct Eq_178437 * fn00811B80()
{
	struct Eq_178437 * eax_6 = operator new(0x30);
	if (eax_6 != null)
		eax_6->dw0000 = 0x00;
	if (eax_6 != (struct Eq_178437 *) 0x04)
		eax_6->dw0004 = 0x00;
	if (eax_6 != (struct Eq_178437 *) 0x08)
		eax_6->dw0008 = 0x00;
	eax_6->b002C = 0x01;
	eax_6->b002D = 0x00;
	return eax_6;
}

// 0081DDF0: Register word32 fn0081DDF0(Register Eq_3 ebx, Register Eq_3 esi, Register Eq_3 edi, Register Eq_409 xmm0, Register out Eq_3 ebxOut, Register out (ptr32 ptr32) ebpOut, Register out Eq_3 esiOut, Register out Eq_3 ediOut, Register out Eq_409 xmm0Out)
// Called from:
//      fn00420510
//      fn0042ACF0
//      fn0042DF20
word32 fn0081DDF0(Eq_3 ebx, Eq_3 esi, Eq_3 edi, Eq_409 xmm0, union Eq_3 & ebxOut, ptr32 & ebpOut, union Eq_3 & esiOut, union Eq_3 & ediOut, union Eq_409 & xmm0Out)
{
	ptr32 eax_9 = fs->ptr0000;
	fs->ptr0000 = fp - 0x0C;
	if ((g_tA7487C & 0x01) == 0x00)
	{
		g_tA7487C |= 0x01;
		g_dwA74860 = 0x00;
		g_dwA74864 = 0x00;
		g_dwA74868 = 0x00;
		xmm0 = __xorps(xmm0, xmm0);
		g_dwA74870 = 0x00;
		g_dwA74874 = 0x00;
		g_dwA74878 = 0x00;
		g_rA74850 = (real32) xmm0;
		g_rA7484C = (real32) xmm0;
		g_rA74858 = (real32) xmm0;
		g_dwA74854 = 0x00;
		ebx = fn00694C8C(ebx, esi, edi, out ebp, out esi, out edi);
	}
	fs->ptr0000 = eax_9;
	ebxOut = ebx;
	ebpOut = ebp;
	esiOut = esi;
	ediOut = edi;
	xmm0Out = xmm0;
	return 0x00A74848;
}

// 0081DE90: Register byte fn0081DE90(Register (ptr32 Eq_26000) ecx, Register Eq_3 ebp, Register Eq_3 edi, Stack Eq_26015 rArg04, Register out Eq_26076 xmm0Out)
// Called from:
//      fn00420510
byte fn0081DE90(struct Eq_26000 * ecx, Eq_3 ebp, Eq_3 edi, Eq_26015 rArg04, union Eq_26076 & xmm0Out)
{
	Eq_3 eax_9 = ecx->t0000;
	if (eax_9 != 0x01)
	{
		if (eax_9 == 0x02)
		{
			uint128 xmm0_14 = (uint128) ecx->t0004;
			uint128 xmm1_15 = (uint128) rArg04;
			Eq_178545 v17_18 = (real32) xmm0_14 + (real32) xmm1_15;
			Eq_178545 edx_16[] = ecx->ptr0018;
			int32 ecx_17 = ecx->dw000C;
			ecx->t0004 = v17_18;
			ecx->r0008 = (real32) xmm1_15;
			xmm0 = SEQ(SLICE(xmm0_14, word96, 32), v17_18);
			if (v17_18 >= edx_16[ecx_17])
			{
				do
				{
					int32 eax_36;
					if (edx_16 == null)
						eax_36 = 0x00;
					else
						eax_36 = ecx->dw001C - edx_16 >> 0x02;
					int32 ecx_43 = ecx->dw000C;
					if (ecx_43 >= eax_36)
						break;
					ecx->dw000C = ecx_43 + 0x01;
				} while ((real32) (uint128) ecx->t0004 >= edx_16[ecx_43 + 0x01]);
			}
			int32 ecx_66;
			if (edx_16 == null)
				ecx_66 = 0x00;
			else
				ecx_66 = ecx->dw001C - edx_16 >> 0x02;
			int32 eax_73 = ecx->dw000C;
			if (eax_73 < ecx_66)
			{
				uint128 xmm1_89 = (uint128) (edx_16 - 0x04)[eax_73];
				ecx->r0010 = (v17_18 - (real32) xmm1_89) / ((real32) ((uint128) edx_16[eax_73]) - (real32) xmm1_89);
				g_dwA74840 = eax_73;
				Eq_26076 xmm0_106 = (uint128) ecx->r0010;
				g_rA74844 = (real32) xmm0_106;
				xmm0Out = xmm0_106;
				return 0x01;
			}
		}
		xmm0Out = xmm0;
		return 0x00;
	}
	else
	{
		uint128 xmm1_112 = (uint128) ecx->t0004;
		++ecx->dw000C;
		Eq_409 xmm0_111 = (uint128) rArg04;
		ecx->r0008 = (real32) xmm0_111;
		Eq_409 xmm0_123 = __xorps(xmm0_111, xmm0_111);
		ecx->t0004 = (real32) xmm1_112 + (real32) xmm0_111;
		ecx->r0010 = (real32) xmm0_123;
		fn00412EA0(&ecx->r0010 + 1, ebp, edi, &ecx->t0004);
		int32 eax_141 = ecx->dw000C;
		g_dwA74840 = eax_141;
		Eq_26076 xmm0_143 = (uint128) ecx->r0010;
		g_rA74844 = (real32) xmm0_143;
		xmm0Out = xmm0_143;
		return 0x01;
	}
}

