// sho_data_0005.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

Eq_34677 g_tA5E0EA = // 00A5E0EA
	{
		0x00,
		0x00,
		0x00,
	};
Eq_179419 g_aA622E8[] = // 00A622E8
	{
	};
Eq_34677 g_tA622EA = // 00A622EA
	{
		0x00,
		0x00,
		0x00,
	};
int8 g_bA62978 = 0; // 00A62978
Eq_41148 g_tA62BE0 = // 00A62BE0
	{
		0x00
	};
byte g_bA62BE4 = 0x00; // 00A62BE4
int32 g_dwA62BE8 = 0; // 00A62BE8
struct Eq_42709 * g_ptrA62CC8 = null; // 00A62CC8
struct Eq_42670 * g_ptrA62CCC = null; // 00A62CCC
struct Eq_42931 * g_ptrA62CD0 = null; // 00A62CD0
struct Eq_42812 * g_ptrA62CD4 = null; // 00A62CD4
word32 g_dwA67638 = 0x00; // 00A67638
word32 * g_ptrA67640 = null; // 00A67640
word32 * g_ptrA67644 = null; // 00A67644
word16 g_wA67B60 = 0x00; // 00A67B60
Eq_44527 g_tA67B64 = // 00A67B64
	{
	};
byte g_bA67BA8 = 0x00; // 00A67BA8
int32 g_dwA67BEC = 0; // 00A67BEC
Eq_3 g_tA67BF0 = // 00A67BF0
	{
		0x00
	};
int32 g_dwA67BF4 = 0; // 00A67BF4
Eq_3 g_tA67BF8 = // 00A67BF8
	{
		0x00
	};
byte g_bA67BFC = 0x00; // 00A67BFC
Eq_3 g_tA67C00 = // 00A67C00
	{
		0x00
	};
Eq_49539 g_tA67C08 = // 00A67C08
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_49609 g_tA67C54 = // 00A67C54
	{
		0x00
	};
word32 g_dwA67C98 = 0x00; // 00A67C98
byte g_bA67CA0 = 0x00; // 00A67CA0
uint32 g_dwA67CB0 = 0x00; // 00A67CB0
Eq_30343 g_tA67CB4 = // 00A67CB4
	{
		0x00
	};
Eq_51081 g_tA67CB8 = // 00A67CB8
	{
		0x00
	};
real64 g_rA67CC0 = 0.0; // 00A67CC0
Eq_51109 g_tA67CC8 = // 00A67CC8
	{
		0x00
	};
byte g_bA696D0 = 0x00; // 00A696D0
Eq_179415 g_aA69720[] = // 00A69720
	{
	};
byte g_bA6973D = 0x00; // 00A6973D
byte g_bA6974A = 0x00; // 00A6974A
byte g_bA69756 = 0x00; // 00A69756
byte g_bA69758 = 0x00; // 00A69758
byte g_bA697BD = 0x00; // 00A697BD
byte g_bA697D8 = 0x00; // 00A697D8
int8 g_bA69858 = 0; // 00A69858
struct Eq_51266 ** g_ptrA69A38 = null; // 00A69A38
word32 g_dwA6B0E0 = 0x00; // 00A6B0E0
Eq_3 g_tA6B0EC = // 00A6B0EC
	{
		0x00
	};
word32 g_dwA6B0F0 = 0x00; // 00A6B0F0
ui32 g_dwA6B0F4 = 0x00; // 00A6B0F4
word32 g_dwA6B100 = 0x00; // 00A6B100
word32 g_dwA6B104 = 0x00; // 00A6B104
Eq_3 g_tA6B10C = // 00A6B10C
	{
		0x00
	};
Eq_3 g_tA6B150 = // 00A6B150
	{
		0x00
	};
word32 g_dwA6B158 = 0x00; // 00A6B158
struct Eq_52198 * g_ptrA6B1E4 = null; // 00A6B1E4
struct Eq_52195 * g_ptrA6B1E8 = null; // 00A6B1E8
struct Eq_7 * g_ptrA6B1EC = null; // 00A6B1EC
struct Eq_8 * g_ptrA6B1F0 = null; // 00A6B1F0
Eq_3 g_tA6B1F4 = // 00A6B1F4
	{
		0x00
	};
Eq_3 g_tA6B1F8 = // 00A6B1F8
	{
		0x00
	};
Eq_3 g_tA6B1FC = // 00A6B1FC
	{
		0x00
	};
Eq_3 g_tA6B200 = // 00A6B200
	{
		0x00
	};
Eq_14 g_tA6B204 = // 00A6B204
	{
		null
	};
Eq_3 g_tA6B208 = // 00A6B208
	{
		0x00
	};
Eq_3 g_tA6B20C = // 00A6B20C
	{
		0x00
	};
Eq_3 g_tA6B210 = // 00A6B210
	{
		0x00
	};
struct Eq_52188 * g_ptrA6B214 = null; // 00A6B214
Eq_52206 g_tA6B218 = // 00A6B218
	{
		0x00
	};
ptr32 g_ptrA6B21C = 0x00; // 00A6B21C
struct Eq_52185 * g_ptrA6B220 = null; // 00A6B220
Eq_3 g_tA6C30C = // 00A6C30C
	{
		0x00
	};
Eq_3 g_tA6C4D0 = // 00A6C4D0
	{
		0x00
	};
Eq_3 g_aA6C4D4[20] = // 00A6C4D4
	{
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
	};
word32 g_dwA6C520 = 0x00; // 00A6C520
Eq_59842 g_tA6C570 = null; // 00A6C570
Eq_3 g_tA6C578 = // 00A6C578
	{
		0x00
	};
<anonymous> * g_aA6C598[] = // 00A6C598
	{
	};
word32 g_dwA6C618 = 0x00; // 00A6C618
word32 g_dwA6C61C = 0x00; // 00A6C61C
Eq_3 g_tA6C620 = // 00A6C620
	{
		0x00
	};
word32 g_dwA6C624 = 0x00; // 00A6C624
int32 g_dwA6C62C = 0; // 00A6C62C
Eq_3 g_tA6C630 = // 00A6C630
	{
		0x00
	};
Eq_3 g_tA6C638 = // 00A6C638
	{
		0x00
	};
Eq_3 g_tA6C63C = // 00A6C63C
	{
		0x00
	};
struct Eq_69119 * g_aA6C640[257] = // 00A6C640
	{
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
	};
Eq_3 g_aA6CA3C[] = // 00A6CA3C
	{
	};
struct Eq_69119 * g_ptrA6CA40 = null; // 00A6CA40
ui32 g_dwA6CB80 = 0x00; // 00A6CB80
Eq_3 g_tA6CB84 = // 00A6CB84
	{
		0x00
	};
Eq_3 g_tA6CB88 = // 00A6CB88
	{
		0x00
	};
Eq_3 g_tA6CB8C = // 00A6CB8C
	{
		0x00
	};
Eq_3 g_tA6CB90 = // 00A6CB90
	{
		0x00
	};
word32 g_dwA6CB94 = 0x00; // 00A6CB94
Eq_3 g_tA6CB98 = // 00A6CB98
	{
		0x00
	};
Eq_3 g_tA6CB9C = // 00A6CB9C
	{
		0x00
	};
Eq_3 g_tA6CBA0 = // 00A6CBA0
	{
		0x00
	};
Eq_3 g_tA6CBA4 = // 00A6CBA4
	{
		0x00
	};
Eq_3 g_tA6CBA8 = // 00A6CBA8
	{
		0x00
	};
Eq_3 g_tA6CBB0 = // 00A6CBB0
	{
		0x00
	};
Eq_3 g_aA6CBB4[] = // 00A6CBB4
	{
	};
Eq_3 g_tA6CCF8 = // 00A6CCF8
	{
		0x00
	};
ui32 g_dwA6CCFC = 0x00; // 00A6CCFC
byte g_bA6CD04 = 0x00; // 00A6CD04
word32 g_dwA6CD08 = 0x00; // 00A6CD08
Eq_3 g_tA6CD0C = // 00A6CD0C
	{
		0x00
	};
Eq_3 g_tA6CD10 = // 00A6CD10
	{
		0x00
	};
Eq_3 g_tA6CD14 = // 00A6CD14
	{
		0x00
	};
Eq_3 g_tA6CD18 = // 00A6CD18
	{
		0x00
	};
Eq_3 g_tA6CD1C = // 00A6CD1C
	{
		0x00
	};
Eq_3 g_tA6CD2C = // 00A6CD2C
	{
		0x00
	};
Eq_3 g_tA6CD30 = // 00A6CD30
	{
		0x00
	};
Eq_3 g_tA6CD34 = // 00A6CD34
	{
		0x00
	};
Eq_3 g_tA6CD38 = // 00A6CD38
	{
		0x00
	};
struct Eq_92476 * g_aA6CD40[] = // 00A6CD40
	{
	};
struct Eq_59236 * g_aA6CD54[] = // 00A6CD54
	{
	};
