// sho_data_0006.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

Eq_3 g_tA6D158 = // 00A6D158
	{
		0x00
	};
struct Eq_59236 * g_ptrA6D15C = null; // 00A6D15C
Eq_179605 g_aA6D160[] = // 00A6D160
	{
	};
Eq_179606 g_aA6D164[] = // 00A6D164
	{
	};
Eq_3 g_tA6D260 = // 00A6D260
	{
		0x00
	};
word32 g_dwA6D264 = 0x00; // 00A6D264
ui32 g_dwA6D268 = 0x00; // 00A6D268
ui32 g_dwA6D26C = 0x00; // 00A6D26C
word32 g_dwA6D270 = 0x00; // 00A6D270
word32 g_dwA6D278 = 0x00; // 00A6D278
Eq_3 g_tA6D37C = // 00A6D37C
	{
		0x00
	};
real64 g_aA6D418[] = // 00A6D418
	{
	};
word32 g_aA6D540[] = // 00A6D540
	{
	};
Eq_3 g_aA6D5D8[] = // 00A6D5D8
	{
	};
Eq_3 g_tA6D66C = // 00A6D66C
	{
		0x00
	};
word32 g_dwA6D670 = 0x00; // 00A6D670
Eq_3 g_tA6D674 = // 00A6D674
	{
		0x00
	};
Eq_3 g_tA6D67C = // 00A6D67C
	{
		0x00
	};
<anonymous> * g_ptrA6D680 = null; // 00A6D680
word32 g_dwA6D7AC = 0x00; // 00A6D7AC
struct Eq_118654 * g_aA6D7B0[257] = // 00A6D7B0
	{
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
	};
Eq_3 g_tA6DBB0 = // 00A6DBB0
	{
		0x00
	};
Eq_3 g_tA6DBB4 = // 00A6DBB4
	{
		0x00
	};
Eq_3 g_tA6DBBC = // 00A6DBBC
	{
		0x00
	};
Eq_3 g_tA6DBC0 = // 00A6DBC0
	{
		0x00
	};
Eq_3 g_tA6DBC4 = // 00A6DBC4
	{
		0x00
	};
Eq_3 g_tA6DBC8 = // 00A6DBC8
	{
		0x00
	};
Eq_3 g_tA6DBCC = // 00A6DBCC
	{
		0x00
	};
word32 g_dwA6DBD0 = 0x00; // 00A6DBD0
Eq_3 g_tA6DBD4 = // 00A6DBD4
	{
		0x00
	};
Eq_3 g_tA6DBD8 = // 00A6DBD8
	{
		0x00
	};
Eq_3 g_tA6DBDC = // 00A6DBDC
	{
		0x00
	};
Eq_3 g_tA6DBE0 = // 00A6DBE0
	{
		0x00
	};
Eq_3 g_tA6DBE4 = // 00A6DBE4
	{
		0x00
	};
Eq_3 g_tA6DBE8 = // 00A6DBE8
	{
		0x00
	};
Eq_3 g_tA6DBEC = // 00A6DBEC
	{
		0x00
	};
Eq_3 g_tA6DBF0 = // 00A6DBF0
	{
		0x00
	};
int32 g_dwA6DBF4 = 0; // 00A6DBF4
Eq_3 g_tA6DBF8 = // 00A6DBF8
	{
		0x00
	};
word32 g_dwA6DC00 = 0x00; // 00A6DC00
struct Eq_139069 * g_ptrA6DC08 = null; // 00A6DC08
struct Eq_139069 * g_ptrA6DC0C = null; // 00A6DC0C
Eq_179817 g_aA6DC10[] = // 00A6DC10
	{
	};
Eq_179818 g_aA6DC14[] = // 00A6DC14
	{
	};
word32 g_dwA6DC20 = 0x00; // 00A6DC20
struct Eq_139069 * g_ptrA6DCC8 = null; // 00A6DCC8
word32 g_dwA6DCCC = 0x00; // 00A6DCCC
void (* g_ptrA6DCD0)(int32 dwArg04) = null; // 00A6DCD0
byte g_aA6DCE0[] = // 00A6DCE0
	{
	};
Eq_3 g_aA6DDDC[] = // 00A6DDDC
	{
	};
Eq_3 g_aA6DDE0[] = // 00A6DDE0
	{
	};
Eq_3 g_tA6DF20 = // 00A6DF20
	{
		0x00
	};
ui32 g_dwA6DF24 = 0x00; // 00A6DF24
Eq_3 g_tA6DF28 = // 00A6DF28
	{
		0x00
	};
Eq_3 g_tA6DF2C = // 00A6DF2C
	{
		0x00
	};
Eq_3 g_tA6DF30 = // 00A6DF30
	{
		0x00
	};
word32 g_dwA6DF34 = 0x00; // 00A6DF34
Eq_3 g_tA6E150 = // 00A6E150
	{
		0x00
	};
Eq_3 g_tA6E154 = // 00A6E154
	{
		0x00
	};
Eq_3 g_tA6E158 = // 00A6E158
	{
		0x00
	};
Eq_3 g_tA6E478 = // 00A6E478
	{
		0x00
	};
word32 g_dwA6E47C = 0x00; // 00A6E47C
Eq_3 g_tA6E488 = // 00A6E488
	{
		0x00
	};
Eq_3 g_tA6E48C = // 00A6E48C
	{
		0x00
	};
Eq_3 g_tA6E4C8 = // 00A6E4C8
	{
		0x00
	};
Eq_3 g_tA6E548 = // 00A6E548
	{
		0x00
	};
<anonymous> * g_ptrA6E54C = null; // 00A6E54C
struct Eq_107701 * g_ptrA6EBE0 = null; // 00A6EBE0
int32 g_dwA74840 = 0; // 00A74840
real32 g_rA74844 = 0.0F; // 00A74844
real32 g_rA7484C = 0.0F; // 00A7484C
real32 g_rA74850 = 0.0F; // 00A74850
word32 g_dwA74854 = 0x00; // 00A74854
real32 g_rA74858 = 0.0F; // 00A74858
word32 g_dwA74860 = 0x00; // 00A74860
word32 g_dwA74864 = 0x00; // 00A74864
word32 g_dwA74868 = 0x00; // 00A74868
word32 g_dwA74870 = 0x00; // 00A74870
word32 g_dwA74874 = 0x00; // 00A74874
word32 g_dwA74878 = 0x00; // 00A74878
Eq_178481 g_tA7487C = // 00A7487C
	{
		0x00
	};
Eq_3 g_tA74AE4 = // 00A74AE4
	{
		0x00
	};
<anonymous> * g_ptrA74AE8 = null; // 00A74AE8
int32 g_dwA74AEC = 0; // 00A74AEC
Eq_3 g_tA74AF0 = // 00A74AF0
	{
		0x00
	};
word32 g_dwA74B08 = 0x00; // 00A74B08
word32 g_dwA74B10 = 0x00; // 00A74B10
Eq_52566 g_tA74B14 = 0; // 00A74B14
<anonymous> * g_ptrA74B18 = null; // 00A74B18
void * g_ptrA74B1C = null; // 00A74B1C
void * g_ptrA74B20 = null; // 00A74B20
