// sho_text_003C.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

// 007C2D70: void fn007C2D70(Stack Eq_3 dwArg04, Stack Eq_3 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn005BB700
//      fn00623210
void fn007C2D70(Eq_3 dwArg04, Eq_3 dwArg08, Eq_3 dwArg0C)
{
	Eq_3 ecx_26 = dwArg08;
	if (dwArg08 > 0x00)
	{
		Eq_3 eax_11 = dwArg04;
		do
		{
			if (eax_11 != 0x00)
			{
				eax_11.u6->dw0000 = (word32) *dwArg0C;
				eax_11.u6->dw0004 = (word32) *((word32) dwArg0C + 4);
			}
			--ecx_26;
			&eax_11.u6->dw0000 = eax_11.u6 + 1;
		} while (ecx_26 > 0x00);
	}
}

