// sho_rdata_0002.c
// Generated by decompiling sho.exe
// using Reko decompiler version 0.10.0.0.

#include "sho.h"

byte g_b8C4880 = 99; // 008C4880
Eq_44429 g_t8C63BC = // 008C63BC
	{
		&g_t61FA90,
		&g_t56E1E0,
	};
Eq_179447 g_a8C63C8[] = // 008C63C8
	{
	};
real32 g_r8C64BC = 0.97F; // 008C64BC
Eq_179510 g_a8CA588[] = // 008CA588
	{
	};
byte g_b8D144C = 0x5F; // 008D144C
byte g_b8D1DC8 = 115; // 008D1DC8
byte g_b8D3168 = 115; // 008D3168
byte g_b8D31F8 = 115; // 008D31F8
byte g_b8D35A0 = 101; // 008D35A0
byte g_b8D35E4 = 0x20; // 008D35E4
byte g_b8D35EC = 0x61; // 008D35EC
byte g_b8D35F8 = 44; // 008D35F8
byte g_b8D3604 = 0x61; // 008D3604
byte g_b8D3610 = 0x25; // 008D3610
byte g_b8D361C = 0x6D; // 008D361C
byte g_b8D3640 = 101; // 008D3640
byte g_b8D3678 = 0x6D; // 008D3678
byte g_b8D36A0 = 101; // 008D36A0
byte g_b8D36C0 = 0x6D; // 008D36C0
byte g_b8D3D70 = 0x25; // 008D3D70
byte g_b8D3E1C = 0x25; // 008D3E1C
byte g_b8D3E44 = 0x25; // 008D3E44
